package com.instagram.model.reels.sponsored;

import X.AbstractC12190kN;
import X.AbstractC16850sd;
import X.C14360o3;
import X.C9Ay;
import android.os.Parcel;
import android.os.Parcelable;
import java.util.LinkedHashMap;
import java.util.Map;
import kotlin.enums.EnumEntries;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: classes2.dex */
public final class AutoGeneratedCardType implements Parcelable {
    public static final Map A01;
    public static final /* synthetic */ EnumEntries A02;
    public static final /* synthetic */ AutoGeneratedCardType[] A03;
    public static final AutoGeneratedCardType A04;
    public static final AutoGeneratedCardType A05;
    public static final AutoGeneratedCardType A06;
    public static final AutoGeneratedCardType A07;
    public static final AutoGeneratedCardType A08;
    public static final AutoGeneratedCardType A09;
    public static final AutoGeneratedCardType A0A;
    public static final AutoGeneratedCardType A0B;
    public static final AutoGeneratedCardType A0C;
    public static final AutoGeneratedCardType A0D;
    public static final AutoGeneratedCardType A0E;
    public static final AutoGeneratedCardType A0F;
    public static final AutoGeneratedCardType A0G;
    public static final AutoGeneratedCardType A0H;
    public static final AutoGeneratedCardType A0I;
    public static final AutoGeneratedCardType A0J;
    public static final Parcelable.Creator CREATOR;
    public final String A00;

    @Override // android.os.Parcelable
    public final int describeContents() {
        return 0;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        C14360o3.A0B(parcel, 0);
        parcel.writeInt(ordinal());
    }

    static {
        AutoGeneratedCardType autoGeneratedCardType = new AutoGeneratedCardType("UNRECOGNIZED", 0, "AutoGeneratedCardType_unspecified");
        A0J = autoGeneratedCardType;
        AutoGeneratedCardType autoGeneratedCardType2 = new AutoGeneratedCardType("CAPTION", 1, "CAPTION");
        A04 = autoGeneratedCardType2;
        AutoGeneratedCardType autoGeneratedCardType3 = new AutoGeneratedCardType("CLICK_TO_MESSAGING_FAQS", 2, "CLICK_TO_MESSAGING_FAQS");
        A05 = autoGeneratedCardType3;
        AutoGeneratedCardType autoGeneratedCardType4 = new AutoGeneratedCardType("CLICK_TO_MESSAGING_WHATSAPP", 3, "CLICK_TO_MESSAGING_WHATSAPP");
        A06 = autoGeneratedCardType4;
        AutoGeneratedCardType autoGeneratedCardType5 = new AutoGeneratedCardType("COLLECTION", 4, "COLLECTION");
        A07 = autoGeneratedCardType5;
        AutoGeneratedCardType autoGeneratedCardType6 = new AutoGeneratedCardType("FIRST_QUESTION_CONTACT_INFO_LEADGEN", 5, "FIRST_QUESTION_CONTACT_INFO_LEADGEN");
        A08 = autoGeneratedCardType6;
        AutoGeneratedCardType autoGeneratedCardType7 = new AutoGeneratedCardType("FIRST_QUESTION_LEADGEN", 6, "FIRST_QUESTION_LEADGEN");
        A09 = autoGeneratedCardType7;
        AutoGeneratedCardType autoGeneratedCardType8 = new AutoGeneratedCardType("FIRST_QUESTION_SHORT_ANSWER_LEADGEN", 7, "FIRST_QUESTION_SHORT_ANSWER_LEADGEN");
        A0A = autoGeneratedCardType8;
        AutoGeneratedCardType autoGeneratedCardType9 = new AutoGeneratedCardType("GENERIC_CARD", 8, "GENERIC_CARD");
        A0B = autoGeneratedCardType9;
        AutoGeneratedCardType autoGeneratedCardType10 = new AutoGeneratedCardType("LEADGEN", 9, "LEADGEN");
        A0C = autoGeneratedCardType10;
        AutoGeneratedCardType autoGeneratedCardType11 = new AutoGeneratedCardType("MAI", 10, "MAI");
        A0D = autoGeneratedCardType11;
        AutoGeneratedCardType autoGeneratedCardType12 = new AutoGeneratedCardType("OFFSITE_LEADGEN_CARD", 11, "OFFSITE_LEADGEN_CARD");
        A0E = autoGeneratedCardType12;
        AutoGeneratedCardType autoGeneratedCardType13 = new AutoGeneratedCardType("ORIGINAL", 12, "ORIGINAL");
        A0F = autoGeneratedCardType13;
        AutoGeneratedCardType autoGeneratedCardType14 = new AutoGeneratedCardType("PRODUCT_EXTENSION", 13, "PRODUCT_EXTENSION");
        A0G = autoGeneratedCardType14;
        AutoGeneratedCardType autoGeneratedCardType15 = new AutoGeneratedCardType("PROFILE", 14, "PROFILE");
        A0H = autoGeneratedCardType15;
        AutoGeneratedCardType autoGeneratedCardType16 = new AutoGeneratedCardType("SHOWCASE", 15, "SHOWCASE");
        A0I = autoGeneratedCardType16;
        AutoGeneratedCardType[] autoGeneratedCardTypeArr = {autoGeneratedCardType, autoGeneratedCardType2, autoGeneratedCardType3, autoGeneratedCardType4, autoGeneratedCardType5, autoGeneratedCardType6, autoGeneratedCardType7, autoGeneratedCardType8, autoGeneratedCardType9, autoGeneratedCardType10, autoGeneratedCardType11, autoGeneratedCardType12, autoGeneratedCardType13, autoGeneratedCardType14, autoGeneratedCardType15, autoGeneratedCardType16, new AutoGeneratedCardType("SHOWREEL_CARD", 16, "SHOWREEL_CARD")};
        A03 = autoGeneratedCardTypeArr;
        A02 = AbstractC12190kN.A00(autoGeneratedCardTypeArr);
        AutoGeneratedCardType[] values = values();
        int A0L = AbstractC16850sd.A0L(values.length);
        LinkedHashMap linkedHashMap = new LinkedHashMap(A0L < 16 ? 16 : A0L);
        for (AutoGeneratedCardType autoGeneratedCardType17 : values) {
            linkedHashMap.put(autoGeneratedCardType17.A00, autoGeneratedCardType17);
        }
        A01 = linkedHashMap;
        CREATOR = new C9Ay(29);
    }

    public static AutoGeneratedCardType valueOf(String str) {
        return (AutoGeneratedCardType) Enum.valueOf(AutoGeneratedCardType.class, str);
    }

    public static AutoGeneratedCardType[] values() {
        return (AutoGeneratedCardType[]) A03.clone();
    }

    @Override // java.lang.Enum
    public final String toString() {
        return this.A00;
    }

    public AutoGeneratedCardType(String str, int i, String str2) {
        this.A00 = str2;
    }
}
