package com.instagram.quickpromotion.intf;

import X.AbstractC12190kN;
import kotlin.enums.EnumEntries;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: classes2.dex */
public final class QPTooltipAnchor {
    public static final /* synthetic */ EnumEntries A01;
    public static final /* synthetic */ QPTooltipAnchor[] A02;
    public static final QPTooltipAnchor A03;
    public static final QPTooltipAnchor A04;
    public static final QPTooltipAnchor A05;
    public static final QPTooltipAnchor A06;
    public static final QPTooltipAnchor A07;
    public static final QPTooltipAnchor A08;
    public static final QPTooltipAnchor A09;
    public static final QPTooltipAnchor A0A;
    public static final QPTooltipAnchor A0B;
    public static final QPTooltipAnchor A0C;
    public static final QPTooltipAnchor A0D;
    public static final QPTooltipAnchor A0E;
    public static final QPTooltipAnchor A0F;
    public static final QPTooltipAnchor A0G;
    public static final QPTooltipAnchor A0H;
    public static final QPTooltipAnchor A0I;
    public static final QPTooltipAnchor A0J;
    public static final QPTooltipAnchor A0K;
    public static final QPTooltipAnchor A0L;
    public static final QPTooltipAnchor A0M;
    public static final QPTooltipAnchor A0N;
    public static final QPTooltipAnchor A0O;
    public static final QPTooltipAnchor A0P;
    public static final QPTooltipAnchor A0Q;
    public static final QPTooltipAnchor A0R;
    public static final QPTooltipAnchor A0S;
    public static final QPTooltipAnchor A0T;
    public static final QPTooltipAnchor A0U;
    public static final QPTooltipAnchor A0V;
    public static final QPTooltipAnchor A0W;
    public static final QPTooltipAnchor A0X;
    public static final QPTooltipAnchor A0Y;
    public static final QPTooltipAnchor A0Z;
    public static final QPTooltipAnchor A0a;
    public static final QPTooltipAnchor A0b;
    public static final QPTooltipAnchor A0c;
    public static final QPTooltipAnchor A0d;
    public static final QPTooltipAnchor A0e;
    public static final QPTooltipAnchor A0f;
    public static final QPTooltipAnchor A0g;
    public static final QPTooltipAnchor A0h;
    public static final QPTooltipAnchor A0i;
    public static final QPTooltipAnchor A0j;
    public static final QPTooltipAnchor A0k;
    public static final QPTooltipAnchor A0l;
    public static final QPTooltipAnchor A0m;
    public static final QPTooltipAnchor A0n;
    public static final QPTooltipAnchor A0o;
    public static final QPTooltipAnchor A0p;
    public static final QPTooltipAnchor A0q;
    public static final QPTooltipAnchor A0r;
    public static final QPTooltipAnchor A0s;
    public static final QPTooltipAnchor A0t;
    public static final QPTooltipAnchor A0u;
    public static final QPTooltipAnchor A0v;
    public static final QPTooltipAnchor A0w;
    public static final QPTooltipAnchor A0x;
    public static final QPTooltipAnchor A0y;
    public static final QPTooltipAnchor A0z;
    public static final QPTooltipAnchor A10;
    public static final QPTooltipAnchor A11;
    public static final QPTooltipAnchor A12;
    public static final QPTooltipAnchor A13;
    public static final QPTooltipAnchor A14;
    public static final QPTooltipAnchor A15;
    public static final QPTooltipAnchor A16;
    public static final QPTooltipAnchor A17;
    public static final QPTooltipAnchor A18;
    public static final QPTooltipAnchor A19;
    public static final QPTooltipAnchor A1A;
    public static final QPTooltipAnchor A1B;
    public static final QPTooltipAnchor A1C;
    public static final QPTooltipAnchor A1D;
    public static final QPTooltipAnchor A1E;
    public static final QPTooltipAnchor A1F;
    public static final QPTooltipAnchor A1G;
    public static final QPTooltipAnchor A1H;
    public static final QPTooltipAnchor A1I;
    public static final QPTooltipAnchor A1J;
    public static final QPTooltipAnchor A1K;
    public static final QPTooltipAnchor A1L;
    public static final QPTooltipAnchor A1M;
    public static final QPTooltipAnchor A1N;
    public final String A00;

    static {
        QPTooltipAnchor qPTooltipAnchor = new QPTooltipAnchor("ACTIVITY_FEED_FILTER_BUTTON", 0, "activity_feed_filter_button");
        A03 = qPTooltipAnchor;
        QPTooltipAnchor qPTooltipAnchor2 = new QPTooltipAnchor("ADVANCED_SETTINGS_ROW", 1, "advanced_settings_row");
        A04 = qPTooltipAnchor2;
        QPTooltipAnchor qPTooltipAnchor3 = new QPTooltipAnchor("ADVANCED_SETTINGS_VIDEO_ROW", 2, "advanced_settings_video_row");
        A05 = qPTooltipAnchor3;
        QPTooltipAnchor qPTooltipAnchor4 = new QPTooltipAnchor("BIO_INTERESTS_FIRST_CELL", 3, "bio_interests_first_cell");
        A06 = qPTooltipAnchor4;
        QPTooltipAnchor qPTooltipAnchor5 = new QPTooltipAnchor("CAPTION_BOX", 4, "caption_box");
        A08 = qPTooltipAnchor5;
        QPTooltipAnchor qPTooltipAnchor6 = new QPTooltipAnchor("CAROUSEL_BUMPING", 5, "carousel_bumping");
        A09 = qPTooltipAnchor6;
        QPTooltipAnchor qPTooltipAnchor7 = new QPTooltipAnchor("CLAIM_LOCATION_PAGE_BUTTON", 6, "claim_location_page_button");
        A0A = qPTooltipAnchor7;
        QPTooltipAnchor qPTooltipAnchor8 = new QPTooltipAnchor("CLIPS_LIKE_BUTTON", 7, "clips_like_button");
        A0C = qPTooltipAnchor8;
        QPTooltipAnchor qPTooltipAnchor9 = new QPTooltipAnchor("CLIPS_TAB_ICON", 8, "reels_tab");
        A0D = qPTooltipAnchor9;
        QPTooltipAnchor qPTooltipAnchor10 = new QPTooltipAnchor("CLIPS_VIEWER_OVERFLOW_ICON_WITH_INSIGHTS", 9, "clips_overflow_with_insights");
        A0E = qPTooltipAnchor10;
        QPTooltipAnchor qPTooltipAnchor11 = new QPTooltipAnchor("CLIPS_CONTENT_APPRECIATION_BUTTON", 10, "clips_send_gift_button");
        A0B = qPTooltipAnchor11;
        QPTooltipAnchor qPTooltipAnchor12 = new QPTooltipAnchor("CONVERT_TO_CREATOR_ACCOUNT_BUTTON", 11, "convert_to_creator_account_button");
        A0G = qPTooltipAnchor12;
        QPTooltipAnchor qPTooltipAnchor13 = new QPTooltipAnchor("CREATE_POST_ICON", 12, "create_post_icon");
        A0H = qPTooltipAnchor13;
        QPTooltipAnchor qPTooltipAnchor14 = new QPTooltipAnchor("DESTINATIONS_SUPPORT_BUTTON", 13, "destinations_support_button");
        A0I = qPTooltipAnchor14;
        QPTooltipAnchor qPTooltipAnchor15 = new QPTooltipAnchor("DIRECT_ICON", 14, "direct_icon");
        A0J = qPTooltipAnchor15;
        QPTooltipAnchor qPTooltipAnchor16 = new QPTooltipAnchor("DIRECT_ICON_TAB_BAR", 15, "direct_icon_tab_bar");
        A0K = qPTooltipAnchor16;
        QPTooltipAnchor qPTooltipAnchor17 = new QPTooltipAnchor("DIRECT_REPLY_TO_AUTHOR_BUTTON", 16, "direct_reply_to_author_button");
        A0L = qPTooltipAnchor17;
        QPTooltipAnchor qPTooltipAnchor18 = new QPTooltipAnchor("EDIT_LOCATION_PAGE_INFO_BUTTON", 17, "edit_location_page_info_button");
        A0M = qPTooltipAnchor18;
        QPTooltipAnchor qPTooltipAnchor19 = new QPTooltipAnchor("EDIT_PROFILE_BUTTON", 18, "edit_profile_button");
        A0N = qPTooltipAnchor19;
        QPTooltipAnchor qPTooltipAnchor20 = new QPTooltipAnchor("EXPLORE_GRID_1X2", 19, "explore_grid_1x2");
        A0O = qPTooltipAnchor20;
        QPTooltipAnchor qPTooltipAnchor21 = new QPTooltipAnchor("EXPLORE_POPULAR_REELS_PILL", 20, "explore_popular_reels_pill");
        A0P = qPTooltipAnchor21;
        QPTooltipAnchor qPTooltipAnchor22 = new QPTooltipAnchor("EXPLORE_SEARCH_BAR_META_AI_BUTTON", 21, "search_bar_meta_ai_button");
        A0Q = qPTooltipAnchor22;
        QPTooltipAnchor qPTooltipAnchor23 = new QPTooltipAnchor("EXPLORE_TAB", 22, "explore_tab");
        A0R = qPTooltipAnchor23;
        QPTooltipAnchor qPTooltipAnchor24 = new QPTooltipAnchor("FUNDRAISER_STICKER", 23, "fundraiser_sticker");
        A0S = qPTooltipAnchor24;
        QPTooltipAnchor qPTooltipAnchor25 = new QPTooltipAnchor("HASHTAG_FOLLOW_BUTTON", 24, "hashtag_follow_button");
        A0T = qPTooltipAnchor25;
        QPTooltipAnchor qPTooltipAnchor26 = new QPTooltipAnchor("IGTV_PIN_PRODUCTS_BUTTON", 25, "igtv_pin_products_button");
        A0W = qPTooltipAnchor26;
        QPTooltipAnchor qPTooltipAnchor27 = new QPTooltipAnchor("INBOX_FOLDER_AD_RESPONSES", 26, "inbox_folder_ad_responses");
        A0Y = qPTooltipAnchor27;
        QPTooltipAnchor qPTooltipAnchor28 = new QPTooltipAnchor("INBOX_FILTER_ICON", 27, "inbox_filter_icon");
        A0X = qPTooltipAnchor28;
        QPTooltipAnchor qPTooltipAnchor29 = new QPTooltipAnchor("INBOX_VIDEO_CALL_ICON", 28, "inbox_video_call_icon");
        A0d = qPTooltipAnchor29;
        QPTooltipAnchor qPTooltipAnchor30 = new QPTooltipAnchor("INBOX_MESSAGE_ADS_ICON", 29, "inbox_message_ads_icon");
        A0Z = qPTooltipAnchor30;
        QPTooltipAnchor qPTooltipAnchor31 = new QPTooltipAnchor("INBOX_OPTIONS_MENU_ICON", 30, "inbox_options_menu_icon");
        A0a = qPTooltipAnchor31;
        QPTooltipAnchor qPTooltipAnchor32 = new QPTooltipAnchor("INBOX_SEARCH_BAR", 31, "inbox_search_bar");
        A0b = qPTooltipAnchor32;
        QPTooltipAnchor qPTooltipAnchor33 = new QPTooltipAnchor("INBOX_THREAD_AUDIO_CALL_ICON", 32, "inbox_thread_audio_call_icon");
        A0c = qPTooltipAnchor33;
        QPTooltipAnchor qPTooltipAnchor34 = new QPTooltipAnchor("KIRBY_THREAD_SETTINGS_BUTTON", 33, "kirby_thread_settings_button");
        A0e = qPTooltipAnchor34;
        QPTooltipAnchor qPTooltipAnchor35 = new QPTooltipAnchor("LIVE_CONSUMER_SHOPPING_BUTTON", 34, "live_consumer_shopping_button");
        A0f = qPTooltipAnchor35;
        QPTooltipAnchor qPTooltipAnchor36 = new QPTooltipAnchor("LIVE_CREATE_DETAILS_BUTTON", 35, "live_create_details_button");
        A0g = qPTooltipAnchor36;
        QPTooltipAnchor qPTooltipAnchor37 = new QPTooltipAnchor("LIVE_CREATE_FUNDRAISER_BUTTON", 36, "live_create_fundraiser_button");
        A0h = qPTooltipAnchor37;
        QPTooltipAnchor qPTooltipAnchor38 = new QPTooltipAnchor("LIVE_SCHEDULED_LIVE_CREATION_BUTTON", 37, "live_scheduled_live_creation_button");
        A0l = qPTooltipAnchor38;
        QPTooltipAnchor qPTooltipAnchor39 = new QPTooltipAnchor("LIVE_SCHEDULED_LIVE_MANAGEMENT_BUTTON", 38, "live_scheduled_live_management_button");
        A0m = qPTooltipAnchor39;
        QPTooltipAnchor qPTooltipAnchor40 = new QPTooltipAnchor("LIVE_CREATE_SHOPPING_BUTTON", 39, "live_create_shopping_button");
        A0i = qPTooltipAnchor40;
        QPTooltipAnchor qPTooltipAnchor41 = new QPTooltipAnchor("LIVE_CREATE_TITLE_BUTTON", 40, "live_create_title_button");
        A0j = qPTooltipAnchor41;
        QPTooltipAnchor qPTooltipAnchor42 = new QPTooltipAnchor("LIVE_CREATE_USER_PAY_BUTTON", 41, "live_create_user_pay_button");
        A0k = qPTooltipAnchor42;
        QPTooltipAnchor qPTooltipAnchor43 = new QPTooltipAnchor("LIVE_VIEWER_BADGES_CTA_BUTTON", 42, "live_viewer_badges_cta_button");
        A0o = qPTooltipAnchor43;
        QPTooltipAnchor qPTooltipAnchor44 = new QPTooltipAnchor("LIVE_SUBSCRIBE_BUTTON", 43, "live_subscribe_button");
        A0n = qPTooltipAnchor44;
        QPTooltipAnchor qPTooltipAnchor45 = new QPTooltipAnchor("MENU_ICON", 44, "menu_icon");
        A0q = qPTooltipAnchor45;
        QPTooltipAnchor qPTooltipAnchor46 = new QPTooltipAnchor("NEWS_TAB", 45, "news_tab");
        A0r = qPTooltipAnchor46;
        QPTooltipAnchor qPTooltipAnchor47 = new QPTooltipAnchor("PRIVACY_AND_SECURITY_BUTTON", 46, "privacy_and_security_button");
        A0t = qPTooltipAnchor47;
        QPTooltipAnchor qPTooltipAnchor48 = new QPTooltipAnchor("PROFILE_ACTIONS_ROW", 47, "profile_actions_row");
        A0v = qPTooltipAnchor48;
        QPTooltipAnchor qPTooltipAnchor49 = new QPTooltipAnchor("PROFILE_BANNER", 48, "profile_banner");
        A0w = qPTooltipAnchor49;
        QPTooltipAnchor qPTooltipAnchor50 = new QPTooltipAnchor("PROMOTIONS_CTA", 49, "promotions_cta");
        A13 = qPTooltipAnchor50;
        QPTooltipAnchor qPTooltipAnchor51 = new QPTooltipAnchor("PROFILE_CONTACT_OR_CALL_ICON", 50, "profile_contact_or_call_icon");
        A0y = qPTooltipAnchor51;
        QPTooltipAnchor qPTooltipAnchor52 = new QPTooltipAnchor("PROFILE_PICTURE", 51, "profile_picture");
        A0z = qPTooltipAnchor52;
        QPTooltipAnchor qPTooltipAnchor53 = new QPTooltipAnchor("PROFILE_TITLE_BAR", 52, "profile_title_bar");
        A11 = qPTooltipAnchor53;
        QPTooltipAnchor qPTooltipAnchor54 = new QPTooltipAnchor("REEL_ITEM", 53, "reel_item");
        A17 = qPTooltipAnchor54;
        QPTooltipAnchor qPTooltipAnchor55 = new QPTooltipAnchor("REELS_SHARE_SHEET_ADVANCED_SETTINGS_ROW", 54, "reels_share_sheet_advanced_settings_row");
        A15 = qPTooltipAnchor55;
        QPTooltipAnchor qPTooltipAnchor56 = new QPTooltipAnchor("REELS_SHARE_SHEET_RECOMMEND_ON_FACEBOOK_ROW", 55, "reels_share_sheet_recommend_on_facebook_row");
        A16 = qPTooltipAnchor56;
        QPTooltipAnchor qPTooltipAnchor57 = new QPTooltipAnchor("SEARCH_ICON", 56, "search_icon");
        A1C = qPTooltipAnchor57;
        QPTooltipAnchor qPTooltipAnchor58 = new QPTooltipAnchor("HOME_HEADER_ACTIVITY_BUTTON", 57, "home_header_activity_button");
        A0U = qPTooltipAnchor58;
        QPTooltipAnchor qPTooltipAnchor59 = new QPTooltipAnchor("HOME_HEADER_CREATE_BUTTON", 58, "home_header_create_button");
        A0V = qPTooltipAnchor59;
        QPTooltipAnchor qPTooltipAnchor60 = new QPTooltipAnchor("SAVE_ICON", 59, "save_icon");
        A19 = qPTooltipAnchor60;
        QPTooltipAnchor qPTooltipAnchor61 = new QPTooltipAnchor("SAVED_REPLIES_ITEM", 60, "saved_replies_item");
        A18 = qPTooltipAnchor61;
        QPTooltipAnchor qPTooltipAnchor62 = new QPTooltipAnchor("SCHOOL_DIRECTORY_INVITE_AIRPLANE", 61, "school_directory_invite_airplane");
        A1A = qPTooltipAnchor62;
        QPTooltipAnchor qPTooltipAnchor63 = new QPTooltipAnchor("SCHOOL_PROFILE_BANNER", 62, "school_profile_banner");
        A1B = qPTooltipAnchor63;
        QPTooltipAnchor qPTooltipAnchor64 = new QPTooltipAnchor("SHARE_COLLECTION_BUTTON", 63, "share_collection_button");
        A1D = qPTooltipAnchor64;
        QPTooltipAnchor qPTooltipAnchor65 = new QPTooltipAnchor("SHOP", 64, "Shop");
        A1E = qPTooltipAnchor65;
        QPTooltipAnchor qPTooltipAnchor66 = new QPTooltipAnchor("SHOPPING_COLLECTION_ICON", 65, "shopping_collection_icon");
        A1F = qPTooltipAnchor66;
        QPTooltipAnchor qPTooltipAnchor67 = new QPTooltipAnchor("SHOPPING_ICON", 66, "shopping_icon");
        A1G = qPTooltipAnchor67;
        QPTooltipAnchor qPTooltipAnchor68 = new QPTooltipAnchor("SHOPPING_SAVE_DIRECTORY_ICON", 67, "shopping_save_directory_icon");
        A1H = qPTooltipAnchor68;
        QPTooltipAnchor qPTooltipAnchor69 = new QPTooltipAnchor("STANDALONE_FUNDRAISER_IN_PROFILE", 68, "standalone_fundraiser_in_profile");
        A1I = qPTooltipAnchor69;
        QPTooltipAnchor qPTooltipAnchor70 = new QPTooltipAnchor("SWITCH_ACCOUNT", 69, "switch_account");
        A1J = qPTooltipAnchor70;
        QPTooltipAnchor qPTooltipAnchor71 = new QPTooltipAnchor("TAG_PRODUCTS_ROW", 70, "tag_products_row");
        A1K = qPTooltipAnchor71;
        QPTooltipAnchor qPTooltipAnchor72 = new QPTooltipAnchor("PROFILE_BOB_LABEL", 71, "profile_bob_label");
        A0x = qPTooltipAnchor72;
        QPTooltipAnchor qPTooltipAnchor73 = new QPTooltipAnchor("PROFILE_TAB", 72, "profile_tab");
        A10 = qPTooltipAnchor73;
        QPTooltipAnchor qPTooltipAnchor74 = new QPTooltipAnchor("MEDIA_OPTIONS_ICON", 73, "media_options");
        A0p = qPTooltipAnchor74;
        QPTooltipAnchor qPTooltipAnchor75 = new QPTooltipAnchor("PROMOTE_CTA", 74, "promote_cta");
        A12 = qPTooltipAnchor75;
        QPTooltipAnchor qPTooltipAnchor76 = new QPTooltipAnchor("PRIVATE_REELS_SHOW_ON_PROFILE_ROW", 75, "private_reels_show_on_profile_row");
        A0u = qPTooltipAnchor76;
        QPTooltipAnchor qPTooltipAnchor77 = new QPTooltipAnchor("PUBLIC_REELS_SHOW_ON_PROFILE_ROW", 76, "public_reels_show_on_profile_row");
        A14 = qPTooltipAnchor77;
        QPTooltipAnchor qPTooltipAnchor78 = new QPTooltipAnchor("VIDEO_CALL_FACE_FILTER", 77, "face_filters_button");
        A1N = qPTooltipAnchor78;
        QPTooltipAnchor qPTooltipAnchor79 = new QPTooltipAnchor("VIDEOS_TAB_ICON", 78, "videos_tab_icon");
        A1M = qPTooltipAnchor79;
        QPTooltipAnchor qPTooltipAnchor80 = new QPTooltipAnchor("CONTENT_FUNDING_REELS_ROW", 79, "content_funding_reels_row");
        A0F = qPTooltipAnchor80;
        QPTooltipAnchor qPTooltipAnchor81 = new QPTooltipAnchor("BONUSES_REELS_ROW", 80, "bonuses_reels_row");
        A07 = qPTooltipAnchor81;
        QPTooltipAnchor qPTooltipAnchor82 = new QPTooltipAnchor("PENDING_INBOX_RANKING_DROPDOWN", 81, "pending_inbox_ranking_dropdown");
        A0s = qPTooltipAnchor82;
        QPTooltipAnchor qPTooltipAnchor83 = new QPTooltipAnchor("THREAD_NAME", 82, "thread_name");
        A1L = qPTooltipAnchor83;
        QPTooltipAnchor[] qPTooltipAnchorArr = new QPTooltipAnchor[83];
        System.arraycopy(new QPTooltipAnchor[]{qPTooltipAnchor, qPTooltipAnchor2, qPTooltipAnchor3, qPTooltipAnchor4, qPTooltipAnchor5, qPTooltipAnchor6, qPTooltipAnchor7, qPTooltipAnchor8, qPTooltipAnchor9, qPTooltipAnchor10, qPTooltipAnchor11, qPTooltipAnchor12, qPTooltipAnchor13, qPTooltipAnchor14, qPTooltipAnchor15, qPTooltipAnchor16, qPTooltipAnchor17, qPTooltipAnchor18, qPTooltipAnchor19, qPTooltipAnchor20, qPTooltipAnchor21, qPTooltipAnchor22, qPTooltipAnchor23, qPTooltipAnchor24, qPTooltipAnchor25, qPTooltipAnchor26, qPTooltipAnchor27}, 0, qPTooltipAnchorArr, 0, 27);
        System.arraycopy(new QPTooltipAnchor[]{qPTooltipAnchor28, qPTooltipAnchor29, qPTooltipAnchor30, qPTooltipAnchor31, qPTooltipAnchor32, qPTooltipAnchor33, qPTooltipAnchor34, qPTooltipAnchor35, qPTooltipAnchor36, qPTooltipAnchor37, qPTooltipAnchor38, qPTooltipAnchor39, qPTooltipAnchor40, qPTooltipAnchor41, qPTooltipAnchor42, qPTooltipAnchor43, qPTooltipAnchor44, qPTooltipAnchor45, qPTooltipAnchor46, qPTooltipAnchor47, qPTooltipAnchor48, qPTooltipAnchor49, qPTooltipAnchor50, qPTooltipAnchor51, qPTooltipAnchor52, qPTooltipAnchor53, qPTooltipAnchor54}, 0, qPTooltipAnchorArr, 27, 27);
        System.arraycopy(new QPTooltipAnchor[]{qPTooltipAnchor55, qPTooltipAnchor56, qPTooltipAnchor57, qPTooltipAnchor58, qPTooltipAnchor59, qPTooltipAnchor60, qPTooltipAnchor61, qPTooltipAnchor62, qPTooltipAnchor63, qPTooltipAnchor64, qPTooltipAnchor65, qPTooltipAnchor66, qPTooltipAnchor67, qPTooltipAnchor68, qPTooltipAnchor69, qPTooltipAnchor70, qPTooltipAnchor71, qPTooltipAnchor72, qPTooltipAnchor73, qPTooltipAnchor74, qPTooltipAnchor75, qPTooltipAnchor76, qPTooltipAnchor77, qPTooltipAnchor78, qPTooltipAnchor79, qPTooltipAnchor80, qPTooltipAnchor81}, 0, qPTooltipAnchorArr, 54, 27);
        System.arraycopy(new QPTooltipAnchor[]{qPTooltipAnchor82, qPTooltipAnchor83}, 0, qPTooltipAnchorArr, 81, 2);
        A02 = qPTooltipAnchorArr;
        A01 = AbstractC12190kN.A00(qPTooltipAnchorArr);
    }

    public static QPTooltipAnchor valueOf(String str) {
        return (QPTooltipAnchor) Enum.valueOf(QPTooltipAnchor.class, str);
    }

    public static QPTooltipAnchor[] values() {
        return (QPTooltipAnchor[]) A02.clone();
    }

    public QPTooltipAnchor(String str, int i, String str2) {
        this.A00 = str2;
    }
}
