package com.instagram.quickpromotion.intf;

import X.AbstractC12190kN;
import X.C55732hE;
import com.facebook.common.dextricks.StringTreeSet;
import com.facebook.tigon.tigonhuc.HucClient;
import com.instagram.realtimeclient.RealtimeClientManager;
import kotlin.enums.EnumEntries;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: classes2.dex */
public final class Trigger {
    public static final /* synthetic */ EnumEntries A02;
    public static final /* synthetic */ Trigger[] A03;
    public static final Trigger A04;
    public static final Trigger A05;
    public static final Trigger A06;
    public static final Trigger A07;
    public static final Trigger A08;
    public static final Trigger A09;
    public static final Trigger A0A;
    public static final Trigger A0B;
    public static final Trigger A0C;
    public static final Trigger A0D;
    public static final Trigger A0E;
    public static final Trigger A0F;
    public static final Trigger A0G;
    public static final Trigger A0H;
    public static final Trigger A0I;
    public static final Trigger A0J;
    public static final Trigger A0K;
    public static final Trigger A0L;
    public static final Trigger A0M;
    public static final Trigger A0N;
    public static final Trigger A0O;
    public static final Trigger A0P;
    public static final Trigger A0Q;
    public static final Trigger A0R;
    public static final Trigger A0S;
    public static final Trigger A0T;
    public static final Trigger A0U;
    public static final Trigger A0V;
    public static final Trigger A0W;
    public static final Trigger A0X;
    public static final Trigger A0Y;
    public static final Trigger A0Z;
    public static final Trigger A0a;
    public static final Trigger A0b;
    public static final Trigger A0c;
    public static final Trigger A0d;
    public static final Trigger A0e;
    public static final Trigger A0f;
    public static final Trigger A0g;
    public static final Trigger A0h;
    public static final Trigger A0i;
    public static final Trigger A0j;
    public static final Trigger A0k;
    public static final Trigger A0l;
    public static final Trigger A0m;
    public static final Trigger A0n;
    public static final Trigger A0o;
    public static final Trigger A0p;
    public static final Trigger A0q;
    public static final Trigger A0r;
    public static final Trigger A0s;
    public static final Trigger A0t;
    public static final Trigger A0u;
    public static final Trigger A0v;
    public static final Trigger A0w;
    public static final Trigger A0x;
    public static final Trigger A0y;
    public static final Trigger A0z;
    public static final Trigger A10;
    public static final Trigger A11;
    public static final Trigger A12;
    public static final Trigger A13;
    public static final Trigger A14;
    public static final Trigger A15;
    public static final Trigger A16;
    public static final Trigger A17;
    public static final Trigger A18;
    public static final Trigger A19;
    public static final Trigger A1A;
    public static final Trigger A1B;
    public static final Trigger A1C;
    public static final Trigger A1D;
    public static final Trigger A1E;
    public static final Trigger A1F;
    public static final Trigger A1G;
    public static final Trigger A1H;
    public static final Trigger A1I;
    public static final Trigger A1J;
    public static final Trigger A1K;
    public static final Trigger A1L;
    public static final Trigger A1M;
    public static final Trigger A1N;
    public static final Trigger A1O;
    public static final Trigger A1P;
    public static final Trigger A1Q;
    public static final Trigger A1R;
    public static final Trigger A1S;
    public static final Trigger A1T;
    public static final Trigger A1U;
    public static final Trigger A1V;
    public static final Trigger A1W;
    public static final Trigger A1X;
    public static final Trigger A1Y;
    public static final Trigger A1Z;
    public static final Trigger A1a;
    public static final Trigger A1b;
    public static final Trigger A1c;
    public static final Trigger A1d;
    public static final Trigger A1e;
    public static final Trigger A1f;
    public static final Trigger A1g;
    public static final Trigger A1h;
    public static final Trigger A1i;
    public static final Trigger A1j;
    public static final Trigger A1k;
    public static final Trigger A1l;
    public static final Trigger A1m;
    public static final Trigger A1n;
    public static final Trigger A1o;
    public static final Trigger A1p;
    public static final Trigger A1q;
    public static final Trigger A1r;
    public static final Trigger A1s;
    public static final Trigger A1t;
    public static final Trigger A1u;
    public static final Trigger A1v;
    public static final Trigger A1w;
    public static final Trigger A1x;
    public static final Trigger A1y;
    public static final Trigger A1z;
    public static final Trigger A20;
    public static final Trigger A21;
    public static final Trigger A22;
    public static final Trigger A23;
    public static final Trigger A24;
    public static final Trigger A25;
    public static final Trigger A26;
    public static final Trigger A27;
    public static final Trigger A28;
    public static final Trigger A29;
    public C55732hE A00;
    public final String A01;

    static {
        Trigger trigger = new Trigger("PROFILE_HEADER", "instagram_profile_page", 0);
        A1e = trigger;
        Trigger trigger2 = new Trigger("PROFILE_PROMPT", "instagram_profile_page_prompt", 1);
        A1j = trigger2;
        Trigger trigger3 = new Trigger("PROFILE_TOOLTIP", "instagram_self_profile_tooltip", 2);
        A1k = trigger3;
        Trigger trigger4 = new Trigger("PROFILE_FLOATING_BANNER_PROMPT", "instagram_self_profile_floating_banner_prompt", 3);
        A1c = trigger4;
        Trigger trigger5 = new Trigger("PROFILE_OTHER_CHECKOUT_TOOLTIP", "instagram_other_checkout_profile_tooltip", 4);
        A1f = trigger5;
        Trigger trigger6 = new Trigger("PROFILE_OTHER_HEADER", "instagram_other_profile_page_header", 5);
        A1g = trigger6;
        Trigger trigger7 = new Trigger("PROFILE_OTHER_PROMPT", "instagram_other_profile_page_prompt", 6);
        A1h = trigger7;
        Trigger trigger8 = new Trigger("PROFILE_OTHER_TOOLTIP", "instagram_other_profile_tooltip", 7);
        A1i = trigger8;
        Trigger trigger9 = new Trigger("PROFESSIONAL_SETTING_TOOLTIP", "instagram_professional_setting_tooltip", 8);
        A1b = trigger9;
        Trigger trigger10 = new Trigger("FEED_BANNER", "instagram_feed_banner", 9);
        A0T = trigger10;
        Trigger trigger11 = new Trigger("FEED_BOTTOMSHEET", "instagram_feed_bottomsheet", 10);
        A0U = trigger11;
        Trigger trigger12 = new Trigger("FEED_COMMENT_HEADER", "instagram_feed_comment_header", 11);
        A0V = trigger12;
        Trigger trigger13 = new Trigger("FEED_HEADER", "instagram_feed_header", 12);
        A0X = trigger13;
        Trigger trigger14 = new Trigger("FEED_PROMPT", "instagram_feed_prompt", 13);
        A0Z = trigger14;
        Trigger trigger15 = new Trigger("FEED_SHARING_HEADER", "instagram_feed_sharing_header", 14);
        A0a = trigger15;
        Trigger trigger16 = new Trigger("FEED_SHARING_PROMPT", "instagram_feed_sharing_prompt", 15);
        A0b = trigger16;
        Trigger trigger17 = new Trigger("FEED_TOOLTIP", "instagram_feed_tool_tip", 16);
        A0c = trigger17;
        Trigger trigger18 = new Trigger("HASHTAG_FEED_TOOLTIP", "instagram_hashtag_feed_tooltip", 17);
        A0f = trigger18;
        Trigger trigger19 = new Trigger("INBOX_HEADER", "instagram_inbox_header", 18);
        A0l = trigger19;
        Trigger trigger20 = new Trigger("INBOX_PROMPT", "instagram_inbox_prompt", 19);
        A0o = trigger20;
        Trigger trigger21 = new Trigger("INBOX_TOOLTIP", "instagram_inbox_tooltip", 20);
        A0q = trigger21;
        Trigger trigger22 = new Trigger("INBOX_SEARCH_HEADER", "instagram_inbox_search_header", 21);
        A0p = trigger22;
        Trigger trigger23 = new Trigger("INBOX_FILTER_TOOLTIP", "instagram_inbox_filter_tooltip", 22);
        A0k = trigger23;
        Trigger trigger24 = new Trigger("INBOX_CLOSE_FRIENDS_FILTER_APPLIED", "instagram_inbox_close_friends_filter_applied", 23);
        A0j = trigger24;
        Trigger trigger25 = new Trigger("INBOX_HIGH_BOTTOMSHEET", "instagram_aud_inbox_bottom_sheet_high", 24);
        A0m = trigger25;
        Trigger trigger26 = new Trigger("INBOX_LOW_BOTTOMSHEET", "instagram_aud_inbox_bottom_sheet_low", 25);
        A0n = trigger26;
        Trigger trigger27 = new Trigger("IGTV_VIEWER_PROMPT", "instagram_tv_viewer_end_of_first_video", 26);
        A0i = trigger27;
        Trigger trigger28 = new Trigger("IGTV_DISCOVER_HEADER", "instagram_tv_discover_header", 27);
        A0h = trigger28;
        Trigger trigger29 = new Trigger("LIVE_BADGES_TOOLTIP", "instagram_live_user_pay_tooltip", 28);
        A1P = trigger29;
        Trigger trigger30 = new Trigger("LIVE_BROADCASTER_SHOPPING_TOOLTIP", "instagram_live_broadcaster_shopping_tooltip", 29);
        A1Q = trigger30;
        Trigger trigger31 = new Trigger("LIVE_COMPOSE", "instagram_live_compose", 30);
        A1R = trigger31;
        Trigger trigger32 = new Trigger("STORY_CREATION", "instagram_story_creation", 31);
        A23 = trigger32;
        Trigger trigger33 = new Trigger("LIVE_ROOMS_INTERSTITIAL", "instagram_live_rooms_interstitial", 32);
        A1S = trigger33;
        Trigger trigger34 = new Trigger("LIVE_ROOMS_TOOLTIP", "instagram_live_rooms_tooltip", 33);
        A1T = trigger34;
        Trigger trigger35 = new Trigger("LIVE_SHOPPING_TOOLTIP", "instagram_live_shopping_tooltip", 34);
        A1U = trigger35;
        Trigger trigger36 = new Trigger("LIVE_VIEWER_BADGES_CTA_TOOLTIP", "instagram_live_viewer_badges_tooltip", 35);
        A1V = trigger36;
        Trigger trigger37 = new Trigger("ACCOUNT_SETTING_TOOLTIP", "instagram_account_setting_tip", 36);
        A05 = trigger37;
        Trigger trigger38 = new Trigger("ACTIVITY_FEED_HEADER", "instagram_activity_feed_header", 37);
        A07 = trigger38;
        Trigger trigger39 = new Trigger("ACTIVITY_FEED_PROMPT", "instagram_activity_feed_prompt", 38);
        A08 = trigger39;
        Trigger trigger40 = new Trigger("ACTIVITY_FEED_TOOLTIP", "instagram_activity_feed_tooltip", 39);
        A09 = trigger40;
        Trigger trigger41 = new Trigger("BRANDED_CONTENT_AND_SHOPPING_ACTIVITY_FEED_HEADER", "instagram_branded_content_and_shopping_activity_feed", 40);
        A0E = trigger41;
        Trigger trigger42 = new Trigger("BRANDED_CONTENT_DISCLOSURE_FLOW_LOADED", "instagram_branded_content_disclosure_flow_loaded", 41);
        A0F = trigger42;
        Trigger trigger43 = new Trigger("BRANDED_CONTENT_SETTINGS_LOADED", "instagram_branded_content_settings_page_header", 42);
        A0G = trigger43;
        Trigger trigger44 = new Trigger("BRANDED_CONTENT_STORY_SHARED", "instagram_branded_content_story_shared", 43);
        A0H = trigger44;
        Trigger trigger45 = new Trigger("EXPLORE_HEADER", "instagram_explore_header", 44);
        A0P = trigger45;
        Trigger trigger46 = new Trigger("EXPLORE_PROMPT", "instagram_explore_prompt", 45);
        A0Q = trigger46;
        Trigger trigger47 = new Trigger("SHOPPING_BUY_ON_INSTAGRAM_HEADER", "instagram_shopping_buy_on_instagram_header", 46);
        A1w = trigger47;
        Trigger trigger48 = new Trigger("SHOPPING_PDP_HEADER", "instagram_shopping_pdp_header", 47);
        A1y = trigger48;
        Trigger trigger49 = new Trigger("SHOPPING_PRODUCT_PICKER_LOADED", "instagram_shopping_product_picker_loaded", 48);
        A1z = trigger49;
        Trigger trigger50 = new Trigger("SHOPPING_SAVE_DIRECTORY_TOOLTIP", "instagram_shopping_save_directory_tooltip", 49);
        A20 = trigger50;
        Trigger trigger51 = new Trigger("SAVE_HOME_LOADED", "instagram_save_home_loaded", 50);
        A1n = trigger51;
        Trigger trigger52 = new Trigger("LOCATION_PAGE_INFO_LOADED", "instagram_location_page_info_loaded", 51);
        A1W = trigger52;
        Trigger trigger53 = new Trigger("SHARE_POST_LOADED", "instagram_share_post_loaded", 52);
        A1t = trigger53;
        Trigger trigger54 = new Trigger("SHARE_TO_FB_SWITCHED_ON", "instagram_share_to_fb_switched_on", 53);
        A1v = trigger54;
        Trigger trigger55 = new Trigger("SHARE_TO_FB_SWITCHED_OFF", "instagram_share_to_fb_switched_off", 54);
        A1u = trigger55;
        Trigger trigger56 = new Trigger("SURVEY", "instagram_survey", 55);
        A27 = trigger56;
        Trigger trigger57 = new Trigger("ACCOUNT_INSIGHTS_HEADER", "instagram_account_insights_header", 56);
        A04 = trigger57;
        Trigger trigger58 = new Trigger("LOGGED_IN_USER_ID_LOADED", "instagram_other_logged_in_user_id_loaded", 57);
        A1X = trigger58;
        Trigger trigger59 = new Trigger("STORY_VIEW_FUNDRAISER_STICKER_TOOLTIP", "instagram_fundraiser_sticker_tooltip", 58);
        A25 = trigger59;
        Trigger trigger60 = new Trigger("QUICK_PROMOTION_TEST", "instagram_quick_promotion_test", 59);
        A1l = trigger60;
        Trigger trigger61 = new Trigger("EDIT_PROFILE", "instagram_edit_profile_loaded", 60);
        A0O = trigger61;
        Trigger trigger62 = new Trigger("CLOSE_FRIENDS_HEADER", "instagram_close_friends_header", 61);
        A0K = trigger62;
        Trigger trigger63 = new Trigger("DIRECT_THREAD_LOADED", "instagram_thread_loaded", 62);
        A0N = trigger63;
        Trigger trigger64 = new Trigger("IN_THREAD_MESSAGE_FOOTER", "instagram_message_footer", 63);
        A1L = trigger64;
        Trigger trigger65 = new Trigger("IN_THREAD_MESSAGE_FOOTER_DOUBLE_TAP_TO_HEART", "instagram_message_footer_double_tap_to_heart", 64);
        A1M = trigger65;
        Trigger trigger66 = new Trigger("IN_THREAD_MESSAGE_SENT", "instagram_direct_message_sent", 65);
        A1N = trigger66;
        Trigger trigger67 = new Trigger("IN_THREAD_SAVED_REPLY_MESSAGE_SENT", "instagram_direct_saved_reply_message_sent", 66);
        A1O = trigger67;
        Trigger trigger68 = new Trigger("SHOPPING_STORY_POSTED", "instagram_shopping_enable_auto_highlight_interstitial", 67);
        A21 = trigger68;
        Trigger trigger69 = new Trigger("NAVIGATION_TOOLTIP", "instagram_navigation_tooltip", 68);
        A1Z = trigger69;
        Trigger trigger70 = new Trigger("FEATURED_PRODUCT_MEDIA_INTERSTITIAL", "instagram_featured_product_media_interstitial", 69);
        A0R = trigger70;
        Trigger trigger71 = new Trigger("FEATURED_PRODUCT_MEDIA_TOOLTIP", "instagram_featured_product_media_tooltip", 70);
        A0S = trigger71;
        Trigger trigger72 = new Trigger("STORY_VIEWER_PROMOTE_CTA_TOOLTIP", "instagram_story_viewer_promote_cta_tooltip", 71);
        A24 = trigger72;
        Trigger trigger73 = new Trigger("FEED_PROMOTE_CTA_TOOLTIP", "instagram_feed_promote_cta_tooltip", 72);
        A0Y = trigger73;
        Trigger trigger74 = new Trigger("CLIPS_CREATION_SHARE_SHEET_LOADED", "instagram_clips_creation_share_sheet_loaded", 73);
        A0I = trigger74;
        Trigger trigger75 = new Trigger("CLIPS_VIEWER_LOADED", "instagram_clips_viewer_loaded", 74);
        A0J = trigger75;
        Trigger trigger76 = new Trigger("SELF_CLIPS_VIEWER_LOADED", "instagram_self_clips_viewer_loaded", 75);
        A1o = trigger76;
        Trigger trigger77 = new Trigger("VIDEO_CALL_LOADED", "instagram_video_call_loaded", 76);
        A28 = trigger77;
        Trigger trigger78 = new Trigger("VIDEO_CALL_PEEK_PROMO_PROMPT", "instagram_video_call_peek_promo_prompt", 77);
        A29 = trigger78;
        Trigger trigger79 = new Trigger("FEED_COMPOSER_PROMPT", "instagram_feed_composer_prompt", 78);
        A0W = trigger79;
        Trigger trigger80 = new Trigger("DIRECT_STICKER_TRAY_HEADER", "instagram_direct_sticker_tray_header", 79);
        A0M = trigger80;
        Trigger trigger81 = new Trigger("INSTAGRAM_PENDING_INBOX_HEADER", "instagram_pending_inbox_header", 80);
        A11 = trigger81;
        Trigger trigger82 = new Trigger("INSTAGRAM_PENDING_INBOX_RANKING_DROPDOWN_TOOLTIP", "instagram_pending_inbox_ranking_dropdown_tooltip", 81);
        A12 = trigger82;
        Trigger trigger83 = new Trigger("INSTAGRAM_MEDIA_GALLERY", "instagram_media_gallery", 82);
        A0y = trigger83;
        Trigger trigger84 = new Trigger("SHOPPING_PDP_BANNER_PROMPT", "instagram_shopping_pdp_banner_prompt", 83);
        A1x = trigger84;
        Trigger trigger85 = new Trigger("INSTAGRAM_EXPLORE_2X2_GRID_LOADED", "instagram_explore_2x2_grid_loaded", 84);
        A0v = trigger85;
        Trigger trigger86 = new Trigger("INSTAGRAM_EXPLORE_META_AI_BOTTOMSHEET", "instagram_explore_meta_ai_bottomsheet", 85);
        A0w = trigger86;
        Trigger trigger87 = new Trigger("INSTAGRAM_EXPLORE_TOOLTIP", "instagram_explore_tooltip", 86);
        A0x = trigger87;
        Trigger trigger88 = new Trigger("INSTAGRAM_SHOPPING_PRODUCT_DETAILS_LOADED", "instagram_shopping_product_details_loaded", 87);
        A1D = trigger88;
        Trigger trigger89 = new Trigger("REEL_CREATED", "instagram_reel_created", 88);
        A1m = trigger89;
        Trigger trigger90 = new Trigger("SELF_REEL_VIEW", "instagram_self_reel_view", 89);
        A1p = trigger90;
        Trigger trigger91 = new Trigger("PROFILE_FOLLOW_BUTTON_CLICKED", "instagram_profile_follow_button_clicked", 90);
        A1d = trigger91;
        Trigger trigger92 = new Trigger("POST_CREATED", "instagram_post_created", 91);
        A1a = trigger92;
        Trigger trigger93 = new Trigger("STORY_CREATED", "instagram_story_created", 92);
        A22 = trigger93;
        Trigger trigger94 = new Trigger("COMMENT_POSTED", "instagram_comment_posted", 93);
        A0L = trigger94;
        Trigger trigger95 = new Trigger("SHARE_COLLECTION_BUTTON_LOADED", "instagram_share_collection_button_loaded", 94);
        A1s = trigger95;
        Trigger trigger96 = new Trigger("SETTINGS_PAGE_PROMPT", "instagram_settings_page_prompt", 95);
        A1r = trigger96;
        Trigger trigger97 = new Trigger("INSTAGRAM_REELS_MIDCARD_LOADED", "instagram_reels_midcard_loaded", 96);
        A16 = trigger97;
        Trigger trigger98 = new Trigger("SUBSCRIPTION_SETTINGS_LOADED", "instagram_subscriptions_settings_page_header", 97);
        A26 = trigger98;
        Trigger trigger99 = new Trigger("INSTAGRAM_SEARCH_BAR_META_AI_TOOLTIP", "instagram_search_bar_meta_ai_tooltip", 98);
        A19 = trigger99;
        Trigger trigger100 = new Trigger("INSTAGRAM_STORY_INSIGHTS_HEADER", "instagram_story_insights_header", 99);
        A1I = trigger100;
        Trigger trigger101 = new Trigger("AUDIO_PAGE_ENTRY_HEADER", "instagram_audio_page_entry_megaphone", 100);
        A0B = trigger101;
        Trigger trigger102 = new Trigger("INSTAGRAM_REELS_AUDIO_BROWSER_HEADER", "instagram_reels_audio_browser_header", 101);
        A15 = trigger102;
        Trigger trigger103 = new Trigger("INSTAGRAM_REELS_AUDIO_BROWSER_FOOTER", "instagram_reels_audio_browser_footer", 102);
        A14 = trigger103;
        Trigger trigger104 = new Trigger("INSTAGRAM_STORIES_AUDIO_BROWSER_HEADER", "instagram_stories_audio_browser_header", 103);
        A1E = trigger104;
        Trigger trigger105 = new Trigger("INSTAGRAM_MUSIC_IN_FEED_AUDIO_BROWSER_HEADER", "instagram_music_in_feed_audio_browser_header", 104);
        A0z = trigger105;
        Trigger trigger106 = new Trigger("INSTAGRAM_NOTES_AUDIO_BROWSER_HEADER", "instagram_notes_audio_browser_header", 105);
        A10 = trigger106;
        Trigger trigger107 = new Trigger("INSTAGRAM_STORY_AUDIO_BROWSER_HEADER_DEPRECATED", "instagram_story_audio_browser_header", 106);
        A1G = trigger107;
        Trigger trigger108 = new Trigger("INSTAGRAM_TABBED_STORY_AUDIO_BROWSER_HEADER", "instagram_tabbed_story_audio_browser_header", 107);
        A1K = trigger108;
        Trigger trigger109 = new Trigger("INSTAGRAM_TABBED_STORY_AUDIO_BROWSER_FOOTER", "instagram_tabbed_story_audio_browser_footer", 108);
        A1J = trigger109;
        Trigger trigger110 = new Trigger("INSTAGRAM_ADD_YOURS_PIVOT_PAGE_CONSUMER_ENTRY_MEGAPHONE", "instagram_add_yours_pivot_page_consumer_entry_megaphone", 109);
        A0r = trigger110;
        Trigger trigger111 = new Trigger("INSTAGRAM_ADD_YOURS_PIVOT_PAGE_CREATOR_ENTRY_MEGAPHONE", "instagram_add_yours_pivot_page_creator_entry_megaphone", 110);
        A0s = trigger111;
        Trigger trigger112 = new Trigger("INSTAGRAM_SELF_PROFILE_PAGE_CREATOR_INVITE_MEGAPHONE", "instagram_self_profile_page_creator_invite_megaphone", 111);
        A1B = trigger112;
        Trigger trigger113 = new Trigger(RealtimeClientManager.APP_FOREGROUND_CONDITION, "app_foreground", 112);
        A0A = trigger113;
        Trigger trigger114 = new Trigger("SESSION_START", "session_start", 113);
        A1q = trigger114;
        Trigger trigger115 = new Trigger("IG4A_PREFETCH", "ig4a_prefetch", 114);
        A0g = trigger115;
        Trigger trigger116 = new Trigger("INSTAGRAM_AUD_STORY_REPLIES_BOTTOMSHEET_LOW", "instagram_aud_story_replies_bottomsheet_low", 115);
        A0u = trigger116;
        Trigger trigger117 = new Trigger("INSTAGRAM_AUD_SHARING_BOTTOMSHEET_LOW", "instagram_aud_sharing_bottomsheet_low", 116);
        A0t = trigger117;
        Trigger trigger118 = new Trigger("ACHIEVEMENTS_HUB_ENTERED", "instagram_achievements_hub_entered", 117);
        A06 = trigger118;
        Trigger trigger119 = new Trigger("FOLLOW_REQUEST_SCREEN_MEGAPHONE", "instagram_follow_requests_screen_megaphone", 118);
        A0e = trigger119;
        Trigger trigger120 = new Trigger("FOLLOW_REQUEST_DENIED", "instagram_follow_request_denied", 119);
        A0d = trigger120;
        Trigger trigger121 = new Trigger("MESSAGE_REQUEST_ACTION_DIALOG", "instagram_message_request_action_dialog", HucClient.BODY_UPLOAD_TIMEOUT_SECONDS);
        A1Y = trigger121;
        Trigger trigger122 = new Trigger("INSTAGRAM_PROFILE_RESTRICTED", "instagram_profile_restricted", 121);
        A13 = trigger122;
        Trigger trigger123 = new Trigger("INSTAGRAM_REPORT_SUBMITTED", "instagram_report_submitted", 122);
        A17 = trigger123;
        Trigger trigger124 = new Trigger("INSTAGRAM_SELF_PROFILE_PAGE_OPEN_CAROUSEL_MEGAPHONE", "instagram_self_profile_page_open_carousel_megaphone", 123);
        A1C = trigger124;
        Trigger trigger125 = new Trigger("INSTAGRAM_SELF_MEDIA_OVERFLOW_MENU_TOOLTIP", "instagram_self_media_overflow_menu_tooltip", 124);
        A1A = trigger125;
        Trigger trigger126 = new Trigger("INSTAGRAM_STORY_ARCHIVE", "instagram_story_archive", 125);
        A1F = trigger126;
        Trigger trigger127 = new Trigger("INSTAGRAM_STORY_EDIT_HIGHLIGHT", "instagram_story_edit_highlight", 126);
        A1H = trigger127;
        Trigger trigger128 = new Trigger("INSTAGRAM_SCHOOL_DIRECTORY_INVITE_AIRPLANE_TOOLTIP", "instagram_school_directory_invite_airplane_tooltip", StringTreeSet.MAX_SYMBOL_COUNT);
        A18 = trigger128;
        Trigger trigger129 = new Trigger("BARCELONA_FEED_HEADER", "barcelona_feed_header", 128);
        A0C = trigger129;
        Trigger trigger130 = new Trigger("BARCELONA_PERMALINK_LOADED", "barcelona_permalink_loaded", 129);
        A0D = trigger130;
        Trigger trigger131 = new Trigger("BARCELONA_INTERSTITIAL", "barcelona_interstitial", 130);
        Trigger[] triggerArr = new Trigger[131];
        System.arraycopy(new Trigger[]{trigger, trigger2, trigger3, trigger4, trigger5, trigger6, trigger7, trigger8, trigger9, trigger10, trigger11, trigger12, trigger13, trigger14, trigger15, trigger16, trigger17, trigger18, trigger19, trigger20, trigger21, trigger22, trigger23, trigger24, trigger25, trigger26, trigger27}, 0, triggerArr, 0, 27);
        System.arraycopy(new Trigger[]{trigger28, trigger29, trigger30, trigger31, trigger32, trigger33, trigger34, trigger35, trigger36, trigger37, trigger38, trigger39, trigger40, trigger41, trigger42, trigger43, trigger44, trigger45, trigger46, trigger47, trigger48, trigger49, trigger50, trigger51, trigger52, trigger53, trigger54}, 0, triggerArr, 27, 27);
        System.arraycopy(new Trigger[]{trigger55, trigger56, trigger57, trigger58, trigger59, trigger60, trigger61, trigger62, trigger63, trigger64, trigger65, trigger66, trigger67, trigger68, trigger69, trigger70, trigger71, trigger72, trigger73, trigger74, trigger75, trigger76, trigger77, trigger78, trigger79, trigger80, trigger81}, 0, triggerArr, 54, 27);
        System.arraycopy(new Trigger[]{trigger82, trigger83, trigger84, trigger85, trigger86, trigger87, trigger88, trigger89, trigger90, trigger91, trigger92, trigger93, trigger94, trigger95, trigger96, trigger97, trigger98, trigger99, trigger100, trigger101, trigger102, trigger103, trigger104, trigger105, trigger106, trigger107, trigger108}, 0, triggerArr, 81, 27);
        System.arraycopy(new Trigger[]{trigger109, trigger110, trigger111, trigger112, trigger113, trigger114, trigger115, trigger116, trigger117, trigger118, trigger119, trigger120, trigger121, trigger122, trigger123, trigger124, trigger125, trigger126, trigger127, trigger128, trigger129, trigger130, trigger131}, 0, triggerArr, 108, 23);
        A03 = triggerArr;
        A02 = AbstractC12190kN.A00(triggerArr);
    }

    public static Trigger valueOf(String str) {
        return (Trigger) Enum.valueOf(Trigger.class, str);
    }

    public static Trigger[] values() {
        return (Trigger[]) A03.clone();
    }

    public Trigger(String str, String str2, int i) {
        this.A01 = str2;
    }
}
