package com.instagram.clips.intf;

import X.AbstractC12190kN;
import X.C14360o3;
import X.C206139Av;
import android.os.Parcel;
import android.os.Parcelable;
import com.facebook.common.dextricks.StringTreeSet;
import com.facebook.tigon.tigonhuc.HucClient;
import com.instagram.realtimeclient.GraphQLSubscriptionID;
import com.instagram.realtimeclient.RealtimeConstants;
import kotlin.enums.EnumEntries;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: classes3.dex */
public final class ClipsViewerSource implements Parcelable {
    public static final /* synthetic */ EnumEntries A01;
    public static final /* synthetic */ ClipsViewerSource[] A02;
    public static final ClipsViewerSource A03;
    public static final ClipsViewerSource A04;
    public static final ClipsViewerSource A05;
    public static final ClipsViewerSource A06;
    public static final ClipsViewerSource A07;
    public static final ClipsViewerSource A08;
    public static final ClipsViewerSource A09;
    public static final ClipsViewerSource A0A;
    public static final ClipsViewerSource A0B;
    public static final ClipsViewerSource A0C;
    public static final ClipsViewerSource A0D;
    public static final ClipsViewerSource A0E;
    public static final ClipsViewerSource A0F;
    public static final ClipsViewerSource A0G;
    public static final ClipsViewerSource A0H;
    public static final ClipsViewerSource A0I;
    public static final ClipsViewerSource A0J;
    public static final ClipsViewerSource A0K;
    public static final ClipsViewerSource A0L;
    public static final ClipsViewerSource A0M;
    public static final ClipsViewerSource A0N;
    public static final ClipsViewerSource A0O;
    public static final ClipsViewerSource A0P;
    public static final ClipsViewerSource A0Q;
    public static final ClipsViewerSource A0R;
    public static final ClipsViewerSource A0S;
    public static final ClipsViewerSource A0T;
    public static final ClipsViewerSource A0U;
    public static final ClipsViewerSource A0V;
    public static final ClipsViewerSource A0W;
    public static final ClipsViewerSource A0X;
    public static final ClipsViewerSource A0Y;
    public static final ClipsViewerSource A0Z;
    public static final ClipsViewerSource A0a;
    public static final ClipsViewerSource A0b;
    public static final ClipsViewerSource A0c;
    public static final ClipsViewerSource A0d;
    public static final ClipsViewerSource A0e;
    public static final ClipsViewerSource A0f;
    public static final ClipsViewerSource A0g;
    public static final ClipsViewerSource A0h;
    public static final ClipsViewerSource A0i;
    public static final ClipsViewerSource A0j;
    public static final ClipsViewerSource A0k;
    public static final ClipsViewerSource A0l;
    public static final ClipsViewerSource A0m;
    public static final ClipsViewerSource A0n;
    public static final ClipsViewerSource A0o;
    public static final ClipsViewerSource A0p;
    public static final ClipsViewerSource A0q;
    public static final ClipsViewerSource A0r;
    public static final ClipsViewerSource A0s;
    public static final ClipsViewerSource A0t;
    public static final ClipsViewerSource A0u;
    public static final ClipsViewerSource A0v;
    public static final ClipsViewerSource A0w;
    public static final ClipsViewerSource A0x;
    public static final ClipsViewerSource A0y;
    public static final ClipsViewerSource A0z;
    public static final ClipsViewerSource A10;
    public static final ClipsViewerSource A11;
    public static final ClipsViewerSource A12;
    public static final ClipsViewerSource A13;
    public static final ClipsViewerSource A14;
    public static final ClipsViewerSource A15;
    public static final ClipsViewerSource A16;
    public static final ClipsViewerSource A17;
    public static final ClipsViewerSource A18;
    public static final ClipsViewerSource A19;
    public static final ClipsViewerSource A1A;
    public static final ClipsViewerSource A1B;
    public static final ClipsViewerSource A1C;
    public static final ClipsViewerSource A1D;
    public static final ClipsViewerSource A1E;
    public static final ClipsViewerSource A1F;
    public static final ClipsViewerSource A1G;
    public static final ClipsViewerSource A1H;
    public static final ClipsViewerSource A1I;
    public static final ClipsViewerSource A1J;
    public static final ClipsViewerSource A1K;
    public static final ClipsViewerSource A1L;
    public static final ClipsViewerSource A1M;
    public static final ClipsViewerSource A1N;
    public static final ClipsViewerSource A1O;
    public static final ClipsViewerSource A1P;
    public static final ClipsViewerSource A1Q;
    public static final ClipsViewerSource A1R;
    public static final ClipsViewerSource A1S;
    public static final ClipsViewerSource A1T;
    public static final ClipsViewerSource A1U;
    public static final ClipsViewerSource A1V;
    public static final ClipsViewerSource A1W;
    public static final ClipsViewerSource A1X;
    public static final ClipsViewerSource A1Y;
    public static final ClipsViewerSource A1Z;
    public static final ClipsViewerSource A1a;
    public static final ClipsViewerSource A1b;
    public static final ClipsViewerSource A1c;
    public static final ClipsViewerSource A1d;
    public static final ClipsViewerSource A1e;
    public static final ClipsViewerSource A1f;
    public static final ClipsViewerSource A1g;
    public static final ClipsViewerSource A1h;
    public static final ClipsViewerSource A1i;
    public static final ClipsViewerSource A1j;
    public static final ClipsViewerSource A1k;
    public static final ClipsViewerSource A1l;
    public static final ClipsViewerSource A1m;
    public static final ClipsViewerSource A1n;
    public static final ClipsViewerSource A1o;
    public static final ClipsViewerSource A1p;
    public static final ClipsViewerSource A1q;
    public static final ClipsViewerSource A1r;
    public static final ClipsViewerSource A1s;
    public static final ClipsViewerSource A1t;
    public static final ClipsViewerSource A1u;
    public static final ClipsViewerSource A1v;
    public static final ClipsViewerSource A1w;
    public static final ClipsViewerSource A1x;
    public static final ClipsViewerSource A1y;
    public static final ClipsViewerSource A1z;
    public static final ClipsViewerSource A20;
    public static final ClipsViewerSource A21;
    public static final ClipsViewerSource A22;
    public static final ClipsViewerSource A23;
    public static final ClipsViewerSource A24;
    public static final ClipsViewerSource A25;
    public static final ClipsViewerSource A26;
    public static final ClipsViewerSource A27;
    public static final ClipsViewerSource A28;
    public static final ClipsViewerSource A29;
    public static final ClipsViewerSource A2A;
    public static final ClipsViewerSource A2B;
    public static final ClipsViewerSource A2C;
    public static final ClipsViewerSource A2D;
    public static final ClipsViewerSource A2E;
    public static final ClipsViewerSource A2F;
    public static final ClipsViewerSource A2G;
    public static final ClipsViewerSource A2H;
    public static final ClipsViewerSource A2I;
    public static final ClipsViewerSource A2J;
    public static final ClipsViewerSource A2K;
    public static final ClipsViewerSource A2L;
    public static final ClipsViewerSource A2M;
    public static final ClipsViewerSource A2N;
    public static final ClipsViewerSource A2O;
    public static final ClipsViewerSource A2P;
    public static final ClipsViewerSource A2Q;
    public static final ClipsViewerSource A2R;
    public static final ClipsViewerSource A2S;
    public static final ClipsViewerSource A2T;
    public static final ClipsViewerSource A2U;
    public static final ClipsViewerSource A2V;
    public static final ClipsViewerSource A2W;
    public static final ClipsViewerSource A2X;
    public static final ClipsViewerSource A2Y;
    public static final ClipsViewerSource A2Z;
    public static final ClipsViewerSource A2a;
    public static final Parcelable.Creator CREATOR;
    public final String A00;

    @Override // android.os.Parcelable
    public final int describeContents() {
        return 0;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        C14360o3.A0B(parcel, 0);
        parcel.writeInt(ordinal());
    }

    static {
        ClipsViewerSource clipsViewerSource = new ClipsViewerSource("ACCOUNT_INSIGHTS", 0, "account_insights");
        A03 = clipsViewerSource;
        ClipsViewerSource clipsViewerSource2 = new ClipsViewerSource("ACTIVITY_CENTER", 1, "activity_center");
        A05 = clipsViewerSource2;
        ClipsViewerSource clipsViewerSource3 = new ClipsViewerSource("ADS_HISTORY", 2, "ads_history");
        A06 = clipsViewerSource3;
        ClipsViewerSource clipsViewerSource4 = new ClipsViewerSource("AR_EFFECT", 3, "effect_page");
        A08 = clipsViewerSource4;
        ClipsViewerSource clipsViewerSource5 = new ClipsViewerSource("AUDIO_NETEGO_PAGE", 4, "audio_netego_page");
        A09 = clipsViewerSource5;
        ClipsViewerSource clipsViewerSource6 = new ClipsViewerSource("AUDIO_PAGE_IN_CREATION", 5, "audio_page_in_creation");
        A0B = clipsViewerSource6;
        ClipsViewerSource clipsViewerSource7 = new ClipsViewerSource("BLEND", 6, "clips_blend");
        A0C = clipsViewerSource7;
        ClipsViewerSource clipsViewerSource8 = new ClipsViewerSource("BLOKS", 7, "bloks");
        A0D = clipsViewerSource8;
        ClipsViewerSource clipsViewerSource9 = new ClipsViewerSource("CAMERA_INSPIRATION_HUB", 8, "camera_inspiration_hub");
        A0H = clipsViewerSource9;
        ClipsViewerSource clipsViewerSource10 = new ClipsViewerSource("FEED_CONTEXTUAL_CHAIN", 9, "feed_contextual_chain");
        A1D = clipsViewerSource10;
        ClipsViewerSource clipsViewerSource11 = new ClipsViewerSource("CONTEXTUAL_HIGHLIGHT_CHAIN", 10, "contextual_chain");
        A0n = clipsViewerSource11;
        ClipsViewerSource clipsViewerSource12 = new ClipsViewerSource("DIRECT", 11, RealtimeConstants.GRAPHQL_SUBSCRIPTION_MESSAGE_TOPIC_FOR_DIRECT_TYPING);
        A0s = clipsViewerSource12;
        ClipsViewerSource clipsViewerSource13 = new ClipsViewerSource("DIRECT_SEARCH", 12, "direct_search");
        A0u = clipsViewerSource13;
        ClipsViewerSource clipsViewerSource14 = new ClipsViewerSource("DIRECT_AD_FEED_OF_ADS", 13, "direct_ad_feed_of_ads");
        A0t = clipsViewerSource14;
        ClipsViewerSource clipsViewerSource15 = new ClipsViewerSource("EXPLORE_GRID_AD_FEED_OF_ADS", 14, "explore_grid_ad_feed_of_ads");
        A0w = clipsViewerSource15;
        ClipsViewerSource clipsViewerSource16 = new ClipsViewerSource("EXPLORE_POPULAR_DEFAULT_UNIT", 15, "explore_popular_default_unit");
        A11 = clipsViewerSource16;
        ClipsViewerSource clipsViewerSource17 = new ClipsViewerSource("EXPLORE_INTEREST_DEFAULT_UNIT", 16, "explore_interest_default_unit");
        A0x = clipsViewerSource17;
        ClipsViewerSource clipsViewerSource18 = new ClipsViewerSource("EXPLORE_POPULAR_MAJOR_UNIT", 17, "explore_popular_major_unit");
        A12 = clipsViewerSource18;
        ClipsViewerSource clipsViewerSource19 = new ClipsViewerSource("EXPLORE_POPULAR_MINOR_UNIT", 18, "explore_popular_minor_unit");
        A13 = clipsViewerSource19;
        ClipsViewerSource clipsViewerSource20 = new ClipsViewerSource("EXPLORE_TRENDING_MINOR_UNIT", 19, "explore_trending_minor_unit");
        A15 = clipsViewerSource20;
        ClipsViewerSource clipsViewerSource21 = new ClipsViewerSource("EXPLORE_NEARBY_MINOR_UNIT", 20, "explore_nearby_minor_unit");
        A0z = clipsViewerSource21;
        ClipsViewerSource clipsViewerSource22 = new ClipsViewerSource("EXPLORE_INTEREST_MINOR_UNIT", 21, "explore_interest_minor_unit");
        A0y = clipsViewerSource22;
        ClipsViewerSource clipsViewerSource23 = new ClipsViewerSource("EXPLORE_POPULAR_AGGREGATE_TREND_MINOR_UNIT", 22, "explore_popular_aggregate_trend_minor_unit");
        A10 = clipsViewerSource23;
        ClipsViewerSource clipsViewerSource24 = new ClipsViewerSource("EXPLORE_VYML", 23, "explore_event_viewer");
        A17 = clipsViewerSource24;
        ClipsViewerSource clipsViewerSource25 = new ClipsViewerSource("EXPLORE_VIDEO_CHAINING", 24, "explore_video_chaining");
        A16 = clipsViewerSource25;
        ClipsViewerSource clipsViewerSource26 = new ClipsViewerSource("EXPLORE_TILE_TWO_BY_TWO", 25, "explore_tile_2x2");
        A14 = clipsViewerSource26;
        ClipsViewerSource clipsViewerSource27 = new ClipsViewerSource("CREATOR_INSPIRATION_HUB", 26, "creator_inspiration_hub");
        A0p = clipsViewerSource27;
        ClipsViewerSource clipsViewerSource28 = new ClipsViewerSource("FEED_LIKED", 27, "feed_liked");
        A1L = clipsViewerSource28;
        ClipsViewerSource clipsViewerSource29 = new ClipsViewerSource("CLIPS_FEED_LIKED", 28, "clips_feed_liked");
        A0J = clipsViewerSource29;
        ClipsViewerSource clipsViewerSource30 = new ClipsViewerSource("FEED_TIMELINE", 29, "feed_timeline");
        A1S = clipsViewerSource30;
        ClipsViewerSource clipsViewerSource31 = new ClipsViewerSource("FEED_TIMELINE_EXPLORE_STORY", 30, "feed_timeline_explore_story");
        A1T = clipsViewerSource31;
        ClipsViewerSource clipsViewerSource32 = new ClipsViewerSource("FEED_TIMELINE_MIXED_UNCONNECTED", 31, "feed_timeline_mixed_unconnected");
        A1X = clipsViewerSource32;
        ClipsViewerSource clipsViewerSource33 = new ClipsViewerSource("FEED_TIMELINE_FOLLOWING", 32, "feed_timeline_following");
        A1W = clipsViewerSource33;
        ClipsViewerSource clipsViewerSource34 = new ClipsViewerSource("FEED_TIMELINE_FAVORITES", 33, "feed_timeline_favorites");
        A1U = clipsViewerSource34;
        ClipsViewerSource clipsViewerSource35 = new ClipsViewerSource("FEED_TIMELINE_POST_TAP", 34, "feed_timeline_post_tap");
        A1Y = clipsViewerSource35;
        ClipsViewerSource clipsViewerSource36 = new ClipsViewerSource("FEED_TIMELINE_SEED_AD", 35, "feed_timeline_seed_ad");
        A1Z = clipsViewerSource36;
        ClipsViewerSource clipsViewerSource37 = new ClipsViewerSource("FEED_TIMELINE_FEED_OF_ADS", 36, "feed_timeline_feed_of_ads");
        A1V = clipsViewerSource37;
        ClipsViewerSource clipsViewerSource38 = new ClipsViewerSource("FEED_MULTI_ADS", 37, "feed_multi_ads");
        A1M = clipsViewerSource38;
        ClipsViewerSource clipsViewerSource39 = new ClipsViewerSource("FEED_MULTI_ADS_AD_CHAIN", 38, "feed_multi_ads_ad_chain");
        A1N = clipsViewerSource39;
        ClipsViewerSource clipsViewerSource40 = new ClipsViewerSource("FEED_PAE_MULTI_ADS", 39, "feed_pae_multi_ads");
        A1O = clipsViewerSource40;
        ClipsViewerSource clipsViewerSource41 = new ClipsViewerSource("FEED_PAE_MULTI_ADS_AD_CHAIN", 40, "feed_pae_multi_ads_ad_chain");
        A1P = clipsViewerSource41;
        ClipsViewerSource clipsViewerSource42 = new ClipsViewerSource("FEED_PAE_MULTI_ADS_WATCH_AND_BROWSE", 41, "feed_pae_multi_ads_watch_and_browse");
        A1Q = clipsViewerSource42;
        ClipsViewerSource clipsViewerSource43 = new ClipsViewerSource("FEED_SA_MULTI_ADS_WATCH_AND_BROWSE", 42, "feed_sa_multi_ads_watch_and_browse");
        A1R = clipsViewerSource43;
        ClipsViewerSource clipsViewerSource44 = new ClipsViewerSource("FEED_ADS_WATCH_AND_BROWSE", 43, "feed_timeline_watch_and_browse");
        A1A = clipsViewerSource44;
        ClipsViewerSource clipsViewerSource45 = new ClipsViewerSource("FEED_ADS_WATCH_AND_BROWSE_WITH_CHAINING", 44, "feed_timeline_watch_and_browse_with_chaining");
        A1B = clipsViewerSource45;
        ClipsViewerSource clipsViewerSource46 = new ClipsViewerSource("FEED_ADS_TALL_VIDEO_WATCH_AND_BROWSE_WITH_CHAINING", 45, "feed_timeline_tall_video_watch_and_browse_with_chaining");
        A19 = clipsViewerSource46;
        ClipsViewerSource clipsViewerSource47 = new ClipsViewerSource("HASHTAG", 46, "feed_hashtag");
        A1c = clipsViewerSource47;
        ClipsViewerSource clipsViewerSource48 = new ClipsViewerSource("IP_DISCOVER_ACCOUNTS", 47, "ip_discover_accounts");
        A1g = clipsViewerSource48;
        ClipsViewerSource clipsViewerSource49 = new ClipsViewerSource("LOCATION", 48, "discovery_map_location_detail");
        A1k = clipsViewerSource49;
        ClipsViewerSource clipsViewerSource50 = new ClipsViewerSource("KEYWORD", 49, "feed_keyword_minor_unit");
        A1h = clipsViewerSource50;
        ClipsViewerSource clipsViewerSource51 = new ClipsViewerSource("NEWSFEED_YOU", 50, "newsfeed_you");
        A1s = clipsViewerSource51;
        ClipsViewerSource clipsViewerSource52 = new ClipsViewerSource("PLAYLIST_NEWSFEED_YOU", 51, "playlist_newsfeed_you");
        A1x = clipsViewerSource52;
        ClipsViewerSource clipsViewerSource53 = new ClipsViewerSource("PROFILE", 52, "clips_profile");
        A20 = clipsViewerSource53;
        ClipsViewerSource clipsViewerSource54 = new ClipsViewerSource("GROUP_PROFILE", 53, "clips_group_profile");
        A1a = clipsViewerSource54;
        ClipsViewerSource clipsViewerSource55 = new ClipsViewerSource("REMIX_REEL", 54, "remix_reel");
        A28 = clipsViewerSource55;
        ClipsViewerSource clipsViewerSource56 = new ClipsViewerSource("REMIX_REEL_CTA", 55, "remix_reel_cta");
        A29 = clipsViewerSource56;
        ClipsViewerSource clipsViewerSource57 = new ClipsViewerSource("REMIX_REEL_NOTIFICATION_REMINDER", 56, "remix_reel_notification_reminder");
        A2A = clipsViewerSource57;
        ClipsViewerSource clipsViewerSource58 = new ClipsViewerSource("REMIX_ORIGINAL_REEL", 57, "remix_original_reel");
        A27 = clipsViewerSource58;
        ClipsViewerSource clipsViewerSource59 = new ClipsViewerSource("SEQUENCE_REEL", 58, "sequence_reel");
        A2G = clipsViewerSource59;
        ClipsViewerSource clipsViewerSource60 = new ClipsViewerSource("SEQUENCE_REEL_CTA", 59, "sequence_reel_cta");
        A2H = clipsViewerSource60;
        ClipsViewerSource clipsViewerSource61 = new ClipsViewerSource("SEQUENCE_ORIGINAL_REEL", 60, "sequence_original_reel");
        A2F = clipsViewerSource61;
        ClipsViewerSource clipsViewerSource62 = new ClipsViewerSource("FEED_CONTEXTUAL_PROFILE", 61, "feed_contextual_profile");
        A1I = clipsViewerSource62;
        ClipsViewerSource clipsViewerSource63 = new ClipsViewerSource("FEED_CONTEXTUAL_GROUP_PROFILE", 62, "feed_contextual_group_profile");
        A1G = clipsViewerSource63;
        ClipsViewerSource clipsViewerSource64 = new ClipsViewerSource("PLAYLIST_PUSH_NOTIF", 63, "playlist_push_notif");
        A1y = clipsViewerSource64;
        ClipsViewerSource clipsViewerSource65 = new ClipsViewerSource("PUSH_NOTIF", 64, "push_notif");
        A22 = clipsViewerSource65;
        ClipsViewerSource clipsViewerSource66 = new ClipsViewerSource("LIVE_PUSH_NOTIF", 65, "live_push_notif");
        A1i = clipsViewerSource66;
        ClipsViewerSource clipsViewerSource67 = new ClipsViewerSource("POST_LIVE", 66, "post_live");
        A1z = clipsViewerSource67;
        ClipsViewerSource clipsViewerSource68 = new ClipsViewerSource("REEL_FEED_TIMELINE", 67, "reel_feed_timeline");
        A26 = clipsViewerSource68;
        ClipsViewerSource clipsViewerSource69 = new ClipsViewerSource("REEL_CLIPS_NETEGO", 68, "reel_clips_netego");
        A25 = clipsViewerSource69;
        ClipsViewerSource clipsViewerSource70 = new ClipsViewerSource("SELF_PROFILE", 69, "self_clips_profile");
        A2E = clipsViewerSource70;
        ClipsViewerSource clipsViewerSource71 = new ClipsViewerSource("SERP_REELS_SUBTAB", 70, "serp_reels_subtab");
        A2J = clipsViewerSource71;
        ClipsViewerSource clipsViewerSource72 = new ClipsViewerSource("SERP_REELS_TRENDS_HCM", 71, "serp_reels_trends_hcm");
        A2K = clipsViewerSource72;
        ClipsViewerSource clipsViewerSource73 = new ClipsViewerSource("SERP_TOP_MINOR_UNIT", 72, "serp_top_minor_unit");
        A2L = clipsViewerSource73;
        ClipsViewerSource clipsViewerSource74 = new ClipsViewerSource("SERP_TOP_MIXED_CONTENT_MINOR_UNIT", 73, "serp_top_mixed_content_minor_unit");
        A2M = clipsViewerSource74;
        ClipsViewerSource clipsViewerSource75 = new ClipsViewerSource("SHOPPING_HOME", 74, "shopping_home");
        A2N = clipsViewerSource75;
        ClipsViewerSource clipsViewerSource76 = new ClipsViewerSource("SHOPPING_RECON_DESTINATION", 75, "shopping_reconsideration_destination");
        A2O = clipsViewerSource76;
        ClipsViewerSource clipsViewerSource77 = new ClipsViewerSource("PROMOTE_FLOW_ADS_PREVIEW", 76, "promote_flow_ads_preview");
        A21 = clipsViewerSource77;
        ClipsViewerSource clipsViewerSource78 = new ClipsViewerSource("FEED_CONTEXTUAL_SELF_PROFILE", 77, "feed_contextual_self_profile");
        A1K = clipsViewerSource78;
        ClipsViewerSource clipsViewerSource79 = new ClipsViewerSource("SAVE_COLLECTION", 78, "feed_contextual_saved_collections");
        A2D = clipsViewerSource79;
        ClipsViewerSource clipsViewerSource80 = new ClipsViewerSource("SONG", 79, "audio_page");
        A2Q = clipsViewerSource80;
        ClipsViewerSource clipsViewerSource81 = new ClipsViewerSource("AUDIO_PAGE_CHAIN", 80, "audio_page_chain");
        A0A = clipsViewerSource81;
        ClipsViewerSource clipsViewerSource82 = new ClipsViewerSource("THIRD_PARTY_URL", 81, "third_party_url");
        A2V = clipsViewerSource82;
        ClipsViewerSource clipsViewerSource83 = new ClipsViewerSource("TRENDS_PAGE", 82, "trends_page");
        A2X = clipsViewerSource83;
        ClipsViewerSource clipsViewerSource84 = new ClipsViewerSource("CLIPS_SAVED_TAB", 83, "feed_saved_collections_clips");
        A0e = clipsViewerSource84;
        ClipsViewerSource clipsViewerSource85 = new ClipsViewerSource("CLIPS_TAB", 84, "clips_tab");
        A0g = clipsViewerSource85;
        ClipsViewerSource clipsViewerSource86 = new ClipsViewerSource("CLIPS_CONNECTED", 85, "clips_connected");
        A0I = clipsViewerSource86;
        ClipsViewerSource clipsViewerSource87 = new ClipsViewerSource("CLIPS_NEARBY", 86, "clips_location");
        A0T = clipsViewerSource87;
        ClipsViewerSource clipsViewerSource88 = new ClipsViewerSource("CLIPS_NETEGO", 87, "clips_netego");
        A0V = clipsViewerSource88;
        ClipsViewerSource clipsViewerSource89 = new ClipsViewerSource("CLIPS_MEDIA_NOTES", 88, "clips_media_notes");
        A0M = clipsViewerSource89;
        ClipsViewerSource clipsViewerSource90 = new ClipsViewerSource("CLIPS_MEDIA_NOTES_NOTIF_CHAIN", 89, "clips_media_notes_notif_chain");
        A0N = clipsViewerSource90;
        ClipsViewerSource clipsViewerSource91 = new ClipsViewerSource("CLIPS_FRIENDLY_VIEWER_DOGFOODING", 90, "clips_friendly_viewer_dogfooding");
        A0K = clipsViewerSource91;
        ClipsViewerSource clipsViewerSource92 = new ClipsViewerSource("CLIPS_MULTI_ADS", 91, "clips_multi_ads");
        A0O = clipsViewerSource92;
        ClipsViewerSource clipsViewerSource93 = new ClipsViewerSource("CLIPS_MULTI_ADS_WATCH_AND_BROWSE", 92, "clips_multi_ads_watch_browse");
        A0R = clipsViewerSource93;
        ClipsViewerSource clipsViewerSource94 = new ClipsViewerSource("CLIPS_MULTI_ADS_FEED_OF_ADS", 93, "clips_multi_ads_feed_of_ads");
        A0P = clipsViewerSource94;
        ClipsViewerSource clipsViewerSource95 = new ClipsViewerSource("CLIPS_MUSIC_DROPS_NETEGO", 94, "clips_music_drops_netego");
        A0S = clipsViewerSource95;
        ClipsViewerSource clipsViewerSource96 = new ClipsViewerSource("CLIPS_PAE_MULTI_ADS_FEED_OF_ADS", 95, "clips_pae_multi_ads_feed_of_ads");
        A0Y = clipsViewerSource96;
        ClipsViewerSource clipsViewerSource97 = new ClipsViewerSource("CLIPS_MULTI_ADS_SEED_AD", 96, "clips_multi_ads_seed_ad");
        A0Q = clipsViewerSource97;
        ClipsViewerSource clipsViewerSource98 = new ClipsViewerSource("CLIPS_PAE_MULTI_ADS_SEED_AD", 97, "clips_pae_multi_ads_seed_ad");
        A0Z = clipsViewerSource98;
        ClipsViewerSource clipsViewerSource99 = new ClipsViewerSource("CLIPS_QUICK_PROMOTION_IN_FEED_UNIT", 98, "clips_qp_netego");
        A0c = clipsViewerSource99;
        ClipsViewerSource clipsViewerSource100 = new ClipsViewerSource("CLIPS_SUGGESTED_FEED_CONTEXTUAL_CHAIN", 99, "clips_suggested_feed_contextual_chain");
        A0f = clipsViewerSource100;
        ClipsViewerSource clipsViewerSource101 = new ClipsViewerSource("CLIPS_TEMPLATE", 100, "clips_template");
        A0h = clipsViewerSource101;
        ClipsViewerSource clipsViewerSource102 = new ClipsViewerSource("CLIPS_TRANSLATED_CLOSED_CAPTIONS_DOGFOODING", 101, "clips_translated_closed_captions_dogfooding");
        A0i = clipsViewerSource102;
        ClipsViewerSource clipsViewerSource103 = new ClipsViewerSource("CLIPS_TRENDING_IN_FEED_UNIT", 102, "clips_trending_netego");
        A0j = clipsViewerSource103;
        ClipsViewerSource clipsViewerSource104 = new ClipsViewerSource("CLIPS_VOICEOVER", 103, "clips_voiceover");
        A0k = clipsViewerSource104;
        ClipsViewerSource clipsViewerSource105 = new ClipsViewerSource("CLIPS_VOICE_TRANSLATION_DOGFOODING", 104, "clips_voice_translation_dogfooding");
        A0l = clipsViewerSource105;
        ClipsViewerSource clipsViewerSource106 = new ClipsViewerSource("CLIPS_PROMPT", 105, "clips_prompt");
        A0a = clipsViewerSource106;
        ClipsViewerSource clipsViewerSource107 = new ClipsViewerSource("CLIPS_OVERLAY_WATCH_MORE_REELS", 106, "clips_overlay_watch_more_reels");
        A0X = clipsViewerSource107;
        ClipsViewerSource clipsViewerSource108 = new ClipsViewerSource("MIXED_MEDIA_CHAINS", 107, "mixed_media_chains");
        A1q = clipsViewerSource108;
        ClipsViewerSource clipsViewerSource109 = new ClipsViewerSource("STAR_SEARCH", 108, "star_search");
        A2S = clipsViewerSource109;
        ClipsViewerSource clipsViewerSource110 = new ClipsViewerSource("ADS_ONLY", 109, "ads_only");
        A07 = clipsViewerSource110;
        ClipsViewerSource clipsViewerSource111 = new ClipsViewerSource("LIVE_SHOPPING_NETEGO", 110, "live_shopping_netego");
        A1j = clipsViewerSource111;
        ClipsViewerSource clipsViewerSource112 = new ClipsViewerSource("THREADS_APP", 111, "threads_app");
        A2W = clipsViewerSource112;
        ClipsViewerSource clipsViewerSource113 = new ClipsViewerSource("IGTV_APP", 112, "igtv_app");
        A1d = clipsViewerSource113;
        ClipsViewerSource clipsViewerSource114 = new ClipsViewerSource("ORIGINAL_CREATOR_VIDEO", 113, "original_creator_video");
        A1w = clipsViewerSource114;
        ClipsViewerSource clipsViewerSource115 = new ClipsViewerSource("VISUAL_REPLY", 114, "visual_reply");
        A2a = clipsViewerSource115;
        ClipsViewerSource clipsViewerSource116 = new ClipsViewerSource("CLIPS_QUESTION_RESPONSE", 115, "question_response");
        A0b = clipsViewerSource116;
        ClipsViewerSource clipsViewerSource117 = new ClipsViewerSource("SERIES", 116, "series");
        A2I = clipsViewerSource117;
        ClipsViewerSource clipsViewerSource118 = new ClipsViewerSource("BREAKING_CREATOR_LABEL", 117, "breaking_creator_label");
        A0G = clipsViewerSource118;
        ClipsViewerSource clipsViewerSource119 = new ClipsViewerSource("MONETIZATION_INBOX", 118, "monetization_inbox");
        A1r = clipsViewerSource119;
        ClipsViewerSource clipsViewerSource120 = new ClipsViewerSource("SAVED_AUDIO_NOTIFICATION", 119, "saved_audio_notification");
        A2C = clipsViewerSource120;
        ClipsViewerSource clipsViewerSource121 = new ClipsViewerSource("RECENTLY_DELETED", HucClient.BODY_UPLOAD_TIMEOUT_SECONDS, "recently_deleted");
        A24 = clipsViewerSource121;
        ClipsViewerSource clipsViewerSource122 = new ClipsViewerSource("SIMILAR_CREATORS", 121, "similar_creators");
        A2P = clipsViewerSource122;
        ClipsViewerSource clipsViewerSource123 = new ClipsViewerSource("FEED_CONTEXTUAL_FAN_CLUB", 122, "feed_contextual_fan_club");
        A1F = clipsViewerSource123;
        ClipsViewerSource clipsViewerSource124 = new ClipsViewerSource("FEED_CONTEXTUAL_SELF_FAN_CLUB", 123, "feed_contextual_self_fan_club");
        A1J = clipsViewerSource124;
        ClipsViewerSource clipsViewerSource125 = new ClipsViewerSource("FAN_CLUB", 124, "fan_club");
        A18 = clipsViewerSource125;
        ClipsViewerSource clipsViewerSource126 = new ClipsViewerSource("GROUP_PROFILE_PENDING_POSTS", 125, "group_profile_pending_posts");
        A1b = clipsViewerSource126;
        ClipsViewerSource clipsViewerSource127 = new ClipsViewerSource("BOARDS", 126, "boards");
        A0E = clipsViewerSource127;
        ClipsViewerSource clipsViewerSource128 = new ClipsViewerSource("RBS_PIVOT_PAGE", StringTreeSet.MAX_SYMBOL_COUNT, "rbs_pivot_page");
        A23 = clipsViewerSource128;
        ClipsViewerSource clipsViewerSource129 = new ClipsViewerSource("THIRD_PARTY_APP_PIVOT_PAGE", 128, "third_party_app_pivot_page");
        A2U = clipsViewerSource129;
        ClipsViewerSource clipsViewerSource130 = new ClipsViewerSource("MID_CARD", 129, "mid_card");
        A1l = clipsViewerSource130;
        ClipsViewerSource clipsViewerSource131 = new ClipsViewerSource("MID_CARD_CONTEXTUAL_CHAIN_WITH_RECIPE_SHEET_TRENDING_TRACK_WITH_SIMILAR_ACCOUNTS", 130, "midcard_trending_track_with_similar_accounts");
        A1m = clipsViewerSource131;
        ClipsViewerSource clipsViewerSource132 = new ClipsViewerSource("MID_CARD_OPEN_REELS_CHAIN", 131, "mid_card_open_reels_chain");
        A1o = clipsViewerSource132;
        ClipsViewerSource clipsViewerSource133 = new ClipsViewerSource("MID_CARD_INJECT_TOOL", 132, "mid_card_inject_tool");
        A1n = clipsViewerSource133;
        ClipsViewerSource clipsViewerSource134 = new ClipsViewerSource("MIFU_USE_AUDIO", 133, "mifu_use_audio");
        A1p = clipsViewerSource134;
        ClipsViewerSource clipsViewerSource135 = new ClipsViewerSource("FEED_CONTEXTUAL_KEYWORD", 134, "feed_contextual_keyword");
        A1H = clipsViewerSource135;
        ClipsViewerSource clipsViewerSource136 = new ClipsViewerSource("INTEREST_PIVOT_CHAIN", 135, "feed_interest_pivot_chain");
        A1f = clipsViewerSource136;
        ClipsViewerSource clipsViewerSource137 = new ClipsViewerSource("ACHIEVEMENTS_EARNED", 136, "achievements_earned");
        A04 = clipsViewerSource137;
        ClipsViewerSource clipsViewerSource138 = new ClipsViewerSource("FEED_CONTEXTUAL_ACCOUNT_HCM", 137, "feed_contextual_account_hcm");
        A1C = clipsViewerSource138;
        ClipsViewerSource clipsViewerSource139 = new ClipsViewerSource("TEXT_PAGE", 138, "text_page");
        A2T = clipsViewerSource139;
        ClipsViewerSource clipsViewerSource140 = new ClipsViewerSource("COMMENT_SHARE", 139, "comment_share");
        A0m = clipsViewerSource140;
        ClipsViewerSource clipsViewerSource141 = new ClipsViewerSource("BOOST", 140, "boost");
        A0F = clipsViewerSource141;
        ClipsViewerSource clipsViewerSource142 = new ClipsViewerSource("CLIPS_OVERLAY_ADS", 141, "clips_overlay_ads");
        A0W = clipsViewerSource142;
        ClipsViewerSource clipsViewerSource143 = new ClipsViewerSource("OPAL_USER_PROFILE", 142, "opal_feed_contextual_profile");
        A1t = clipsViewerSource143;
        ClipsViewerSource clipsViewerSource144 = new ClipsViewerSource("OPAL_USER_SELF_PROFILE", 143, "opal_feed_contextual_self_profile");
        A1u = clipsViewerSource144;
        ClipsViewerSource clipsViewerSource145 = new ClipsViewerSource("CLIPS_NEARBY_PUSH", 144, "clips_nearby_push");
        A0U = clipsViewerSource145;
        ClipsViewerSource clipsViewerSource146 = new ClipsViewerSource("CLIPS_HSCROLL", 145, "clips_hscroll");
        A0L = clipsViewerSource146;
        ClipsViewerSource clipsViewerSource147 = new ClipsViewerSource("FEED_CONTEXTUAL_CHAIN_SEED_AD", 146, "feed_contextual_chain_seed_ad");
        A1E = clipsViewerSource147;
        ClipsViewerSource clipsViewerSource148 = new ClipsViewerSource("CLIPS_REVIEW_TRANSLATED_DUBS", 147, "review_translated_dubs");
        A0d = clipsViewerSource148;
        ClipsViewerSource clipsViewerSource149 = new ClipsViewerSource("SPOTLIGHT", 148, "spotlight");
        A2R = clipsViewerSource149;
        ClipsViewerSource clipsViewerSource150 = new ClipsViewerSource("ORIGINALITY_INFO_LABEL", 149, "originality_info_label");
        A1v = clipsViewerSource150;
        ClipsViewerSource clipsViewerSource151 = new ClipsViewerSource("REVIEW_FOLLOWING_SCREEN", 150, "review_following_screen");
        A2B = clipsViewerSource151;
        ClipsViewerSource clipsViewerSource152 = new ClipsViewerSource("CREATOR_VIEWER_INSIGHT_MORE_SIMILAR_POPULAR_REELS", 151, "popular_with_your_followers");
        A0r = clipsViewerSource152;
        ClipsViewerSource clipsViewerSource153 = new ClipsViewerSource("IMMERSIVE_CATCH_UP", 152, "immersive_catch_up");
        A1e = clipsViewerSource153;
        ClipsViewerSource clipsViewerSource154 = new ClipsViewerSource("EDUCATION_HUB", 153, "education_hub");
        A0v = clipsViewerSource154;
        ClipsViewerSource clipsViewerSource155 = new ClipsViewerSource("CREATOR_DIGEST", 154, "creator_digest");
        A0o = clipsViewerSource155;
        ClipsViewerSource clipsViewerSource156 = new ClipsViewerSource("TRIALS", 155, "trials");
        A2Y = clipsViewerSource156;
        ClipsViewerSource clipsViewerSource157 = new ClipsViewerSource("CREATOR_INSPIRATION_SIGNALS_PLAYGROUND", 156, "creator_inspiration_signals_playground");
        A0q = clipsViewerSource157;
        ClipsViewerSource clipsViewerSource158 = new ClipsViewerSource("UNKNOWN", 157, GraphQLSubscriptionID.INAPP_NOTIFICATION_TYPE_DEFAULT);
        A2Z = clipsViewerSource158;
        ClipsViewerSource[] clipsViewerSourceArr = new ClipsViewerSource[158];
        System.arraycopy(new ClipsViewerSource[]{clipsViewerSource, clipsViewerSource2, clipsViewerSource3, clipsViewerSource4, clipsViewerSource5, clipsViewerSource6, clipsViewerSource7, clipsViewerSource8, clipsViewerSource9, clipsViewerSource10, clipsViewerSource11, clipsViewerSource12, clipsViewerSource13, clipsViewerSource14, clipsViewerSource15, clipsViewerSource16, clipsViewerSource17, clipsViewerSource18, clipsViewerSource19, clipsViewerSource20, clipsViewerSource21, clipsViewerSource22, clipsViewerSource23, clipsViewerSource24, clipsViewerSource25, clipsViewerSource26, clipsViewerSource27}, 0, clipsViewerSourceArr, 0, 27);
        System.arraycopy(new ClipsViewerSource[]{clipsViewerSource28, clipsViewerSource29, clipsViewerSource30, clipsViewerSource31, clipsViewerSource32, clipsViewerSource33, clipsViewerSource34, clipsViewerSource35, clipsViewerSource36, clipsViewerSource37, clipsViewerSource38, clipsViewerSource39, clipsViewerSource40, clipsViewerSource41, clipsViewerSource42, clipsViewerSource43, clipsViewerSource44, clipsViewerSource45, clipsViewerSource46, clipsViewerSource47, clipsViewerSource48, clipsViewerSource49, clipsViewerSource50, clipsViewerSource51, clipsViewerSource52, clipsViewerSource53, clipsViewerSource54}, 0, clipsViewerSourceArr, 27, 27);
        System.arraycopy(new ClipsViewerSource[]{clipsViewerSource55, clipsViewerSource56, clipsViewerSource57, clipsViewerSource58, clipsViewerSource59, clipsViewerSource60, clipsViewerSource61, clipsViewerSource62, clipsViewerSource63, clipsViewerSource64, clipsViewerSource65, clipsViewerSource66, clipsViewerSource67, clipsViewerSource68, clipsViewerSource69, clipsViewerSource70, clipsViewerSource71, clipsViewerSource72, clipsViewerSource73, clipsViewerSource74, clipsViewerSource75, clipsViewerSource76, clipsViewerSource77, clipsViewerSource78, clipsViewerSource79, clipsViewerSource80, clipsViewerSource81}, 0, clipsViewerSourceArr, 54, 27);
        System.arraycopy(new ClipsViewerSource[]{clipsViewerSource82, clipsViewerSource83, clipsViewerSource84, clipsViewerSource85, clipsViewerSource86, clipsViewerSource87, clipsViewerSource88, clipsViewerSource89, clipsViewerSource90, clipsViewerSource91, clipsViewerSource92, clipsViewerSource93, clipsViewerSource94, clipsViewerSource95, clipsViewerSource96, clipsViewerSource97, clipsViewerSource98, clipsViewerSource99, clipsViewerSource100, clipsViewerSource101, clipsViewerSource102, clipsViewerSource103, clipsViewerSource104, clipsViewerSource105, clipsViewerSource106, clipsViewerSource107, clipsViewerSource108}, 0, clipsViewerSourceArr, 81, 27);
        System.arraycopy(new ClipsViewerSource[]{clipsViewerSource109, clipsViewerSource110, clipsViewerSource111, clipsViewerSource112, clipsViewerSource113, clipsViewerSource114, clipsViewerSource115, clipsViewerSource116, clipsViewerSource117, clipsViewerSource118, clipsViewerSource119, clipsViewerSource120, clipsViewerSource121, clipsViewerSource122, clipsViewerSource123, clipsViewerSource124, clipsViewerSource125, clipsViewerSource126, clipsViewerSource127, clipsViewerSource128, clipsViewerSource129, clipsViewerSource130, clipsViewerSource131, clipsViewerSource132, clipsViewerSource133, clipsViewerSource134, clipsViewerSource135}, 0, clipsViewerSourceArr, 108, 27);
        System.arraycopy(new ClipsViewerSource[]{clipsViewerSource136, clipsViewerSource137, clipsViewerSource138, clipsViewerSource139, clipsViewerSource140, clipsViewerSource141, clipsViewerSource142, clipsViewerSource143, clipsViewerSource144, clipsViewerSource145, clipsViewerSource146, clipsViewerSource147, clipsViewerSource148, clipsViewerSource149, clipsViewerSource150, clipsViewerSource151, clipsViewerSource152, clipsViewerSource153, clipsViewerSource154, clipsViewerSource155, clipsViewerSource156, clipsViewerSource157, clipsViewerSource158}, 0, clipsViewerSourceArr, 135, 23);
        A02 = clipsViewerSourceArr;
        A01 = AbstractC12190kN.A00(clipsViewerSourceArr);
        CREATOR = new C206139Av(48);
    }

    public static ClipsViewerSource valueOf(String str) {
        return (ClipsViewerSource) Enum.valueOf(ClipsViewerSource.class, str);
    }

    public static ClipsViewerSource[] values() {
        return (ClipsViewerSource[]) A02.clone();
    }

    public final boolean A00() {
        if (this != A0t && this != A0w && this != A0P && this != A0Y && this != A1V && this != A1N && this != A1P && this != A1Q && this != A1R) {
            return false;
        }
        return true;
    }

    public final boolean A01() {
        if (this != A12 && this != A13 && this != A11 && this != A15 && this != A0z && this != A0y && this != A0x && this != A10 && this != A17 && this != A16 && this != A14) {
            return false;
        }
        return true;
    }

    public final boolean A02() {
        if (this != A20 && this != A1a && this != A1I && this != A1G && this != A1K && this != A2E && this != A1F && this != A1J && this != A1u && this != A1t) {
            return false;
        }
        return true;
    }

    public ClipsViewerSource(String str, int i, String str2) {
        this.A00 = str2;
        if (A02() && this != A1S && this != A1I && this != A1G && this != A1K && this != A1F && this != A1J && this != A1T && this != A1X && this != A1D) {
            ClipsViewerSource clipsViewerSource = A1W;
        }
    }
}
