package com.instagram.api.schemas;

import X.AbstractC12190kN;
import X.AbstractC16850sd;
import X.AbstractC62862SUj;
import X.C14360o3;
import X.C206149Aw;
import android.os.Parcel;
import android.os.Parcelable;
import com.facebook.common.dextricks.StringTreeSet;
import com.facebook.tigon.tigonhuc.HucClient;
import com.instagram.realtimeclient.RealtimeSubscription;
import java.util.LinkedHashMap;
import java.util.Map;
import kotlin.enums.EnumEntries;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: classes3.dex */
public final class CameraTool implements Parcelable {
    public static final Map A01;
    public static final /* synthetic */ EnumEntries A02;
    public static final /* synthetic */ CameraTool[] A03;
    public static final CameraTool A04;
    public static final CameraTool A05;
    public static final CameraTool A06;
    public static final CameraTool A07;
    public static final CameraTool A08;
    public static final CameraTool A09;
    public static final CameraTool A0A;
    public static final CameraTool A0B;
    public static final CameraTool A0C;
    public static final CameraTool A0D;
    public static final CameraTool A0E;
    public static final CameraTool A0F;
    public static final CameraTool A0G;
    public static final CameraTool A0H;
    public static final CameraTool A0I;
    public static final CameraTool A0J;
    public static final CameraTool A0K;
    public static final CameraTool A0L;
    public static final CameraTool A0M;
    public static final CameraTool A0N;
    public static final CameraTool A0O;
    public static final CameraTool A0P;
    public static final CameraTool A0Q;
    public static final CameraTool A0R;
    public static final CameraTool A0S;
    public static final CameraTool A0T;
    public static final CameraTool A0U;
    public static final CameraTool A0V;
    public static final CameraTool A0W;
    public static final CameraTool A0X;
    public static final CameraTool A0Y;
    public static final CameraTool A0Z;
    public static final CameraTool A0a;
    public static final CameraTool A0b;
    public static final CameraTool A0c;
    public static final CameraTool A0d;
    public static final CameraTool A0e;
    public static final CameraTool A0f;
    public static final CameraTool A0g;
    public static final CameraTool A0h;
    public static final CameraTool A0i;
    public static final CameraTool A0j;
    public static final CameraTool A0k;
    public static final CameraTool A0l;
    public static final CameraTool A0m;
    public static final CameraTool A0n;
    public static final CameraTool A0o;
    public static final CameraTool A0p;
    public static final CameraTool A0q;
    public static final CameraTool A0r;
    public static final CameraTool A0s;
    public static final CameraTool A0t;
    public static final CameraTool A0u;
    public static final CameraTool A0v;
    public static final CameraTool A0w;
    public static final CameraTool A0x;
    public static final CameraTool A0y;
    public static final CameraTool A0z;
    public static final CameraTool A10;
    public static final CameraTool A11;
    public static final CameraTool A12;
    public static final CameraTool A13;
    public static final CameraTool A14;
    public static final CameraTool A15;
    public static final CameraTool A16;
    public static final CameraTool A17;
    public static final CameraTool A18;
    public static final CameraTool A19;
    public static final CameraTool A1A;
    public static final CameraTool A1B;
    public static final CameraTool A1C;
    public static final CameraTool A1D;
    public static final CameraTool A1E;
    public static final CameraTool A1F;
    public static final CameraTool A1G;
    public static final CameraTool A1H;
    public static final CameraTool A1I;
    public static final CameraTool A1J;
    public static final CameraTool A1K;
    public static final CameraTool A1L;
    public static final CameraTool A1M;
    public static final CameraTool A1N;
    public static final CameraTool A1O;
    public static final CameraTool A1P;
    public static final CameraTool A1Q;
    public static final CameraTool A1R;
    public static final CameraTool A1S;
    public static final CameraTool A1T;
    public static final CameraTool A1U;
    public static final CameraTool A1V;
    public static final CameraTool A1W;
    public static final CameraTool A1X;
    public static final CameraTool A1Y;
    public static final CameraTool A1Z;
    public static final CameraTool A1a;
    public static final CameraTool A1b;
    public static final CameraTool A1c;
    public static final CameraTool A1d;
    public static final CameraTool A1e;
    public static final CameraTool A1f;
    public static final CameraTool A1g;
    public static final CameraTool A1h;
    public static final CameraTool A1i;
    public static final CameraTool A1j;
    public static final CameraTool A1k;
    public static final CameraTool A1l;
    public static final CameraTool A1m;
    public static final CameraTool A1n;
    public static final CameraTool A1o;
    public static final CameraTool A1p;
    public static final CameraTool A1q;
    public static final CameraTool A1r;
    public static final CameraTool A1s;
    public static final CameraTool A1t;
    public static final CameraTool A1u;
    public static final CameraTool A1v;
    public static final CameraTool A1w;
    public static final CameraTool A1x;
    public static final CameraTool A1y;
    public static final CameraTool A1z;
    public static final CameraTool A20;
    public static final CameraTool A21;
    public static final CameraTool A22;
    public static final CameraTool A23;
    public static final CameraTool A24;
    public static final CameraTool A25;
    public static final CameraTool A26;
    public static final CameraTool A27;
    public static final CameraTool A28;
    public static final CameraTool A29;
    public static final CameraTool A2A;
    public static final CameraTool A2B;
    public static final CameraTool A2C;
    public static final CameraTool A2D;
    public static final CameraTool A2E;
    public static final CameraTool A2F;
    public static final CameraTool A2G;
    public static final CameraTool A2H;
    public static final CameraTool A2I;
    public static final CameraTool A2J;
    public static final CameraTool A2K;
    public static final CameraTool A2L;
    public static final CameraTool A2M;
    public static final CameraTool A2N;
    public static final CameraTool A2O;
    public static final CameraTool A2P;
    public static final CameraTool A2Q;
    public static final CameraTool A2R;
    public static final CameraTool A2S;
    public static final CameraTool A2T;
    public static final CameraTool A2U;
    public static final CameraTool A2V;
    public static final CameraTool A2W;
    public static final CameraTool A2X;
    public static final CameraTool A2Y;
    public static final CameraTool A2Z;
    public static final CameraTool A2a;
    public static final CameraTool A2b;
    public static final CameraTool A2c;
    public static final CameraTool A2d;
    public static final CameraTool A2e;
    public static final CameraTool A2f;
    public static final CameraTool A2g;
    public static final CameraTool A2h;
    public static final CameraTool A2i;
    public static final CameraTool A2j;
    public static final CameraTool A2k;
    public static final CameraTool A2l;
    public static final CameraTool A2m;
    public static final CameraTool A2n;
    public static final CameraTool A2o;
    public static final CameraTool A2p;
    public static final CameraTool A2q;
    public static final CameraTool A2r;
    public static final CameraTool A2s;
    public static final CameraTool A2t;
    public static final CameraTool A2u;
    public static final CameraTool A2v;
    public static final CameraTool A2w;
    public static final CameraTool A2x;
    public static final CameraTool A2y;
    public static final CameraTool A2z;
    public static final CameraTool A30;
    public static final CameraTool A31;
    public static final CameraTool A32;
    public static final CameraTool A33;
    public static final CameraTool A34;
    public static final CameraTool A35;
    public static final CameraTool A36;
    public static final CameraTool A37;
    public static final CameraTool A38;
    public static final CameraTool A39;
    public static final CameraTool A3A;
    public static final CameraTool A3B;
    public static final CameraTool A3C;
    public static final CameraTool A3D;
    public static final CameraTool A3E;
    public static final CameraTool A3F;
    public static final CameraTool A3G;
    public static final CameraTool A3H;
    public static final CameraTool A3I;
    public static final CameraTool A3J;
    public static final CameraTool A3K;
    public static final CameraTool A3L;
    public static final CameraTool A3M;
    public static final Parcelable.Creator CREATOR;
    public final String A00;

    @Override // android.os.Parcelable
    public final int describeContents() {
        return 0;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        C14360o3.A0B(parcel, 0);
        parcel.writeInt(ordinal());
    }

    static {
        CameraTool cameraTool = new CameraTool("UNRECOGNIZED", 0, "CameraTool_unspecified");
        A3E = cameraTool;
        CameraTool cameraTool2 = new CameraTool("ADD_YOURS", 1, "44");
        A04 = cameraTool2;
        CameraTool cameraTool3 = new CameraTool("ADD_YOURS_TEMPLATES_PRECAP", 2, "257");
        A05 = cameraTool3;
        CameraTool cameraTool4 = new CameraTool("ADJUST_PITCH", 3, "284");
        A06 = cameraTool4;
        CameraTool cameraTool5 = new CameraTool("ADJUST_ROLL", 4, "283");
        A07 = cameraTool5;
        CameraTool cameraTool6 = new CameraTool("ADJUST_STRAIGHTEN", 5, "285");
        A08 = cameraTool6;
        CameraTool cameraTool7 = new CameraTool("AI_CONTEXTUAL_BACKGROUND", 6, "248");
        A09 = cameraTool7;
        CameraTool cameraTool8 = new CameraTool("AI_EXPANDER", 7, "228");
        A0A = cameraTool8;
        CameraTool cameraTool9 = new CameraTool("AI_REWRITE", 8, "250");
        A0B = cameraTool9;
        CameraTool cameraTool10 = new CameraTool("AI_REWRITE_TEXT", 9, "252");
        A0C = cameraTool10;
        CameraTool cameraTool11 = new CameraTool("AI_REWRITE_TONE", 10, "251");
        A0D = cameraTool11;
        CameraTool cameraTool12 = new CameraTool("AI_REWRITE_WITH_META_AI_INTENT", 11, "261");
        A0E = cameraTool12;
        CameraTool cameraTool13 = new CameraTool("ALIGN_MODE", 12, "15");
        A0F = cameraTool13;
        CameraTool cameraTool14 = new CameraTool("APPEARANCE_EFFECT", 13, "22");
        A0G = cameraTool14;
        CameraTool cameraTool15 = new CameraTool("AR_EFFECT", 14, "81");
        A0H = cameraTool15;
        CameraTool cameraTool16 = new CameraTool("AR_STICKERS", 15, "40");
        A0I = cameraTool16;
        CameraTool cameraTool17 = new CameraTool("ASPECT_RATIO", 16, "87");
        A0J = cameraTool17;
        CameraTool cameraTool18 = new CameraTool("AUTO_TRIM", 17, "95");
        A0K = cameraTool18;
        CameraTool cameraTool19 = new CameraTool("BACKDROP", 18, "68");
        A0L = cameraTool19;
        CameraTool cameraTool20 = new CameraTool("BOOMERANG", 19, RealtimeSubscription.GRAPHQL_MQTT_VERSION);
        A0M = cameraTool20;
        CameraTool cameraTool21 = new CameraTool("BRIGHTNESS", 20, "153");
        A0N = cameraTool21;
        CameraTool cameraTool22 = new CameraTool("CAMERA_ICON", 21, "96");
        A0O = cameraTool22;
        CameraTool cameraTool23 = new CameraTool("CAMERA_SETTING", 22, "114");
        A0P = cameraTool23;
        CameraTool cameraTool24 = new CameraTool("CAMERA_SWITCH", 23, "89");
        A0Q = cameraTool24;
        CameraTool cameraTool25 = new CameraTool("CAROUSEL_CLIPS_FORMAT_SWITCHER", 24, "279");
        A0R = cameraTool25;
        CameraTool cameraTool26 = new CameraTool("CATEGORY_ADS_AND_MONETIZATION", 25, "301");
        A0S = cameraTool26;
        CameraTool cameraTool27 = new CameraTool("CATEGORY_AUDIENCE", 26, "299");
        A0T = cameraTool27;
        CameraTool cameraTool28 = new CameraTool("CATEGORY_XPOSTING", 27, "300");
        A0U = cameraTool28;
        CameraTool cameraTool29 = new CameraTool("CLIPS_ADD", 28, "110");
        A0V = cameraTool29;
        CameraTool cameraTool30 = new CameraTool("COLLAGE", 29, "36");
        A0W = cameraTool30;
        CameraTool cameraTool31 = new CameraTool("COLOR_FILTER", 30, "84");
        A0X = cameraTool31;
        CameraTool cameraTool32 = new CameraTool("COLOR_FILTERS", 31, "25");
        A0Y = cameraTool32;
        CameraTool cameraTool33 = new CameraTool("COMMENT_PROMPTS", 32, "253");
        A0Z = cameraTool33;
        CameraTool cameraTool34 = new CameraTool("CONTENT_BASED_HASHTAG_SUGGESTION", 33, "266");
        A0a = cameraTool34;
        CameraTool cameraTool35 = new CameraTool("CONTRAST", 34, "154");
        A0b = cameraTool35;
        CameraTool cameraTool36 = new CameraTool("COVER_PHOTO_ADD", 35, "123");
        A0c = cameraTool36;
        CameraTool cameraTool37 = new CameraTool("CREATE", 36, "4");
        A0d = cameraTool37;
        CameraTool cameraTool38 = new CameraTool("CREATE_MODE_FORMAT", 37, "113");
        A0e = cameraTool38;
        CameraTool cameraTool39 = new CameraTool("CREATE_MODE_RANDOM", 38, "138");
        A0f = cameraTool39;
        CameraTool cameraTool40 = new CameraTool("CREATE_MODE_SUB_FORMAT", 39, "127");
        A0g = cameraTool40;
        CameraTool cameraTool41 = new CameraTool("CRUNCHY", 40, "79");
        A0h = cameraTool41;
        CameraTool cameraTool42 = new CameraTool("CUTOUT_MONTAGE", 41, "55");
        A0i = cameraTool42;
        CameraTool cameraTool43 = new CameraTool("DANCIFICATION", 42, "37");
        A0j = cameraTool43;
        CameraTool cameraTool44 = new CameraTool("DIRECT_ADD_YOURS", 43, "49");
        A0k = cameraTool44;
        CameraTool cameraTool45 = new CameraTool("DIRECT_ROLL_CALL", 44, "50");
        A0l = cameraTool45;
        CameraTool cameraTool46 = new CameraTool("DREAMY", 45, "71");
        A0m = cameraTool46;
        CameraTool cameraTool47 = new CameraTool("DUAL", 46, "18");
        A0n = cameraTool47;
        CameraTool cameraTool48 = new CameraTool("DUAL_ON_REELS", 47, "34");
        A0o = cameraTool48;
        CameraTool cameraTool49 = new CameraTool("DURATION_15_SEC", 48, "26");
        A0p = cameraTool49;
        CameraTool cameraTool50 = new CameraTool("DURATION_30_SEC", 49, "27");
        A0q = cameraTool50;
        CameraTool cameraTool51 = new CameraTool("DURATION_60_SEC", 50, "45");
        A0r = cameraTool51;
        CameraTool cameraTool52 = new CameraTool("DURATION_90_SEC", 51, "46");
        A0s = cameraTool52;
        CameraTool cameraTool53 = new CameraTool("DURATION_SELECTOR", 52, "16");
        A0t = cameraTool53;
        CameraTool cameraTool54 = new CameraTool("EDIT_CLIP_SELECTOR", 53, "39");
        A0u = cameraTool54;
        CameraTool cameraTool55 = new CameraTool("EFFECT_SELECTOR", 54, "7");
        A0v = cameraTool55;
        CameraTool cameraTool56 = new CameraTool("FACE_DETECTOR", 55, "82");
        A0w = cameraTool56;
        CameraTool cameraTool57 = new CameraTool("FADE", 56, "157");
        A0x = cameraTool57;
        CameraTool cameraTool58 = new CameraTool("FEED_EDIT_TOOL_BAR", 57, "282");
        A0y = cameraTool58;
        CameraTool cameraTool59 = new CameraTool("FLASH", 58, "60");
        A0z = cameraTool59;
        CameraTool cameraTool60 = new CameraTool("FLIP_CAMERA", 59, "62");
        A10 = cameraTool60;
        CameraTool cameraTool61 = new CameraTool("FUNDED_CONTENT", 60, "119");
        A11 = cameraTool61;
        CameraTool cameraTool62 = new CameraTool("GALLERY_ALBUM_PICKER", 61, "94");
        A12 = cameraTool62;
        CameraTool cameraTool63 = new CameraTool("GALLERY_CONTEXT_MENU", 62, "112");
        A13 = cameraTool63;
        CameraTool cameraTool64 = new CameraTool("GALLERY_TIMELINE_SCRUBBER", 63, "61");
        A14 = cameraTool64;
        CameraTool cameraTool65 = new CameraTool("GALLERY_TOOLBAR", 64, "58");
        A15 = cameraTool65;
        CameraTool cameraTool66 = new CameraTool("GESTURE_CONTROL", 65, "42");
        A16 = cameraTool66;
        CameraTool cameraTool67 = new CameraTool("GREEN_SCREEN", 66, "54");
        A17 = cameraTool67;
        CameraTool cameraTool68 = new CameraTool("GRID_MODE", 67, "17");
        A18 = cameraTool68;
        CameraTool cameraTool69 = new CameraTool("HANDS_FREE", 68, "2");
        A19 = cameraTool69;
        CameraTool cameraTool70 = new CameraTool("HIDE_SHARE_COUNT", 69, "260");
        A1A = cameraTool70;
        CameraTool cameraTool71 = new CameraTool("HIGHLIGHTS", 70, "158");
        A1B = cameraTool71;
        CameraTool cameraTool72 = new CameraTool("HIGHLIGHTS_COLOR", 71, "287");
        A1C = cameraTool72;
        CameraTool cameraTool73 = new CameraTool("HORIZON", 72, "43");
        A1D = cameraTool73;
        CameraTool cameraTool74 = new CameraTool("IMAGE_TO_TEXT_WITH_META_AI_INTENT", 73, "278");
        A1E = cameraTool74;
        CameraTool cameraTool75 = new CameraTool("IMAGINE", 74, "224");
        A1F = cameraTool75;
        CameraTool cameraTool76 = new CameraTool("IMAGINE_BUNDLE", 75, "263");
        A1G = cameraTool76;
        CameraTool cameraTool77 = new CameraTool("IMAGINE_BUNDLE_WITH_META_AI_INTENT", 76, "262");
        A1H = cameraTool77;
        CameraTool cameraTool78 = new CameraTool("IMAGINE_ME", 77, "225");
        A1I = cameraTool78;
        CameraTool cameraTool79 = new CameraTool("IMAGINE_ME_WITH_META_AI_INTENT", 78, "265");
        A1J = cameraTool79;
        CameraTool cameraTool80 = new CameraTool("IMAGINE_WITH_META_AI_INTENT", 79, "264");
        A1K = cameraTool80;
        CameraTool cameraTool81 = new CameraTool("INTERNAL_TOGGLE", 80, "305");
        A1L = cameraTool81;
        CameraTool cameraTool82 = new CameraTool("LAYOUT", 81, "3");
        A1M = cameraTool82;
        CameraTool cameraTool83 = new CameraTool("LAYOUT_SCALE", 82, "133");
        A1N = cameraTool83;
        CameraTool cameraTool84 = new CameraTool("LAYOUT_VARIANTS", 83, "142");
        A1O = cameraTool84;
        CameraTool cameraTool85 = new CameraTool("LIVE_AUDIENCE", 84, "23");
        A1P = cameraTool85;
        CameraTool cameraTool86 = new CameraTool("LIVE_BADGES", 85, "11");
        A1Q = cameraTool86;
        CameraTool cameraTool87 = new CameraTool("LIVE_FUNDRAISER", 86, "10");
        A1R = cameraTool87;
        CameraTool cameraTool88 = new CameraTool("LIVE_GAMES", 87, "76");
        A1S = cameraTool88;
        CameraTool cameraTool89 = new CameraTool("LIVE_INTERNAL", 88, "9");
        A1T = cameraTool89;
        CameraTool cameraTool90 = new CameraTool("LIVE_PHOTO_OFF", 89, "59");
        A1U = cameraTool90;
        CameraTool cameraTool91 = new CameraTool("LIVE_PHOTO_ON", 90, "57");
        A1V = cameraTool91;
        CameraTool cameraTool92 = new CameraTool("LIVE_PROMPTS", 91, "66");
        A1W = cameraTool92;
        CameraTool cameraTool93 = new CameraTool("LIVE_SCHEDULING", 92, "33");
        A1X = cameraTool93;
        CameraTool cameraTool94 = new CameraTool("LIVE_SHOPPING", 93, "30");
        A1Y = cameraTool94;
        CameraTool cameraTool95 = new CameraTool("LIVE_SUBSCRIBE", 94, "41");
        A1Z = cameraTool95;
        CameraTool cameraTool96 = new CameraTool("LIVE_TITLE", 95, "12");
        A1a = cameraTool96;
        CameraTool cameraTool97 = new CameraTool("LIVE_TRIVIA", 96, "64");
        A1b = cameraTool97;
        CameraTool cameraTool98 = new CameraTool("LIVE_VIDEO_TOGGLE", 97, "31");
        A1c = cameraTool98;
        CameraTool cameraTool99 = new CameraTool("LUX", 98, "281");
        A1d = cameraTool99;
        CameraTool cameraTool100 = new CameraTool("MAGICMOD_BUNDLE", 99, "77");
        A1e = cameraTool100;
        CameraTool cameraTool101 = new CameraTool("MAGIC_CUT", 100, "306");
        A1f = cameraTool101;
        CameraTool cameraTool102 = new CameraTool("MEME_HUB", 101, "249");
        A1g = cameraTool102;
        CameraTool cameraTool103 = new CameraTool("MEMU_IN_FEED", 102, "272");
        A1h = cameraTool103;
        CameraTool cameraTool104 = new CameraTool("MEMU_IN_FEED_WITH_MIMICRY", 103, "277");
        A1i = cameraTool104;
        CameraTool cameraTool105 = new CameraTool("MONTAGE", 104, "35");
        A1j = cameraTool105;
        CameraTool cameraTool106 = new CameraTool("MOTION_FILTER", 105, "28");
        A1k = cameraTool106;
        CameraTool cameraTool107 = new CameraTool("MULTICAPTURE", 106, "21");
        A1l = cameraTool107;
        CameraTool cameraTool108 = new CameraTool("MUSIC_ARTIST", 107, "98");
        A1m = cameraTool108;
        CameraTool cameraTool109 = new CameraTool("MUSIC_BROWSER", 108, "88");
        A1n = cameraTool109;
        CameraTool cameraTool110 = new CameraTool("MUSIC_BROWSER_VOLUME", 109, "131");
        A1o = cameraTool110;
        CameraTool cameraTool111 = new CameraTool("MUSIC_CHANGE", 110, "125");
        A1p = cameraTool111;
        CameraTool cameraTool112 = new CameraTool("MUSIC_SAVED_AUDIO_TAB", 111, "109");
        A1q = cameraTool112;
        CameraTool cameraTool113 = new CameraTool("MUSIC_SAVE_TO_CAMERA", 112, "129");
        A1r = cameraTool113;
        CameraTool cameraTool114 = new CameraTool("MUSIC_SELECTOR", 113, "32");
        A1s = cameraTool114;
        CameraTool cameraTool115 = new CameraTool("MUTE", 114, "8");
        A1t = cameraTool115;
        CameraTool cameraTool116 = new CameraTool("NO_FILTER", 115, "80");
        A1u = cameraTool116;
        CameraTool cameraTool117 = new CameraTool("OCULUS", 116, "65");
        A1v = cameraTool117;
        CameraTool cameraTool118 = new CameraTool("PHOTOBOOTH", 117, "29");
        A1w = cameraTool118;
        CameraTool cameraTool119 = new CameraTool("PHOTO_DUMP", 118, "63");
        A1x = cameraTool119;
        CameraTool cameraTool120 = new CameraTool("POSES", 119, "6");
        A1y = cameraTool120;
        CameraTool cameraTool121 = new CameraTool("PROFILE_COVER_PHOTO_CROP", HucClient.BODY_UPLOAD_TIMEOUT_SECONDS, "126");
        A1z = cameraTool121;
        CameraTool cameraTool122 = new CameraTool("PROMPT_PICKER", 121, "121");
        A20 = cameraTool122;
        CameraTool cameraTool123 = new CameraTool("RADIO", 122, "78");
        A21 = cameraTool123;
        CameraTool cameraTool124 = new CameraTool("RECIPIENT_PICKER", 123, "92");
        A22 = cameraTool124;
        CameraTool cameraTool125 = new CameraTool("REMIX_AUDIO", 124, "20");
        A23 = cameraTool125;
        CameraTool cameraTool126 = new CameraTool("REMIX_LAYOUT", 125, "19");
        A24 = cameraTool126;
        CameraTool cameraTool127 = new CameraTool("REORDER", 126, "122");
        A25 = cameraTool127;
        CameraTool cameraTool128 = new CameraTool("RESTYLE", StringTreeSet.MAX_SYMBOL_COUNT, "67");
        A26 = cameraTool128;
        CameraTool cameraTool129 = new CameraTool("RETAKE", 128, "147");
        A27 = cameraTool129;
        CameraTool cameraTool130 = new CameraTool("ROLL_CALL", 129, "48");
        A28 = cameraTool130;
        CameraTool cameraTool131 = new CameraTool("ROLL_CALL_DIRECT", 130, "148");
        A29 = cameraTool131;
        CameraTool cameraTool132 = new CameraTool("SATURATION", 131, "156");
        A2A = cameraTool132;
        CameraTool cameraTool133 = new CameraTool("SAVED_AUDIO_IN_CLIPS_GALLERY", 132, "280");
        A2B = cameraTool133;
        CameraTool cameraTool134 = new CameraTool("SCALE", 133, "56");
        A2C = cameraTool134;
        CameraTool cameraTool135 = new CameraTool("SCALE_MODE", 134, "146");
        A2D = cameraTool135;
        CameraTool cameraTool136 = new CameraTool("SELECT_FORMAT", 135, "107");
        A2E = cameraTool136;
        CameraTool cameraTool137 = new CameraTool("SELECT_SEGMENT", 136, "102");
        A2F = cameraTool137;
        CameraTool cameraTool138 = new CameraTool("SETTING_CLIPS_TO_FEED", 137, "106");
        A2G = cameraTool138;
        CameraTool cameraTool139 = new CameraTool("SETTING_CONTROL", 138, "139");
        A2H = cameraTool139;
        CameraTool cameraTool140 = new CameraTool("SETTING_HIDE_USER", 139, "101");
        A2I = cameraTool140;
        CameraTool cameraTool141 = new CameraTool("SETTING_PRELOAD", 140, "103");
        A2J = cameraTool141;
        CameraTool cameraTool142 = new CameraTool("SETTING_RECOMMEND_ON_FB", 141, "140");
        A2K = cameraTool142;
        CameraTool cameraTool143 = new CameraTool("SETTING_SAVE_TO_CAMERA_ROLL", 142, "136");
        A2L = cameraTool143;
        CameraTool cameraTool144 = new CameraTool("SETTING_SHARE_TO_FB_ACCESS", 143, "128");
        A2M = cameraTool144;
        CameraTool cameraTool145 = new CameraTool("SETTING_SHARE_TO_FB_SELECT", 144, "134");
        A2N = cameraTool145;
        CameraTool cameraTool146 = new CameraTool("SETTING_SHARE_TO_FEED_UNSELECT", 145, "132");
        A2O = cameraTool146;
        CameraTool cameraTool147 = new CameraTool("SETTING_UNHIDE_USER", 146, "100");
        A2P = cameraTool147;
        CameraTool cameraTool148 = new CameraTool("SHADOWS", 147, "159");
        A2Q = cameraTool148;
        CameraTool cameraTool149 = new CameraTool("SHADOWS_COLOR", 148, "286");
        A2R = cameraTool149;
        CameraTool cameraTool150 = new CameraTool("SHARE_SHEET_INTEREST_TOPIC_SELECT", 149, "120");
        A2S = cameraTool150;
        CameraTool cameraTool151 = new CameraTool("SHARE_SHEET_INTEREST_TOPIC_UNSELECT", 150, "135");
        A2T = cameraTool151;
        CameraTool cameraTool152 = new CameraTool("SHARE_TO_BARCELONA", 151, "303");
        A2U = cameraTool152;
        CameraTool cameraTool153 = new CameraTool("SHARE_TO_FB_OPTION", 152, "105");
        A2V = cameraTool153;
        CameraTool cameraTool154 = new CameraTool("SHARE_TO_FB_PRIMER", 153, "124");
        A2W = cameraTool154;
        CameraTool cameraTool155 = new CameraTool("SHARE_TO_FB_TOGGLE_SHARE_TYPE", 154, "141");
        A2X = cameraTool155;
        CameraTool cameraTool156 = new CameraTool("SHARE_TO_INSTAGRAM", 155, "302");
        A2Y = cameraTool156;
        CameraTool cameraTool157 = new CameraTool("SHARPEN", 156, "161");
        A2Z = cameraTool157;
        CameraTool cameraTool158 = new CameraTool("SLOWED", 157, "70");
        A2a = cameraTool158;
        CameraTool cameraTool159 = new CameraTool("SMART_TRACKING", 158, "51");
        A2b = cameraTool159;
        CameraTool cameraTool160 = new CameraTool("SOUND_SYNC", 159, "38");
        A2c = cameraTool160;
        CameraTool cameraTool161 = new CameraTool("SOUND_SYNC_LAYOUT_EFFECT", 160, "152");
        A2d = cameraTool161;
        CameraTool cameraTool162 = new CameraTool("SPED_UP", 161, "72");
        A2e = cameraTool162;
        CameraTool cameraTool163 = new CameraTool("SPEED_SELECTOR", 162, "13");
        A2f = cameraTool163;
        CameraTool cameraTool164 = new CameraTool("SPEED_SLIDER", 163, "143");
        A2g = cameraTool164;
        CameraTool cameraTool165 = new CameraTool("SPINS_CREATIVE_TOOL_TOGGLE", 164, "256");
        A2h = cameraTool165;
        CameraTool cameraTool166 = new CameraTool("SPINS_TOGGLE", 165, "255");
        A2i = cameraTool166;
        CameraTool cameraTool167 = new CameraTool("SPLIT", 166, "151");
        A2j = cameraTool167;
        CameraTool cameraTool168 = new CameraTool("STACKED_TIMELINE_ENTER", 167, "111");
        A2k = cameraTool168;
        CameraTool cameraTool169 = new CameraTool("STICKER", 168, "86");
        A2l = cameraTool169;
        CameraTool cameraTool170 = new CameraTool("STICKER_TRAY", 169, "85");
        A2m = cameraTool170;
        CameraTool cameraTool171 = new CameraTool("STOP_MOTION", AbstractC62862SUj.MAX_FACTORIAL, "144");
        A2n = cameraTool171;
        CameraTool cameraTool172 = new CameraTool("SUGGESTED_AUDIO_PILL", 171, "258");
        A2o = cameraTool172;
        CameraTool cameraTool173 = new CameraTool("SUGGESTED_AUDIO_PILL_ADD", 172, "259");
        A2p = cameraTool173;
        CameraTool cameraTool174 = new CameraTool("SUPERZOOM", 173, "5");
        A2q = cameraTool174;
        CameraTool cameraTool175 = new CameraTool("SWIRL", 174, "73");
        A2r = cameraTool175;
        CameraTool cameraTool176 = new CameraTool("TAG_ANOTHER_PERSON", 175, "115");
        A2s = cameraTool176;
        CameraTool cameraTool177 = new CameraTool("TAG_PERSON", 176, "116");
        A2t = cameraTool177;
        CameraTool cameraTool178 = new CameraTool("TAP_TO_CUT", 177, "53");
        A2u = cameraTool178;
        CameraTool cameraTool179 = new CameraTool("TEMPERATURE", 178, "155");
        A2v = cameraTool179;
        CameraTool cameraTool180 = new CameraTool("TEMPLATES", 179, "47");
        A2w = cameraTool180;
        CameraTool cameraTool181 = new CameraTool("TEMPLATE_BROWSER", 180, "130");
        A2x = cameraTool181;
        CameraTool cameraTool182 = new CameraTool("TEMP_CAMERA_TOOL", 181, "91");
        A2y = cameraTool182;
        CameraTool cameraTool183 = new CameraTool("TEMP_FEED_ALBUM_SELECT", 182, "117");
        A2z = cameraTool183;
        CameraTool cameraTool184 = new CameraTool("TEMP_FEED_GALLERY_ALBUM_PICKER", 183, "118");
        A30 = cameraTool184;
        CameraTool cameraTool185 = new CameraTool("TEMP_SHARE_SHEET_ENTITY", 184, "99");
        A31 = cameraTool185;
        CameraTool cameraTool186 = new CameraTool("TEXT_ALIGNMENT", 185, "108");
        A32 = cameraTool186;
        CameraTool cameraTool187 = new CameraTool("TEXT_ANIMATION", 186, "104");
        A33 = cameraTool187;
        CameraTool cameraTool188 = new CameraTool("TEXT_COLOR", 187, "93");
        A34 = cameraTool188;
        CameraTool cameraTool189 = new CameraTool("TEXT_COLOR_EDIT", 188, "149");
        A35 = cameraTool189;
        CameraTool cameraTool190 = new CameraTool("TEXT_EFFECT", 189, "90");
        A36 = cameraTool190;
        CameraTool cameraTool191 = new CameraTool("TEXT_FORMAT", 190, "83");
        A37 = cameraTool191;
        CameraTool cameraTool192 = new CameraTool("TEXT_FORMAT_EDIT", 191, "150");
        A38 = cameraTool192;
        CameraTool cameraTool193 = new CameraTool("TEXT_TO_FILTER", 192, "288");
        A39 = cameraTool193;
        CameraTool cameraTool194 = new CameraTool("THIRD_PARTY_MEDIA", 193, "75");
        A3A = cameraTool194;
        CameraTool cameraTool195 = new CameraTool("TIMER_SELECTOR", 194, "14");
        A3B = cameraTool195;
        CameraTool cameraTool196 = new CameraTool("TRIAL", 195, "254");
        A3C = cameraTool196;
        CameraTool cameraTool197 = new CameraTool("TRIM", 196, "97");
        A3D = cameraTool197;
        CameraTool cameraTool198 = new CameraTool("VIDEO_HIGHTLIGHTS_DETECTION", 197, "52");
        A3F = cameraTool198;
        CameraTool cameraTool199 = new CameraTool("VIDEO_LAYOUT", 198, "24");
        A3G = cameraTool199;
        CameraTool cameraTool200 = new CameraTool("VIDEO_LAYOUT_VARIANTS", 199, "145");
        A3H = cameraTool200;
        CameraTool cameraTool201 = new CameraTool("VIDEO_LENGTH_TOGGLE", 200, "137");
        A3I = cameraTool201;
        CameraTool cameraTool202 = new CameraTool("VIGNETTE", 201, "160");
        A3J = cameraTool202;
        CameraTool cameraTool203 = new CameraTool("VINYL", 202, "74");
        A3K = cameraTool203;
        CameraTool cameraTool204 = new CameraTool("WAND", 203, "69");
        A3L = cameraTool204;
        CameraTool cameraTool205 = new CameraTool("WRITE_ALT_TEXT", 204, "304");
        A3M = cameraTool205;
        CameraTool[] cameraToolArr = new CameraTool[205];
        System.arraycopy(new CameraTool[]{cameraTool, cameraTool2, cameraTool3, cameraTool4, cameraTool5, cameraTool6, cameraTool7, cameraTool8, cameraTool9, cameraTool10, cameraTool11, cameraTool12, cameraTool13, cameraTool14, cameraTool15, cameraTool16, cameraTool17, cameraTool18, cameraTool19, cameraTool20, cameraTool21, cameraTool22, cameraTool23, cameraTool24, cameraTool25, cameraTool26, cameraTool27}, 0, cameraToolArr, 0, 27);
        System.arraycopy(new CameraTool[]{cameraTool28, cameraTool29, cameraTool30, cameraTool31, cameraTool32, cameraTool33, cameraTool34, cameraTool35, cameraTool36, cameraTool37, cameraTool38, cameraTool39, cameraTool40, cameraTool41, cameraTool42, cameraTool43, cameraTool44, cameraTool45, cameraTool46, cameraTool47, cameraTool48, cameraTool49, cameraTool50, cameraTool51, cameraTool52, cameraTool53, cameraTool54}, 0, cameraToolArr, 27, 27);
        System.arraycopy(new CameraTool[]{cameraTool55, cameraTool56, cameraTool57, cameraTool58, cameraTool59, cameraTool60, cameraTool61, cameraTool62, cameraTool63, cameraTool64, cameraTool65, cameraTool66, cameraTool67, cameraTool68, cameraTool69, cameraTool70, cameraTool71, cameraTool72, cameraTool73, cameraTool74, cameraTool75, cameraTool76, cameraTool77, cameraTool78, cameraTool79, cameraTool80, cameraTool81}, 0, cameraToolArr, 54, 27);
        System.arraycopy(new CameraTool[]{cameraTool82, cameraTool83, cameraTool84, cameraTool85, cameraTool86, cameraTool87, cameraTool88, cameraTool89, cameraTool90, cameraTool91, cameraTool92, cameraTool93, cameraTool94, cameraTool95, cameraTool96, cameraTool97, cameraTool98, cameraTool99, cameraTool100, cameraTool101, cameraTool102, cameraTool103, cameraTool104, cameraTool105, cameraTool106, cameraTool107, cameraTool108}, 0, cameraToolArr, 81, 27);
        System.arraycopy(new CameraTool[]{cameraTool109, cameraTool110, cameraTool111, cameraTool112, cameraTool113, cameraTool114, cameraTool115, cameraTool116, cameraTool117, cameraTool118, cameraTool119, cameraTool120, cameraTool121, cameraTool122, cameraTool123, cameraTool124, cameraTool125, cameraTool126, cameraTool127, cameraTool128, cameraTool129, cameraTool130, cameraTool131, cameraTool132, cameraTool133, cameraTool134, cameraTool135}, 0, cameraToolArr, 108, 27);
        System.arraycopy(new CameraTool[]{cameraTool136, cameraTool137, cameraTool138, cameraTool139, cameraTool140, cameraTool141, cameraTool142, cameraTool143, cameraTool144, cameraTool145, cameraTool146, cameraTool147, cameraTool148, cameraTool149, cameraTool150, cameraTool151, cameraTool152, cameraTool153, cameraTool154, cameraTool155, cameraTool156, cameraTool157, cameraTool158, cameraTool159, cameraTool160, cameraTool161, cameraTool162}, 0, cameraToolArr, 135, 27);
        System.arraycopy(new CameraTool[]{cameraTool163, cameraTool164, cameraTool165, cameraTool166, cameraTool167, cameraTool168, cameraTool169, cameraTool170, cameraTool171, cameraTool172, cameraTool173, cameraTool174, cameraTool175, cameraTool176, cameraTool177, cameraTool178, cameraTool179, cameraTool180, cameraTool181, cameraTool182, cameraTool183, cameraTool184, cameraTool185, cameraTool186, cameraTool187, cameraTool188, cameraTool189}, 0, cameraToolArr, 162, 27);
        System.arraycopy(new CameraTool[]{cameraTool190, cameraTool191, cameraTool192, cameraTool193, cameraTool194, cameraTool195, cameraTool196, cameraTool197, cameraTool198, cameraTool199, cameraTool200, cameraTool201, cameraTool202, cameraTool203, cameraTool204, cameraTool205}, 0, cameraToolArr, 189, 16);
        A03 = cameraToolArr;
        A02 = AbstractC12190kN.A00(cameraToolArr);
        CameraTool[] values = values();
        int A0L2 = AbstractC16850sd.A0L(values.length);
        LinkedHashMap linkedHashMap = new LinkedHashMap(A0L2 < 16 ? 16 : A0L2);
        for (CameraTool cameraTool206 : values) {
            linkedHashMap.put(cameraTool206.A00, cameraTool206);
        }
        A01 = linkedHashMap;
        CREATOR = new C206149Aw(57);
    }

    public static CameraTool valueOf(String str) {
        return (CameraTool) Enum.valueOf(CameraTool.class, str);
    }

    public static CameraTool[] values() {
        return (CameraTool[]) A03.clone();
    }

    @Override // java.lang.Enum
    public final String toString() {
        return this.A00;
    }

    public CameraTool(String str, int i, String str2) {
        this.A00 = str2;
    }
}
