package com.facebook.graphql.enums;

import X.AbstractC31175DnJ;
import X.AbstractC72048XLo;
import java.util.HashSet;
import java.util.Set;

/* loaded from: classes12.dex */
public final class GraphQLAREffectMLModelAssetTypeSet {
    public static final HashSet A00;

    static {
        String[] strArr = new String[44];
        A00 = AbstractC72048XLo.A0N(new String[]{"NAMETAG_OCR_PRED", "OCR2GO_CONFIG", "OCR2GO_DET_MODEL", "OCR2GO_RCG_MODEL", "PYTORCH_MODEL", "RECOGNITION_CLASSIFICATION_INIT", "RECOGNITION_DETECTION_INIT", "RUNTIME_RIG_RETARGETING_CONFIG", "TARGET_RECOGNITION_CLASSIFICATION_INIT", "TARGET_RECOGNITION_CLASSIFICATION_PRED", "TARGET_RECOGNITION_DETECTION_INIT", "TARGET_RECOGNITION_DETECTION_PRED", "UNKNOWN", "XRAY_CLASSES", "XRAY_CONFIGURATION", "XRAY_INIT_NET", "XRAY_PREDICT_NET"}, strArr, AbstractC31175DnJ.A1b(new String[]{"BODY_TRACKING_3D_DETECTION", "BODY_TRACKING_3D_LANDMARK", "CAFFE2_INIT_NET", "CAFFE2_PREDICT_NET", "EXPRESSION_FITTING", "FACE_TRACKER_FACE_ALIGN", "FACE_TRACKER_FACE_CONTOUR", "FACE_TRACKER_FACE_DETECT", "FACE_TRACKER_FACE_MESH", "MULTICLASS_INIT_NET", "MULTICLASS_PREDICT_NET", "M_SUGGESTIONS_CORE_P13N_FILTERING_FEATURES", "M_SUGGESTIONS_CORE_P13N_FILTERING_INIT", "M_SUGGESTIONS_CORE_P13N_FILTERING_PREDICT", "M_SUGGESTIONS_CORE_SENSITIVITY_INIT", "M_SUGGESTIONS_CORE_SENSITIVITY_PREDICT", "M_SUGGESTIONS_CORE_STICKER_RECEIVER_INTENT_INIT", "M_SUGGESTIONS_CORE_STICKER_RECEIVER_INTENT_PREDICT", "M_SUGGESTIONS_CORE_STICKER_RECEIVER_TAG_INIT", "M_SUGGESTIONS_CORE_STICKER_RECEIVER_TAG_PREDICT", "M_SUGGESTIONS_CORE_STICKER_SENDER_INTENT_INIT", "M_SUGGESTIONS_CORE_STICKER_SENDER_INTENT_PREDICT", "M_SUGGESTIONS_CORE_STICKER_SENDER_TAG_INIT", "M_SUGGESTIONS_CORE_STICKER_SENDER_TAG_PREDICT", "NAMETAG_DETECTION_INIT", "NAMETAG_DETECTION_PRED", "NAMETAG_OCR_INIT"}, strArr) ? 1 : 0, 27, 17);
    }

    public static final Set getSet() {
        return A00;
    }
}
