package com.facebook.graphql.enums;

import X.AbstractC72048XLo;
import com.facebookpay.offsite.models.message.PriceTableAnnotation$Companion;
import java.util.HashSet;
import java.util.Set;

/* loaded from: classes12.dex */
public final class GraphQLAllPaymentTypeFieldsSet {
    public static final HashSet A00;

    static {
        String[] strArr = new String[199];
        System.arraycopy(new String[]{"ADS_MANAGER", "AD_PUBLISHER", "AGE_VERIFICATION_CCV", "AURORA", "BILLING", "BILLING_HUB", "BILLING_WIZARD", "CAL_SETTING", "CARRIER_MONETIZATION", "CONNECT_VIA_IAW", "CONTACTLESS_PAYMENT", "CREATORS_AS_MARKETER_AFFILIATE", "CREATOR_MARKETPLACE", "DIGITAL_CODE", "DIGITAL_COLLECTIBLES", "DUMMY_FIRST_PARTY_V2", "DUMMY_THIRD_PARTY_V2", "ECP", "FBPAY_CARD_TOKENIZATION", "FBPAY_HUB", "FB_BROWSER_PAYMENT", "FB_DIGITAL_COLLECTIBLES", "FB_DIGITAL_COLLECTIBLES_PAYMENTS", "FB_MINTING", "FINANCIAL_SERVICES", "FRAUD_CHECK", "IAB_AUTOFILL"}, 0, strArr, 0, 27);
        System.arraycopy(new String[]{"IAB_AUTOFILL_BINDING_UPDATER", "IAB_AUTOFILL_CROSS_APP", "IAB_AUTOFILL_CROSS_APP_MIGRATION", "IAB_AUTOFILL_MIGRATION", "IAB_AUTOFILL_SILENT_BINDING", "IAB_AUTOFILL_UNBOUND_CARD_TRUSTED_DEVICE_CHAIN", "IAP_ADS_BILLING", "IAP_AFS_SUBSCRIPTION", "IAP_AI_PREMIUM", "IAP_ALL_PRODUCTS", "IAP_AVATAR_CONTENT", "IAP_CREATOR_STOREFRONT", "IAP_DCP_DEMO", "IAP_FAN_FUNDING", "IAP_GAMES_SUBSCRIPTION", "IAP_GAME_TIPPING", "IAP_GROUP_SUBSCRIPTION", "IAP_HORIZON_PURCHASES", "IAP_INSTAGRAM_CONTENT_APPRECIATION", "IAP_INSTAGRAM_FAN_SUBS", "IAP_INSTAGRAM_P2A", "IAP_INSTAGRAM_USERPAY_BADGES", "IAP_INSTANT_GAME", "IAP_META_GEM", "IAP_MV4B", "IAP_MV_PAID_TOKEN", "IAP_NFT"}, 0, strArr, 27, 27);
        System.arraycopy(new String[]{"IAP_NME_SUBSCRIPTION", "IAP_NON_CONSUMABLE_VIDEO", "IAP_PAID_ONLINE_EVENT", "IAP_SUPER_MEET_AND_GREET", "IAP_SUPER_VIRTUAL_GIFT", "IAP_WA_BUSINESS_CREDIT", "IAP_WA_BUSINESS_SUBS", "IAP_WA_PAID_CHANNEL", "IG_DIGITAL_COLLECTIBLES", "IG_DIGITAL_COLLECTIBLES_PAYMENTS", "IG_MINTING", "IG_MOR_DONATIONS", "IG_NMOR_DONATION_P4P", "IG_NMOR_P2B", "IG_NMOR_SHOPPING", "IG_NMOR_SHOPPING_ONBOARDING", "IG_NMOR_SHOP_ADS", "IG_PAYMENT_SETTINGS", "INSTAGRAM_P2M", "IN_APP_WEBVIEWER_PURCHASE", "LITE_CHECKOUT", "LOYALTY", "MENU", "MERCHANT_LOYALTY", "MERCHANT_ONBOARDING", "MESSENGER_BUSINESS_MESSAGING_API", "MESSENGER_P2M"}, 0, strArr, 54, 27);
        System.arraycopy(new String[]{"META_CHECKOUT_SDK", "META_PAY_VAULT", "META_PAY_WALLET", "META_REWARD", "MOR_ADS_AFA", "MOR_ADS_AUTH", "MOR_ADS_BUSINESS", "MOR_ADS_CONSENT", "MOR_ADS_CONSENT_AFA", "MOR_ADS_INVOICE", "MOR_ADS_RISK_3DS_AUTHENTICATION", "MOR_ADS_STORED_BALANCE", "MOR_AFS_SUBSCRIPTION", "MOR_AIRMAIL", "MOR_AI_PREMIUM", "MOR_ALT_APP_STORES", "MOR_BILL", "MOR_BILLING_OMEGA_INVOICE", "MOR_BIZ_MESSAGING", "MOR_CP_RETURN_LABEL", "MOR_DONATIONS", "MOR_DONATIONS_CAUSE_FOR_CHARITIES", "MOR_DONATIONS_MATCHING_CONFIRMATION", "MOR_DONATIONS_MATCHING_PLEDGE", "MOR_EVENT_TICKETING", "MOR_FACEBOOK_SHOP", "MOR_FAN_FUNDING"}, 0, strArr, 81, 27);
        System.arraycopy(new String[]{"MOR_GAMES_SUBSCRIPTION", "MOR_GAME_TIPPING_TOKEN", "MOR_GIFTS", "MOR_GROUP_SUBSCRIPTION", "MOR_INSTANT_GAMES", "MOR_MESSENGER_COMMERCE", "MOR_MV4B", "MOR_NME_SUBSCRIPTION", "MOR_NONE", "MOR_NON_CONSUMABLE_VIDEO", "MOR_OCULUS_CV1", "MOR_OCULUS_LAUNCH_V1", "MOR_OCULUS_LAUNCH_V2", "MOR_OCULUS_SUBSCRIPTION", "MOR_OPEN_GRAPH_PRODUCT", "MOR_OZONE", "MOR_P2P_TRANSFER", "MOR_PAID_ONLINE_EVENT", "MOR_PAYOUT_ADNET", "MOR_PAYOUT_AUTOPAY", "MOR_PAYOUT_CHARITY", "MOR_PAYOUT_CONTENT", "MOR_PAYOUT_DCP", "MOR_PAYOUT_DEV", "MOR_PAYOUT_MISCAP", "MOR_PAYOUT_OCU", "MOR_REPAYMENT"}, 0, strArr, 108, 27);
        System.arraycopy(new String[]{"MOR_SUPER_MEET_AND_GREET", "MOR_SUPER_VIRTUAL_GIFT", "MOR_THIRD_PARTY_APP_STORES_IAP", "MOR_VOICES", "MOR_WA_PAID_MESSAGING", "MOR_WA_PAID_MESSAGING_AUTH", "MOR_WHATSAPP_P2P", "MOR_WHATSAPP_SMB", "MOR_WHATSAPP_SMB_TOPUP", "MOR_WORKPLACE_USAGE", "MP_PAYMENT_SETTINGS", "NMOR_ADVERTISER_SUBSCRIPTION", "NMOR_BLACKBAUD_RWR_DONATION", "NMOR_BUSINESS_PLATFORM_COMMERCE", "NMOR_BUY_ON_FACEBOOK", "NMOR_C2C_CHECKOUT_EXPERIENCES", "NMOR_CHECKOUT_EXPERIENCES", "NMOR_COMPONENT_FLOW", "NMOR_DONATION_CIELO", "NMOR_DONATION_P4C", "NMOR_DONATION_P4P", "NMOR_DUMMY", "NMOR_EVENT_TICKETING", "NMOR_FB_SHOP_ADS", "NMOR_INSTAGRAM_P2B", "NMOR_INSTANT_EXPERIENCES", "NMOR_LIBRA"}, 0, strArr, 135, 27);
        System.arraycopy(new String[]{"NMOR_MARKETPLACE_SHIPPING", "NMOR_MARKETPLACE_TICKETING", "NMOR_MESSAGING_COMMERCE", "NMOR_MESSENGER_P2P", "NMOR_MESSENGER_PLATFORM", "NMOR_MFS", "NMOR_MOBILE_TOP_UP", "NMOR_MOVIE_TICKETING", "NMOR_NETWORK_TOKEN_NOTIF", "NMOR_NONE", "NMOR_OFFSITE_SHOPPING", "NMOR_P2P", "NMOR_PAGES_COMMERCE", "NMOR_PAGES_SOLUTION_DEPRECATED", "NMOR_PLATFORM_SELF_SERVE", "NMOR_PPGF_DONATION", "NMOR_SERVICES", "NMOR_SHIPPING_LABEL_DEPRECATED", "NMOR_SYNCHRONOUS_COMPONENT_FLOW", "NMOR_TIP_JAR", "NMOR_UNKNOWN", "NMOR_WHATSAPP_P2M", "NMOR_WHATSAPP_P2P", PriceTableAnnotation$Companion.OFFER, "OFFSITE_ACCT_LINKING_PAYPAL", "PAYMENTS_API_UNKNOWN_PRODUCT", "PAYMENT_SETTINGS"}, 0, strArr, 162, 27);
        A00 = AbstractC72048XLo.A0N(new String[]{"PAYOUTHUB_MSC", "PAYOUT_CONSUMER", "REWARDS_CENTER", "SHOPIFY_API", "SIGMA", "SOFT_DESCRIPTOR_AUTH", "TRUST_BINDING", "TRUST_PROFILE", "UNKNOWN", "WHATSAPP_P2M_LITE"}, strArr, 0, 189, 10);
    }

    public static final Set getSet() {
        return A00;
    }
}
