package com.facebook.graphql.enums;

import X.AbstractC16830sb;
import java.util.HashSet;
import java.util.Set;

/* loaded from: classes9.dex */
public final class GraphQLMNCommerceMessageTypeSet {
    public static final HashSet A00;

    static {
        String[] strArr = new String[85];
        System.arraycopy(new String[]{"AD_ADMIN_TEXT", "AD_BUBBLE", "AD_TEXT", "AIRLINE_BOARDINGPASS", "AIRLINE_BOARDING_PASS", "AIRLINE_CHECKIN", "AIRLINE_CHECKIN_REMINDER", "AIRLINE_ITINERARY", "AIRLINE_UPDATE", "AUDIO", "BLOCK_ALL", "BLOCK_PROMOTION", "BUTTON", "COMMERCE_COMPACT_LIST", "COMPACT_LIST", "CONTENT_SUBSCRIPTION", "COUPON", "CUSTOMER_FEEDBACK", "FALLBACK", "FEEDBACK", "FILE", "FORCED_FETCH_MESSAGE", "FORM_PROGRESS", "GAMING_SERVICES_GAME_INVITE", "GENERIC", "GENERIC_LEGACY", "GET_RIDE"}, 0, strArr, 0, 27);
        System.arraycopy(new String[]{"GIVE_RIDE", "ICE_BREAKER", "IMAGE", "INITIAL_PROMOTION", "INSTANT_FORM", "INSTANT_GAMES_CUSTOM_UPDATE", "INSTANT_GAMES_CUSTOM_UPDATE_MEDIA", "INSTANT_GAMES_LIVE_STREAM", "INSTANT_GAMES_SCORE", "INSTANT_GAMES_SHARE", "INSTANT_GAMES_TOURNAMENT_UPDATE", "LINK", "LIST", "LOCATION", "MEDIA", "MESSENGER_BOT_BASE_GENERIC", "MESSENGER_CALL_PROMPT", "MESSENGER_CALL_USER_PROMPT_SENT", "MESSENGER_TEAM_BOT_MESSAGE", "NON_AD", "NOTIFICATION_MESSAGES", "ONE_TIME_NOTIF_REQ", "OPEN_GRAPH", "OTHER", "PLACE_CARD", "RECEIPT", "REFERER_PROMO"}, 0, strArr, 27, 27);
        System.arraycopy(new String[]{"RETAIL_CANCELLATION", "RETAIL_PRODUCT_SUBSCRIPTION", "RETAIL_PROMOTION", "RETAIL_SHIPMENT", "RIDE_ADMIN_MESSAGE", "RIDE_COMPLETE", "RIDE_DRIVER_ARRIVING", "RIDE_DRIVER_CANCELED", "RIDE_DRIVER_ON_THE_WAY", "RIDE_INTENT", "RIDE_NO_DRIVER", "RIDE_ORDER_CONFIRMATION", "RIDE_RECEIPT", "RIDE_REENGAGEMENT_FIRST_RIDE", "RIDE_REQUESTED", "RIDE_RIDER_CANCELED", "RIDE_SIGNUP", "RIDE_WELCOME", "ROBOT_TEXT", "SENDER_ACTION", "SHIPMENT_TRACKING_EVENT", "SHOPS_PRODUCT", "SHOPS_PRODUCT_HSCROLL", "TEMPLATE", "TEXT", "UNBLOCK_ALL", "UNBLOCK_PROMOTION"}, 0, strArr, 54, 27);
        System.arraycopy(new String[]{"UNKNOWN", "UNLINK", "VIDEO", "WEAK_CONSENT_ADMIN_MESSAGE"}, 0, strArr, 81, 4);
        A00 = AbstractC16830sb.A05(strArr);
    }

    public static final Set getSet() {
        return A00;
    }
}
