package com.facebook.graphql.enums;

import X.AbstractC72048XLo;
import com.facebookpay.offsite.models.message.PriceTableAnnotation$Companion;
import java.util.HashSet;
import java.util.Set;

/* loaded from: classes12.dex */
public final class GraphQLPaymentCredentialTypeEnumSet {
    public static final HashSet A00;

    static {
        String[] strArr = new String[77];
        System.arraycopy(new String[]{"ADS_STORED_BALANCE", "AFFIRM", "ALT_PAY", "APPLE_IAP", "APPLE_PAY", "CREDIT_CARD", "CREDIT_CARD_AMERICANEXPRESS", "CREDIT_CARD_CUP", "CREDIT_CARD_DINERSCLUB", "CREDIT_CARD_DISCOVER", "CREDIT_CARD_ELO", "CREDIT_CARD_INTERAC", "CREDIT_CARD_JCB", "CREDIT_CARD_MAESTRO", "CREDIT_CARD_MASTERCARD", "CREDIT_CARD_PIN_ONLY", "CREDIT_CARD_RUPAY", "CREDIT_CARD_VISA", "DEBIT_CARD_PAYOUT", "DIRECT_DEBIT", "DUMMY", "EARNINGS_PAYOUT", "EXTENDED_CREDIT", "EXTERNAL_CREDENTIAL", "EXTERNAL_UPI", "EXTERNAL_WALLET", "FACEBOOK_PAY"}, 0, strArr, 0, 27);
        System.arraycopy(new String[]{"FB_TOKEN", "GIFTCARD", "GIFTCARD_BALANCE", "GOOGLE_PAY", "HPP_PAYMENT_LINK", "INCENTIVE_FUNDING", "INCENTIVE_MOR_OMNIPE_MIGRATION", "INCENTIVE_NMOR_OMNIPE_MIGRATION", "META_DUMMY", "META_PAY", "META_REWARD_DONATION", "MOCK_OPAQUE_REDIRECT_LPM", "MOMO", "NETWORK_TOKEN", "NET_BANKING", "NET_BANKING_BUALUANG", "NET_BANKING_KMA", "NET_BANKING_KRUNGTHAI_NEXT", "NET_BANKING_K_PLUS", "NET_BANKING_SCB", "NEW_BUSINESS_STORED_BALANCE", "NEW_CREDENTIAL_NUX", "NEW_CREDIT_CARD", "NEW_EXTENDED_CREDIT", "NEW_EXTERNAL_WALLET", "NEW_PAYPAL_BA", "NEW_PAYPAL_BNPL_CHECKOUT"}, 0, strArr, 27, 27);
        A00 = AbstractC72048XLo.A0N(new String[]{"NEW_PAYPAL_CHECKOUT", "NEW_SHOP_PAY", "NEW_WA_EXTERNAL_WALLET", PriceTableAnnotation$Companion.OFFER, "PAYONEER", "PAYOUT_CONSUMER_EARNING", "PAYPAL_BA", "PAYPAL_PAYOUT", "PAYPAL_TOKEN", "PAY_ON_DELIVERY", "PIX", "PIX_KEY", "QR_CODE", "REWARD", "SHOPIFY_BNPL", "SHOPIFY_OTC", "SHOP_PAY", "SOFORT", "STORED_CREDIT", "STORED_VALUE", "UPI", "VIRTUAL_CARD_KLARNA_BNPL", "WA_EXTERNAL_WALLET"}, strArr, 0, 54, 23);
    }

    public static final Set getSet() {
        return A00;
    }
}
