package com.facebook.graphql.enums;

import X.AbstractC31175DnJ;
import X.AbstractC72048XLo;
import java.util.HashSet;
import java.util.Set;

/* loaded from: classes12.dex */
public final class GraphQLPAYFBPayAuthenticationScreenContentTypeSet {
    public static final HashSet A00;

    static {
        String[] strArr = new String[34];
        A00 = AbstractC72048XLo.A0N(new String[]{"UNABLE_TO_CONNECT_HUB", "VERIFY_BIO_TO_DISABLE_BIO", "VERIFY_BIO_TO_ENABLE_BIO", "VERIFY_BIO_TO_PAY", "VERIFY_PIN_HUB", "VERIFY_PIN_TO_CHANGE_PIN", "VERIFY_PIN_TO_PAY"}, strArr, AbstractC31175DnJ.A1b(new String[]{"CHANGE_PIN_CONFIRM_NEW_PIN", "CHANGE_PIN_CREATE_NEW_PIN", "CHANGE_PIN_NEW_PIN_CREATED", "CONFIRM_PIN", "CONNECT_CVV_VERIFICATION", "CONNECT_PAYPAL_VERIFICATION", "CONNECT_PIN_VERIFICATION", "CONNECT_WITH_PIN_AUTH_FAILURE_CVV_FALLBACK", "CONNECT_WITH_PIN_AUTH_FAILURE_PAYPAL_FALLBACK", "CONNECT_WITH_PIN_AUTH_FAILURE_SDC_FALLBACK", "CREATE_BIO", "CREATE_PIN", "DISABLE_BIO_CONFORMATION", "DISABLE_PIN_CONFIRMATION", "FORGOT_PIN_RESET_WITH_PASSWORD", "LEAVE_WITHOUT_ENTERING_CVV_TO_CONNECT_DIALOG", "LEAVE_WITHOUT_ENTERING_PIN_TO_CONNECT_DIALOG", "LEAVE_WITHOUT_LOG_IN_PAYPAL_TO_CONNECT_DIALOG", "LEAVE_WITHOUT_RESETTING_PIN_CONFIRMATION", "PIN_CREATED", "PIN_VERIFY_TO_CHECKOUT", "RESET_CONFIRM_NEW_PIN", "RESET_CREATE_NEW_PIN", "RESET_NEW_PIN_CREATED", "RESET_PIN_WITH_PASSWORD", "SETUP_PIN_TO_CREATE_BIO_CONFIRMATION", "UNABLE_TO_CONNECT_CHECKOUT"}, strArr) ? 1 : 0, 27, 7);
    }

    public static final Set getSet() {
        return A00;
    }
}
