package com.facebook.graphql.enums;

import X.AbstractC31175DnJ;
import X.AbstractC72048XLo;
import java.util.HashSet;
import java.util.Set;

/* loaded from: classes12.dex */
public final class GraphQLContextualProfileTileTypeSet {
    public static final HashSet A00;

    static {
        String[] strArr = new String[31];
        A00 = AbstractC72048XLo.A0N(new String[]{"TEST_TILE", "THINGS_IN_COMMON", "USER_SIGNALS", "WORK_INFORMATION"}, strArr, AbstractC31175DnJ.A1b(new String[]{"CLAIMABLE_MEMBER_BADGES", "COMMUNITY_AWARDS", "COMMUNITY_AWARDS_EARNINGS", "GAMING_ACTIVITY", "GROUP_ADMIN_INSIGHTS", "GROUP_EXPERTISE", "GROUP_MEMBER_INTEGRITY_STATS", "GROUP_MEMBER_RECENT_ACTIVITY", "GROUP_POSTS", "GROUP_QUESTIONS", "MARKETPLACE_LISTINGS", "MEMBER_BADGES", "MEMBER_QUESTIONS", "MEMBER_STATS", "NEIGHBORHOODS_AWARDS", "NEIGHBORHOODS_FAVORITE_PLACES", "NEIGHBORHOODS_INTERESTS", "NEIGHBORHOODS_MEMBER_BADGES", "NEIGHBORHOODS_PETS", "NEIGHBORHOODS_ROLES_V2", "RECENT_PHOTOS", "REPUTATION_SYSTEM_ACTIVITY", "REPUTATION_SYSTEM_CONTRIBUTIONS", "REPUTATION_SYSTEM_FAQS", "REPUTATION_SYSTEM_PERCENTILE_RANK", "REPUTATION_SYSTEM_POINTS_BY_CATEGORY", "REPUTATION_SYSTEM_SEE_YOUR_POINTS"}, strArr) ? 1 : 0, 27, 4);
    }

    public static final Set getSet() {
        return A00;
    }
}
