package com.facebook.graphql.enums;

import X.AbstractC16830sb;
import com.facebookpay.offsite.models.message.PaymentDetailChangeTypes$Companion;
import java.util.HashSet;
import java.util.Set;

/* loaded from: classes11.dex */
public final class GraphQLBizAppTabNameSet {
    public static final HashSet A00;

    static {
        String[] strArr = new String[188];
        System.arraycopy(new String[]{"ACCOUNT_QUALITY", "ACCOUNT_SWITCHER", "ACTIVITY", "ADS_EXPERIMENTS", "ADS_MANAGEMENT", "ADS_MANAGER", "ADS_MANAGER_ACCOUNT_OVERVIEW", "ADS_MANAGER_ADS_REPORTING", "ADS_MANAGER_AUDIENCES", "ADS_MANAGER_BILLING_PAYMENTS", "ADS_MANAGER_CAMPAIGNS", "ADS_MANAGER_IN_MBS_ADS", "ADS_MANAGER_SUBNAV", "ADS_REPORTING", "ADS_TEST_TOOL", "ADVERTISING_SETTINGS", "AD_ACCOUNT_SETTINGS", "AD_APP_SETTINGS", "AD_CENTER", "AD_LIMITS", "AFT_AGENCY_MANAGEMENT_TOOL", "APPOINTMENTS", "AUDIENCES", "AUDIENCE_GROWTH", "AUDIENCE_INSIGHTS", "AUTOMATED_RULES", "AUTOMATIONS_COMPOSER"}, 0, strArr, 0, 27);
        System.arraycopy(new String[]{"BANK_SLIPS", "BILLING", "BILLING_AND_PAYMENTS", "BILLING_HUB", "BILLING_HUB_EXTERNAL", "BM_INSIGHTS", "BRANDED_PROMOTIONAL_PROGRAMS", "BRAND_COLLABS_MANAGER", "BRAND_RIGHTS_PROTECTION", "BRAND_SAFETY", "BULK_EDIT_COMPOSER", "BULK_UPLOAD_COMPOSER", "BUSINESS_AI", "BUSINESS_APP_STORE", "BUSINESS_CALL", "BUSINESS_FEED", "BUSINESS_HOME", "BUSINESS_MANAGER", "BUSINESS_SETTINGS", "CAMPAIGN_PLANNER", "CATALOG", "COLLABORATION_CENTER", "COMMENTS", "COMMERCE", "COMPARISON_MODAL", "COMPOSER", "CONSUMER_TRENDS"}, 0, strArr, 27, 27);
        System.arraycopy(new String[]{"CONTACTS", "CONTENT_CALENDAR", "CREATE_ADS", "CREATE_CREATOR_CAMPAIGN", "CREATE_FUNDRAISER", "CREATE_MARKETING_EMAIL", "CREATE_MARKETING_MESSAGE", "CREATE_POST", "CREATE_STORY", "CREATIVE_ASSETS", "CREATIVE_HUB", "CREATIVE_IDEAS", "CREATIVE_REPORTING", "CREATOR_MANAGEMENT_TOOL", "CREATOR_MARKETPLACE", "CREATOR_STUDIO", "CREATOR_TOOLS", "CUSTOMER", "DISMISSED_UNLABELLED_CONTENT", "EDIT_NAV", "EDUCATION_HUB", "EVENTS", "EVENTS_MANAGER", "EXPERIMENTS", "FACEBOOK_INSIGHTS", "FACEBOOK_PAGE", "FBM_CHANNELS"}, 0, strArr, 54, 27);
        System.arraycopy(new String[]{"FOAA_INSIGHTS", "FOR_REVIEW_UNLABELLED_CONTENT", "GET_STARTED", "GLOBAL_SEARCH", "HELP_CENTER", "HOME", "IG_PRESENCE", "IMAGES_AND_VIDEO", "INBOX", "INBOX_SETTINGS", "INSIGHTS", "INSIGHTS_AD_AUDIENCE", "INSIGHTS_AD_PERFORMANCE", "INSIGHTS_AD_PLACEMENTS", "INSIGHTS_CONTENT", "INSIGHTS_FACEBOOK_AUDIENCE", "INSIGHTS_INSTAGRAM_AUDIENCE", "INSIGHTS_TRENDS", "INSPIRATION_HUB", "INSTAGRAM_INSIGHTS", "INSTAGRAM_PROFILE", "INSTANT_FORMS", "INVENTORY", "INVOICES", "JOBS", "LANGUAGE_SETTINGS", "LEADS_CENTER"}, 0, strArr, 81, 27);
        System.arraycopy(new String[]{"LICENSED_MUSIC", "LIVE_VIDEO", "MARKETING_MESSAGES", "MARKETING_MESSAGE_COMPOSER", "MARKETING_MESSAGE_GET_STARTED", "MARKETING_MESSAGE_INVITE_CONTACT", "MARKETING_MESSAGE_ONBOARDING", "MARKETING_MESSAGE_ONE_TIME_CAMPAIGNS", "MARKETING_MESSAGE_OPTIN", "MARKETING_MESSAGE_OPTIN_SURFACE", "MARKETING_MESSAGE_SUBSCRIBER_GROWTH", "MARKETING_SOLUTIONS", "MEDIA_LIBRARY", "MESSENGER_SELLER_CENTER", "MESSENGER_SELLER_CENTER_V2", "META_AI", "MISSING_MUST_FIX", "MM_CAMPAIGN_LIST", "MM_LWI", "MM_LWI_COMPOSER", "MONETIZATION", "MONETIZATION_MANAGER", "MONETIZATION_REELS_ADS", "MONETIZATION_UNIFIED_PROGRAM", "MORE_TOOLS", "NONPROFIT_MANAGER", PaymentDetailChangeTypes$Companion.OFFERS}, 0, strArr, 108, 27);
        System.arraycopy(new String[]{"OMNI_AI", "ORDERS", "PAGES_FEED", "PAGE_POSTS", "PAGE_PRESENCE", "PAGE_SETTINGS", "PAGE_TIMELINE", "PARTNERSHIP_ADS_HUB", "PARTNER_CENTER", "PAYMENTS", "PAYMENTS_EARNINGS", "PAYMENTS_PAYOUTS", "PAYMENTS_SETTINGS", "PAYMENTS_SUPPORT", "PHOTOS", "PLANNER", "POST", "POST_DETAIL", "POST_DRAFTS", "PRODUCT_TESTING_AND_OPTIMIZATION", "PROFILE_PLUS_INSIGHTS", "PUBLIC_CONVERSATIONS", "PUBLISHED_CONTENT", "PUBLISHED_POSTS", "PUBLISHED_THREADS", "RATINGS_AND_REVIEWS", "REELS_BULK_UPLOAD_COMPOSER"}, 0, strArr, 135, 27);
        System.arraycopy(new String[]{"REELS_COMPOSER", "REPORT_PROBLEM", "RESOURCE_LIBRARY", "REWARDS", "RIGHTS_MANAGER", "SCHEDULED_CONTENT", "SCHEDULED_POSTS", "SELF_VIEW", "SERVICES_MENU", "SETTINGS", "SHOPIFY_META_APP", "SOUND_COLLECTION", "SOUND_COLLECTION_MBS", "STORE_LOCATIONS", "STORY_COMPOSER", "STREAMER_HOME", "TRAFFIC_ANALYSIS", "UNIFIED_VOD_AND_REELS_COMPOSER", "UNKNOWN", "VIDEOS", "VIDEOS_YOU_CAN_CROSSPOST", "VIEW_PAGE", "WHATSAPP_CAMPAIGN_COMPOSER", "WHATSAPP_MANAGER", "WHATSAPP_MANAGER_EXTERNAL_LINK", "WHATSAPP_OPT_IN_COMPOSER"}, 0, strArr, 162, 26);
        A00 = AbstractC16830sb.A05(strArr);
    }

    public static final Set getSet() {
        return A00;
    }
}
