package com.facebook.graphql.enums;

import X.AbstractC72048XLo;
import java.util.HashSet;
import java.util.Set;

/* loaded from: classes12.dex */
public final class GraphQLAREffectFailureCodeSet {
    public static final HashSet A00;

    static {
        String[] strArr = new String[67];
        System.arraycopy(new String[]{"AGE_CONSTRAINT", "AGE_RESTRICTION", "AIRPORT_CONSTRAINT", "AVAILABILITY_GK", "AVATAR_BLOCKED_FROM_SINGLE_LOADING", "BIRTHDAY_CONSTRAINT", "BLACKLISTED", "CAN_NOT_USE_FACE_LANDMARKS_AND_MESHES_EFFECT", "CLIENT_EXCLUDED", "COPLAY_BLOCKED_FROM_SINGLE_LOADING", "COUNTRY_CONSTRAINT", "DAYS_OF_THE_WEEK_CONSTRAINT", "DEEPLINK_MISSING_EFFECT", "DEFAULT_FAILURE", "DISCONTINUED_BETA_SDK_VERSION", "DISCONTINUED_SDK_VERSION", "EVENT_ATTENDANCE_CONSTRAINT", "EVENT_ELIGIBILITY_CONSTRAINT", "EXCEEDS_TESTING_LINK_LIMIT", "FORM_FACTOR_MISMATCH", "GATEKEEPER_CONSTRAINT", "GATELOGIC_CONSTRAINT", "GENDER_CONSTRAINT", "HAS_SCRIPTS", "HOLDOUT_GK", "IG_CAMERA_FORMAT_CONSTRAINT", "INACTIVE"}, 0, strArr, 0, 27);
        System.arraycopy(new String[]{"INCOMPATIBLE_BETA_SDK_VERSION", "INCOMPATIBLE_CAPABILITIES", "INCOMPATIBLE_CAPABILITY_LIST", "INCOMPATIBLE_COMPRESSION", "INCOMPATIBLE_SDK_VERSION", "INSPIRATIONS_TIME_RANGE_CONSTRAINT", "INVALID_ATTRIBUTION", "INVALID_MAX_SUPPORTED_VERSIONS", "INVALID_TESTING_LINK", "INVALID_USERNAME", "IN_ANY_CITY_CONSTRAINT", "LOCALE_CONSTRAINT", "LOCATION_PAGE_CONSTRAINT", "METAL_MIGRATION", "MULTI_COUNTRY_CONSTRAINT", "MULTI_LOCATION_CONSTRAINT", "NMLML_REASON_UNAVAILABLE", "NOT_APPROVED", "NO_APPROVED_INSTANCE", "NO_GYRO", "NO_OWNER", "NO_PASSING_ACTIVATIONS", "NO_PERMISSION", "OLD_BETA_SDK_VERSION", "OLD_SDK_VERSION", "OTHER", "PAGE_LIKE_CONSTRAINT"}, 0, strArr, 27, 27);
        A00 = AbstractC72048XLo.A0N(new String[]{"PLACE_CONSTRAINT", "PRODUCT_VISIBILITY", "SUPER_APP_DISALLOWED", "TEST_CONSTRAINT", "TEST_EFFECT_NOT_WHITELISTED", "THIRD_PARTY_ACCESS", "TIME_OF_DAY_CONSTRAINT", "TIME_OF_WEEK_CONSTRAINT", "TIME_RANGE_CONSTRAINT", "UNKNOWN_PRODUCT", "VERSION_CONFIG_GK", "VERSION_CONFIG_QE", "WRONG_SURFACE"}, strArr, 0, 54, 13);
    }

    public static final Set getSet() {
        return A00;
    }
}
