package com.facebook.graphql.enums;

import X.AbstractC16830sb;
import java.util.HashSet;
import java.util.Set;

/* loaded from: classes4.dex */
public final class GraphQLAREffectMLModelTypeSet {
    public static final HashSet A00;

    static {
        String[] strArr = new String[51];
        System.arraycopy(new String[]{"AML_FACE_TRACKER", "BI_BYTEDOC", "BI_DEEPTEXT", "BI_XRAY", "BODY_TRACKER", "BODY_TRACKING", "BODY_TRACKING_3D", "CONVO2EMOTION", "DEPTH_ESTIMATION", "EGO_DETECTOR_TRACKER", "ENLIGHTEN_GAN", "FACE_TRACKER", "FACE_WAVE", "FITTED_EXPRESSION_TRACKER", "FITTED_EXPRESSION_TRACKER_RUNTIME_RIG_RETARGETING", "GAZE_CORRECTION", "HAIR_SEGMENTATION", "HAND_GESTURE", "HAND_RECOGNITION", "IGREELS_XRAY", "II_FACE_TRACKER", "II_ID_DETECTOR", "II_REDUCED_FACE_TRACKER", "METADET_TRACK", "MOBILE_VISION_IMAGE_UNDERSTANDING", "MULTICLASS_SEGMENTATION", "MULTITASK_PEOPLE_SEGMENTATION"}, 0, strArr, 0, 27);
        System.arraycopy(new String[]{"M_SUGGESTIONS_CORE", "NAMETAG", "OCR2GO_CREDIT_CARD", "PHOTO_CROP", "PORTAL_ASR", "PORTAL_NLU", "PORTAL_TTS", "PORTAL_WW", "PYTORCH_TEST", "RECOGNITION", "RING_TRY_ON", "SAFECHAT", "SALIENCY", "SCENE_DEPTH", "SCENE_DEPTH_WITH_FALLBACK", "SCENE_UNDERSTANDING", "SEGMENTATION", "SEGMENT_ANYTHING", "SKY_SEGMENTATION", "TARGET_RECOGNITION", "U_TWO_NET", "VIDEO_HIGHLIGHTS", "VIDEO_HIGHLIGHTS_TEMPORAL", "XRAY"}, 0, strArr, 27, 24);
        A00 = AbstractC16830sb.A05(strArr);
    }

    public static final Set getSet() {
        return A00;
    }
}
