package com.facebook.graphql.enums;

import X.AbstractC16830sb;
import X.AbstractC31175DnJ;
import java.util.HashSet;
import java.util.Set;

/* loaded from: classes10.dex */
public final class GraphQLInstantGameSupportCheckResponseCodeSet {
    public static final HashSet A00;

    static {
        String[] strArr = new String[28];
        System.arraycopy(new String[]{"USER_CAN_ONLY_PLAY_ON_FB"}, AbstractC31175DnJ.A1b(new String[]{"ACCESS_DENIED", "AGE_RATING_RESTRICTED", "CLOUD_GAMES_DEPRECATED", "CROSS_PLAY_DID_NOT_GRANT_ALL_PERMISSION_FOR_CONTEXT", "DATA_USE_CHECKUP_FAIL", "MESSENGER_APP_ONLY_GAME_GENERIC", "MESSENGER_APP_ONLY_GAME_SPECIFIC", "PLATFORM_ACCESS_DISABLED", "SUPPORTED", "UNSUPPORTED_APP_ID", "UNSUPPORTED_BLACKLISTED_CARRIER", "UNSUPPORTED_BLOCKED_ON_CURRENT_DEVICE_PLATFORM", "UNSUPPORTED_BLOCKED_ON_CURRENT_PLATFORM_AFTER_MIGRATION", "UNSUPPORTED_BLOCKED_ON_CURRENT_PLATFORM_APP_PAIRS", "UNSUPPORTED_BROKEN_GAME", "UNSUPPORTED_CANVAS_FLASH_DEPRECATION", "UNSUPPORTED_DENIED_FOR_EPD_JURISDICTION", "UNSUPPORTED_DENIED_FOR_MSITE_IN_THIRD_PARTY_APP", "UNSUPPORTED_DEVICE", "UNSUPPORTED_GAME_TAKEN_DOWN", "UNSUPPORTED_GENERIC", "UNSUPPORTED_INCOMPATIBLE_APP_VERSION", "UNSUPPORTED_PLAY_FOR_PAGE_USER", "UNSUPPORTED_PRODUCT_HOLDOUT", "UNSUPPORTED_PROFILE_PLUS_USER", "UNSUPPORTED_REQUESTED_PERMISSIONS", "UNSUPPORTED_SOAP_USER"}, strArr) ? 1 : 0, strArr, 27, 1);
        A00 = AbstractC16830sb.A05(strArr);
    }

    public static final Set getSet() {
        return A00;
    }
}
