package com.facebook.graphql.enums;

import X.AbstractC72048XLo;
import java.util.HashSet;
import java.util.Set;

/* loaded from: classes12.dex */
public final class GraphQLPaymentProviderSet {
    public static final HashSet A00;

    static {
        String[] strArr = new String[129];
        System.arraycopy(new String[]{"ADS", "ADYEN_ALTPAY", "ADYEN_AMEX", "ADYEN_CC", "ADYEN_CHECKOUT", "AFFIRM", "AMEX", "ANT_FINANCIAL", "ARVATO_DD", "ASYNC_DUMMY", "AXIS", "BANGO", "BANK_OF_AMERICA_DD", "BBVA", "BILLDESK", "BOF_API", "BOKU", "BOKU_WALLET", "BRAINTREE_AMEX", "BRAINTREE_GRAPH", "BRAINTREE_PAYMENTECH", "BT", "BUNDLE", "BYOG_HPP_CIELO", "BYOG_PAYPAL", "BYOG_PAYPAL_MARKETPLACE", "BYOG_STRIPE"}, 0, strArr, 0, 27);
        System.arraycopy(new String[]{"BYOG_STRIPE_LITE", "CARDINAL", "CHASE", "CHECKOUT_COM", "CIELO", "CIELO_CONSUMER", "CIELO_ECOMMERCE", "CIELO_MERCHANT_V1", "CITI_DD", "CONTACT_MERCHANT", "COURTESY_CREDITS", "CREDIT_CARD", "CYBERSOURCE_AMEX", "CYBERSOURCE_PAYMENTECH", "DCP_APPLE", "DCP_GOOGLE", "DIRECT_DEBIT", "DLOCAL", "DUMMY", "EBANX", "ECOBANK", "FB", "FB_SPEC_MOCK", "FISERV", "FLUTTERWAVE", "GETNET", "GMG"}, 0, strArr, 27, 27);
        System.arraycopy(new String[]{"GO", "HDFC", "HYPERWALLET", "ICICI", "INICIADOR", "JIO", "JUSPAY_CONSUMER", "LIVEGAMER", "LPM_DUMMY_REVERSE", "MANAGED_STRIPE", "MERCADO_PAGO", "MERCADO_PAGO_DIRECT", "META_HPP_MOCK", "META_PLATFORM", "MOCK_BRAINTREE_GRAPH", "MOCK_CC", "MOCK_CC_AUTHENTICATE", "MOCK_CHAINING", "MOCK_GENERIC_HTTP", "MOCK_RETRY", "MOCK_UPI", "MOCK_WALLET", "MOCK_WITH_PREDEFINED_CCS", "NMOR_PAYPAL", "NMOR_SHOPIFY_DIRECT", "O3P_KBANK", "O3P_STRIPE_P4P"}, 0, strArr, 54, 27);
        System.arraycopy(new String[]{"OAUTH", "OFFSITE_LINK", "OTTO", "OVO", "PAGSEGURO", "PAYMAYA", "PAYMENTECH", "PAYMENTWALL", "PAYONEER", "PAYOUT", "PAYPAL", "PAYPAL_COMMERCE", "PAYU", "PAYU_INDIA", "PAY_WITH_MY_BANK_DD", "PB", "PE_TEST", "PINGPONG", "PLATFORMIZED_ADYEN_CHECKOUT", "PLATFORMIZED_BRAINTREE", "PLATFORMIZED_CYBERSOURCE", "PLATFORMIZED_KBANK", "PLATFORMIZED_PAYPAL", "PLATFORMIZED_PAYU", "PLATFORMIZED_STRIPE", "PLAYSPAN", "RAZORPAY"}, 0, strArr, 81, 27);
        A00 = AbstractC72048XLo.A0N(new String[]{"REDE", "RISKIFIED", "SAFECHARGE", "SBI", "SHOPIFY", "SMARTPAY", "STONE", "STRIPE", "STRIPE_AMEX", "SUMUP", "TINCHECKER", "TOPPS", "TWO_C_TWO_P", "UNKNOWN", "UPI", "USER_STORED_BALANCE", "WITHDRAW", "WORLDLINE_CC", "XENDIT", "ZAAKPAY", "ZONG"}, strArr, 0, 108, 21);
    }

    public static final Set getSet() {
        return A00;
    }
}
