package com.facebook.graphql.enums;

import X.AbstractC16830sb;
import java.util.HashSet;
import java.util.Set;

/* loaded from: classes6.dex */
public final class GraphQLMNetRankTypeSet {
    public static final HashSet A00;

    static {
        String[] strArr = new String[55];
        System.arraycopy(new String[]{"ACTIVE_BEEPER", "BROADCAST_FLOW_NEEDY_CONTACTS", "BROADCAST_FLOW_TOP_CONTACTS", "BROADCAST_FLOW_TOP_CONTACTS_AND_TOP_THREAD_FB_SHARE", "BROADCAST_FLOW_TOP_CONTACTS_EXTERNAL_SHARE", "BROADCAST_FLOW_TOP_CONTACTS_FB_SHARE", "BROADCAST_FLOW_TOP_CONTACTS_MESSENGER_SHARE", "BROADCAST_FLOW_TOP_THREADS_FB_SHARE", "CONTACT_TAB_ACTIVE_NOW", "FB_H_SCROLL_RANKING", "FB_MESSAGING_USER_SEARCH", "FB_MESSAGING_USER_SEARCH_NULLSTATE", "FB_ORIGINAL_PRIVATE_SHARING", "INBOX_ACTIVE_NOW", "INBOX_ACTIVE_NOW_NO_BOOSTING", "INBOX_ACTIVE_NOW_PREFETCH", "INSTAGRAM_DIRECT_SEARCH_NULLSTATE", "MESSENGER_ACTIVE_NOW_TRAY_ACTIVE_CC", "MESSENGER_BCF_FREQUENTS", "MESSENGER_BLENDED_KEYPRESS", "MESSENGER_BLENDED_NULLSTATE", "MESSENGER_BROADCAST_FLOW_TOP_THREADS", "MESSENGER_CARRIER_MESSAGING", "MESSENGER_CLOSE_CONNECTION", "MESSENGER_COMMUNITY_TAB_UNJOINED_COMMUNITIES", "MESSENGER_GAME_SEARCH", "MESSENGER_GROUP_SEARCH"}, 0, strArr, 0, 27);
        System.arraycopy(new String[]{"MESSENGER_INBOX_BIRTHDAY_ITEM", "MESSENGER_INBOX_THREADS", "MESSENGER_MONTAGE_SEEN_SHEET", "MESSENGER_NON_CONTACT_SEARCH", "MESSENGER_NOTIF_QP_TARGETING_UPSELL_TYPE", "MESSENGER_OMNIPICKER_KEYPRESS", "MESSENGER_OMNIPICKER_NULLSTATE", "MESSENGER_PAGE_SEARCH", "MESSENGER_PENDING_REQUEST", "MESSENGER_ROOM_INVITE", "MESSENGER_ROOM_INVITE_GROUP", "MESSENGER_ROOM_INVITE_SEARCH", "MESSENGER_SEARCH_BOOTSTRAP", "MESSENGER_SENDS_28D", "MESSENGER_SHARE_SHEET", "MESSENGER_TRENDING_STICKERS", "MESSENGER_UNIV_NULLSTATE_BLEND", "MESSENGER_USER_SEARCH", "MESSENGER_USER_SEARCH_NULLSTATE", "MLITE_DIODE_PROMOTION", "MONTAGE_AND_ACTIVE_NOW", "MONTAGE_USER", "PSTN_TOP_CONTACTS", "RTC_GROWTH", "RTC_SEQUENTIAL_TOP_CONTACTS", "RTC_TOP_CONTACTS", "UNDEFINED_RANKING_TYPE"}, 0, strArr, 27, 27);
        System.arraycopy(new String[]{"WWW_NULLSTATE"}, 0, strArr, 54, 1);
        A00 = AbstractC16830sb.A05(strArr);
    }

    public static final Set getSet() {
        return A00;
    }
}
