package com.facebook.graphql.enums;

import X.AbstractC16830sb;
import java.util.HashSet;
import java.util.Set;

/* loaded from: classes6.dex */
public final class GraphQLBusinessSharingErrorCodeSet {
    public static final HashSet A00 = AbstractC16830sb.A05("BOOST_POST_EDIT_FAILURE", "DELETE_FAILED", "EDIT_FAILED", "EMPTY_CHANNELS", "FB_POST_CREATION_FAILURE", "FB_REEL_CREATION_FAILURE", "GROUP_POST_CREATION_FAILURE", "IG_POST_CREATION_FAILURE", "IG_POST_WITHOUT_MEDIA", "IG_REEL_CREATION_FAILURE", "IG_REEL_INPUT_EMPTY_MEDIA_SOURCE", "IG_STORY_CREATION_FAILURE", "IG_STORY_INPUT_EMPTY_MEDIA_SOURCE", "NO_ENT_STORY_FOR_FB_POST", "NO_ENT_VIDEO_FOR_IG_REEL", "NO_ENT_VIDEO_FOR_IG_STORY", "NO_FB_POST_PERMISSION", "NO_IG_DELETE_PERMISSION", "NO_IG_EDIT_PERMISSION", "NO_IG_POST_PERMISSION", "POST_CREATION_FAILURE", "RESHARED_POST_IS_NULL", "UNABLE_TO_CANCEL_SCHEDULE_POST", "UNABLE_TO_DELETE_POST", "UNABLE_TO_EDIT_POST", "UNABLE_TO_POST", "UNSUPPORTED_IG_ATTACHMENT_TYPE");

    public static final Set getSet() {
        return A00;
    }
}
