package com.instagram.creation.capture.quickcapture.rulesystem;

import X.C0T6;
import X.C14360o3;
import X.C206139Av;
import X.C8B9;
import X.EnumC150226pU;
import X.MSV;
import android.os.Parcel;
import android.os.Parcelable;

/* loaded from: classes4.dex */
public final class CaptureRuleSystemState extends C0T6 implements Parcelable {
    public static final Parcelable.Creator CREATOR = new C206139Av(69);
    public int A00;
    public int A01;
    public int A02;
    public EnumC150226pU A03;
    public C8B9 A04;
    public Boolean A05;
    public boolean A06;
    public boolean A07;
    public boolean A08;
    public boolean A09;
    public boolean A0A;
    public boolean A0B;
    public boolean A0C;
    public boolean A0D;
    public boolean A0E;
    public boolean A0F;
    public boolean A0G;
    public boolean A0H;
    public boolean A0I;
    public boolean A0J;
    public boolean A0K;
    public boolean A0L;
    public boolean A0M;
    public boolean A0N;
    public boolean A0O;
    public boolean A0P;
    public boolean A0Q;
    public boolean A0R;
    public boolean A0S;
    public boolean A0T;
    public boolean A0U;
    public boolean A0V;
    public boolean A0W;
    public boolean A0X;
    public boolean A0Y;
    public boolean A0Z;
    public boolean A0a;
    public boolean A0b;
    public boolean A0c;
    public boolean A0d;
    public boolean A0e;
    public boolean A0f;
    public boolean A0g;
    public boolean A0h;
    public boolean A0i;
    public boolean A0j;
    public boolean A0k;
    public boolean A0l;
    public boolean A0m;
    public boolean A0n;
    public boolean A0o;
    public boolean A0p;
    public boolean A0q;
    public boolean A0r;
    public boolean A0s;
    public boolean A0t;

    @Override // android.os.Parcelable
    public final int describeContents() {
        return 0;
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("CaptureRuleSystemState(contentType=");
        sb.append(this.A04);
        sb.append(", addedStickerType=");
        sb.append(this.A03);
        sb.append(", hasMusic=");
        sb.append(this.A0T);
        sb.append(", isMusicFromPreCapture=");
        sb.append(this.A0p);
        sb.append(", hasFeedSticker=");
        sb.append(this.A0I);
        sb.append(", hasProductShareSticker=");
        sb.append(this.A0Z);
        sb.append(", hasIGTVSticker=");
        sb.append(this.A0K);
        sb.append(", hasArchiveFeedSticker=");
        sb.append(this.A08);
        sb.append(", hasReelCTAs=");
        sb.append(this.A0d);
        sb.append(", isPaidPartnershipLabel=");
        sb.append(this.A0r);
        sb.append(", createPartnershipAdsAdCode=");
        sb.append(this.A06);
        sb.append(", brandedContentTagsCount=");
        sb.append(this.A00);
        sb.append(", hasBrandedContentPendingSponsor=");
        sb.append(this.A0C);
        sb.append(", hasBrandedContentIneligibleSponsorForCrossposting=");
        sb.append(this.A0A);
        sb.append(", isDestinationFBPageEligibleForBrandedContentXPosting=");
        sb.append(this.A05);
        sb.append(", hasBrandedContentMediaGating=");
        sb.append(this.A0B);
        sb.append(", hasProfileShopLink=");
        sb.append(this.A0a);
        sb.append(", hasProductLink=");
        sb.append(this.A0Y);
        sb.append(", isMusicPartnerShare=");
        sb.append(this.A0q);
        sb.append(", hasCountdownSharedSticker=");
        sb.append(this.A0F);
        sb.append(", isMentionReshare=");
        sb.append(this.A0n);
        sb.append(", isMentionReshareOfCrosspostIneligibleMedia=");
        sb.append(this.A0o);
        sb.append(", isReelMemoryShare=");
        sb.append(this.A0s);
        sb.append(", hasShoppingSticker=");
        sb.append(this.A0f);
        sb.append(", isClipsStory=");
        sb.append(this.A0m);
        sb.append(", isClipsReshare=");
        sb.append(this.A0k);
        sb.append(", isClipsReshareOfCrosspostIneligibleMedia=");
        sb.append(this.A0l);
        sb.append(", hasUpcomingEventSticker=");
        sb.append(this.A0j);
        sb.append(", hasCollabSticker=");
        sb.append(this.A0D);
        sb.append(", hasLinkSticker=");
        sb.append(this.A0P);
        sb.append(", hasFbEntitySticker=");
        sb.append(this.A0H);
        sb.append(MSV.A00(628));
        sb.append(this.A0c);
        sb.append(", hasInternalStickers=");
        sb.append(this.A02);
        sb.append(", hasGroupMentionSticker=");
        sb.append(this.A0J);
        sb.append(", isThreadsAppShare=");
        sb.append(this.A0t);
        sb.append(", hasPromptSticker=");
        sb.append(this.A0b);
        sb.append(", hasBeforeAndAfterSticker=");
        sb.append(this.A09);
        sb.append(", hasStoryTemplateSticker=");
        sb.append(this.A0i);
        sb.append(", hasStoryTemplateCrosspostInegliblePinnedItems=");
        sb.append(this.A0g);
        sb.append(", hasStoryTemplateReshareCrosspostInegliblePinnedItems=");
        sb.append(this.A0h);
        sb.append(", hasMagicModEdits=");
        sb.append(this.A0Q);
        sb.append(", hasMagicModSticker=");
        sb.append(this.A0R);
        sb.append(", hasAddYoursBackdropSticker=");
        sb.append(this.A07);
        sb.append(", hasCommentShareSticker=");
        sb.append(this.A0E);
        sb.append(", hasElectionAddYoursSticker=");
        sb.append(this.A0G);
        sb.append(", hasPhotoCredSticker=");
        sb.append(this.A0X);
        sb.append(", hasNotifyMeSticker=");
        sb.append(this.A0W);
        sb.append(", hasSecretSticker=");
        sb.append(this.A0e);
        sb.append(", hasMusicPickSticker=");
        sb.append(this.A0V);
        sb.append(", hasMusicPickCreationSticker=");
        sb.append(this.A0U);
        sb.append(", hasMediaSticker=");
        sb.append(this.A0S);
        sb.append(", hasImagineTemplateSticker=");
        sb.append(this.A0O);
        sb.append(", hasImagineMeSticker=");
        sb.append(this.A0M);
        sb.append(", hasImagineSticker=");
        sb.append(this.A0N);
        sb.append(", hasImagineEdits=");
        sb.append(this.A0L);
        sb.append(", gifStickerCount=");
        sb.append(this.A01);
        sb.append(')');
        return sb.toString();
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        C14360o3.A0B(parcel, 0);
        parcel.writeString(this.A04.name());
        EnumC150226pU enumC150226pU = this.A03;
        if (enumC150226pU == null) {
            parcel.writeInt(0);
        } else {
            parcel.writeInt(1);
            parcel.writeString(enumC150226pU.name());
        }
        parcel.writeInt(this.A0T ? 1 : 0);
        parcel.writeInt(this.A0p ? 1 : 0);
        parcel.writeInt(this.A0I ? 1 : 0);
        parcel.writeInt(this.A0Z ? 1 : 0);
        parcel.writeInt(this.A0K ? 1 : 0);
        parcel.writeInt(this.A08 ? 1 : 0);
        parcel.writeInt(this.A0d ? 1 : 0);
        parcel.writeInt(this.A0r ? 1 : 0);
        parcel.writeInt(this.A06 ? 1 : 0);
        parcel.writeInt(this.A00);
        parcel.writeInt(this.A0C ? 1 : 0);
        parcel.writeInt(this.A0A ? 1 : 0);
        Boolean bool = this.A05;
        if (bool == null) {
            parcel.writeInt(0);
        } else {
            parcel.writeInt(1);
            parcel.writeInt(bool.booleanValue() ? 1 : 0);
        }
        parcel.writeInt(this.A0B ? 1 : 0);
        parcel.writeInt(this.A0a ? 1 : 0);
        parcel.writeInt(this.A0Y ? 1 : 0);
        parcel.writeInt(this.A0q ? 1 : 0);
        parcel.writeInt(this.A0F ? 1 : 0);
        parcel.writeInt(this.A0n ? 1 : 0);
        parcel.writeInt(this.A0o ? 1 : 0);
        parcel.writeInt(this.A0s ? 1 : 0);
        parcel.writeInt(this.A0f ? 1 : 0);
        parcel.writeInt(this.A0m ? 1 : 0);
        parcel.writeInt(this.A0k ? 1 : 0);
        parcel.writeInt(this.A0l ? 1 : 0);
        parcel.writeInt(this.A0j ? 1 : 0);
        parcel.writeInt(this.A0D ? 1 : 0);
        parcel.writeInt(this.A0P ? 1 : 0);
        parcel.writeInt(this.A0H ? 1 : 0);
        parcel.writeInt(this.A0c ? 1 : 0);
        parcel.writeInt(this.A02);
        parcel.writeInt(this.A0J ? 1 : 0);
        parcel.writeInt(this.A0t ? 1 : 0);
        parcel.writeInt(this.A0b ? 1 : 0);
        parcel.writeInt(this.A09 ? 1 : 0);
        parcel.writeInt(this.A0i ? 1 : 0);
        parcel.writeInt(this.A0g ? 1 : 0);
        parcel.writeInt(this.A0h ? 1 : 0);
        parcel.writeInt(this.A0Q ? 1 : 0);
        parcel.writeInt(this.A0R ? 1 : 0);
        parcel.writeInt(this.A07 ? 1 : 0);
        parcel.writeInt(this.A0E ? 1 : 0);
        parcel.writeInt(this.A0G ? 1 : 0);
        parcel.writeInt(this.A0X ? 1 : 0);
        parcel.writeInt(this.A0W ? 1 : 0);
        parcel.writeInt(this.A0e ? 1 : 0);
        parcel.writeInt(this.A0V ? 1 : 0);
        parcel.writeInt(this.A0U ? 1 : 0);
        parcel.writeInt(this.A0S ? 1 : 0);
        parcel.writeInt(this.A0O ? 1 : 0);
        parcel.writeInt(this.A0M ? 1 : 0);
        parcel.writeInt(this.A0N ? 1 : 0);
        parcel.writeInt(this.A0L ? 1 : 0);
        parcel.writeInt(this.A01);
    }

    public CaptureRuleSystemState(EnumC150226pU enumC150226pU, C8B9 c8b9, Boolean bool, int i, int i2, int i3, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12, boolean z13, boolean z14, boolean z15, boolean z16, boolean z17, boolean z18, boolean z19, boolean z20, boolean z21, boolean z22, boolean z23, boolean z24, boolean z25, boolean z26, boolean z27, boolean z28, boolean z29, boolean z30, boolean z31, boolean z32, boolean z33, boolean z34, boolean z35, boolean z36, boolean z37, boolean z38, boolean z39, boolean z40, boolean z41, boolean z42, boolean z43, boolean z44, boolean z45, boolean z46, boolean z47, boolean z48, boolean z49, boolean z50) {
        C14360o3.A0B(c8b9, 1);
        this.A04 = c8b9;
        this.A03 = enumC150226pU;
        this.A0T = z;
        this.A0p = z2;
        this.A0I = z3;
        this.A0Z = z4;
        this.A0K = z5;
        this.A08 = z6;
        this.A0d = z7;
        this.A0r = z8;
        this.A06 = z9;
        this.A00 = i;
        this.A0C = z10;
        this.A0A = z11;
        this.A05 = bool;
        this.A0B = z12;
        this.A0a = z13;
        this.A0Y = z14;
        this.A0q = z15;
        this.A0F = z16;
        this.A0n = z17;
        this.A0o = z18;
        this.A0s = z19;
        this.A0f = z20;
        this.A0m = z21;
        this.A0k = z22;
        this.A0l = z23;
        this.A0j = z24;
        this.A0D = z25;
        this.A0P = z26;
        this.A0H = z27;
        this.A0c = z28;
        this.A02 = i2;
        this.A0J = z29;
        this.A0t = z30;
        this.A0b = z31;
        this.A09 = z32;
        this.A0i = z33;
        this.A0g = z34;
        this.A0h = z35;
        this.A0Q = z36;
        this.A0R = z37;
        this.A07 = z38;
        this.A0E = z39;
        this.A0G = z40;
        this.A0X = z41;
        this.A0W = z42;
        this.A0e = z43;
        this.A0V = z44;
        this.A0U = z45;
        this.A0S = z46;
        this.A0O = z47;
        this.A0M = z48;
        this.A0N = z49;
        this.A0L = z50;
        this.A01 = i3;
    }

    public CaptureRuleSystemState() {
        this(null, C8B9.UNSET_OR_UNRECOGNIZED_ENUM_VALUE, null, 0, 0, 0, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false);
    }
}
