package X;

import com.facebook.forker.Process;
import com.instagram.react.modules.base.IgReactQEModule;
import org.webrtc.CameraVideoCapturer;

/* renamed from: X.Rz3, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62094Rz3 {
    public static String A00(int i) {
        switch (i) {
            case 2:
                return "STELLA_APP_COMPONENT_TTI";
            case 4:
                return "STELLA_APP_PROCESS_MEDIA_CAPTURE";
            case 5:
                return "STELLA_APP_FETCH_RAW_MEDIA";
            case 10:
                return "STELLA_APP_THUMBNAIL_LIST_QUERY_RESPONSE";
            case 11:
                return "STELLA_APP_FULL_SCREEN_MEDIA_QUERY_RESPONSE";
            case IgReactQEModule.CONFIG_KEY_OFFSET /* 12 */:
                return "STELLA_APP_FULL_SCREEN_MEDIA_TTI";
            case 14:
                return "STELLA_APP_BLUELINK_READY";
            case Process.SIGTERM /* 15 */:
                return "STELLA_APP_PLUGIN_LATENCY";
            case 17:
                return "STELLA_APP_CAPTURE_NOTIF_TO_THUMBNAIL_UI";
            case 1143:
                return "STELLA_APP_STELLA_FIRMWARE_UPDATE_FUNNEL";
            case 1341:
                return "STELLA_APP_ASSISTANT_RESOURCE_OTA";
            case 1813:
                return "STELLA_APP_CAPTURED_MEDIA_SYNC_USER_FLOW";
            case 1926:
                return "STELLA_APP_MEDIA_GALLERY_TTRC";
            case 1972:
                return "STELLA_APP_WIFI_CONNECTION_SETUP";
            case 2649:
                return "STELLA_APP_USER_PAIRING_FAIL";
            case 2745:
                return "STELLA_APP_WIFI_FETCH_ASSET";
            case 2949:
                return "STELLA_APP_BLUELINK_SERVICE_REQUEST";
            case 2993:
                return "STELLA_APP_WIP_CONNECTIVITY_WIFI";
            case 3587:
                return "STELLA_APP_IMPORT_UX_FLOW";
            case 3782:
                return "STELLA_APP_IMPORT_SESSION";
            case 3949:
                return "STELLA_APP_FETCH_DEVICE_ERROR_REPORT";
            case 3991:
                return "STELLA_APP_OTA_ARTIFACT_INSTALL";
            case CameraVideoCapturer.CameraStatistics.CAMERA_FREEZE_REPORT_TIMOUT_MS /* 4000 */:
                return "STELLA_APP_MWA_MEDIA_SAVE_QPL_EVENT";
            case 4062:
                return "STELLA_APP_FIRMWARE_OTA_SHOW_CLOUD_OTA_UPSELL";
            case 4210:
                return "STELLA_APP_NAVIGATION_TTRC";
            case 4305:
                return "STELLA_APP_CHANGE_EIS_MODE_FLOW";
            case 4570:
                return "STELLA_APP_DEVICE_HTTP_REQUEST";
            case 4646:
                return "STELLA_APP_FOA_PROVIDER_LINKING";
            case 4717:
                return "STELLA_APP_MCU_FLYTRAP_INIT";
            case 4828:
                return "STELLA_APP_TAR_QPL_EVENT";
            case 5145:
                return "STELLA_APP_FIRMWARE_OTA_DOWNLOAD";
            case 5442:
                return "STELLA_APP_EDITED_MEDIA_SYNC_USER_FLOW";
            case 5492:
                return "STELLA_APP_AI_MODEL_FETCH_PERF";
            case 5890:
                return "STELLA_APP_REQUEST_FETCH_CHANNEL";
            case 6260:
                return "STELLA_APP_SHOW_FULL_SCREEN_VIDEO_TTRC";
            case 6402:
                return "STELLA_APP_DELETE_DEVICE_ERROR_REPORT";
            case 6819:
                return "STELLA_APP_AUTO_EXPORT_ADOPTION";
            case 6911:
                return "STELLA_APP_CLOUD_RESTORE";
            case 7599:
                return "SCROLL_PERF_STELLA_GALLERY";
            case 7996:
                return "STELLA_APP_MWA_MEDIA_UNDERSTANDING_PLATFORM_JOB_FLOW";
            case 8500:
                return "STELLA_APP_STELLA_PAIRING_FUNNEL";
            case 8582:
                return "STELLA_APP_USER_PAIRING";
            case 8780:
                return "STELLA_APP_OTA_ARTIFACT_DOWNLOAD";
            case 9336:
                return "STELLA_APP_BTC_CONNECTION_UPDATE";
            case 9461:
                return "STELLA_APP_BASIC_MEDIA_EDITOR_TRIM_TOOL_TTRC";
            case 9617:
                return "STELLA_APP_STELLA_ASSISTANT_SETUP_FUNNEL";
            case 9845:
                return "STELLA_APP_STARTUP_PLUGINS";
            case 10365:
                return "STELLA_APP_BLUELINK_FETCH_ASSET";
            case 10420:
                return "STELLA_APP_DEVICE_TELEMETRY_LIST";
            case 10629:
                return "STELLA_APP_BASIC_MEDIA_EDITOR_SAVE_EDIT_TTRC";
            case 10910:
                return "STELLA_APP_SHARINGSERVICE_MWA_EVENT";
            case 10928:
                return "STELLA_APP_LOGOUT";
            case 10931:
                return "STELLA_APP_MEDIA_DELETION";
            case 11078:
                return "STELLA_APP_AUTOFIX_PERF";
            case 11089:
                return "STELLA_APP_MEDIA_SAVE_TO_CAMERA_ROLL";
            case 11322:
                return "STELLA_APP_PAIRING_CONNECTION";
            case 11423:
                return "STELLA_APP_STELLA_DEVICE_SETTINGS_CHANGE";
            case 11538:
                return "STELLA_APP_BASIC_MEDIA_EDITOR_BOOST_TTRC";
            case 11541:
                return "STELLA_APP_HOME_TAB_SERVER_MODULES";
            case 11557:
                return "STELLA_APP_SCROLL_PERF";
            case 11724:
                return "STELLA_APP_SHARINGSERVICE_ESSENTIAL_EVENT";
            case 11916:
                return "STELLA_APP_TASK_VISIT";
            case 12159:
                return "STELLA_APP_FIRMWARE_OTA_INSTALL";
            case 12293:
                return "STELLA_APP_GRAPHQL_QUERY_RESPONSE";
            case 12336:
                return "STELLA_APP_LOGIN";
            case 12395:
                return "STELLA_APP_DEVICE_STATES";
            case 12621:
                return "STELLA_APP_BASIC_MEDIA_EDITOR_REVERT_EDIT_TTRC";
            case 12624:
                return "STELLA_APP_BASIC_MEDIA_EDITOR_CROP_TOOL_TTRC";
            case 12709:
                return "STELLA_APP_SHOW_FULL_SCREEN_PHOTO_TTRC";
            case 12787:
                return "STELLA_APP_BASIC_MEDIA_EDITOR_LIGHTING_TOOL_TTRC";
            case 12867:
                return "STELLA_APP_MEDIA_GALLERY_SCROLL_PERF";
            case 13300:
                return "STELLA_APP_AUDIO_CONNECTIVITY_ATTEMPT";
            case 13641:
                return "STELLA_APP_WIFI_DIRECT_P2P_GROUP_SETUP";
            case 13653:
                return "STELLA_APP_COMPILATION_CLIP_VIEW_TTI";
            case 13723:
                return "STELLA_APP_BATTERY_INSIGHT";
            case 13788:
                return "STELLA_APP_PLACE_SEARCH_REQUEST";
            case 13898:
                return "STELLA_APP_BASIC_MEDIA_EDITOR_LANDING_TTRC";
            case 13938:
                return "STELLA_APP_STELLA_OOBE_FUNNEL";
            case 14534:
                return "STELLA_APP_STELLA_LOGIN_FUNNEL";
            case 14770:
                return "STELLA_APP_SHOW_FULL_SCREEN_MEDIA_TTRC";
            case 14909:
                return "STELLA_APP_NATIVE_PROVIDER_LINKING";
            case 14982:
                return "STELLA_APP_USER_ED_EVENTS";
            case 15183:
                return "STELLA_APP_DEVICE_BATTERY_PERCENTAGE";
            case 15314:
                return "STELLA_APP_UPLOAD_DEVICE_ERROR_REPORT";
            case 15685:
                return "STELLA_APP_SHARINGSERVICE_EVENT";
            case 15706:
                return "STELLA_APP_FIRMWARE_OTA_CHECK";
            case 15882:
                return "STELLA_APP_DEVICE_TELEMETRY_PROCESS_BATCH";
            case 15903:
                return "STELLA_APP_MEDIA_IMPORTING_USER_WAIT";
            case 15954:
                return "STELLA_APP_ROUTE_PREVIEW_REQUEST";
            case 16040:
                return "STELLA_APP_TASK_TRANSITIVE_TOTAL";
            case 16091:
                return "STELLA_APP_USER_PAIRING_SUCCESS";
            case 16319:
                return "STELLA_APP_USER_PAIRING_START";
            case 16359:
                return "STELLA_APP_QUERY_DEVICE_ERROR_REPORT";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
