package X;

/* renamed from: X.RvY, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC61900RvY {
    public static String A00(int i) {
        return i != 11238 ? i != 12335 ? i != 12707 ? i != 13494 ? i != 13500 ? i != 15937 ? i != 16240 ? i != 16298 ? "UNDEFINED_QPL_EVENT" : "FBLITE_ATTESTATION_FBLITE_WARMUP_ATTESTATION" : "FBLITE_ATTESTATION_FBLITE_STARTUP_ATTESTATION" : "FBLITE_ATTESTATION_FBLITE_SIGN_TIMESTAMP" : "FBLITE_ATTESTATION_FBLITE_GEN_KEY_PAIR" : "FBLITE_ATTESTATION_FBLITE_ASYNC_WARM_UP_AND_SIGN" : "FBLITE_ATTESTATION_FBLITE_KEY_STORE_CONSTRUCTION" : "FBLITE_ATTESTATION_FBLITE_GEN_ATTESTATION_DATA" : "FBLITE_ATTESTATION_FBLITE_GET_KEY_HASH";
    }
}
