package X;

/* renamed from: X.RxN, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62013RxN {
    public static String A00(int i) {
        return i != 1112 ? i != 3164 ? i != 3612 ? i != 6769 ? i != 7555 ? i != 8144 ? i != 8985 ? i != 9996 ? i != 10268 ? i != 11270 ? "UNDEFINED_QPL_EVENT" : "MESSENGER_ANDROID_MME_IMAGE_TRANSCODE_ERRORS" : "MESSENGER_ANDROID_MME_AUDIO_DOWNLOAD_FAILED" : "MESSENGER_ANDROID_MME_SHARING_BCF_ERROR" : "MESSENGER_ANDROID_MME_SEND_ERROR_PERMANENT_FAILURE" : "MESSENGER_ANDROID_MME_UNKNOWN_MESSAGE_TYPE" : "MESSENGER_ANDROID_MME_THREAD_LIST_LOAD_ERROR" : "MESSENGER_ANDROID_MME_THREAD_VIEW_LOAD_ERRORS" : "MESSENGER_ANDROID_MME_MESSAGE_SENT_ERROR" : "MESSENGER_ANDROID_MME_TOMBSTONE_MESSAGE_TYPE" : "MESSENGER_ANDROID_MME_MESSAGE_RECEIVE_ERROR";
    }
}
