package X;

/* renamed from: X.Rvh, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC61909Rvh {
    public static String A00(int i) {
        return i != 1328 ? i != 2203 ? i != 3725 ? i != 4565 ? i != 8122 ? i != 8448 ? i != 11173 ? i != 12505 ? "UNDEFINED_QPL_EVENT" : "FBLITE_SPATIAL_STUCKNESS_FBLITE_CALCULATE_LINKED_COMPONENT" : "FBLITE_SPATIAL_STUCKNESS_FBLITE_SYSTEM_CURSOR_ON_SPATIAL" : "FBLITE_SPATIAL_STUCKNESS_FBLITE_FOCUS_THRESHOLD_EXCEEDED" : "FBLITE_SPATIAL_STUCKNESS_FBLITE_SCROLL_WITHOUT_FOCUS_CHANGE" : "FBLITE_SPATIAL_STUCKNESS_FBLITE_NAVIGATE_TO_DEAD_END" : "FBLITE_SPATIAL_STUCKNESS_FBLITE_PREPARE_GRAPH" : "FBLITE_SPATIAL_STUCKNESS_FBLITE_FOCUS_CHANGE_AFTER_SCREEN_UPDATE" : "FBLITE_SPATIAL_STUCKNESS_FBLITE_SPATIAL_FOCUS_CHANGE";
    }
}
