package X;

/* renamed from: X.Rv9, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC61877Rv9 {
    public static String A00(int i) {
        return i != 1 ? i != 2 ? i != 4 ? i != 5 ? i != 8 ? i != 12 ? i != 2858 ? i != 4846 ? i != 6067 ? i != 7523 ? i != 12248 ? i != 13125 ? "UNDEFINED_QPL_EVENT" : "CRF_PLATFORM_HEADLOAD_LOGGER_ANDROID" : "CRF_PLATFORM_PRUNE_STORAGE_STORIES" : "CRF_PLATFORM_CSR_TAIL_LOAD_CACHE_TIMER" : "CRF_PLATFORM_CRF_RANKING_SIGNAL_DISTRIBUTION" : "CRF_PLATFORM_NETWORK_THROTTLE" : "CRF_PLATFORM_CSR_STORAGE_PRUNE" : "CRF_PLATFORM_CRF_POOL_EDGE_RETRIEVAL" : "CRF_PLATFORM_CRF_DATA_SENT_TO_UI" : "CRF_PLATFORM_CRF_INFRA_1ST_FETCH_ANDROID" : "CRF_PLATFORM_CRF_STORAGE_STATS" : "CRF_PLATFORM_EDGE_INFLATION_ANDROID" : "CRF_PLATFORM_NETWORK_FETCH_LOGGER_ANDROID";
    }
}
