package X;

/* renamed from: X.RwJ, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC61947RwJ {
    public static String A00(int i) {
        return i != 2516 ? i != 4378 ? i != 5828 ? i != 9074 ? i != 9280 ? i != 10821 ? i != 10990 ? "UNDEFINED_QPL_EVENT" : "IG_ANDROID_BACKGROUND_PREFETCH_TASK_EXECUTED" : "IG_ANDROID_BACKGROUND_PREFETCH_IG_ANDROID_BG_STORY_PREFETCH_RUNNABLE_EXCEPTION" : "IG_ANDROID_BACKGROUND_PREFETCH_TASK_EXECUTION" : "IG_ANDROID_BACKGROUND_PREFETCH_TASK_SCHEDULED" : "IG_ANDROID_BACKGROUND_PREFETCH_TASK_STOPPED" : "IG_ANDROID_BACKGROUND_PREFETCH_TASK_STARTED" : "IG_ANDROID_BACKGROUND_PREFETCH_TASK_CANCELED";
    }
}
