package X;

/* renamed from: X.Rz5, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62096Rz5 {
    public static String A00(int i) {
        return i != 1677 ? i != 1797 ? i != 2780 ? i != 3186 ? i != 3208 ? i != 8886 ? i != 11246 ? "UNDEFINED_QPL_EVENT" : "STICKER_TYPEAHEAD_SUGGESTION_DOWNLOAD_AVATAR_STICKERS" : "STICKER_TYPEAHEAD_SUGGESTION_DOWNLOAD_STICKER_IMAGE" : "STICKER_TYPEAHEAD_SUGGESTION_DOWNLOAD_STICKERS" : "STICKER_TYPEAHEAD_SUGGESTION_LOAD_SUGGESTION_TRAY" : "STICKER_TYPEAHEAD_SUGGESTION_INITIALIZE_LIB" : "STICKER_TYPEAHEAD_SUGGESTION_DOWNLOAD_INTENT_STICKERS" : "STICKER_TYPEAHEAD_SUGGESTION_GET_STICKERS";
    }
}
