package X;

/* renamed from: X.Rzo, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62141Rzo {
    public static String A00(int i) {
        return i != 3026 ? i != 6159 ? i != 9820 ? i != 9939 ? i != 10364 ? i != 13581 ? i != 13841 ? i != 14709 ? "UNDEFINED_QPL_EVENT" : "WEARABLE_SHAREBAR_APP_START" : "WEARABLE_SHAREBAR_SHAREBAR_LOAD_STORIES_TARGETS" : "WEARABLE_SHAREBAR_SHAREBAR_CONTACT_ROW_SCROLL_PERF" : "WEARABLE_SHAREBAR_SHAREBAR_STAGING_TTRC" : "WEARABLE_SHAREBAR_SHAREBAR_LOAD_TOP_CONTACTS" : "WEARABLE_SHAREBAR_SHAREBAR_LOAD_CONTACTS_ROW" : "WEARABLE_SHAREBAR_SHAREBAR_STORY_TARGET_CACHE" : "WEARABLE_SHAREBAR_SHAREBAR_UPDATE_STORY_TARGETS";
    }
}
