package X;

/* renamed from: X.Rvw, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC61924Rvw {
    public static String A00(int i) {
        return i != 3 ? i != 8 ? i != 16 ? i != 18 ? i != 3708 ? i != 4324 ? i != 6630 ? i != 11183 ? "UNDEFINED_QPL_EVENT" : "GAMING_DESTINATION_RN_GAMING_HOME_TTRC" : "GAMING_DESTINATION_RN_HOME_PAGINATION_FCRT" : "GAMING_DESTINATION_GAMING_BOOKMARK_TTRC" : "GAMING_DESTINATION_WWW_GRAPHQL_EXECUTION" : "GAMING_DESTINATION_GAMING_SURFACE_TRANSITION_TTRC" : "GAMING_DESTINATION_GAMING_FBGG_DEEPLINK_TTI" : "GAMING_DESTINATION_GAMING_TAB_PAGING_TTI" : "GAMING_DESTINATION_GAMING_TAB_TTRC";
    }
}
