package X;

/* renamed from: X.RxF, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62005RxF {
    public static String A00(int i) {
        return i != 2259 ? i != 4077 ? i != 4809 ? i != 8154 ? i != 9185 ? i != 10283 ? i != 12885 ? "UNDEFINED_QPL_EVENT" : "MARKETPLACE_MESSAGING_MARKETPLACE_SAFETY_INTERVENTION_SEND_MESSAGE_INTERVENTION" : "MARKETPLACE_MESSAGING_MARKETPLACE_CONTENT_FILTER_DICTIONARY_DATA_FETCH" : "MARKETPLACE_MESSAGING_MARKETPLACE_CONTENT_FILTER_MARKED_SAFETY_INTERVENTIONS_DATA_FETCH" : "MARKETPLACE_MESSAGING_MARKETPLACE_SAFETY_INTERVENTION_LINK_CLICK_INTERVENTION_DATA_FETCH" : "MARKETPLACE_MESSAGING_MARKETPLACE_SAFETY_INTERVENTION_LINK_CLICK_INTERVENTION" : "MARKETPLACE_MESSAGING_MARKETPLACE_CONTENT_FILTER_MATCH_TTC" : "MARKETPLACE_MESSAGING_MARKETPLACE_CONTENT_FILTER_ELIGIBILITY_DATA_FETCH";
    }
}
