package X;

/* renamed from: X.Rzy, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62151Rzy {
    public static String A00(int i) {
        return i != 1 ? i != 1403 ? i != 3853 ? i != 4352 ? i != 4429 ? i != 7627 ? i != 13243 ? i != 13685 ? "UNDEFINED_QPL_EVENT" : "WHATSAPP_META_VERIFIED_WHATSAPP_MV_IAP_FETCH_PRICE" : "WHATSAPP_META_VERIFIED_WHATSAPP_BLOKS_ANDROID" : "WHATSAPP_META_VERIFIED_WHATSAPP_MV_IAP_QUERY_PURCHASE" : "WHATSAPP_META_VERIFIED_WHATSAPP_MV_IDV_UPLOAD" : "WHATSAPP_META_VERIFIED_WHATSAPP_MV_IAP_PURCHASE" : "WHATSAPP_META_VERIFIED_WHATSAPP_NATIVE_TO_BLOKS_ANDROID" : "WHATSAPP_META_VERIFIED_WHATSAPP_MV_DOC_UPLOAD" : "WHATSAPP_META_VERIFIED_WHATSAPP_MV_ELIGIBILITY_CHECK";
    }
}
