package X;

/* renamed from: X.Rzd, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62130Rzd {
    public static String A00(int i) {
        return i != 2928 ? i != 5621 ? i != 6660 ? i != 7988 ? i != 8602 ? i != 9705 ? i != 10680 ? i != 11875 ? i != 13214 ? i != 14434 ? "UNDEFINED_QPL_EVENT" : "WEARABLE_GALLERY_AUTOMATIC_MEDIA_SYNC" : "WEARABLE_GALLERY_USER_INITIATED_MEDIA_SYNC" : "WEARABLE_GALLERY_RENDER_GRID_ITEM" : "WEARABLE_GALLERY_APP_START" : "WEARABLE_GALLERY_GALLERY_CLOUD_UPLOAD" : "WEARABLE_GALLERY_EDITOR_STICKER_SINGLE_STICKER_LOAD" : "WEARABLE_GALLERY_GET_FULL_RES_IMAGE_REQUEST" : "WEARABLE_GALLERY_VIEW_ALBUMS" : "WEARABLE_GALLERY_RENDER_PAGER_ITEM" : "WEARABLE_GALLERY_ANY_DIRECT_MEDIA_SYNC";
    }
}
