package X;

/* renamed from: X.Rz1, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62092Rz1 {
    public static String A00(int i) {
        return i != 4286 ? i != 8543 ? i != 8562 ? i != 9111 ? i != 9230 ? i != 9581 ? i != 11054 ? i != 11227 ? i != 11330 ? i != 12045 ? "UNDEFINED_QPL_EVENT" : "SPARK_SCRIPTING_SCRIPTING_CALLBACKS" : "SPARK_SCRIPTING_REACTIVE_GRAPH_UPDATE" : "SPARK_SCRIPTING_TEST_UNCACHED_STATE_CHANGE" : "SPARK_SCRIPTING_TEST_CACHED_STATE_CHANGE" : "SPARK_SCRIPTING_SCENE_SYNCHRONIZE" : "SPARK_SCRIPTING_SCRIPT_UPDATE" : "SPARK_SCRIPTING_TEST_UNINSTANTIATE" : "SPARK_SCRIPTING_TEST_STARTUP" : "SPARK_SCRIPTING_TEST_UPDATE" : "SPARK_SCRIPTING_TEST_INSTANTIATE";
    }
}
