package X;

/* renamed from: X.RzV, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62122RzV {
    public static String A00(int i) {
        return i != 1299 ? i != 2082 ? i != 3866 ? i != 7496 ? i != 10097 ? i != 14838 ? "UNDEFINED_QPL_EVENT" : "WEARABLE_ACHIEVEMENTS_ACHIEVEMENTS_SUBMIT_NOTIFICATION" : "WEARABLE_ACHIEVEMENTS_ACHIEVEMENTS_ANONYMOUS_UPLOAD" : "WEARABLE_ACHIEVEMENTS_ACHIEVEMENTS_DETAILS_LOADING" : "WEARABLE_ACHIEVEMENTS_WEARABLE_ACHEIVEMENTS_SUBSCRIPTION_INIT" : "WEARABLE_ACHIEVEMENTS_WEARABLE_ACHIEVEMENTS_DOWNLOAD_DEFINITIONS" : "WEARABLE_ACHIEVEMENTS_ACHIEVEMENTS_MENU_LOADING";
    }
}
