package X;

/* renamed from: X.Rvo, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC61916Rvo {
    public static String A00(int i) {
        return i != 1124 ? i != 2459 ? i != 4295 ? i != 6146 ? i != 8010 ? i != 9162 ? i != 10991 ? i != 11241 ? i != 14205 ? i != 14463 ? "UNDEFINED_QPL_EVENT" : "FEED_PERSONALIZATION_QUERY_PARAMETERS" : "FEED_PERSONALIZATION_STATE_RESTORATION" : "FEED_PERSONALIZATION_FRESHNESS_SCORE_FOR_URR_FB4A" : "FEED_PERSONALIZATION_NUM_MODELS_IN_POOL" : "FEED_PERSONALIZATION_RESET_TO_FEED_FB4A" : "FEED_PERSONALIZATION_WARM_START" : "FEED_PERSONALIZATION_LAND_TO_CACHE_FB4A" : "FEED_PERSONALIZATION_FRESHNESS_SCORE_STARTUP_VEND_TIMER_V2_FB4A" : "FEED_PERSONALIZATION_FRESHNESS_SCORE_FOR_STARTUP_FB4A" : "FEED_PERSONALIZATION_FRESHNESS_SCORE_URR_VEND_TIMER_V2_FB4A";
    }
}
