package X;

/* renamed from: X.Rz8, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62099Rz8 {
    public static String A00(int i) {
        return i != 1 ? i != 2 ? i != 3 ? i != 4 ? i != 5 ? i != 1625 ? i != 3255 ? i != 4947 ? i != 5381 ? i != 16176 ? "UNDEFINED_QPL_EVENT" : "STORIES_RELIABILITY_ANDROID_UNSAMPLED_DEBUG_EVENT" : "STORIES_RELIABILITY_ANDROID_FB_STORIES_VIEWER_USER_FLOW_LOGGER" : "STORIES_RELIABILITY_ANDROID_FB_STORIES_DATA_INSERTION_FLOW" : "STORIES_RELIABILITY_ANDROID_BUCKET_FETCH_USERFLOW" : "STORIES_RELIABILITY_ANDROID_MEDIA_EVENT" : "STORIES_RELIABILITY_ANDROID_UI_LAYER" : "STORIES_RELIABILITY_ANDROID_TRAY" : "STORIES_RELIABILITY_ANDROID_USER_ACTION" : "STORIES_RELIABILITY_ANDROID_DATA_LAYER" : "STORIES_RELIABILITY_ANDROID_NETWORK";
    }
}
