package X;

/* renamed from: X.RuP, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC61831RuP {
    public static String A00(int i) {
        return i != 8 ? i != 15 ? i != 3511 ? i != 8011 ? i != 12137 ? i != 13166 ? i != 13799 ? i != 13917 ? i != 10 ? i != 11 ? "UNDEFINED_QPL_EVENT" : "APPLICATION_MODULES_FBLITE_DOWNLOAD_MODULE_BATCH" : "APPLICATION_MODULES_FBLITE_DOWNLOAD_MODULE" : "APPLICATION_MODULES_OXYGEN_INSTALLER" : "APPLICATION_MODULES_GOOGLE_DOWNLOADER" : "APPLICATION_MODULES_DG_REQUEST" : "APPLICATION_MODULES_DOPPEL_SWAP" : "APPLICATION_MODULES_SIDELOAD" : "APPLICATION_MODULES_LOAD" : "APPLICATION_MODULES_API_EXECUTE_BATCH" : "APPLICATION_MODULES_FBLITE_OPEN_MODULE";
    }
}
