package X;

/* renamed from: X.Rwu, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC61984Rwu {
    public static String A00(int i) {
        return i != 2841 ? i != 3317 ? i != 6029 ? i != 6378 ? i != 8798 ? i != 9145 ? i != 12303 ? "UNDEFINED_QPL_EVENT" : "INSTAGRAM_DIRECT_SEARCH_CHANNEL_CONTEXT_LINE_FETCH" : "INSTAGRAM_DIRECT_SEARCH_IGD_IOS_NAVIGATION_FROM_UNIVERSAL_SEARCH" : "INSTAGRAM_DIRECT_SEARCH_BANYAN_SYNCED_FOR_NS_RANKING_VIEWS" : "INSTAGRAM_DIRECT_SEARCH_FETCH_AI_AGENTS_FROM_NETWORK" : "INSTAGRAM_DIRECT_SEARCH_UNIVERSAL_SEARCH_CONTEXTUAL_PROFILE_LONG_PRESS" : "INSTAGRAM_DIRECT_SEARCH_IGD_IOS_RECIPIENT_SEARCH" : "INSTAGRAM_DIRECT_SEARCH_LOAD_AI_AGENTS_FROM_DISK";
    }
}
