package X;

/* renamed from: X.RwL, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC61949RwL {
    public static String A00(int i) {
        return i != 5848 ? i != 11299 ? i != 12058 ? i != 14789 ? i != 15085 ? i != 16313 ? "UNDEFINED_QPL_EVENT" : "IG_ANDROID_REELS_PERFORMANCE_CLIPS_FETCH_ANDROID_PERF" : "IG_ANDROID_REELS_PERFORMANCE_CLIPS_VIEWER_CACHE_PERFORMANCE" : "IG_ANDROID_REELS_PERFORMANCE_MEASURE_VIEWS" : "IG_ANDROID_REELS_PERFORMANCE_FRAGMENT_LIFECYCLE" : "IG_ANDROID_REELS_PERFORMANCE_CLIPS_VIEWER_RENDER_PERFORMANCE" : "IG_ANDROID_REELS_PERFORMANCE_CLIPS_VIEWER_TRANSITION";
    }
}
