package X;

/* renamed from: X.Rvr, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC61919Rvr {
    public static String A00(int i) {
        return i != 2986 ? i != 3829 ? i != 4985 ? i != 5213 ? i != 5628 ? i != 9434 ? i != 10956 ? i != 11966 ? i != 12637 ? "UNDEFINED_QPL_EVENT" : "FOA_MESSAGING_HEALTH_MESSAGE_SEND_TO_SENT" : "FOA_MESSAGING_HEALTH_LOCAL_SEND_SPEED" : "FOA_MESSAGING_HEALTH_MESSAGE_SEND_TO_SENT_AGGREGATED" : "FOA_MESSAGING_HEALTH_INBOX_TTRC" : "FOA_MESSAGING_HEALTH_PUSH_TO_THREADVIEW" : "FOA_MESSAGING_HEALTH_MESSAGING_READY_ARMADILLO" : "FOA_MESSAGING_HEALTH_THREADLIST_TO_THREADVIEW_TTRC" : "FOA_MESSAGING_HEALTH_LOCAL_SEND_SPEED_AGGREGATED" : "FOA_MESSAGING_HEALTH_CHANNEL_HEALTH";
    }
}
