package X;

/* renamed from: X.RxJ, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62009RxJ {
    public static String A00(int i) {
        return i != 1841 ? i != 2053 ? i != 13758 ? i != 15085 ? i != 15612 ? i != 16319 ? "UNDEFINED_QPL_EVENT" : "MCP_QUEUE_HEALTH_MCIEXECUTION_QUEUE_INFORMATION_MAIN" : "MCP_QUEUE_HEALTH_MCIEXECUTION_QUEUE_INFORMATION_UTILITY" : "MCP_QUEUE_HEALTH_MCIEXECUTION_QUEUE_INFORMATION_NETWORK" : "MCP_QUEUE_HEALTH_MCIEXECUTION_QUEUE_INFORMATION_DATABASE_READ_ONLY" : "MCP_QUEUE_HEALTH_MCIEXECUTION_QUEUE_INFORMATION_CRYPTO" : "MCP_QUEUE_HEALTH_MCIEXECUTION_QUEUE_INFORMATION_DATABASE";
    }
}
