package X;

/* renamed from: X.Rxo, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62040Rxo {
    public static String A00(int i) {
        return i != 1878 ? i != 2279 ? i != 3228 ? i != 4318 ? i != 7256 ? i != 9050 ? i != 11608 ? i != 12111 ? i != 15216 ? "UNDEFINED_QPL_EVENT" : "MSGR_AI_STUDIO_CONSUMPTION_JTBD_PAGE_LAUNCH" : "MSGR_AI_STUDIO_CONSUMPTION_AI_HOME_FUNNEL" : "MSGR_AI_STUDIO_CONSUMPTION_AI_HOME_LAUNCH" : "MSGR_AI_STUDIO_CONSUMPTION_AI_HOME_SEARCH_RESULTS" : "MSGR_AI_STUDIO_CONSUMPTION_CREATE_AI_CHAT" : "MSGR_AI_STUDIO_CONSUMPTION_CHAT_FUNNEL" : "MSGR_AI_STUDIO_CONSUMPTION_OPEN_AI_CHAT" : "MSGR_AI_STUDIO_CONSUMPTION_AI_HOME_SCROLLING" : "MSGR_AI_STUDIO_CONSUMPTION_PRE_FETCH_AI_HOME_LAUNCH";
    }
}
