package X;

/* renamed from: X.Rwx, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC61987Rwx {
    public static String A00(int i) {
        return i != 9 ? i != 10 ? i != 4165 ? i != 5259 ? i != 9116 ? i != 9897 ? i != 12406 ? i != 15682 ? "UNDEFINED_QPL_EVENT" : "INTERNATIONALIZATION_RLX_SWITCH_LANGUAGE_ANDROID" : "INTERNATIONALIZATION_ULS_INTERFACE_STATE_FB4A" : "INTERNATIONALIZATION_RLX_NDX_FLOW_ANDROID" : "INTERNATIONALIZATION_FB_RESOURCES_LAODING_VOLTRON_MODULE" : "INTERNATIONALIZATION_ULS_LANGUAGE_PROPAGATION_FB4A" : "INTERNATIONALIZATION_FB_RESOURCES_PRELOAD_VOLTRON_MODULE" : "INTERNATIONALIZATION_FB_RESOURCES_LOADING_STRINGS_ANDROID" : "INTERNATIONALIZATION_LANGUAGE_SWITCHER_PREFETCH_LOCALE";
    }
}
