package X;

/* renamed from: X.RyN, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62052RyN {
    public static String A00(int i) {
        return i != 1242 ? i != 2191 ? i != 4888 ? i != 8170 ? i != 8425 ? i != 12878 ? i != 14824 ? i != 15253 ? i != 15754 ? "UNDEFINED_QPL_EVENT" : "POST_PURCHASE_ORDERS_EXPERIENCE_ORDER_MANAGEMENT_SCREEN_TTRC" : "POST_PURCHASE_ORDERS_EXPERIENCE_ORDER_RETURN_SCREEN_TTRC" : "POST_PURCHASE_ORDERS_EXPERIENCE_IG_ORDER_RETURN_SCREEN_TTI" : "POST_PURCHASE_ORDERS_EXPERIENCE_IG_ORDERS_HUB_HOME_TTI" : "POST_PURCHASE_ORDERS_EXPERIENCE_FB_ORDERS_HUB_ORDER_DETAILS_TTI" : "POST_PURCHASE_ORDERS_EXPERIENCE_ITEM_DETAIL_SCREEN_V2_TTRC" : "POST_PURCHASE_ORDERS_EXPERIENCE_IG_ORDERS_HUB_ORDER_DETAILS_TTI" : "POST_PURCHASE_ORDERS_EXPERIENCE_FB_ORDER_RETURN_SCREEN_TTI" : "POST_PURCHASE_ORDERS_EXPERIENCE_FB_ORDERS_HUB_HOME_TTI";
    }
}
