package X;

import androidx.credentials.playservices.controllers.CreatePublicKeyCredential.PublicKeyCredentialControllerUtility;
import com.facebook.catalyst.modules.cameraroll.CameraRollManager;
import com.facebook.catalyst.modules.netinfo.NetInfoModule;
import com.facebook.common.dextricks.DexOptimizationMessageHandler;
import com.facebook.common.dextricks.JITProfilePQR;
import com.facebook.common.dextricks.StringTreeSet;
import com.facebook.forker.Process;
import com.facebook.location.platform.api.Location;
import com.facebook.proxygen.TraceFieldType;
import com.facebook.tigon.tigonhuc.HucClient;
import com.facebookpay.offsite.models.message.MessageType$Companion;
import com.instagram.debug.devoptions.direct.burner.BurnerSendSettingsHelper;
import com.instagram.debug.devoptions.fbpay.IgECPPlaygroundActivity;
import com.instagram.debug.devoptions.sandboxselector.DevServerEntity;
import com.instagram.react.modules.base.IgReactQEModule;
import go.Seq;
import org.webrtc.ScreenCapturerAndroid;

/* renamed from: X.Pt9, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC58317Pt9 {
    public static String A00(int i) {
        switch (i) {
            case 0:
                return "com.instagram.android";
            case 1:
                return "null cannot be cast to non-null type kotlin.collections.Map<kotlin.String, kotlin.Any>";
            case 2:
                return "null cannot be cast to non-null type android.view.WindowManager";
            case 3:
                return "null cannot be cast to non-null type com.instagram.common.session.LoggedOutSession";
            case 4:
                return "android.intent.category.BROWSABLE";
            case 5:
                return "error_message_title";
            case 6:
                return "logging_session_id";
            case 7:
                return "null cannot be cast to non-null type com.instagram.base.activity.IgFragmentActivity";
            case 8:
                return "android.intent.action.MAIN";
            case 9:
                return "application/octet-stream";
            case 10:
                return "developer_app_logo_url";
            case 11:
                return "null cannot be cast to non-null type kotlin.collections.Map<kotlin.String, kotlin.String>";
            case IgReactQEModule.CONFIG_KEY_OFFSET /* 12 */:
                return "shipping_address_id";
            case JITProfilePQR.HEADER_COMPRESSED_SIZE_OFFSET /* 13 */:
                return TraceFieldType.StatusCode;
            case 14:
                return "OxygenInstallSDK_UnexpectedException";
            case Process.SIGTERM /* 15 */:
                return "PAYMENT_AUTOFILL";
            case 16:
                return "XIGGenAIIGCreatorPersona";
            case 17:
                return "android.permission.READ_MEDIA_IMAGES";
            case 18:
                return "android.settings.APPLICATION_DETAILS_SETTINGS";
            case Process.SIGSTOP /* 19 */:
                return "blocks_logging_data";
            case 20:
                return "client_subscription_id";
            case 21:
                return "com.instagram.url.extra.BUNDLE";
            case 22:
                return TraceFieldType.Error;
            case 23:
                return TraceFieldType.ErrorDomain;
            case 24:
                return "error_title";
            case 25:
                return "exclude_unused_fields";
            case 26:
                return "expiring_at";
            case 27:
                return "ig_messaging_data";
            case 28:
                return "null cannot be cast to non-null type com.facebook.common.locale.Country";
            case CameraRollManager.IMAGES_MEDIA_LATITUDE_LONGITUDE_DEPRECATED_API_LEVEL /* 29 */:
                return "response_type";
            case 30:
                return "user_add_credential_submit";
            case 31:
                return ", payload=";
            case 32:
                return "An operation is not implemented: ";
            case 33:
                return "Message was missing required fields.  (Lite runtime could not determine which fields were missing).";
            case 34:
                return "android.permission.READ_MEDIA_VISUAL_USER_SELECTED";
            case 35:
                return "checkout_session_id";
            case 36:
                return "com.meta.arfx.engine.interfaces.IARNetworkClientWorkerHost";
            case 37:
                return "custom_benefits";
            case 38:
                return "custom_benefits_payload";
            case 39:
                return "extra_params";
            case 40:
                return "following_count";
            case Seq.NULL_REFNUM /* 41 */:
                return "iab_session_id";
            case Seq.RefTracker.REF_OFFSET /* 42 */:
                return "is_added_to_main_grid";
            case 43:
                return "is_background";
            case 44:
                return "layout_inflater";
            case 45:
                return "null cannot be cast to non-null type com.fbpay.util.exceptions.PaymentsUserFacingException";
            case JITProfilePQR.MEGA_ZIP_NAME_PREFIX_LEN /* 46 */:
                return "null cannot be cast to non-null type com.instagram.common.session.Session";
            case 47:
                return "oxp_show_app_update_installed_notifications";
            case 48:
                return "prize_option";
            case 49:
                return "profile_badge_localized";
            case BurnerSendSettingsHelper.MESSAGE_SEND_BATCH_SIZE /* 50 */:
                return "response_metadata";
            case 51:
                return "selected_credential";
            case 52:
                return "submission_id";
            case 53:
                return "suggested_prompts";
            case 54:
                return "user_remove_credential_enter";
            case 55:
                return "user_remove_credential_submit";
            case 56:
                return "xdt_remove_user_school";
            case 57:
                return "xfb_igd_channel_directory(data:$data)";
            case 58:
                return ", description=";
            case 59:
                return ", message=";
            case 60:
                return ", sessionId=";
            case 61:
                return ".facebook.com";
            case 62:
                return "Android";
            case StringTreeSet.PAYLOAD_MASK /* 63 */:
                return "AndroidKeyStore";
            case 64:
                return "BrowserLiteIntent.EXTRA_IS_LOGGING_ENABLED";
            case 65:
                return "BrowserLiteIntent.IABLoggingExtras.IAB_SESSION_ID";
            case 66:
                return "CHECKOUT_NOT_AVAILABLE";
            case 67:
                return "Deprecated and not implemented.";
            case 68:
                return "ERROR_MESSAGE";
            case 69:
                return "Failed to unregister broadcast receiver";
            case 70:
                return "GraphQLQuery required for GraphQL call";
            case 71:
                return "THEME_INSTAGRAM_WATCH_AND_BROWSE";
            case 72:
                return "Tracking.ARG_CLICK_SOURCE";
            case 73:
                return "TrackingInfo.ARG_CALLSITE_SESSION_ID";
            case 74:
                return "Unknown ViewModel class: ";
            case 75:
                return "address_typeahead";
            case 76:
                return "ads_event_sharing_ig_business_user_opt_in_status";
            case 77:
                return "android";
            case 78:
                return "android.intent.action.SCREEN_OFF";
            case 79:
                return "android.intent.category.LAUNCHER";
            case 80:
                return "android.permission.ACCESS_MEDIA_LOCATION";
            case 81:
                return "android.permission.ACCESS_NETWORK_STATE";
            case 82:
                return "android.permission.READ_MEDIA_VIDEO";
            case 83:
                return "android.resource";
            case 84:
                return "autofill_key";
            case 85:
                return "bloks_bundle_tree";
            case 86:
                return "business_id";
            case 87:
                return "bytes_downloaded";
            case 88:
                return "can_reshare";
            case 89:
                return "chat.whatsapp.com";
            case 90:
                return "checkout_info";
            case 91:
                return "client_remove_contact_success";
            case 92:
                return "client_remove_credential_fail";
            case 93:
                return "client_remove_credential_success";
            case 94:
                return "color_ranges";
            case 95:
                return "cross_app_discoverability_map";
            case 96:
                return "display_category_name";
            case 97:
                return "download_url";
            case 98:
                return "error_message_description";
            case 99:
                return "error_msg";
            case 100:
                return "exception_trace";
            case 101:
                return "filesize_bytes";
            case 102:
                return "first_party_cdn_proxied_images";
            case 103:
                return "has_unseen_media";
            case 104:
                return "hd_profile_pic_url_info";
            case 105:
                return "hex_rgb_color";
            case 106:
                return "hex_rgb_color_dark";
            case 107:
                return "image_versions2";
            case 108:
                return "include_biography";
            case 109:
                return "include_unseen_count";
            case 110:
                return "inline_style";
            case 111:
                return "inline_style_ranges";
            case 112:
                return "interaction_tap";
            case 113:
                return "jobscheduler";
            case 114:
                return "json_response";
            case 115:
                return "link_action";
            case 116:
                return "manufacturer";
            case 117:
                return "navbar_title";
            case 118:
                return "null cannot be cast to non-null type com.instagram.graphql.error.GraphQLException";
            case 119:
                return "null cannot be cast to non-null type com.instagram.nux.aymh.accountprovider.credentials.TokenCredentials";
            case HucClient.BODY_UPLOAD_TIMEOUT_SECONDS /* 120 */:
                return "null cannot be cast to non-null type com.instagram.nux.aymh.accountprovider.credentials.UsernameAndPasswordCredentials";
            case 121:
                return "null cannot be cast to non-null type java.net.HttpURLConnection";
            case 122:
                return "nux_checkout";
            case 123:
                return "open_carousel_submission_state";
            case 124:
                return "previous_submitter";
            case 125:
                return "primary_button_label";
            case 126:
                return "prompt_source";
            case StringTreeSet.MAX_SYMBOL_COUNT /* 127 */:
                return "qualcomm";
            case 128:
                return "raw_phone_number";
            case 129:
                return "recent_searches";
            case 130:
                return "response_timestamp";
            case 131:
                return "selected_user_id";
            case 132:
                return "show_fb_link_on_profile";
            case 133:
                return "show_fb_page_link_on_profile";
            case 134:
                return "square";
            case 135:
                return "storefront_attribution_username";
            case 136:
                return DevServerEntity.COLUMN_SUPPORTS_VPNLESS;
            case 137:
                return "target_url";
            case 138:
                return "transaction_id";
            case 139:
                return "universal_link";
            case 140:
                return "user_edit_credential_enter";
            case 141:
                return "user_edit_credential_submit";
            case 142:
                return "video/x-vnd.on2.vp8";
            case 143:
                return "xdt_async_confirm_confirmation_code(data:$data)";
            case 144:
                return "xfb_biig_ads_event_sharing_settings(business_ig_id:$business_ig_id)";
            case 145:
                return "xfb_commerce_cart_add_product(data:$input)";
            case 146:
                return "xfb_genai_write_with_ai_query(params:$params)";
            case 147:
                return "xfb_meta_ai_intents_feedback(feedback_kind:$feedback_kind,intent_task:$intent_task,metagen_request_id:$metagen_request_id,metagen_response_id:$metagen_response_id,surface:$surface)";
            case 148:
                return "xig_creator_ai_fact_preview_query(request:$request)";
            case 149:
                return "xig_user_by_igid_v2(id:$user_id)";
            case 150:
                return ", adId=";
            case 151:
                return ", constraints=";
            case 152:
                return ", endTime=";
            case 153:
                return ", product=";
            case 154:
                return ", status=";
            case 155:
                return ", tags=";
            case 156:
                return "2024-10";
            case 157:
                return "Accept-Language";
            case 158:
                return "AdHideReasonsFragment.FEED_ITEM_ID";
            case 159:
                return "AdHideReasonsFragment.TOKEN";
            case 160:
                return "AutofillGraphQLRequest";
            case 161:
                return "BrowserLiteCallbacker";
            case 162:
                return "BrowserLiteIntent.EXTRA_AUTOFILL_EDIT_AUTOFILL_ENTRY_REQUEST_SOURCE";
            case 163:
                return "BrowserLiteIntent.EXTRA_AUTOFILL_ENTRY_JSON_STRINGS";
            case 164:
                return "BrowserLiteIntent.EXTRA_IAB_PLAY_STORE_ALLEYOOP_ENABLED";
            case 165:
                return "BrowserLiteIntent.EXTRA_IS_E2EE_BLACK_HOLE_ENABLED";
            case 166:
                return "BrowserLiteIntent.EXTRA_IS_TRANSPARENT_IAB_ENABLED";
            case 167:
                return "BrowserLiteIntent.EXTRA_LE_DESIGN_EXPERIMENT_STYLE";
            case 168:
                return "BrowserLiteIntent.EXTRA_MEDIA_ID";
            case 169:
                return "BrowserLiteIntent.EXTRA_TRACKING";
            case AbstractC62862SUj.MAX_FACTORIAL /* 170 */:
                return "BrowserLiteIntent.HANDLE_INTENT_START_TIME";
            case 171:
                return "BrowserLiteIntent.IAB_UX_FEATURES_ENABLED";
            case 172:
                return "DELIVERY_RETRY_INTERVAL";
            case 173:
                return "DefaultHttpDataSource";
            case 174:
                return "ECP_CONTAINER_FRAGMENT_NAV_BAR_STYLE";
            case 175:
                return "ECP_CONTAINER_FRAGMENT_TITLE";
            case 176:
                return "ECP_PAYPAL_BA_ALLOWED_INTERCEPT_URL";
            case 177:
                return "ECP_PAYPAL_BA_LOADING_URL";
            case 178:
                return "EXTRAS_SHOULD_WARM_AGAIN";
            case 179:
                return "FBPAY_CONTAINER_FRAGMENT";
            case 180:
                return "GoogleApiAvailability";
            case 181:
                return "GraphQLResult is null.";
            case 182:
                return "HORIZONTAL";
            case 183:
                return "IAB_AUTOFILL";
            case 184:
                return "Inconsistent headers [";
            case 185:
                return "Input fragment or fragmentActivity cannot be null";
            case 186:
                return "Invalid Object Id definition for %s: cannot find property with name %s";
            case 187:
                return "Invalid mode: ";
            case 188:
                return "KEY_SWIPE_HISTORY_V2";
            case 189:
                return "KEY_URL";
            case 190:
                return Location.TAG;
            case 191:
                return "Missing ";
            case 192:
                return "No user session found";
            case 193:
                return "Optional.of(";
            case 194:
                return "PAYFBPayComponentIncentives";
            case 195:
                return "PERSISTENT_UP_TO_DATE";
            case 196:
                return "RECENTS";
            case 197:
                return "REFRESH_PUSH_TOKEN_EXPERIMENT_JOB_INTERVAL_PREF_KEY";
            case 198:
                return "REFRESH_PUSH_TOKEN_EXPERIMENT_REFRESH_INTERVAL_PREF_KEY";
            case 199:
                return "REFRESH_PUSH_TOKEN_EXPERIMENT_SHOULD_REFRESH_PREF_KEY";
            case 200:
                return "REUSE_ATS_IN_AUTH_PROMPT_OBJ_SCOPED";
            case 201:
                return "Retry-After";
            case 202:
                return "Should not be called";
            case 203:
                return "Tracking.ARG_SESSION_ID";
            case 204:
                return "TrackingInfo.ARG_AD_ID";
            case 205:
                return "TrackingInfo.ARG_MEDIA_ID";
            case 206:
                return "TrackingInfo.ARG_TRACKING_TOKEN";
            case 207:
                return "TrackingInfo.ARG_USER_ID";
            case 208:
                return "Unexpected Content-Length [";
            case 209:
                return "Unexpected Content-Range [";
            case 210:
                return "Unsupported codec for ";
            case 211:
                return "XFBWriteWithAITentativeSuggestion";
            case 212:
                return "XFBWriteWithAITentativeSuggestionResult";
            case 213:
                return "accounts/set_comment_filter/";
            case 214:
                return "accuracy_meters";
            case 215:
                return "add ig implementation";
            case 216:
                return "add_shipping_address";
            case 217:
                return "additional_candidates";
            case 218:
                return "all_previous_submitters";
            case 219:
                return "allowUniversalAccessFromFileURLs";
            case 220:
                return "alwaysReloadOnSourceChange";
            case 221:
                return "android.hardware.camera";
            case 222:
                return "android.hardware.camera.front";
            case 223:
                return "android.intent.action.CALL";
            case 224:
                return "android.permission.READ_PHONE_STATE";
            case 225:
                return "android.provider.extra.APP_PACKAGE";
            case 226:
                return "application_id";
            case 227:
                return "appmanager_unknown";
            case 228:
                return "attachment_media_uri";
            case 229:
                return "audience_enum";
            case 230:
                return "autofill_contact_enhanced";
            case 231:
                return "best_instance";
            case 232:
                return "bk.action.media.LoadAlbums";
            case 233:
                return "bk.action.media.LoadMediaV3";
            case 234:
                return "bloks_params";
            case 235:
                return "btp_timestamps";
            case 236:
                return "cache_ttl";
            case 237:
                return "callSummaryInfo";
            case 238:
                return "carousel_media_count";
            case 239:
                return "carousel_media_pending_post_count";
            case 240:
                return "channels_directory_info";
            case 241:
                return "checkout_flow";
            case 242:
                return "client_edit_credential_fail";
            case 243:
                return "client_edit_credential_success";
            case 244:
                return "client_suppression_policy";
            case 245:
                return "clips_spin_swapped_elements";
            case 246:
                return "clips_spins_author_count";
            case 247:
                return "collapsed";
            case 248:
                return "com.android.chrome";
            case 249:
                return "com.android.vending";
            case C8S8.DEFAULT_SWIPE_ANIMATION_DURATION /* 250 */:
                return "com.facebook.mqtt.service.ipc.IMqttSubscribeListener";
            case 251:
                return "com.facebook.pages.app";
            case 252:
                return "com.facebook.rti.fbns.intent.REGISTER";
            case 253:
                return "com.fbpay.w3c.FBPaymentServiceRemoveCardCallback";
            case 254:
                return "com.instagram.android.WHATSAPP_OTP";
            case 255:
                return "com.sec.android.app.samsungapps";
            case 256:
                return "com.sec.android.app.samsungapps.downloadservice.aidl.IGalaxyStoreDownloadCallback";
            case 257:
                return "contacts_upload_snapshot";
            case 258:
                return "content_appreciation";
            case 259:
                return "contextual_link_cta_info";
            case 260:
                return "creator_response_options_query";
            case 261:
                return "credentials";
            case 262:
                return "ctc_call_initiated_directly";
            case 263:
                return "dialog_impression";
            case 264:
                return "ecp_container_fragment";
            case 265:
                return "entry_point_container";
            case 266:
                return NetInfoModule.CONNECTION_TYPE_ETHERNET;
            case 267:
                return "example_dialogue_answer_1";
            case 268:
                return "example_dialogue_answer_2";
            case 269:
                return "example_dialogue_answer_3";
            case 270:
                return "example_dialogue_prompt_1";
            case 271:
                return "example_dialogue_prompt_2";
            case 272:
                return "example_dialogue_prompt_3";
            case 273:
                return "external_session_id";
            case 274:
                return "external_source_label";
            case 275:
                return "external_transaction_id";
            case 276:
                return "fail_count";
            case 277:
                return "fetch__XDTUserDict(id:$id)";
            case 278:
                return "full_item_dict";
            case 279:
                return "gen_ai_persona_user";
            case 280:
                return "generated_content";
            case 281:
                return "gif_info";
            case 282:
                return "graduation_year";
            case 283:
                return "hardwareAccelerationEnabledExperimental";
            case 284:
                return "has_container_fragment";
            case 285:
                return "has_more_available";
            case 286:
                return "has_new_nux_story";
            case 287:
                return "iaw_session_id";
            case 288:
                return "ig_iab_autofill_update_settings";
            case 289:
                return "image/vnd.android.heic";
            case 290:
                return "initial_camera_facing";
            case 291:
                return "instagram_location_id";
            case 292:
                return "instagram_messaging_challenges_prompt";
            case 293:
                return "interest_story";
            case 294:
                return DevServerEntity.TABLE_NAME;
            case 295:
                return "internal_transaction_id";
            case 296:
                return "interop_messaging_user_fbid";
            case 297:
                return "is_call_to_action_enabled";
            case 298:
                return "is_dismiss_pending_media_banner";
            case 299:
                return "is_payment_enabled";
            case DexOptimizationMessageHandler.DEFAULT_RESTART_IMPORTANCE_THRESHOLD /* 300 */:
                return "is_reconsent_enabled";
            case 301:
                return "is_secondary_account_creation";
            case 302:
                return "is_streaming_last_chunk";
            case 303:
                return "is_wa_installed";
            case 304:
                return "key_uri";
            case 305:
                return "keyboard";
            case 306:
                return "l.instagram.com";
            case 307:
                return "last_session_survey_notification_seen_timestamp_ms";
            case 308:
                return "logging_id";
            case 309:
                return "logging_policy_product";
            case 310:
                return "lookahead_count_tray";
            case 311:
                return "lookahead_count_viewer";
            case 312:
                return "mediaPlaybackRequiresUserAction";
            case 313:
                return "merchant_carts";
            case 314:
                return "more_spins_available";
            case 315:
                return "next_page_size";
            case 316:
                return "no calls to next() since the last call to remove()";
            case 317:
                return "normalized_phone_number";
            case 318:
                return "null cannot be cast to non-null type com.facebook.react.bridge.ReactContext";
            case 319:
                return "null cannot be cast to non-null type com.facebookpay.expresscheckout.exceptions.EcpPaymentDetailsException";
            case 320:
                return "null cannot be cast to non-null type com.facebookpay.form.fragment.repository.ComponentFormRepository";
            case 321:
                return "null cannot be cast to non-null type java.text.DecimalFormat";
            case 322:
                return "null cannot be cast to non-null type kotlin.collections.Map<kotlin.String, java.lang.Object>";
            case 323:
                return "number_of_avatars";
            case 324:
                return "offer_id";
            case 325:
                return "one_time_checkout_input";
            case 326:
                return "openNewWindowLinksInNewView";
            case 327:
                return "open_link_generic_error";
            case 328:
                return "open_to_public_submission_description_text";
            case 329:
                return "open_trustly_lightbox";
            case 330:
                return "organic_cta_type";
            case 331:
                return "oxp_show_app_update_available_notifications";
            case 332:
                return "packaged_file(supported_compression_types:$supported_compression_types,supported_texture_formats:$supported_texture_formats)";
            case 333:
                return "page_title";
            case 334:
                return "paging_cursor";
            case 335:
                return "payment_product_id";
            case 336:
                return "persistent";
            case 337:
                return "persona_version_for_viewer";
            case 338:
                return "personalization_features";
            case 339:
                return "phone_numbers";
            case 340:
                return "preview_image_height";
            case 341:
                return "price_currency_code";
            case 342:
                return "primary_profile_link_type";
            case 343:
                return "privacy_policy_terms";
            case 344:
                return "productID";
            case 345:
                return "profile_picture_info";
            case 346:
                return "public-key";
            case 347:
                return "public_phone_country_code";
            case 348:
                return "public_phone_number";
            case 349:
                return "quiet_time_intervals_for_enforcement";
            case 350:
                return "refresh_interval";
            case 351:
                return "refresh_window_ms";
            case 352:
                return "regenerated_field_value";
            case 353:
                return "remove_card";
            case 354:
                return "remove_card_cancel";
            case 355:
                return "remove_paypal";
            case 356:
                return "remove_paypal_cancel";
            case 357:
                return "remove_paypal_save";
            case 358:
                return "render_config_hash";
            case 359:
                return "reportContentSizeChanges";
            case 360:
                return "row_cta";
            case 361:
                return "saveFormDataDisabled";
            case 362:
                return "save_autofill_learn_more";
            case 363:
                return "scrubber_spritesheet_info_candidates";
            case 364:
                return "secondary_button_label";
            case 365:
                return "secondary_text";
            case 366:
                return "seen_ranked_position";
            case 367:
                return "should_show_public_contacts";
            case 368:
                return "social_context_users_count";
            case 369:
                return "social_signal_message_count";
            case 370:
                return "state_changed";
            case 371:
                return "statusBarTranslucent";
            case 372:
                return "stories_viewer_gestures_nux_eligible";
            case 373:
                return "story_suite_organic_campaign";
            case 374:
                return "summary_list";
            case 375:
                return "tentative_suggestions";
            case 376:
                return "thirdPartyCookiesEnabled";
            case 377:
                return "topContentSizeChange";
            case 378:
                return "total_item_count";
            case 379:
                return "trainedAlgorithmicMedia";
            case 380:
                return "tray_image_width_ratio";
            case 381:
                return "ui_mode";
            case 382:
                return "upcoming_event_id_type";
            case 383:
                return "urlPrefixesForDefaultIntent";
            case 384:
                return "user_add_contact_enter";
            case 385:
                return "user_add_credential_enter";
            case 386:
                return "user_edit_contact_enter";
            case 387:
                return "video_bitrate";
            case 388:
                return "viewer_marked_not_interested";
            case 389:
                return "vnd.android.cursor.item/name";
            case 390:
                return "wearable_attribution_info";
            case 391:
                return "webviewDebuggingEnabled";
            case 392:
                return "window.Shopify.CheckoutSheetProtocol.postMessage";
            case 393:
                return "xdt_fetch_spotlight_posts";
            case 394:
                return "xdt_get_friend_map_settings";
            case 395:
                return "xdt_get_listening_now_info";
            case 396:
                return "xdt_update_badge_name(input:$input)";
            case 397:
                return "xdt_update_graduation(input:$input)";
            case 398:
                return "xdt_update_seo_indexing_opted_out(data:$data)";
            case 399:
                return "xdt_user_trial_reels_graphql(data:$data)";
            case ScreenCapturerAndroid.VIRTUAL_DISPLAY_DPI /* 400 */:
                return "xfb_fetch_genai_persona_discovery_paginated_layout(focused_section:$focused_section)";
            case 401:
                return "xfb_fetch_mobile_kirby_field_regeneration(data:$input)";
            case 402:
                return "xfb_fetch_viewer_created_genai_personas";
            case 403:
                return "xfb_genai_persona_initial_creation_image_subscribe(persona_version_id:$persona_version_Id)";
            case 404:
                return "xfb_genai_wwai_suggestion_stream_mutation(input:$input)";
            case 405:
                return "xfb_kirby_mobile_quick_create_genai_persona(data:$input)";
            case 406:
                return "xfb_kitkat_user_experience";
            case 407:
                return "xfb_messenger_gen_ai_nux_consent_status_query";
            case 408:
                return "xig_ig_magic_mod_set_flm_consent_mutation(params:$params)";
            case 409:
                return "xig_meta_ai_voice_ig_user_setting_fetch";
            case 410:
                return "\u0001\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001a";
            case 411:
                return " is not a primitive type";
            case 412:
                return " is not supported!";
            case 413:
                return " must be positive but was: ";
            case 414:
                return " with args => ";
            case 415:
                return ") is out of bound of [0, ";
            case 416:
                return ", accessToken=";
            case 417:
                return ", adGroups=[";
            case 418:
                return ", adResumePositionUs=";
            case 419:
                return ", analyticsDetail=\"";
            case 420:
                return ", borderWidth=";
            case 421:
                return ", bottomLeft=";
            case 422:
                return ", bottomRight=";
            case 423:
                return ", cache key: ";
            case 424:
                return ", cacheTtlSeconds=";
            case 425:
                return ", codepoints:";
            case 426:
                return ", confidence=";
            case 427:
                return ", containerHeight=";
            case 428:
                return ", containerWidth=";
            case 429:
                return ", error message: ";
            case 430:
                return ", errorDomain=";
            case 431:
                return ", firstName=";
            case 432:
                return ", initialDelayMillis=";
            case 433:
                return ", interpolator=";
            case 434:
                return ", longitude=";
            case 435:
                return ", must be one of ";
            case 436:
                return ", photoSize=";
            case 437:
                return ", runAttemptCount=";
            case 438:
                return ", uptimeMillis=";
            case 439:
                return ", videoSize=";
            case 440:
                return ".instagram.com";
            case 441:
                return "/browser/closeWindow";
            case 442:
                return "/fbns_msg_hp";
            case 443:
                return "/fbns_reg_req";
            case 444:
                return "3419628305025917";
            case 445:
                return "567310203415052";
            case 446:
                return "ACCEPTED_SAVE";
            case 447:
                return "ACCESS_TOKEN";
            case 448:
                return "ACTION_PROMPT_IAB_AUTOFILL_ON_EXIT_BROWSER";
            case 449:
                return "Accept-Encoding";
            case 450:
                return "AdHideReasonsFragment.AD_ID";
            case 451:
                return "AdHideReasonsFragment.IS_SURVEY";
            case 452:
                return "AdHideReasonsFragment.MEDIA_AD_CAROUSEL_INDEX";
            case 453:
                return "AdHideReasonsFragment.SOURCE";
            case 454:
                return "AdPlaybackState(adsId=";
            case 455:
                return "Already released";
            case 456:
                return "AmazonShopExternalInterfaceHandler";
            case 457:
                return "Android SDK built for x86";
            case 458:
                return "AppLogPersistenceProxyBase";
            case 459:
                return "Attempted to warm up child process without Helium browser process initialization, current state:";
            case 460:
                return "AudioCapabilities[maxChannelCount=";
            case 461:
                return "AutofillScript";
            case 462:
                return "BALANCED_POWER_AND_ACCURACY";
            case 463:
                return "Binder object is null.";
            case 464:
                return "Ble scan error: ";
            case 465:
                return "Both parameters are null";
            case 466:
                return "BrowserContextHelper";
            case 467:
                return "BrowserLiteIntent.ACTIVITY_INTENT";
            case 468:
                return "BrowserLiteIntent.EXTRA_ALLEYOOP_AD_ACCOUNT_IDS";
            case 469:
                return "BrowserLiteIntent.EXTRA_ALLEYOOP_CAMPAIGN_GROUP_IDS";
            case 470:
                return "BrowserLiteIntent.EXTRA_ALLEYOOP_PACKAGE_NAME";
            case 471:
                return "BrowserLiteIntent.EXTRA_ALLOW_THIRD_PARTY_COOKIES";
            case 472:
                return "BrowserLiteIntent.EXTRA_AUTOFILL_CONTACT_AUTOFILL_BLOCK_LIST";
            case 473:
                return "BrowserLiteIntent.EXTRA_AUTOFILL_CONTACT_OPT_IN_STATUS";
            case 474:
                return "BrowserLiteIntent.EXTRA_AUTOFILL_ENABLED";
            case 475:
                return "BrowserLiteIntent.EXTRA_AUTOFILL_OPTOUT_INFO_BUNDLE_DOMAIN_KEY";
            case 476:
                return "BrowserLiteIntent.EXTRA_AUTOFILL_OPTOUT_INFO_BUNDLE_IS_OPTOUT_KEY";
            case 477:
                return "BrowserLiteIntent.EXTRA_AUTOFILL_PAYMENT_AUTOFILL_BLOCK_LIST";
            case 478:
                return "BrowserLiteIntent.EXTRA_AUTOFILL_PAYMENT_ENABLED";
            case 479:
                return "BrowserLiteIntent.EXTRA_AUTOFILL_SHOULD_REMOVE_AUTOFILL_DOMAIN_OPT_OUT";
            case 480:
                return "BrowserLiteIntent.EXTRA_AUTOFILL_SHOULD_SHOW_FBPAY_DISCLOSURE";
            case 481:
                return "BrowserLiteIntent.EXTRA_AUTOFILL_SHOW_CONSENT";
            case 482:
                return "BrowserLiteIntent.EXTRA_AUTOFILL_UPPER_FUNNEL_LOGGING_ENABLED";
            case 483:
                return "BrowserLiteIntent.EXTRA_BLACK_HOLE_LIST";
            case 484:
                return "BrowserLiteIntent.EXTRA_BROWSER_HISTORY_ITEM_ID";
            case 485:
                return "BrowserLiteIntent.EXTRA_COOKIES";
            case 486:
                return "BrowserLiteIntent.EXTRA_IG_FBPAY_BUTTON_AUTOFILL_DATA";
            case 487:
                return "BrowserLiteIntent.EXTRA_IG_FBPAY_BUTTON_SUPPORT";
            case 488:
                return "BrowserLiteIntent.EXTRA_IG_META_CHECKOUT_SDK_ENABLED";
            case 489:
                return "BrowserLiteIntent.EXTRA_IMAGES_SIZES_LOGGING";
            case 490:
                return "BrowserLiteIntent.EXTRA_INTEGRITY_LOGGING";
            case 491:
                return "BrowserLiteIntent.EXTRA_IS_E2EE_BLACK_HOLE_LOGGING_ENABLED";
            case 492:
                return "BrowserLiteIntent.EXTRA_IS_IN_APP_BROWSER_PROFILING_ENABLED";
            case 493:
                return "BrowserLiteIntent.EXTRA_IS_PERSISTENT_IAB";
            case 494:
                return "BrowserLiteIntent.EXTRA_IS_WEBVIEW_HOT_INSTANCE_EXPERIMENT_TYPE";
            case 495:
                return "BrowserLiteIntent.EXTRA_LOGCAT";
            case 496:
                return "BrowserLiteIntent.EXTRA_MIXED_CONTENT_COMPATABILITY_MODE";
            case 497:
                return "BrowserLiteIntent.EXTRA_MODULE_NAME";
            case 498:
                return "BrowserLiteIntent.EXTRA_PAGE_SIZE_LOGGING";
            case 499:
                return "BrowserLiteIntent.EXTRA_PREFETCH_INFO";
            case 500:
                return "BrowserLiteIntent.EXTRA_PROMO_EXTENSION_ENABLED";
            case 501:
                return "BrowserLiteIntent.EXTRA_REFERER";
            case 502:
                return "BrowserLiteIntent.EXTRA_RELOAD_URL_IN_CURRENT_IAB";
            case 503:
                return "BrowserLiteIntent.EXTRA_REQUEST_LOG_LEVEL";
            case 504:
                return "BrowserLiteIntent.EXTRA_SHOULD_BUFFER_PIXEL_REQUESTS";
            case 505:
                return "BrowserLiteIntent.EXTRA_SHOULD_DISABLE_SWIPE_TO_CLOSE";
            case 506:
                return "BrowserLiteIntent.EXTRA_SHOULD_LOG_IAB_LAUNCH_WHEN_FULLY_VISIBLE";
            case 507:
                return "BrowserLiteIntent.EXTRA_SHOULD_REFRESH_ON_RESUME";
            case 508:
                return "BrowserLiteIntent.EXTRA_SIM_HASH_LOGGING";
            case 509:
                return "BrowserLiteIntent.EXTRA_STATIC_TITLE_TEXT";
            case 510:
                return "BrowserLiteIntent.EXTRA_UA";
            case 511:
                return "BrowserLiteIntent.EXTRA_USE_DEFAULT_USER_AGENT";
            case 512:
                return "BrowserLiteIntent.EXTRA_USE_WIDE_VIEW_PORT";
            case 513:
                return "BrowserLiteIntent.EXTRA_ZONE_POLICY";
            case 514:
                return "BrowserLiteIntent.IABLoggingExtras.IAB_IS_NON_VIEWABLE_SYSTEM_ENABLED";
            case 515:
                return "BrowserLiteIntent.IABLoggingExtras.IAB_NV_SOURCE";
            case 516:
                return "BrowserLiteIntent.IABLoggingExtras.IAB_USER_CLICK_TS";
            case 517:
                return "BrowserLiteIntent.IAB_CAMERA_PERMISSION_DIALOG_ENABLED";
            case 518:
                return "BrowserLiteIntent.IAB_EXTERNAL_INTERSTITIAL_ENABLED";
            case 519:
                return "BrowserLiteIntent.IAB_HTML_MEDIA_CAPTURE_ENABLED";
            case 520:
                return "BrowserLiteIntent.IAB_IG_EXPANDABLE_FOOTER_ENABLED";
            case 521:
                return "BrowserLiteIntent.IAB_IG_EXTENSIONS_ENABLED";
            case 522:
                return "BrowserLiteIntent.IAB_PERMISSION_DIALOG_ENABLED";
            case 523:
                return "BrowserLiteIntent.InstagramExtras.EXTRA_AUTOFILL_OPTOUT_INFO";
            case 524:
                return "BrowserLiteIntent.InstagramExtras.EXTRA_CTWA_BROWSER_CTA_EXTENSION_MODEL";
            case 525:
                return "BrowserLiteIntent.InstagramExtras.EXTRA_IG_CALL_EXTENSION_MODEL";
            case 526:
                return "BrowserLiteIntent.InstagramExtras.EXTRA_IG_LEAD_FORM_EXTENSION_MODEL";
            case 527:
                return "BrowserLiteIntent.InstagramExtras.EXTRA_IG_SCRENSHOT_PREVIEW_DATA";
            case 528:
                return "BrowserLiteIntent.InstagramExtras.EXTRA_KEEP_BROWSER_OPEN_ON_BACK_PRESSED";
            case 529:
                return "BrowserLiteWebChromeClient";
            case 530:
                return "COL_PHONE_ID";
            case 531:
                return "COL_TIMESTAMP";
            case 532:
                return "CONTACT_AND_PAYMENT_AUTOFILL";
            case 533:
                return "CREATE_CONTAINER";
            case 534:
                return "Cannot construct instance of %s (no Creators, like default constructor, exist): %s";
            case 535:
                return "Cannot create empty instance of %s, no default Creator";
            case 536:
                return "Cleartext HTTP traffic not permitted. See https://developer.android.com/guide/topics/media/issues/cleartext-not-permitted";
            case 537:
                return "CodedInputStream encountered an embedded string or message which claimed to have negative size.";
            case 538:
                return "CollabNoteCollaborator";
            case 539:
                return "CommerceCheckoutConstant.request_type";
            case 540:
                return "Content-Encoding";
            case 541:
                return "ContentValues";
            case 542:
                return "Context cannot be null";
            case 543:
                return "Corrupt bundle, cancelling job";
            case 544:
                return "Could not access the field in remoteBinder.";
            case 545:
                return "DEVELOPER_ERROR";
            case 546:
                return "DataSource is already opened";
            case 547:
                return "DataSource is not opened";
            case 548:
                return "DeserializationFeature.UNWRAP_SINGLE_VALUE_ARRAYS";
            case 549:
                return "DisplayMetricsHolder must be initialized with initDisplayMetricsIfNotInitialized or initDisplayMetrics";
            case 550:
                return "Don't know how to handle message: ";
            case 551:
                return IgECPPlaygroundActivity.DOMAIN;
            case 552:
                return "EXTERNAL_CONFIRMATION_URL";
            case 553:
                return "EXTRA_BE_IG_CALL_EXTENSION_ENABLED";
            case 554:
                return "EXTRA_REFERRER";
            case 555:
                return "EvaluatorError";
            case 556:
                return "Expected a valid component query response but found empty";
            case 557:
                return "Failed to access name of field #%d (of %d) of Record type %s";
            case 558:
                return "Failed to read system property ";
            case 559:
                return "FbMsqrdRendererModelLoaderCallback";
            case 560:
                return "FbnsRegistrarRetry";
            case 561:
                return "Fetch failed";
            case 562:
                return "File exists: ";
            case 563:
                return "GoogleDriveIntegration";
            case 564:
                return "GoogleSignatureVerifier";
            case 565:
                return "HIGH_ACCURACY";
            case 566:
                return "IAWOffsiteMessageHandler";
            case 567:
                return "IGDirectLiveLocationSessionsForThreadQuery";
            case 568:
                return "IgOrdersRoute";
            case 569:
                return "IgReactFragment.ARGUMENT_APP_KEY";
            case 570:
                return "IgReactFragment.ARGUMENT_IS_INLINE_NAV_BAR_ENABLED";
            case 571:
                return "IgReactFragment.ARGUMENT_ORIENTATION";
            case 572:
                return "InlineXDTTagSearchResultItemDict";
            case 573:
                return "InlineXDTTagsSearchResponseDict";
            case 574:
                return "Integer value (";
            case 575:
                return "Invalid display size: ";
            case 576:
                return "Invalid icon";
            case 577:
                return "Invalid key count ";
            case 578:
                return "Invalid value count ";
            case 579:
                return "JSON_PARSE_ERROR";
            case 580:
                return "Job with no build ID, cancelling job";
            case 581:
                return "KEY_STRING_ARRAY";
            case 582:
                return "KeyValueWrapper";
            case 583:
                return "Location sharing session creation request failed";
            case 584:
                return "META_CHECKOUT_APP_STYLE_IG";
            case 585:
                return "MM/dd/yyyy, hh:mm a";
            case 586:
                return "MetaCheckoutScript";
            case 587:
                return "Misunderstood job service extras: %s";
            case 588:
                return "MqttNetworkManager";
            case 589:
                return "Must specify ids, uniqueNames, tags or states when building a WorkQuery";
            case 590:
                return "NOT_NOW_CLICK";
            case 591:
                return "Native method not registered. Did you intend to set upcall impl through provider's holder?";
            case 592:
                return "No external inserts";
            case 593:
                return "No external updates";
            case 594:
                return "Not able to convert to VersionedCapability. This should never happen. type: %s";
            case 595:
                return "NoteCustomTheme";
            case 596:
                return "NotePogImageDict";
            case 597:
                return "NotePogVideoDict";
            case 598:
                return "OAUTH_BASE_URI";
            case 599:
                return "OAUTH_DO_NOT_REMOVE_PREVIOUS_SESSION";
            case 600:
                return "Optional.absent()";
            case 601:
                return "Optional.get() cannot be called on an absent value";
            case 602:
                return "Overflow in the size of parcelable";
            case 603:
                return "Overread allowed size end=";
            case 604:
                return "PARTNER_TYPE";
            case 605:
                return "PAYMENT_OTC_SESSION_ID";
            case 606:
                return "PAYMENT_OTC_TYPE";
            case 607:
                return "PERMISSION_DENIED";
            case 608:
                return "PERSISTENT_UP_TO_5_MINS";
            case 609:
                return "PKCS1Padding";
            case 610:
                return "PRE_CLICK_AD_PROCESSING";
            case 611:
                return "Parcelable too small";
            case 612:
                return "Protocol message tag had invalid wire type.";
            case 613:
                return "PushRegistrationService.PUSH_DEVICE_TYPE";
            case 614:
                return "REMOTE_EXCEPTION";
            case 615:
                return "Request failed";
            case 616:
                return "Required View not found. Your layout is missing the ID requested.";
            case 617:
                return "Response code: ";
            case 618:
                return "SERVICE_DISABLED";
            case 619:
                return "SUPPORT_INFO";
            case 620:
                return "SecurityException";
            case 621:
                return "Session required for IG GraphQL call";
            case 622:
                return "Shortcut must have a non-empty label";
            case 623:
                return "Shortcut must have an intent";
            case 624:
                return "Suppliers.ofInstance(";
            case 625:
                return "SuppressAndDeferToClose";
            case 626:
                return "SuppressIndefinitely";
            case 627:
                return "THEME_INSTAGRAM_SIDE_PANEL";
            case 628:
                return "TRUST_BINDING";
            case 629:
                return "TrackingInfo.ARG_CLICK_ID";
            case 630:
                return "TrackingInfo.ARG_LINK_HISTORY_ITEM_ID";
            case 631:
                return "TrackingInfo.ARG_REEL_VIEWER_SESSION_ID";
            case 632:
                return "TrackingInfo.USE_MEDIA_REPORTING_FLOW";
            case 633:
                return "UNEXPECTED_TOPIC";
            case 634:
                return "UNINJECT_MERCHANT_JS";
            case 635:
                return "USAGE_NOTIFICATION";
            case 636:
                return "USAGE_NOTIFICATION_COMMUNICATION_REQUEST";
            case 637:
                return "USAGE_NOTIFICATION_RINGTONE";
            case 638:
                return "UTF-8 length does not fit in int: ";
            case 639:
                return "Unknown error code: ";
            case 640:
                return "Unknown focus change type: ";
            case 641:
                return "Unknown message id: ";
            case 642:
                return "Unknown type: ";
            case 643:
                return "Unknown value: ";
            case 644:
                return "Unsupported message type: ";
            case 645:
                return "Use default gson builders to create JSON strings from Kotlin objects";
            case 646:
                return "Voltron bridge was null, but Helium was marked loaded";
            case 647:
                return "WEB_VIEW_ALLOWED_INTERCEPT_URLS";
            case 648:
                return "WEB_VIEW_FULL_SCREEN";
            case 649:
                return "WEB_VIEW_RESULT_ERROR_MESSAGE_FOR_LOGGING";
            case 650:
                return "WEB_VIEW_RESULT_INTERCEPT_URL";
            case 651:
                return "WEB_VIEW_URL";
            case 652:
                return "Webview url is empty";
            case 653:
                return "While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.";
            case 654:
                return "XFBGenAISearchViewModel";
            case 655:
                return "XFBMessagingPromptV2SimpleMediaSubmission";
            case 656:
                return "XIGGenAIPersona";
            case 657:
                return "ZeroCmsAPIUtil";
            case 658:
                return "__infra__app_id";
            case 659:
                return "__infra__cache_ttl";
            case 660:
                return "__infra__container_config_id";
            case 661:
                return "__infra__screen_id";
            case 662:
                return "__infra__ttrc_marker_id";
            case 663:
                return "access_denied";
            case 664:
                return "accounts/set_comment_filter_keywords/";
            case 665:
                return "active_corpus";
            case 666:
                return "add_card_save";
            case 667:
                return "address_details";
            case 668:
                return "address_street";
            case 669:
                return "ads_event_sharing_ig_consumer_opt_in_status(consumer_ig_id:$consumer_ig_id,ignore_business_opt_in_status:$ignore_business_opt_in_status)";
            case 670:
                return "ads_page_name";
            case 671:
                return "android.hardware.camera.any";
            case 672:
                return "android.hardware.telephony";
            case 673:
                return "android.intent.action.GET_CONTENT";
            case 674:
                return "android.intent.category.DEFAULT";
            case 675:
                return "android.intent.category.OPENABLE";
            case 676:
                return "android.intent.extra.REFERRER";
            case 677:
                return "android.media.action.IMAGE_CAPTURE";
            case 678:
                return "android.net.conn.CONNECTIVITY_CHANGE";
            case 679:
                return "android.permission.WRITE_CALENDAR";
            case 680:
                return "android.settings.APP_NOTIFICATION_SETTINGS";
            case 681:
                return "arg_should_hide_tab_widget";
            case 682:
                return PublicKeyCredentialControllerUtility.JSON_KEY_AUTH_SELECTION;
            case 683:
                return "auto_reg_retry";
            case 684:
                return "auto_reply_audience";
            case 685:
                return "autofill_request_fragment";
            case 686:
                return "besties_count";
            case 687:
                return "billing_address";
            case 688:
                return "billing_length";
            case 689:
                return "billing_type";
            case 690:
                return "biography_with_entities";
            case 691:
                return "birthday_badge_enabled";
            case 692:
                return "blank String (all whitespace)";
            case 693:
                return "block_commenters";
            case 694:
                return "blocked_members";
            case 695:
                return "blocking_gc_count";
            case 696:
                return "blocking_gc_time";
            case 697:
                return "bottom_sheet_title";
            case 698:
                return "browser_consecutive_decline_autofill";
            case 699:
                return "browser_settings_fragment";
            case 700:
                return "business_contact_method";
            case 701:
                return DevServerEntity.COLUMN_CACHE_TIMESTAMP;
            case 702:
                return "calling_package";
            case 703:
                return "can_boost_post";
            case 704:
                return "can_create_new_standalone_personal_fundraiser";
            case 705:
                return "can_react_with_avatar";
            case 706:
                return "capability_options";
            case 707:
                return "capture_stage";
            case 708:
                return "cardholder_name";
            case 709:
                return "carousel_parent_id";
            case 710:
                return "carrier_name";
            case 711:
                return "checkoutSetupPayload";
            case 712:
                return "checkout_init";
            case 713:
                return "checkout_pdp_prefetch(data:{\"payment_type\":\"IG_NMOR_SHOPPING\",\"product_ids\":$product_ids})";
            case 714:
                return "checkout_url";
            case 715:
                return "classification";
            case 716:
                return "cleartext.*not permitted.*";
            case 717:
                return PublicKeyCredentialControllerUtility.JSON_KEY_CLIENT_EXTENSION_RESULTS;
            case 718:
                return "client_add_debug_atomic";
            case 719:
                return "client_load_iap_store_purchases_init";
            case 720:
                return "client_load_iap_store_purchases_success";
            case 721:
                return "client_load_metacheckoutsdk_success";
            case 722:
                return "client_load_shippingaddress_success";
            case 723:
                return "client_load_shopslitecheckouteligibility_success";
            case 724:
                return "client_submit_ecpeventhandling_init";
            case 725:
                return "clips_ad_cta_fragment";
            case 726:
                return "com.facebook.analytics2.logger.USER_LOGOUT";
            case 727:
                return "com.facebook.rti.fbns.intent.RECEIVE_RTC";
            case 728:
                return "com.facebook.rti.fbns.intent.RECEIVE_VR";
            case 729:
                return "com.facebook.rti.intent.ACTION_NOTIFICATION_ACK";
            case 730:
                return "com.facebook.rti.mqtt.ACTION_MQTT_CONFIG_CHANGED";
            case 731:
                return "com.fbpay.w3c.FBPaymentServiceAddCardCallback";
            case 732:
                return "com.google.android.gms.credentials.Credential";
            case 733:
                return "com.instagram.url.extra.IS_ON_CREATE";
            case 734:
                return "com.sony.dtv.hardware.panel.qfhd";
            case 735:
                return "com.spotify.music";
            case 736:
                return "com\\.instagram\\.android\\.";
            case 737:
                return "combined_config_hash";
            case 738:
                return "commerce_checkout_session_id";
            case 739:
                return "complete_paypal_ba_linking_input";
            case 740:
                return "completion_path";
            case 741:
                return "connections_posts";
            case 742:
                return "consent_state";
            case 743:
                return "contact_autofill_automatic_autofill_expiry_timestamp";
            case 744:
                return "contact_autofill_eligible_for_automatic_autofill";
            case 745:
                return "contact_type";
            case 746:
                return "contains_stitched_media_blocked_by_rm";
            case 747:
                return "contains_unavailable_story";
            case 748:
                return "country_name";
            case 749:
                return "creator_agent_persona";
            case 750:
                return "creator_ai_audience_control";
            case 751:
                return "creditCardExpirationDate";
            case 752:
                return "creditCardNumber";
            case 753:
                return "creditCardSecurityCode";
            case 754:
                return "credit_card_token";
            case 755:
                return "ctc_confirmation_dialog_shown";
            case 756:
                return "current_catalog_id";
            case 757:
                return "current_root_id";
            case 758:
                return "current_size_constraint";
            case 759:
                return "data URL did not have correct base64 format.";
            case 760:
                return "declaringClass";
            case 761:
                return "direct_widget";
            case 762:
                return "disabled_reply_types";
            case 763:
                return "displayed_action_button_partner";
            case 764:
                return "displayed_action_button_type";
            case 765:
                return "dynamic_pytorch_impl";
            case 766:
                return "edit_card_save";
            case 767:
                return "edit_shipping_address";
            case 768:
                return "emailAddress";
            case 769:
                return "enable_add_school_in_edit_profile";
            case 770:
                return "ended_challenge";
            case 771:
                return "epoch_time_sec";
            case 772:
                return "error_card_not_found";
            case 773:
                return "error_messages";
            case 774:
                return "establishData";
            case 775:
                return PublicKeyCredentialControllerUtility.JSON_KEY_EXCLUDE_CREDENTIALS;
            case 776:
                return "expiration_time";
            case 777:
                return "expired_link_keywords(after:$expired_end_cursor)";
            case 778:
                return "expiry_month";
            case 779:
                return "external_confirmation_url";
            case 780:
                return "external_tap";
            case 781:
                return "extra_hide_system_status_bar";
            case 782:
                return "extra_report_target";
            case 783:
                return "failed to parse bloks payload";
            case 784:
                return "failing_client_id";
            case 785:
                return "fb_analyticsExtras";
            case 786:
                return "fb_request_id";
            case 787:
                return "fbns_notification_store";
            case 788:
                return "fetch__XDTUserDict(id:$user_id)";
            case 789:
                return "flm_magic_mod_consent_states(products:$products)";
            case 790:
                return "full_context_string";
            case 791:
                return "geo_timestamp_s";
            case 792:
                return "graphql response is empty";
            case 793:
                return "handleMissingInstantiator";
            case 794:
                return "handle_checkout_event(input:$input)";
            case 795:
                return "handle_checkout_event_list";
            case 796:
                return "has_anonymous_profile_picture";
            case 797:
                return "has_besties_media";
            case 798:
                return "has_fan_club_media";
            case 799:
                return "has_main_thread_layout_state";
            case 800:
                return "has_onboarded_to_text_post_app";
            case 801:
                return "has_previous_page";
            case 802:
                return "has_seen_intent_card";
            case 803:
                return "head_movements_directions_json";
            case 804:
                return "highlight_reel_type";
            case 805:
                return "http://schemas.android.com/apk/res/android";
            case 806:
                return "https://connect.facebook.net/en_US/iab.autofill.js";
            case 807:
                return "https://play.google.com/store/apps/details?id=";
            case 808:
                return "https://www.instagram.com/payments/paypal_close/";
            case 809:
                return "hype_commenter_list";
            case 810:
                return "iab_session_params";
            case 811:
                return "icebreaker_prompt_1";
            case 812:
                return "icebreaker_prompt_2";
            case 813:
                return "icebreaker_prompt_3";
            case 814:
                return "id_capture_config";
            case 815:
                return "id_verification";
            case 816:
                return "ig_age_verification_idv";
            case 817:
                return "ig_branded_threads_session_user_info";
            case 818:
                return "ig_contact_invite";
            case 819:
                return "ig_fully_disconnect_fb_pages_bizlink";
            case 820:
                return "ig_has_accepted_tifu_a_likes";
            case 821:
                return "ig_supervised_user_quiet_time_settings_subscribe(data:$input)";
            case 822:
                return "igd_magic_remix_layout";
            case 823:
                return "igd_shared_links_in_thread_details(max_timestamp:$max_timestamp,max_timestamp_float:$max_timestamp_float,thread_igid:$thread_igid)";
            case 824:
                return "import_progress";
            case 825:
                return "include_count";
            case 826:
                return "include_reactions";
            case 827:
                return "include_replies";
            case 828:
                return "initial_path";
            case 829:
                return "inline_disclosure_text";
            case 830:
                return "instagram://shop_pay_did_finish";
            case 831:
                return "intermittent_fail";
            case 832:
                return "interstitial";
            case 833:
                return "iptcExt:DigitalSourceType";
            case 834:
                return "is greater than ";
            case 835:
                return "is_accepting_questions";
            case 836:
                return "is_allowed_to_create_standalone_personal_fundraisers";
            case 837:
                return "is_available";
            case 838:
                return "is_cacheable";
            case 839:
                return "is_cis_enabled";
            case 840:
                return "is_default_toggle_state_on";
            case 841:
                return "is_facebook_friend";
            case 842:
                return "is_feed_favorite";
            case 843:
                return "is_interactive";
            case 844:
                return "is_invitation_valid";
            case 845:
                return "is_pinned_highlight";
            case 846:
                return "is_profile_action_needed";
            case 847:
                return "is_promotions_in_profile_enabled";
            case 848:
                return "is_quiet_mode_enforcement_non_blocking";
            case 849:
                return "is_spotify_account_linked";
            case 850:
                return "is_supervision_features_enabled";
            case 851:
                return "is_watch_and_browse_v2";
            case 852:
                return "latest_besties_reel_media";
            case 853:
                return "link_keywords(after:$active_end_cursor)";
            case 854:
                return "lite_checkout";
            case 855:
                return "live_broadcast_id";
            case 856:
                return "live_location_session_id";
            case 857:
                return "location_context";
            case 858:
                return "logging_enabled";
            case 859:
                return "logging_metadata";
            case 860:
                return "max_instances";
            case 861:
                return "media_id_for_logging";
            case 862:
                return "merchant_domain";
            case 863:
                return "metaCheckoutExperienceType";
            case 864:
                return "metadata_type";
            case 865:
                return "mqtt_radio_active_time";
            case 866:
                return "must be power of 2 between 2^1 and 2^30: ";
            case 867:
                return "mutation_data";
            case 868:
                return "nativePollOnce:bg";
            case 869:
                return "native_auth_attempted";
            case 870:
                return "native_auth_error";
            case 871:
                return "native_auth_success";
            case 872:
                return "navigation_categories_formatted";
            case 873:
                return "navigation_category";
            case 874:
                return "nearby_users";
            case 875:
                return "neighborhood";
            case 876:
                return "no String-argument constructor/factory method to deserialize from String value ('%s')";
            case 877:
                return "non_auth_step_up_error";
            case 878:
                return "normalized_email_address";
            case 879:
                return "notice_content_text";
            case 880:
                return "notice_ui_type";
            case 881:
                return "notif_received_push";
            case 882:
                return "notify_manager";
            case 883:
                return "null cannot be cast to non-null type android.net.ConnectivityManager";
            case 884:
                return "null cannot be cast to non-null type android.text.SpannableString";
            case 885:
                return "null cannot be cast to non-null type com.facebook.react.uimanager.drawable.CompositeBackgroundDrawable";
            case 886:
                return "null cannot be cast to non-null type com.facebookpay.paymentmethod.model.CreditCard";
            case 887:
                return "null cannot be cast to non-null type kotlin.collections.Map<kotlin.Any, kotlin.Any>";
            case 888:
                return "null cannot be cast to non-null type kotlin.collections.Map<kotlin.String, kotlin.Any?>";
            case 889:
                return "null key in entry: null=";
            case 890:
                return "number_of_categories_localized";
            case 891:
                return "oauthIntegrationId";
            case 892:
                return "offer_details";
            case 893:
                return "on_save_callback";
            case 894:
                return "open_bwp_more_info_bottom_sheet";
            case 895:
                return "open_external_url_with_in_app_browser";
            case 896:
                return "otc_session_id";
            case 897:
                return "overflow, value cannot be represented as 16-bit value";
            case 898:
                return "overflow, value cannot be represented as 8-bit value";
            case 899:
                return "oxygen_fbns_config";
            case 900:
                return "partner_type";
            case 901:
                return "path undefined";
            case 902:
                return "payer_name_input";
            case 903:
                return MessageType$Companion.PAYMENT_RESPONSE;
            case 904:
                return "payment_details_updates";
            case 905:
                return "payment_info";
            case 906:
                return "payment_type";
            case 907:
                return "paymod_extra_data";
            case 908:
                return "paypal_consent_fragment";
            case 909:
                return "pending_intent";
            case 910:
                return "pending_request_banner_text";
            case 911:
                return "persona_version";
            case 912:
                return "personal_account_ads_page_id";
            case 913:
                return "personal_account_ads_page_name";
            case 914:
                return "photo_quality";
            case 915:
                return "platform_trust_token";
            case 916:
                return "playable_request_key";
            case 917:
                return "playable_result_key";
            case 918:
                return "playable_result_open_cta";
            case 919:
                return "playable_title";
            case 920:
                return "plugin_response";
            case 921:
                return "prefetch_count";
            case 922:
                return "presence_points";
            case 923:
                return "preview_size";
            case 924:
                return "price_amount_micros";
            case 925:
                return "profile-level-id";
            case 926:
                return "profile_image_id";
            case 927:
                return "profile_pic_id";
            case 928:
                return "profile_reporting_search_results";
            case 929:
                return "promote_pro2pro_client_token";
            case 930:
                return "proxy_refusal";
            case 931:
                return PublicKeyCredentialControllerUtility.JSON_KEY_PUB_KEY_CRED_PARAMS;
            case 932:
                return "public_email";
            case 933:
                return "push_delivery_results";
            case 934:
                return "ranker_scores";
            case 935:
                return "rdf:Description";
            case 936:
                return "receiver_name";
            case 937:
                return "recs_from_friends";
            case 938:
                return "redirect_uri";
            case 939:
                return "reel_auto_archive";
            case 940:
                return "regenerate_bio";
            case 941:
                return "remove_birthday_selfie";
            case 942:
                return "remove_shipping_address";
            case 943:
                return "remove_shipping_address_cancel";
            case 944:
                return "remove_shipping_address_save";
            case 945:
                return "report_bottom_sheet_title";
            case 946:
                return "report_reason";
            case 947:
                return "request must not be null";
            case 948:
                return TraceFieldType.ReqBodySize;
            case 949:
                return "result_upload_response";
            case 950:
                return "safebrowsing_instagram_standalone";
            case 951:
                return "safety_violation_header";
            case 952:
                return "safety_violation_reasons";
            case 953:
                return "save_credential_input";
            case 954:
                return "save_email_input";
            case 955:
                return "save_phone_input";
            case 956:
                return "save_shipping_address_input";
            case 957:
                return "saved_members";
            case 958:
                return "school_name_abbreviation";
            case 959:
                return "search_box_text";
            case 960:
                return "secondary_action_title";
            case 961:
                return "sections_query";
            case 962:
                return "selfie_evidence";
            case 963:
                return "send_message";
            case 964:
                return "sender_not_verified";
            case 965:
                return "session_level_survey";
            case 966:
                return "session_level_survey_notification";
            case 967:
                return "session_survey_controller";
            case 968:
                return "settings_row_title";
            case 969:
                return "share_url_wrapper";
            case 970:
                return "shipping_address_input";
            case 971:
                return "shopify_sdk_payload";
            case 972:
                return "shopping_onboarding_state";
            case 973:
                return "short_prompt_fbt";
            case 974:
                return "should_hide_report_website";
            case 975:
                return "should_prefetch";
            case 976:
                return "should_show_category";
            case 977:
                return "should_show_node_in_accounts_center(interface:\"IG_ANDROID\",selected_node_id:\"AD_PROFILE_CENTER\")";
            case 978:
                return "show_ad_choices";
            case 979:
                return "show_fan_club_stories_teaser";
            case 980:
                return "show_hashtag_icon";
            case 981:
                return "show_schools_badge";
            case 982:
                return "simple_web_view_config";
            case 983:
                return "size_constraint";
            case 984:
                return "skewed_crop_points";
            case 985:
                return "skipExtraFields";
            case 986:
                return "source cannot be null";
            case 987:
                return "spotify_status";
            case 988:
                return "spotlight_posts";
            case 989:
                return "start_media_report";
            case 990:
                return "start_website_report";
            case 991:
                return "story_duration_secs";
            case 992:
                return "story_metadata";
            case 993:
                return "story_prompt";
            case 994:
                return "subtitle_button_text";
            case 995:
                return "suggested_members";
            case 996:
                return "supportedOrientations";
            case 997:
                return "target_account_id";
            case 998:
                return "texts_provider";
            case 999:
                return "thread_content_to_share_url";
            case 1000:
                return "thread_theme";
            case 1001:
                return "thread_theme_attributes";
            case 1002:
                return "thumbnail_url_for_post_or_reel";
            case 1003:
                return "thumbnail_urls";
            case 1004:
                return "toggle_content";
            case 1005:
                return "topLoadingError";
            case 1006:
                return "topLoadingFinish";
            case 1007:
                return "topLoadingStart";
            case 1008:
                return "topPointerCancel";
            case 1009:
                return "topPointerDown";
            case 1010:
                return "topPointerEnter";
            case 1011:
                return "topPointerLeave";
            case 1012:
                return "topPointerMove";
            case 1013:
                return "topPointerOut";
            case 1014:
                return "topPointerOver";
            case 1015:
                return "topPointerUp";
            case 1016:
                return "torch-code-gen";
            case 1017:
                return "tracking_codes";
            case 1018:
                return "translated_full_prompt";
            case 1019:
                return "union_sections_query";
            case 1020:
                return "unregistered";
            case 1021:
                return "upcoming_events";
            case 1022:
                return "updated_cart";
            case 1023:
                return "upload_medium";
            case 1024:
                return "uri has query and/or fragment, which are not supported. Did you call Uri.parse() on a string containing '?' or '#'? Use Uri.fromFile(new File(path)) to avoid this. path=%s,query=%s,fragment=%s";
            case 1025:
                return "url passed in: ";
            case 1026:
                return "user_add_shippingaddress_enter";
            case 1027:
                return "user_click_shippingaddress_atomic";
            case 1028:
                return "user_edit_shippingaddress_enter";
            case 1029:
                return "user_for_attribution";
            case 1030:
                return "user_input_email_address";
            case 1031:
                return "user_remove_credential_exit";
            case 1032:
                return "user_remove_shippingaddress_cancel";
            case 1033:
                return "user_remove_shippingaddress_enter";
            case 1034:
                return "user_remove_shippingaddress_submit";
            case 1035:
                return "using_helium";
            case 1036:
                return "utm_campaign";
            case 1037:
                return "vendor.display-size";
            case 1038:
                return "video_quality";
            case 1039:
                return "video_versions";
            case 1040:
                return "viewer_has_liked";
            case 1041:
                return "vnd.android.cursor.item/email_v2";
            case 1042:
                return "vnd.android.cursor.item/phone_v2";
            case 1043:
                return "watcherClass cannot be null";
            case 1044:
                return "winning_submissions";
            case 1045:
                return "work_last_analytics_endpoint";
            case 1046:
                return "work_last_host";
            case 1047:
                return "xdt__generate_share_url_wrapper(request:$input)";
            case 1048:
                return "xdt_api__v1__dogfooding__eligibility_status(lookback_days:$lookback_days)";
            case 1049:
                return "xdt_api__v1__feed__reels_tray(request_data:{\"page_size\":$page_size,\"reason\":$reason})";
            case 1050:
                return "xdt_api__v1__profile_timeline_by_username(request_data:$request_data,username:$username)";
            case 1051:
                return "xdt_create_friend_map_hidden_location(data:$data)";
            case 1052:
                return "xdt_creators_challenges_additional_challenge_info(challenge_id:$challenge_id,fetch_earned_version:$fetch_earned_version)";
            case 1053:
                return "xdt_creators_challenges_end_challenge(challenge_id:$challenge_id)";
            case 1054:
                return "xdt_get_comment_summary_by_comment_summary_id(request_data:$request_data)";
            case 1055:
                return "xdt_get_igd_thread_content_to_share_url(input:$input)";
            case 1056:
                return "xdt_get_potato_media_items(container_id:$container_id,request_data:{\"excluded_media_ids\":$excluded_media_ids,\"max_id\":$max_id,\"page_size\":$page_size})";
            case 1057:
                return "xdt_get_presence_audience_list_members(data:$data)";
            case 1058:
                return "xdt_get_relationship_for_shid(shid:$shid)";
            case 1059:
                return "xdt_ig_delete_friends_story(input:$input)";
            case 1060:
                return "xdt_profile_reporting_search(request_data:$request_data)";
            case 1061:
                return "xdt_resend_otp_email(input:$input)";
            case 1062:
                return "xdt_start_validation(input:$input)";
            case 1063:
                return "xdt_update_friend_map_hidden_location(data:$data,location_id:$location_id)";
            case 1064:
                return "xdt_update_friend_map_settings(additional_settings:$additional_settings,last_active_location_audience:$audience,update_seen_time:$update_seen_time)";
            case 1065:
                return "xdt_update_presence_audience_list_members(data:$data)";
            case 1066:
                return "xdt_update_school_badge_visibility(input:$input)";
            case 1067:
                return "xfb_avatar_editor_launch_data";
            case 1068:
                return "xfb_biig_ads_event_sharing_notice(business_ig_id:$business_ig_id,consumer_ig_id:$consumer_ig_id,event_type:$event_type)";
            case 1069:
                return "xfb_delete_recent_ad_activity(data:$input)";
            case 1070:
                return "xfb_genai_imagine_memu_spotlight";
            case 1071:
                return "xfb_genai_imagine_suggestions_for_intents(icebreaker_type:$icebreaker_type,intent:$intent,num_suggestions:$num_suggestions,orientation:$orientation,surface:$surface)";
            case 1072:
                return "xfb_genai_memu_update_profile_settings(input:{\"client_mutation_id\":$client_mutation_id,\"should_see_in_feed\":$should_see_in_feed,\"user_id\":$user_id})";
            case 1073:
                return "xfb_genai_persona_save_changes_with_audience_settings_v2(data:$input)";
            case 1074:
                return "xfb_get_ig_wearables_contacts";
            case 1075:
                return "xfb_get_memu_user(user_id:$user_id)";
            case 1076:
                return "xfb_igd_broadcast_channel_thread(id:$id)";
            case 1077:
                return "xfb_igd_channels_update_creator_education_goal(goal:$goal,thread_id:$id)";
            case 1078:
                return "xfb_live_location_sessions_for_thread_query";
            case 1079:
                return "xfb_messaging_search_genai_snippet(entry_point:$entry_point,user_prompt:$user_prompt)";
            case 1080:
                return "xfb_meta_ai_intent_card_user_status(intent_card_type:$intent_card_type)";
            case 1081:
                return "xfb_metagen_ai_write_with_ai_suggestion(context:$context,initial_content:$initial_content,output_quantity:$output_quantity,prompt:$prompt,prompt_request_id:$prompt_request_id,surface_session_id:$surface_session_id,target_surface:$target_surface)";
            case 1082:
                return "xfb_prompt_sheet_starter_prompts(app:$app)";
            case 1083:
                return "xfb_should_show_ig_detected_outcomes_nux(consumer_ig_fbidv2:$consumer_fbid)";
            case 1084:
                return "xfb_social_avatar_stickers_mark_disclaimer_as_seen";
            case 1085:
                return "xfb_undo_delete_recent_ad_activity(data:$input)";
            case 1086:
                return "xfb_write_with_ai_suggested_prompts(context:$context,target_surface:$target_surface)";
            case 1087:
                return "xig_cancel_setting_change_request(data:{\"setting_type\":$setting_type,\"supervised_user_id\":$supervised_user_id})";
            case 1088:
                return "xig_create_creator_agent_thread(request:{\"user_igid\":$user_igid})";
            case 1089:
                return "xig_create_creator_ai_link_keyword(data:$data)";
            case 1090:
                return "xig_creator_ai_agent_create(request:$request)";
            case 1091:
                return "xig_creator_ai_free_form_fact_delete_mutation(data:$request)";
            case 1092:
                return "xig_creator_ai_terms_status_update(data:$data)";
            case 1093:
                return "xig_creator_ai_validate_keyword(data:$data)";
            case 1094:
                return "xig_creator_ai_validate_link(data:$data)";
            case 1095:
                return "xig_delete_creator_ai_link_keyword_schema(data:$data)";
            case 1096:
                return "xig_encrypted_shared_account_access_info(id:$id)";
            case 1097:
                return "xig_get_setting_change_requests(first:1,request_status:$request_status,setting_type:$setting_type,supervised_user_id:$supervised_user_id)";
            case 1098:
                return "xig_ig_creator_ai_content_categories_query(request:$request)";
            case 1099:
                return "xig_ig_creator_ai_fact_query(after:$cursor,first:20,request:$request)";
            case 1100:
                return "xig_ig_creator_ai_free_form_fact_save_mutation(request:$request)";
            case 1101:
                return "xig_ig_creator_ai_set_content_category_value_mutation(mutation:{\"creator_id\":$creator_fbid,\"key\":$key,\"value\":$value})";
            case 1102:
                return "xig_ig_creator_ai_topic_avoidance_example_query(request:$request)";
            case 1103:
                return "xig_ig_creator_ai_topic_avoidance_topics_query(request:$request)";
            case 1104:
                return "xig_igd_business_ml_sayt_list_query";
            case 1105:
                return "xig_is_user_subscribed_to_creator_igid(creator_igid:$creator_id,user_igid:$user_id)";
            case 1106:
                return "xig_teen_bio_education_qp";
            case 1107:
                return "xig_update_bio_creator_agent_persona(data:$data)";
            default:
                return "xig_update_creator_ai_link_keyword(data:$data)";
        }
    }
}
