package X;

/* renamed from: X.RxB, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62001RxB {
    public static String A00(int i) {
        switch (i) {
            case 1028:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_REELS_DRAFT_ERROR";
            case 1050:
                return "MANAGED_MOBILE_ERRORS_REMOVE_PANAVISION_SQUARE_CROP";
            case 1142:
                return "MANAGED_MOBILE_ERRORS_SURFACE_UNTRUSTED_CALLER_NAVIGATION";
            case 1156:
                return "MANAGED_MOBILE_ERRORS_FEEDBACK_REACTIONS_SETTINGS_QUERY_PRE_ERROR";
            case 1238:
                return "MANAGED_MOBILE_ERRORS_MULTISHARE_ITEM_IMP";
            case 1285:
                return "MANAGED_MOBILE_ERRORS_MOBILE_ZONE_EVALUATOR_ERROR";
            case 1368:
                return "MANAGED_MOBILE_ERRORS_MOBILE_ZONE_RECLASSIFICATION";
            case 1382:
                return "MANAGED_MOBILE_ERRORS_SERVER_CONFIG_DETECTION_SIMULATED_ERROR";
            case 1423:
                return "MANAGED_MOBILE_ERRORS_ANDROID_VIDEO_PLAYBACK_BAYMAX_UNEXPECTED_EVENT";
            case 1488:
                return "MANAGED_MOBILE_ERRORS_LITHO_VIDEO_ATTACHMENT_UNEXPECTED_EVENT";
            case 1510:
                return "MANAGED_MOBILE_ERRORS_FB_USER_SESSION_WITHOUT_BUNDLE_ID_MISMATCH";
            case 1569:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_HOME_MOBILE_ERROR_EVENT";
            case 1615:
                return "MANAGED_MOBILE_ERRORS_STRICT_MODE_VIOLATIONS_V1";
            case 1653:
                return "MANAGED_MOBILE_ERRORS_MESSENGER_UNIVERSAL_SEARCH_UNEXPECTED_EVENT";
            case 1674:
                return "MANAGED_MOBILE_ERRORS_FX_PRODUCT_FOUNDATION_RL_UNEXPECTED_EVENT";
            case 1729:
                return "MANAGED_MOBILE_ERRORS_IG_DIRECT_XMA_UNEXPECTED_EVENT";
            case 1828:
                return "MANAGED_MOBILE_ERRORS_VIDEO_TRANSCODE_EXCEPTION";
            case 1831:
                return "MANAGED_MOBILE_ERRORS_FEED_TIMELINE_AUTHOR_ACCOUNT_TYPE";
            case 1833:
                return "MANAGED_MOBILE_ERRORS_M4A_THREAD_VIEW_STALE";
            case 1859:
                return "MANAGED_MOBILE_ERRORS_FB4A_GBF_ERRORS";
            case 1867:
                return "MANAGED_MOBILE_ERRORS_IG_FEED_LITHO_UNEXPECTED_ERROR";
            case 1922:
                return "MANAGED_MOBILE_ERRORS_THREAD_SNAPSHOT_INVALID_THREAD_ID";
            case 1929:
                return "MANAGED_MOBILE_ERRORS_DEEP_DELETION_REQUEST_CREATION_EXCEPTION";
            case 1960:
                return "MANAGED_MOBILE_ERRORS_MEDIA_SESSIONS_STATE";
            case 1964:
                return "MANAGED_MOBILE_ERRORS_MEDIA_TYPE_HASH_MAP_NOT_CONTAIN_SERVER_KEY_EVENT";
            case 1983:
                return "MANAGED_MOBILE_ERRORS_INVALID_PERMALINK";
            case 2120:
                return "MANAGED_MOBILE_ERRORS_DECORBITMAPHELPER_CREATE_DOODLE_BITMAP";
            case 2130:
                return "MANAGED_MOBILE_ERRORS_CROP_FRAGMENT";
            case 2248:
                return "MANAGED_MOBILE_ERRORS_FB_SHORTS_CONNECTED_LIVE_PILL";
            case 2324:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_MEDIA_UPLOAD_ERROR";
            case 2330:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_SPONSORED_ITEM_DELIVERED_OUTSIDE_ACP";
            case 2375:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_DIRECT_MOBILE_ERROR_EVENT";
            case 2403:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_STORIES_CANDID_ERROR";
            case 2488:
                return "MANAGED_MOBILE_ERRORS_FB_VIDEOX_UNEXPECTED_EVENT";
            case 2518:
                return "MANAGED_MOBILE_ERRORS_PUBLISHER_NULL_MEDIA_ITEM_PATH";
            case 2629:
                return "MANAGED_MOBILE_ERRORS_REGION_TRACKING_FILTER_UTIL";
            case 2770:
                return "MANAGED_MOBILE_ERRORS_MESSENGER_UNEXPECTED_MEDIA_TYPE";
            case 2999:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_CAMERA_INIT_ERROR";
            case 3000:
                return "MANAGED_MOBILE_ERRORS_CLIPS_FAILED_NETWORK_REQUEST_DEBUG";
            case 3009:
                return "MANAGED_MOBILE_ERRORS_SHARED_PREFERENCES_STORAGE_SYNC_FAILED";
            case 3060:
                return "MANAGED_MOBILE_ERRORS_IG_BUG_REPORTER_SOFT_ERROR";
            case 3098:
                return "MANAGED_MOBILE_ERRORS_IG_FLASH_LOCAL_DATA_SOURCE_UNEXPECTED_EVENT";
            case 3232:
                return "MANAGED_MOBILE_ERRORS_PUBLISHER_DB_SERIALIZATION_FAILURE";
            case 3247:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_CREATION_RENDER_ERROR";
            case 3255:
                return "MANAGED_MOBILE_ERRORS_IG_COMMENT_BOTTOM_SHEET_ERROR_EVENT";
            case 3292:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_TWO_PANE_REELS_NULL_CHILD_FRAGMENT_MANAGER";
            case 3305:
                return "MANAGED_MOBILE_ERRORS_XAPP_PRIVACY_COMM_EVENT";
            case 3367:
                return "MANAGED_MOBILE_ERRORS_IG_CONTENT_NOTES_UNEXPECTED_ERROR";
            case 3387:
                return "MANAGED_MOBILE_ERRORS_PHOTOIMPORTCALLABLE_IMAGE_METADATA";
            case 3413:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_RTC_MISSING_CRYPTO_CONTEXT_ERROR";
            case 3560:
                return "MANAGED_MOBILE_ERRORS_EXECUTOR_ILLEGAL_VCM_GET_VIEWER_CONTEXT";
            case 3580:
                return "MANAGED_MOBILE_ERRORS_FX_PRODUCT_FOUNDATION_FB_UNEXPECTED_EVENT";
            case 3634:
                return "MANAGED_MOBILE_ERRORS_IG_FAST_AND_SAFE_SOFT_ERROR";
            case 3636:
                return "MANAGED_MOBILE_ERRORS_MANUAL_APP_TERMINATION";
            case 3653:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_STORIES_UNEXPECTED_EVENT";
            case 3665:
                return "MANAGED_MOBILE_ERRORS_IG_ONE_CAMERA_SERVICE_FACTORY_MEDIA_GRAPH_ERROR";
            case 3743:
                return "MANAGED_MOBILE_ERRORS_DUPLICATE_CLIPS_IN_CLIPS_TAB_PREFETCH";
            case 3788:
                return "MANAGED_MOBILE_ERRORS_LOAD_JPEG_IMAGE_EXCEPTION";
            case 3809:
                return "MANAGED_MOBILE_ERRORS_IG_AD_SECURE_URL_OPENER";
            case 3854:
                return "MANAGED_MOBILE_ERRORS_LITHO_COMMENTS_UNEXPECTED_EVENT";
            case 3937:
                return "MANAGED_MOBILE_ERRORS_GROUP_COMPOSER_HINT";
            case 3938:
                return "MANAGED_MOBILE_ERRORS_FB4A_UP_UPSTREAM_PLAYER_SOURCE_NULL_EVENT";
            case 3981:
                return "MANAGED_MOBILE_ERRORS_SELECTABLE_PRIVACY_PILL_VIEW_CONTROLLER_UNEXPECTED_EVENT";
            case 4023:
                return "MANAGED_MOBILE_ERRORS_NULL_CAUGHT_CRASH_UPLOADER_STACK";
            case 4025:
                return "MANAGED_MOBILE_ERRORS_FB_USER_SESSION_USER_ID_INCORRECT";
            case 4031:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_MANUAL_APP_RESTART";
            case 4107:
                return "MANAGED_MOBILE_ERRORS_IG_REELS_AUDIO_EXTRACTOR_SOFT_ERROR";
            case 4116:
                return "MANAGED_MOBILE_ERRORS_REELS_ADS_BLOKS_TOOLTIP_GESTURE_ERROR";
            case 4154:
                return "MANAGED_MOBILE_ERRORS_PUBLISHER_ZERO_TARGET_ID_ERROR";
            case 4367:
                return "MANAGED_MOBILE_ERRORS_IG_USER_DETAILS_GRID_TAP_OUT_OF_BOUNDS_ERROR_EVENT";
            case 4371:
                return "MANAGED_MOBILE_ERRORS_STICKER_MODEL_LEGACY_TO_UNIFIED_FAILED";
            case 4379:
                return "MANAGED_MOBILE_ERRORS_LITHO_PROFILE_UNEXPECTED_EVENT";
            case 4454:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_RECORDING_ERROR";
            case 4481:
                return "MANAGED_MOBILE_ERRORS_STICKER_MODEL_UNIFIED_TO_LEGACY_FAILED";
            case 4505:
                return "MANAGED_MOBILE_ERRORS_FB_USER_SESSION_EMPTY_SESSION_VC";
            case 4513:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_WEARABLES_MOBILE_ERROR_EVENT";
            case 4517:
                return "MANAGED_MOBILE_ERRORS_GAMES_UNEXPECTED_EVENT";
            case 4636:
                return "MANAGED_MOBILE_ERRORS_IG_SHARESHEET_NULL_CONTENT_TO_SHARE";
            case 4760:
                return "MANAGED_MOBILE_ERRORS_GALLERY_THUMBNAIL_UTIL_LOAD_THUMBNAILS";
            case 4782:
                return "MANAGED_MOBILE_ERRORS_IG_REELS_BLANK_SCREEN_SHOWREEL_COMPOSITION_NOT_ATTACHED";
            case 4789:
                return "MANAGED_MOBILE_ERRORS_UPLOAD_RECORD_INTERNAL_DESERIALIZATION_FAILURE";
            case 4889:
                return "MANAGED_MOBILE_ERRORS_PUBLIC_CHANNELS_UNEXPECTED_ERRORS";
            case 4898:
                return "MANAGED_MOBILE_ERRORS_EXCEPTION_REPLAYING_BROADCAST_POST_APP_INIT";
            case 4909:
                return "MANAGED_MOBILE_ERRORS_CONTEXTUAL_MUSIC_FAILURE_SCENE_UNDERSTANDING";
            case 4993:
                return "MANAGED_MOBILE_ERRORS_INJECTED_TOO_EARLY";
            case 5032:
                return "MANAGED_MOBILE_ERRORS_NOTIFICATIONS_ERRORS";
            case 5039:
                return "MANAGED_MOBILE_ERRORS_PRIVACY_OPTIONS_RESULT_FACTORY_UNEXPECTED_EVENT";
            case 5057:
                return "MANAGED_MOBILE_ERRORS_DUAL_SEND_TEST_UNEXPECTED_EVENT";
            case 5119:
                return "MANAGED_MOBILE_ERRORS_CREATION_OVERRIDE_GRADIENT_COLORS";
            case 5128:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_MEDIA_INFINITE_CAROUSEL";
            case 5159:
                return "MANAGED_MOBILE_ERRORS_STATIC_STICKER_TEXTURE_PROVIDER";
            case 5315:
                return "MANAGED_MOBILE_ERRORS_MOBILE_ZONE_BLOCKED_FLOW";
            case 5345:
                return "MANAGED_MOBILE_ERRORS_FX_PRODUCT_FOUNDATION_IG_UNEXPECTED_EVENT";
            case 5374:
                return "MANAGED_MOBILE_ERRORS_QUANTUM_SIGNAL_UNEXPECTED_EVENT";
            case 5409:
                return "MANAGED_MOBILE_ERRORS_TWO_SNAPSHOT_AT_SAME_TIME";
            case 5422:
                return "MANAGED_MOBILE_ERRORS_LITHO_REELS_UNEXPECTED_EVENT";
            case 5493:
                return "MANAGED_MOBILE_ERRORS_UNSUPPORTED_DESTINATION_GRADIENT_COLOR_EXPERIMENT";
            case 5507:
                return "MANAGED_MOBILE_ERRORS_LITHO_GROOT_VIDEO_UNEXPECTED_EVENT";
            case 5519:
                return "MANAGED_MOBILE_ERRORS_IG_CLIENT_NONCE_MANAGER";
            case 5526:
                return "MANAGED_MOBILE_ERRORS_CROP_IMAGE_CONTROLLER";
            case 5564:
                return "MANAGED_MOBILE_ERRORS_FB4A_UCR_UNEXPECTED_EVENTS";
            case 5568:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_CAMERA_MOBILE_ERROR_EVENT";
            case 5611:
                return "MANAGED_MOBILE_ERRORS_IG_BROWSER_LAUNCHER_DEEPLINK_URL";
            case 5638:
                return "MANAGED_MOBILE_ERRORS_M4A_CHATD_USER_DATA_PARSE_ERROR";
            case 5691:
                return "MANAGED_MOBILE_ERRORS_MQD_STALL";
            case 5713:
                return "MANAGED_MOBILE_ERRORS_UPLOAD_RECORD_INTERNAL_DESERIALIZATION_NULL";
            case 5765:
                return "MANAGED_MOBILE_ERRORS_DEBUG_CLIPS_VIEWER_INDEX_OOB_CRASH";
            case 5790:
                return "MANAGED_MOBILE_ERRORS_IG_NDX_UNEXPECTED_EVENT";
            case 5987:
                return "MANAGED_MOBILE_ERRORS_MOBILE_ARCHITECTURE_MATCH_REPORTING";
            case 6019:
                return "MANAGED_MOBILE_ERRORS_FB_USER_SESSION_NOT_SET_IN_SURFACE_SPEC";
            case 6104:
                return "MANAGED_MOBILE_ERRORS_MESSAGING_MENTIONS";
            case 6133:
                return "MANAGED_MOBILE_ERRORS_OC_FILTER_MIGRATION_DEBUG";
            case 6174:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_CREATION_LOGGING_ERROR";
            case 6179:
                return "MANAGED_MOBILE_ERRORS_IG_ADS_SCROLL_PERF_REGRESSION_TEST";
            case 6231:
                return "MANAGED_MOBILE_ERRORS_EVENT_MIXVM_ERROR";
            case 6236:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_STORY_DRAFT_ERROR";
            case 6240:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_AD_SYNC_FLOW";
            case 6283:
                return "MANAGED_MOBILE_ERRORS_MESSENGER_PAGE_TO_ADMIN_SWITCH_NULL_ADMIN_CONTEXT_EVENT";
            case 6355:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_IGDS_BOTTOM_SHEET_MOBILE_ERROR_EVENT";
            case 6443:
                return "MANAGED_MOBILE_ERRORS_ANALYTICS_LOGGER_INJECTED_TOO_EARLY";
            case 6524:
                return "MANAGED_MOBILE_ERRORS_GALLERY_THUMBNAIL_LOADER_ERROR";
            case 6526:
                return "MANAGED_MOBILE_ERRORS_REVERB_USE_SUPPLIMENT_AS_TOPLEVEL";
            case 6570:
                return "MANAGED_MOBILE_ERRORS_FBM_ENCRYPTED_BACKUP";
            case 6636:
                return "MANAGED_MOBILE_ERRORS_CONNECTIVITY_UNEXPECTED_EVENT";
            case 6637:
                return "MANAGED_MOBILE_ERRORS_FBM_ACTIVE_NOW";
            case 6719:
                return "MANAGED_MOBILE_ERRORS_SHARED_PREFERENCES_KEY_TOO_LARGE";
            case 6800:
                return "MANAGED_MOBILE_ERRORS_IGWB_ANTI_BULLYING_ERRORS";
            case 6841:
                return "MANAGED_MOBILE_ERRORS_HOST_PROFILE_ID_OVERWRITE";
            case 6924:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_GALLERY_ERROR";
            case 6966:
                return "MANAGED_MOBILE_ERRORS_IG_REELS_ANDROID_CTA_CRASH";
            case 6992:
                return "MANAGED_MOBILE_ERRORS_LAST_ITEM_TIMESTAMP_REGRESSION";
            case 7024:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_FEED_TBI_UNEXPECTED_EVENT";
            case 7045:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_COMMENTS_UNEXPECTED_EVENT";
            case 7055:
                return "MANAGED_MOBILE_ERRORS_PERF_BENCHMARK_FAILURE";
            case 7199:
                return "MANAGED_MOBILE_ERRORS_IG_CONSENT_ALASKA_NATIVE_SOFT_ERROR";
            case 7232:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_ATTEST_PLAYINTEGRITY_UNEXPECTED_EVENT";
            case 7235:
                return "MANAGED_MOBILE_ERRORS_ANDROID_SHARESHEET_LATENCY_NEGATIVE_TEST_ERROR";
            case 7293:
                return "MANAGED_MOBILE_ERRORS_SHARED_PREFERENCES_ORPHANED_EXTERNAL_KEY";
            case 7373:
                return "MANAGED_MOBILE_ERRORS_IG_ERROR_PARSING_MEDIA_JSON";
            case 7376:
                return "MANAGED_MOBILE_ERRORS_VIEWER_CONTEXT_CACHE_NULL_HITS";
            case 7408:
                return "MANAGED_MOBILE_ERRORS_STICKER_TYPE_LEGACY_TO_UNIFIED_FAILED";
            case 7558:
                return "MANAGED_MOBILE_ERRORS_LEGACY_THREADS_DB2_RECREATED_EVENT";
            case 7562:
                return "MANAGED_MOBILE_ERRORS_STORIES_AR_FRAME_LITE_MEDIA_GRAPH_ERROR";
            case 7584:
                return "MANAGED_MOBILE_ERRORS_CLIPS_AR_FRAME_LITE_MEDIA_GRAPH_ERROR";
            case 7644:
                return "MANAGED_MOBILE_ERRORS_PROFILE_ANDROID_UNEXPECTED_GRAPHQL_INPUT_EVENT";
            case 7724:
                return "MANAGED_MOBILE_ERRORS_FBLITE_VIDEO_PLAYBACK_UNEXPECTED_EVENT";
            case 7799:
                return "MANAGED_MOBILE_ERRORS_IG_AMG_DB_ERROR";
            case 7822:
                return "MANAGED_MOBILE_ERRORS_FBM_INBOX_PEOPLE_PICKER_SEARCH";
            case 7857:
                return "MANAGED_MOBILE_ERRORS_SHARED_PREFERENCES_EXTERNAL_WRITE_FAILED";
            case 7862:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_REEL_STICKER_VIEW_INVALID";
            case 7932:
                return "MANAGED_MOBILE_ERRORS_IG_1PD_INSTALL_ERROR_EVENT";
            case 7950:
                return "MANAGED_MOBILE_ERRORS_FB_MEDIA_UPLOADER_ERROR";
            case 7968:
                return "MANAGED_MOBILE_ERRORS_CLIPS_CAMERA_FRAGMENT_NAVIGATION_ERROR";
            case 7978:
                return "MANAGED_MOBILE_ERRORS_CLIPS_VIDEO_IMPORT_UTIL";
            case 7992:
                return "MANAGED_MOBILE_ERRORS_TRACKING_NODES_MIGRATION_UPDATED_FORMAT";
            case 8017:
                return "MANAGED_MOBILE_ERRORS_LITHO_DEBUG_EVENTS";
            case 8116:
                return "MANAGED_MOBILE_ERRORS_ANDROID_SHARING_UNEXPECTED_EVENT";
            case 8122:
                return "MANAGED_MOBILE_ERRORS_MOBILE_ZONE_PRIVACY_VIOLATION_EVENT";
            case 8178:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_DEEPLINK_UNEXPECTED_EVENT";
            case 8190:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_REPRO_ATTEMPT_AFTER_RESTART";
            case 8203:
                return "MANAGED_MOBILE_ERRORS_FBM_BUG_REPORTS";
            case 8273:
                return "MANAGED_MOBILE_ERRORS_INCORRECT_LEGACY_TRANSFORM_MATRIX";
            case 8379:
                return "MANAGED_MOBILE_ERRORS_PUBLISHER_OPTIMISTIC_CANCEL_FAILED";
            case 8432:
                return "MANAGED_MOBILE_ERRORS_UL_FALLBACK_TRANSIENT_FAILURE";
            case 8446:
                return "MANAGED_MOBILE_ERRORS_API_UNEXPECTED_EVENT_TEST";
            case 8480:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_IAA_STORIES_NON_GAP_ZERO_RULES";
            case 8488:
                return "MANAGED_MOBILE_ERRORS_LITHO_WATCH_UNEXPECTED_EVENT";
            case 8504:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_INTENT_AWARE_ADS_STORIES_UNEXPECTED_EVENT";
            case 8617:
                return "MANAGED_MOBILE_ERRORS_MOBILE_CONFIG_INJECTED_TOO_EARLY";
            case 8646:
                return "MANAGED_MOBILE_ERRORS_IG_BOOST_UNEXPECTED_EVENT";
            case 8686:
                return "MANAGED_MOBILE_ERRORS_IGD_ANDROID_CALL_MANAGER_INIT_FAILURE";
            case 8728:
                return "MANAGED_MOBILE_ERRORS_MESSENGER_QUICK_PROMOTION_UNEXPECTED_EVENT";
            case 8736:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_CREATION_VIRTUAL_VIDEO_ERROR";
            case 8752:
                return "MANAGED_MOBILE_ERRORS_THREADS_ANDROID_FEED_UNEXPECTED_EVENT";
            case 8792:
                return "MANAGED_MOBILE_ERRORS_CONTENT_RESOLVER_UTIL_INBITMAP";
            case 8803:
                return "MANAGED_MOBILE_ERRORS_GIF_TEXTURE_PROVIDER_ADD_IMAGE_REGION";
            case 8832:
                return "MANAGED_MOBILE_ERRORS_IG_LITHO_REELS_CLIP_ITEM_ERROR_EVENT";
            case 8878:
                return "MANAGED_MOBILE_ERRORS_LOCALE_UNEXPECTED_EVENT";
            case 8900:
                return "MANAGED_MOBILE_ERRORS_IG_UHL_LIVE_CHAT";
            case 8941:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_CREATION_MIGRATION_ERROR";
            case 9035:
                return "MANAGED_MOBILE_ERRORS_FB_STORY_ADS_CAPTION_CALCULATION_ERROR";
            case 9059:
                return "MANAGED_MOBILE_ERRORS_EXECUTOR_ILLEGAL_VIEWER_CONTEXT_ACCESS";
            case 9163:
                return "MANAGED_MOBILE_ERRORS_PLAY_INTEGRITY_UNEXPECTED_EVENT";
            case 9167:
                return "MANAGED_MOBILE_ERRORS_FB_REELS_POST_PUBLISH_EDITING";
            case 9170:
                return "MANAGED_MOBILE_ERRORS_PC_LITHO_DEBUG_MISMATCH";
            case 9273:
                return "MANAGED_MOBILE_ERRORS_ZERO_RATING_UNEXPECTED_EVENT";
            case 9281:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_EFFECT_INFO_OPTION_ADAPTER_ERROR";
            case 9393:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_STORIES_MOBILE_ERROR_EVENT";
            case 9437:
                return "MANAGED_MOBILE_ERRORS_TAM_ATTACHMENT_ERROR";
            case 9451:
                return "MANAGED_MOBILE_ERRORS_MOBILE_ZONE_RUN_EVENT";
            case 9548:
                return "MANAGED_MOBILE_ERRORS_ANDROID_PLAYBACK_ERRORS";
            case 9557:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_REPEATED_NAVIGATION";
            case 9561:
                return "MANAGED_MOBILE_ERRORS_QCC_MODULARIZATION_ERROR";
            case 9571:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_BACKGROUND_DETECTOR_LISTENER_EXCEPTION";
            case 9592:
                return "MANAGED_MOBILE_ERRORS_XAPP_PRIVACY_DEEPLINK_EVENT";
            case 9610:
                return "MANAGED_MOBILE_ERRORS_NT_DEEPLINK_MESSAGING_ENTRYPOINT";
            case 9617:
                return "MANAGED_MOBILE_ERRORS_FB_MEDIA_INVALID_OVERLAY_PARAMS";
            case 9640:
                return "MANAGED_MOBILE_ERRORS_MAIN_TAB_CONTROLLER_IS_NULL";
            case 9666:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_NAS_UNEXPECTED_EVENT";
            case 9670:
                return "MANAGED_MOBILE_ERRORS_HOST_PROFILE_ID_MISMATCH";
            case 9754:
                return "MANAGED_MOBILE_ERRORS_MEDIA_SAVER";
            case 9826:
                return "MANAGED_MOBILE_ERRORS_TOP_STAR_SENDERS_UNEXPECTED_EVENT";
            case 9893:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_CLIPS_DRAFT_ERROR";
            case 9943:
                return "MANAGED_MOBILE_ERRORS_PUBLISHER_OPTIMISTIC_UPLOAD_FAILED";
            case 9950:
                return "MANAGED_MOBILE_ERRORS_MIB_UNKNOWN_ENTRY_POINT_LOGGING";
            case 9967:
                return "MANAGED_MOBILE_ERRORS_NEW_MESSAGE_DURING_SNAPSHOT";
            case 10023:
                return "MANAGED_MOBILE_ERRORS_CUTOVER_THREAD_INVALID_SEND";
            case 10098:
                return "MANAGED_MOBILE_ERRORS_PROFILE_ANDROID_UNEXPECTED_EVENT";
            case 10109:
                return "MANAGED_MOBILE_ERRORS_FILTER_KIT_VIDEO_RENDER_OVERLAY_CONTROLLER";
            case 10139:
                return "MANAGED_MOBILE_ERRORS_FB_USER_SESSION_USER_ID_MISMATCH";
            case 10181:
                return "MANAGED_MOBILE_ERRORS_THREADS_ANDROID_ERROR";
            case 10188:
                return "MANAGED_MOBILE_ERRORS_LITHO_PHOTO_ATTACHMENT_UNEXPECTED_EVENT";
            case 10198:
                return "MANAGED_MOBILE_ERRORS_MESSENGER_PAGE_TO_ADMIN_SWITCH_NULL_ADMIN_CONTEXT_2_EVENT";
            case 10306:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_FEED_RENDERING_UNEXPECTED_EVENT";
            case 10319:
                return "MANAGED_MOBILE_ERRORS_OXYGEN_INSTALL_SDK";
            case 10341:
                return "MANAGED_MOBILE_ERRORS_LSS_MIB_UNEXPECTED_EVENT";
            case 10361:
                return "MANAGED_MOBILE_ERRORS_IG4A_ON_DEVICE_APP_HISTORY_DEDUP_EXCEPTION";
            case 10369:
                return "MANAGED_MOBILE_ERRORS_IG_REELS_ANDROID_CAPTION_VIEW_DEBUG";
            case 10377:
                return "MANAGED_MOBILE_ERRORS_SHARE_SHEET_ERRORS";
            case 10388:
                return "MANAGED_MOBILE_ERRORS_BIZAPP_NO_PAGE_VC_IN_STORY_PERMALINK_FRAGMENT";
            case 10392:
                return "MANAGED_MOBILE_ERRORS_MESSENGER_THREAD_VIEW_THREAD_KEY_NULL";
            case 10408:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_REEL_TRAY_MANAGER";
            case 10417:
                return "MANAGED_MOBILE_ERRORS_EXPANDABLE_SELECTABLE_ADAPTOR_CAST_ERROR";
            case 10521:
                return "MANAGED_MOBILE_ERRORS_IGD_VISUAL_MEDIA_GALLERY_INVALID_LOG";
            case 10523:
                return "MANAGED_MOBILE_ERRORS_IG_STORY_PREFETCH_ODML_UNEXPECTED_EVENT";
            case 10549:
                return "MANAGED_MOBILE_ERRORS_FBM_INBOX_THREADVIEW";
            case 10646:
                return "MANAGED_MOBILE_ERRORS_SESSIONLESS_MOBILE_CONFIG_INJECTED_TOO_EARLY";
            case 10662:
                return "MANAGED_MOBILE_ERRORS_LITHO_STRICT_MODE_VIOLATION";
            case 10682:
                return "MANAGED_MOBILE_ERRORS_PUBLISHER_MEDIA_ITEM_NOT_EXIST";
            case 10933:
                return "MANAGED_MOBILE_ERRORS_STICKER_TEXTURE_PROVIDER_ADD_IMAGE_REGIONS";
            case 10955:
                return "MANAGED_MOBILE_ERRORS_MEMORY_UNEXPECTED_EVENT";
            case 10969:
                return "MANAGED_MOBILE_ERRORS_OC_FEED_CAROUSEL_SAVE";
            case 10976:
                return "MANAGED_MOBILE_ERRORS_IG_DUAL_SCHEDULER_SOFT_ERROR";
            case 11001:
                return "MANAGED_MOBILE_ERRORS_IG_CLIPS_VIEWER_RENDERER_CACHE_ERROR";
            case 11013:
                return "MANAGED_MOBILE_ERRORS_IG_ZERO_UNEXPECTED_EVENT";
            case 11025:
                return "MANAGED_MOBILE_ERRORS_FB4A_UNEXPECTED_ROOT_FEEDBACK";
            case 11098:
                return "MANAGED_MOBILE_ERRORS_MUTATION_SEND_MODE_MIGRATION";
            case 11148:
                return "MANAGED_MOBILE_ERRORS_IG_META_AI_UNEXPECTED_EVENT";
            case 11215:
                return "MANAGED_MOBILE_ERRORS_IMAGE_TEXTURE_PROVIDER_ADD_IMAGE_REGIONS";
            case 11220:
                return "MANAGED_MOBILE_ERRORS_ANDROID_PATTERN_FNL";
            case 11325:
                return "MANAGED_MOBILE_ERRORS_MAIN_THREAD_LOAD";
            case 11326:
                return "MANAGED_MOBILE_ERRORS_LITHO_SEARCH_UNEXPECTED_EVENT";
            case 11347:
                return "MANAGED_MOBILE_ERRORS_UQPP_INJECTION_PROOF";
            case 11470:
                return "MANAGED_MOBILE_ERRORS_COLOR_PALETTE_INVALID_BOUNDS";
            case 11504:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_RTC_CRYPTO_CONTEXT_INIT_NO_EIMU_ERROR";
            case 11574:
                return "MANAGED_MOBILE_ERRORS_CANT_EXTRACT_GRADIENT_COLORS_IN_GPU";
            case 11614:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_CAMERA_VIEW_CONTROLLER_ERROR";
            case 11635:
                return "MANAGED_MOBILE_ERRORS_FB_USER_SESSION_FROM_BUNDLE_ID_MISMATCH";
            case 11658:
                return "MANAGED_MOBILE_ERRORS_LEGACY_1CS_ERROR_REQUEST_DEBOUNCED";
            case 11692:
                return "MANAGED_MOBILE_ERRORS_UAF_PROTECTIONS_UNEXPECTED_EVENT";
            case 11722:
                return "MANAGED_MOBILE_ERRORS_RTC_LITECAMERA_INTERGREATION_ERROR";
            case 11767:
                return "MANAGED_MOBILE_ERRORS_HANDLE_VIDEO_FROM_GALLERY";
            case 11787:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_ACTIVITY_FEED_UNEXPECTED_EVENT";
            case 11873:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_EXPLORE_MOBILE_ERROR_EVENT";
            case 11894:
                return "MANAGED_MOBILE_ERRORS_ANDROID_VIDEO_ERROR";
            case 11920:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_MAC_STORIES_MULTIPLE_ITEMS_IN_REEL";
            case 11922:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_CONTENT_SCHEDULING_MISSING_METADATA_ERROR";
            case 11941:
                return "MANAGED_MOBILE_ERRORS_ACTIONS_PROTOCOL_SELECTOR_ENTRY_POINT";
            case 12052:
                return "MANAGED_MOBILE_ERRORS_PUBLISHER_DB_DESERIALIZATION_FAILURE";
            case 12076:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_CREATION_INVALID_ENTRYPOINT";
            case 12126:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_UI_TOAST_ERROR_EVENT";
            case 12147:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_CREATION_MEDIA_SAVE_ERROR";
            case 12237:
                return "MANAGED_MOBILE_ERRORS_FBMAINTABACTIVITY_TARGET_TAB_ID_TRUSTED_CALLER_VIOLATION";
            case 12278:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_CAMERA_TOOL_ERROR";
            case 12281:
                return "MANAGED_MOBILE_ERRORS_FIXIE_ERROR";
            case 12319:
                return "MANAGED_MOBILE_ERRORS_PUSH_SDK_ERROR";
            case 12366:
                return "MANAGED_MOBILE_ERRORS_UNEXPECTED_NAVBAR_HEIGHT_IS_ZERO";
            case 12396:
                return "MANAGED_MOBILE_ERRORS_IG4A_QP_SOFT_ERROR";
            case 12452:
                return "MANAGED_MOBILE_ERRORS_VIEWER_CONTEXT_MANAGER_TRUSTED_CALLER_ERROR";
            case 12459:
                return "MANAGED_MOBILE_ERRORS_REELS_CAROUSEL_RENDERING_CONFIG_ERROR";
            case 12515:
                return "MANAGED_MOBILE_ERRORS_CLIPS_GRID_NULL_IMAGE_PREVIEW";
            case 12578:
                return "MANAGED_MOBILE_ERRORS_THUMBNAIL_LOAD_ERROR";
            case 12583:
                return "MANAGED_MOBILE_ERRORS_UI_GRAPH_UNEXPECTED_EVENT";
            case 12597:
                return "MANAGED_MOBILE_ERRORS_LITHO_EVENTS_TAB_UNEXPECTED_EVENTS";
            case 12736:
                return "MANAGED_MOBILE_ERRORS_VIDEO_SCREEN_ON_FLAG_STATUS_ON_ENTRY";
            case 12854:
                return "MANAGED_MOBILE_ERRORS_AR_GIFTING_UNEXPECTED_EVENT";
            case 12893:
                return "MANAGED_MOBILE_ERRORS_IG_REELS_BLANK_SCREEN_SHOWREEL_NATIVE_NOT_ATTACHED";
            case 12946:
                return "MANAGED_MOBILE_ERRORS_IG_LIVE_AVATAR_REACTION_EXPIRED";
            case 13008:
                return "MANAGED_MOBILE_ERRORS_DELETE_THREAD_WITH_MESSAGES";
            case 13038:
                return "MANAGED_MOBILE_ERRORS_CLIPS_END_CARD_UNEXPECTED_EVENT";
            case 13039:
                return "MANAGED_MOBILE_ERRORS_ANDROID_VIDEO_PLAYBACK_UNEXPECTED_EVENT";
            case 13064:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_CREATION_AUDIO_ERROR";
            case 13123:
                return "MANAGED_MOBILE_ERRORS_TRANSFORM_MATRIX_ENCAPSULATION_TRACKING";
            case 13129:
                return "MANAGED_MOBILE_ERRORS_VIDEO_IMPORT_CALLABLE";
            case 13144:
                return "MANAGED_MOBILE_ERRORS_HOST_PROFILE_ID_FORMAT_ERROR";
            case 13167:
                return "MANAGED_MOBILE_ERRORS_IG_AD_SECURE_URL_OPENER_V2";
            case 13229:
                return "MANAGED_MOBILE_ERRORS_SELECT_PROXY_ERROR";
            case 13240:
                return "MANAGED_MOBILE_ERRORS_JUST_WATCHED_ERROR";
            case 13248:
                return "MANAGED_MOBILE_ERRORS_IG_REELS_EXPLORE_GRID_STORE_REBUILT_ADS_MISSING_LABEL_CRASH";
            case 13440:
                return "MANAGED_MOBILE_ERRORS_IG_REELS_GENERIC_SOFT_ERROR";
            case 13476:
                return "MANAGED_MOBILE_ERRORS_MOBILE_ZONE_PRIVACY_UNWRAP";
            case 13491:
                return "MANAGED_MOBILE_ERRORS_INVALID_OC_IMAGE_RENDERER_OUTPUT_ASPECT_RATIO";
            case 13519:
                return "MANAGED_MOBILE_ERRORS_FBUSERSESSION_PROVIDER_EMPTY_VC_CACHE_ERROR";
            case 13533:
                return "MANAGED_MOBILE_ERRORS_TEST_EVENT_CREATION";
            case 13650:
                return "MANAGED_MOBILE_ERRORS_CREATE_REEL_FROM_VOD_THUMBNAIL_UPLOAD_ERRORS";
            case 13651:
                return "MANAGED_MOBILE_ERRORS_COMBINED_THREAD_POOL_INJECTED_TOO_EARLY";
            case 13748:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_VIDEO_FRAME_GENERATION_ERROR";
            case 13764:
                return "MANAGED_MOBILE_ERRORS_PROFILE_ANDROID_CONTEXT_CONFLICT_EVENT";
            case 13790:
                return "MANAGED_MOBILE_ERRORS_OVERLAY_ETC1_TEXTURE_CREATED";
            case 13840:
                return "MANAGED_MOBILE_ERRORS_LITHO_GROUP_MALL_UNEXPECTED_EVENT";
            case 13843:
                return "MANAGED_MOBILE_ERRORS_IG_REELS_SYNC_FLOW_IMP_NOT_HANDLED";
            case 13863:
                return "MANAGED_MOBILE_ERRORS_IG_SOCIAL_CONTEXT_TEXT_USERNAMES_EMPTY_LIST";
            case 13895:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_CAMERA_BUTTON_ERROR";
            case 13921:
                return "MANAGED_MOBILE_ERRORS_IG_CLIPS_ADS_OVERFLOW_MENU_UNSUPPORTED_ITEM";
            case 13927:
                return "MANAGED_MOBILE_ERRORS_IG_REELS_CLIPS_PAGINATION_TOKEN_ERROR_EVENT";
            case 13988:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_ADS_MOBILE_ERROR_EVENT";
            case 14018:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_ATTEST_KEYSTORE_UNEXPECTED_EVENT";
            case 14078:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_CREATION_UNEXPECTED_EVENT";
            case 14154:
                return "MANAGED_MOBILE_ERRORS_LOGGED_IN_USER_SESSION_MANAGER_INJECTED_TOO_EARLY";
            case 14212:
                return "MANAGED_MOBILE_ERRORS_MSYS_PUSH_NOTIFICATION";
            case 14284:
                return "MANAGED_MOBILE_ERRORS_CONTENT_RESOLVER_UTIL_ILLEGAL_ARGUMENT_EXCEPTION";
            case 14287:
                return "MANAGED_MOBILE_ERRORS_UPLOADER_UNCAUGHT_EXCEPTION";
            case 14290:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_TEXT_COMPOSER_BACKGROUND_ERROR";
            case 14378:
                return "MANAGED_MOBILE_ERRORS_TIGON_UNEXPECTED_ERROR_EVENT";
            case 14401:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_STICKER_OVERLAY_ERROR";
            case 14402:
                return "MANAGED_MOBILE_ERRORS_ANDROID_PATTERN_VIDEO";
            case 14461:
                return "MANAGED_MOBILE_ERRORS_IG_ADS_SOFT_ERROR";
            case 14468:
                return "MANAGED_MOBILE_ERRORS_AOSP_THREAD_SAFETY_ISSUE";
            case 14481:
                return "MANAGED_MOBILE_ERRORS_LITHO_NEWSFEED_UNEXPECTED_EVENT";
            case 14487:
                return "MANAGED_MOBILE_ERRORS_LITHO_COMPASS_ITEM_UNEXPECTED_EVENT";
            case 14505:
                return "MANAGED_MOBILE_ERRORS_APP_INIT_NOT_RESPONDING";
            case 14536:
                return "MANAGED_MOBILE_ERRORS_GRADIENT_EXTRACTION_ERROR";
            case 14585:
                return "MANAGED_MOBILE_ERRORS_DECORBITMAPHELPER_CREATE_VIDEO_STICKER";
            case 14649:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_IMAGE_INFRA";
            case 14658:
                return "MANAGED_MOBILE_ERRORS_LEGACY_1CS_ERROR_POST_PARAM_NULL";
            case 14671:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_NETWORK_MOBILE_ERROR_EVENT";
            case 14703:
                return "MANAGED_MOBILE_ERRORS_QPL_INJECTED_TOO_EARLY";
            case 14709:
                return "MANAGED_MOBILE_ERRORS_PHOTOIMPORTCALLABLE_JPEG_CONVERSION_ERROR";
            case 14727:
                return "MANAGED_MOBILE_ERRORS_SHOWREEL_UNEXPECTED_EVENT";
            case 14751:
                return "MANAGED_MOBILE_ERRORS_MISSING_MODAL_FRAGMENT_FACTORY";
            case 14839:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_CAPTURE_ERROR";
            case 14865:
                return "MANAGED_MOBILE_ERRORS_SIMPLE_WEBVIEW_INFLATION_EXCEPTION";
            case 14904:
                return "MANAGED_MOBILE_ERRORS_IG_REELS_CLIPS_PAGINATION_TOKEN_ADS_ERROR_EVENT";
            case 14936:
                return "MANAGED_MOBILE_ERRORS_MSGR_HIGHLIGHTS_TAB_MANAGED_ERRORS";
            case 15031:
                return "MANAGED_MOBILE_ERRORS_IG_REELS_NON_LITHO_INITIALIZATION_LOGGING_DEBUG";
            case 15037:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_MAE_EXCLUSION_UNEXPECTED_LOGGING";
            case 15112:
                return "MANAGED_MOBILE_ERRORS_IG_TRIALS_ERROR_EVENT";
            case 15207:
                return "MANAGED_MOBILE_ERRORS_UNIFIED_PLAYER_UNEXPECTED_EVENT";
            case 15222:
                return "MANAGED_MOBILE_ERRORS_BPS_UNEXPECTED_EVENT";
            case 15271:
                return "MANAGED_MOBILE_ERRORS_QE_CHECKED_BEFORE_INIT";
            case 15345:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_PROFILE_UNEXPECTED_EVENT";
            case 15372:
                return "MANAGED_MOBILE_ERRORS_OVERLAP_NAVBAR_ZERO_OR_NEGATIVE";
            case 15418:
                return "MANAGED_MOBILE_ERRORS_IG_REELS_NON_LITHO_BIND_LOGGING_DEBUG";
            case 15448:
                return "MANAGED_MOBILE_ERRORS_EXECUTOR_ILLEGAL_VCM_GET_VIEWER_CONTEXT_V2";
            case 15462:
                return "MANAGED_MOBILE_ERRORS_LITHO_WORDMARK_NAVBAR_UNEXPECTED_EVENTS";
            case 15472:
                return "MANAGED_MOBILE_ERRORS_TLC_INVALID_SEND";
            case 15581:
                return "MANAGED_MOBILE_ERRORS_FB4A_SHARE_SHEET_ERRORS";
            case 15597:
                return "MANAGED_MOBILE_ERRORS_MTV_FRAGMENT_DESTROYED_FOR_ACTIVITY_LAUNCH";
            case 15655:
                return "MANAGED_MOBILE_ERRORS_FRAGMENT_INSTANTIATION_EXCEPTION";
            case 15711:
                return "MANAGED_MOBILE_ERRORS_ARMADILLO_PUSH_NOTIFICATION_DATA_SYNC_RENDER_NOT_ALLOWED";
            case 15725:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_FLASH_FEED_ERROR";
            case 15738:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_STORY_VIEWER";
            case 15744:
                return "MANAGED_MOBILE_ERRORS_LITHO_INSPIRATION_UNEXPECTED_EVENT";
            case 15779:
                return "MANAGED_MOBILE_ERRORS_INLINE_ADD_HIGHLIGHT_FRAGMENT";
            case 15786:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_MOBILE_ERROR_EVENT";
            case 15796:
                return "MANAGED_MOBILE_ERRORS_LITHO_STORY_VIEWER_UNEXPECTED_EVENT";
            case 15805:
                return "MANAGED_MOBILE_ERRORS_KATANA_CONSENT_ALASKA_NATIVE_SOFT_ERROR";
            case 15859:
                return "MANAGED_MOBILE_ERRORS_BITMAP_UTIL_CLOSE_INPUT_STREAM_IO_EXCEPTION";
            case 15887:
                return "MANAGED_MOBILE_ERRORS_ALBUM_NULL_COVER_IMAGE_PATH";
            case 15959:
                return "MANAGED_MOBILE_ERRORS_NATIVE_TEMPLATE_UNEXPECTED_EVENT";
            case 15973:
                return "MANAGED_MOBILE_ERRORS_IG_BOTTOM_SHEET_NAVIGATION_ERROR";
            case 16070:
                return "MANAGED_MOBILE_ERRORS_VIDEO_STITCHER_FAILURE";
            case 16088:
                return "MANAGED_MOBILE_ERRORS_TIFU_PARSE_ERROR";
            case 16096:
                return "MANAGED_MOBILE_ERRORS_SIMPLER_HEADER_INVALID_VARIANT";
            case 16155:
                return "MANAGED_MOBILE_ERRORS_LITHO_WATCH_RECYCLER_UNEXPECTED_EVENT";
            case 16206:
                return "MANAGED_MOBILE_ERRORS_STICKER_TYPE_UNIFIED_TO_LEGACY_FAILED";
            case 16237:
                return "MANAGED_MOBILE_ERRORS_PANDO_CONSISTENCY_MISMATCH_USER";
            case 16334:
                return "MANAGED_MOBILE_ERRORS_BPS_REELS_FB4A_UNEXPECTED_EVENT";
            case 16341:
                return "MANAGED_MOBILE_ERRORS_LITHO_LOCATION_PICKER_UNEXPECTED_EVENT";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
