package X;

/* renamed from: X.Rzk, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62137Rzk {
    public static String A00(int i) {
        return i != 1189 ? i != 1848 ? i != 2767 ? i != 4403 ? i != 5648 ? i != 7373 ? i != 7564 ? i != 7903 ? i != 11831 ? i != 15662 ? "UNDEFINED_QPL_EVENT" : "WEARABLE_SELF_CARE_SHARING_RECAP_VIDEO_BUILD_COMPOSITION_DATA" : "WEARABLE_SELF_CARE_SHARING_STORIES_SHARING" : "WEARABLE_SELF_CARE_SHARING_GROUPS_PICKER_SEARCH_LOAD" : "WEARABLE_SELF_CARE_SHARING_GROUPS_PICKER_LOAD" : "WEARABLE_SELF_CARE_SHARING_PREMADE_STORY_LOAD_TIME" : "WEARABLE_SELF_CARE_SHARING_PREMADE_STORIES_WORKOUT_LOAD_TIME" : "WEARABLE_SELF_CARE_SHARING_FBGROUPS_SHARING" : "WEARABLE_SELF_CARE_SHARING_PREMADE_STORIES_ACTIVITY_LOAD_TIME" : "WEARABLE_SELF_CARE_SHARING_PREMADE_STORIES_WORKOUT_STICKER_SELECT_TIME" : "WEARABLE_SELF_CARE_SHARING_CONTACTS_SHARING";
    }
}
