package X;

/* renamed from: X.Rwq, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC61980Rwq {
    public static String A00(int i) {
        return i != 2832 ? i != 6317 ? i != 8040 ? i != 12421 ? i != 13218 ? i != 14630 ? i != 16232 ? i != 16309 ? "UNDEFINED_QPL_EVENT" : "IGD_PRIVACY_EXPERIENCES_CHECK_TYPING_INDICATOR_CONTROL_ENABLED" : "IGD_PRIVACY_EXPERIENCES_BATCHED_THREAD_DELETION" : "IGD_PRIVACY_EXPERIENCES_MUTATE_TYPING_INDICATOR_SETTING" : "IGD_PRIVACY_EXPERIENCES_LOAD_READ_RECEIPT_SETTING" : "IGD_PRIVACY_EXPERIENCES_BATCHED_THREAD_DELETION_API_CALL" : "IGD_PRIVACY_EXPERIENCES_BATCHED_THREAD_DELETION_NUX" : "IGD_PRIVACY_EXPERIENCES_MUTATE_READ_RECEIPT_SETTING" : "IGD_PRIVACY_EXPERIENCES_BATCHED_THREAD_DELETION_TOAST";
    }
}
