package X;

/* renamed from: X.RxW, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62022RxW {
    public static String A00(int i) {
        return i != 1913 ? i != 3594 ? i != 4064 ? i != 4548 ? i != 5147 ? i != 11024 ? i != 14154 ? "UNDEFINED_QPL_EVENT" : "MESSENGER_WELLBEING_HIDDEN_WORDS_UPSELL_NUX_TURN_ON_TRACING" : "MESSENGER_WELLBEING_USER_UNBLOCK_TRACING" : "MESSENGER_WELLBEING_USER_BLOCK_TRACING" : "MESSENGER_WELLBEING_COMPOSER_NUX_CREATOR_NETWORK_FETCH" : "MESSENGER_WELLBEING_KINDNESS_REMINDER_IN_THREAD_BANNER_TRACING" : "MESSENGER_WELLBEING_HIDDEN_WORDS_UPSELL_NUX_TRACING" : "MESSENGER_WELLBEING_HIDDEN_WORDS_UPSELL_POST_DELETE_TRACING";
    }
}
