package X;

/* renamed from: X.RvP, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC61893RvP {
    public static String A00(int i) {
        return i != 2118 ? i != 9315 ? i != 10262 ? i != 10523 ? i != 10802 ? i != 12474 ? i != 13435 ? i != 13710 ? i != 15710 ? "UNDEFINED_QPL_EVENT" : "FB4A_CREATION_VIDEO_TOOLS_MME_TIMELINE_EDITOR_ILLEGAL_STATE" : "FB4A_CREATION_VIDEO_TOOLS_MME_INVALID_START_TIME_ON_CLIP_TRIM" : "FB4A_CREATION_VIDEO_TOOLS_MME_CLIP_LEVEL_EDITING_AUTO_CROP_ERROR" : "FB4A_CREATION_VIDEO_TOOLS_MME_INDEX_OUT_OF_BOUNDS_ON_READ_DRAFT" : "FB4A_CREATION_VIDEO_TOOLS_MME_NO_SUCH_ELEMENT_RMS_EMPTY_MEDIAS" : "FB4A_CREATION_VIDEO_TOOLS_MME_FRAME_RETRIEVER_RELEASE_ERROR" : "FB4A_CREATION_VIDEO_TOOLS_MME_SMART_TRIM_ERROR" : "FB4A_CREATION_VIDEO_TOOLS_MME_TRANSITIONS_LOAD_ERROR" : "FB4A_CREATION_VIDEO_TOOLS_MME_NULL_TEXT_TOOL_ACTIVE_STATE_IN_TEXT_EDITING_MODE";
    }
}
