package X;

/* renamed from: X.Rxb, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62027Rxb {
    public static String A00(int i) {
        return i != 2685 ? i != 7661 ? i != 8078 ? i != 9871 ? i != 10205 ? i != 10776 ? i != 12616 ? "UNDEFINED_QPL_EVENT" : "MMA_ADMIN_CONSOLE_MMA_LOGIN_OIDC_HANDLE_RESPONSE" : "MMA_ADMIN_CONSOLE_L6_MIGRATION_DETAIL_MIGRATION_PROGRESS_CONTROLLER" : "MMA_ADMIN_CONSOLE_MMA_LOGIN_OIDC_START" : "MMA_ADMIN_CONSOLE_EXTERNAL_USER_TOGGLE_FORWARD_FIX" : "MMA_ADMIN_CONSOLE_L6_MIGRATE_ABLE_USERS_PAGINATION_QUERY" : "MMA_ADMIN_CONSOLE_MIGRATE_ALL_UNMIGRATED_USERS" : "MMA_ADMIN_CONSOLE_L6_MIGRATE_ABLE_USERS_SEVER_SEARCH";
    }
}
