package X;

import com.facebook.pando.TreeUpdaterJNI;
import com.facebook.react.modules.dialog.DialogModule;
import com.instagram.api.schemas.CarouselRenderingType;
import com.instagram.api.schemas.FanClubStoriesTeaserType;
import com.instagram.api.schemas.HallpassDetailsDict;
import com.instagram.api.schemas.HighlightReelTypeStr;
import com.instagram.api.schemas.IGPostTriggerExperience;
import com.instagram.api.schemas.IntentAwareAdsInfoIntf;
import com.instagram.api.schemas.RingSpec;
import com.instagram.model.reels.ReelType;
import com.instagram.model.reels.sponsored.AutoGeneratedCardType;
import com.instagram.sponsored.signals.model.AdsIAWRatingInfoIntf;
import com.instagram.sponsored.signals.model.AdsRatingInfoIntf;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/* renamed from: X.I2k, reason: case insensitive filesystem */
/* loaded from: classes7.dex */
public abstract /* synthetic */ class AbstractC40704I2k {
    public static Map A00(InterfaceC37791pH interfaceC37791pH) {
        ArrayList arrayList;
        TreeUpdaterJNI treeUpdaterJNI;
        TreeUpdaterJNI treeUpdaterJNI2;
        TreeUpdaterJNI treeUpdaterJNI3;
        TreeUpdaterJNI treeUpdaterJNI4;
        TreeUpdaterJNI treeUpdaterJNI5;
        TreeUpdaterJNI treeUpdaterJNI6;
        TreeUpdaterJNI treeUpdaterJNI7;
        TreeUpdaterJNI treeUpdaterJNI8;
        TreeUpdaterJNI treeUpdaterJNI9;
        TreeUpdaterJNI treeUpdaterJNI10;
        String str;
        TreeUpdaterJNI treeUpdaterJNI11;
        TreeUpdaterJNI treeUpdaterJNI12;
        TreeUpdaterJNI treeUpdaterJNI13;
        ArrayList arrayList2;
        TreeUpdaterJNI treeUpdaterJNI14;
        TreeUpdaterJNI treeUpdaterJNI15;
        TreeUpdaterJNI treeUpdaterJNI16;
        TreeUpdaterJNI treeUpdaterJNI17;
        ArrayList arrayList3;
        TreeUpdaterJNI treeUpdaterJNI18;
        TreeUpdaterJNI treeUpdaterJNI19;
        String str2;
        TreeUpdaterJNI treeUpdaterJNI20;
        String str3;
        TreeUpdaterJNI treeUpdaterJNI21;
        TreeUpdaterJNI treeUpdaterJNI22;
        ArrayList arrayList4;
        TreeUpdaterJNI treeUpdaterJNI23;
        TreeUpdaterJNI treeUpdaterJNI24;
        ArrayList arrayList5;
        String str4;
        TreeUpdaterJNI treeUpdaterJNI25;
        TreeUpdaterJNI treeUpdaterJNI26;
        TreeUpdaterJNI treeUpdaterJNI27;
        TreeUpdaterJNI treeUpdaterJNI28;
        TreeUpdaterJNI treeUpdaterJNI29;
        TreeUpdaterJNI treeUpdaterJNI30;
        TreeUpdaterJNI treeUpdaterJNI31;
        LinkedHashMap A1I = AbstractC166987dD.A1I();
        ArrayList arrayList6 = null;
        if (interfaceC37791pH.AYI() != null) {
            InterfaceC37821pL AYI = interfaceC37791pH.AYI();
            if (AYI != null) {
                treeUpdaterJNI31 = AYI.F7o();
            } else {
                treeUpdaterJNI31 = null;
            }
            A1I.put("acr_in_story", treeUpdaterJNI31);
        }
        if (interfaceC37791pH.AYx() != null) {
            A1I.put("actor_id", interfaceC37791pH.AYx());
        }
        if (interfaceC37791pH.AZ2() != null) {
            InterfaceC37861pP AZ2 = interfaceC37791pH.AZ2();
            if (AZ2 != null) {
                treeUpdaterJNI30 = AZ2.F7o();
            } else {
                treeUpdaterJNI30 = null;
            }
            A1I.put("ad4ad", treeUpdaterJNI30);
        }
        if (interfaceC37791pH.AZC() != null) {
            A1I.put(AbstractC111324zv.A00(715), interfaceC37791pH.AZC());
        }
        if (interfaceC37791pH.AZO() != null) {
            InterfaceC37891pS AZO = interfaceC37791pH.AZO();
            if (AZO != null) {
                treeUpdaterJNI29 = AZO.F7o();
            } else {
                treeUpdaterJNI29 = null;
            }
            A1I.put("ad_pod_rules", treeUpdaterJNI29);
        }
        if (interfaceC37791pH.Aa6() != null) {
            AdsIAWRatingInfoIntf Aa6 = interfaceC37791pH.Aa6();
            if (Aa6 != null) {
                treeUpdaterJNI28 = Aa6.F7o();
            } else {
                treeUpdaterJNI28 = null;
            }
            A1I.put(AbstractC111324zv.A00(719), treeUpdaterJNI28);
        }
        if (interfaceC37791pH.AaD() != null) {
            AdsRatingInfoIntf AaD = interfaceC37791pH.AaD();
            if (AaD != null) {
                treeUpdaterJNI27 = AaD.F7o();
            } else {
                treeUpdaterJNI27 = null;
            }
            A1I.put(AbstractC111324zv.A00(720), treeUpdaterJNI27);
        }
        if (interfaceC37791pH.AcH() != null) {
            A1I.put("app_id", interfaceC37791pH.AcH());
        }
        if (interfaceC37791pH.AcX() != null) {
            A1I.put("archive_id", interfaceC37791pH.AcX());
        }
        if (interfaceC37791pH.Ag6() != null) {
            A1I.put(AbstractC58317Pt9.A00(691), interfaceC37791pH.Ag6());
        }
        if (interfaceC37791pH.AgY() != null) {
            InterfaceC37931pa AgY = interfaceC37791pH.AgY();
            if (AgY != null) {
                treeUpdaterJNI26 = AgY.F7o();
            } else {
                treeUpdaterJNI26 = null;
            }
            A1I.put("bloks_netego", treeUpdaterJNI26);
        }
        if (interfaceC37791pH.AiD() != null) {
            InterfaceC37961pd AiD = interfaceC37791pH.AiD();
            if (AiD != null) {
                treeUpdaterJNI25 = AiD.F7o();
            } else {
                treeUpdaterJNI25 = null;
            }
            A1I.put("broadcast", treeUpdaterJNI25);
        }
        if (interfaceC37791pH.AkD() != null) {
            A1I.put("campaign_id", interfaceC37791pH.AkD());
        }
        if (interfaceC37791pH.Ake() != null) {
            A1I.put(AbstractC58317Pt9.A00(705), interfaceC37791pH.Ake());
        }
        if (interfaceC37791pH.Aki() != null) {
            A1I.put("can_reply", interfaceC37791pH.Aki());
        }
        if (interfaceC37791pH.Akk() != null) {
            A1I.put("can_reshare", interfaceC37791pH.Akk());
        }
        if (interfaceC37791pH.AmH() != null) {
            A1I.put(AbstractC111324zv.A00(4068), interfaceC37791pH.AmH());
        }
        if (interfaceC37791pH.AmL() != null) {
            CarouselRenderingType AmL = interfaceC37791pH.AmL();
            if (AmL != null) {
                str4 = AmL.A00;
            } else {
                str4 = null;
            }
            A1I.put("carousel_rendering_type", str4);
        }
        if (interfaceC37791pH.AmR() != null) {
            List<AutoGeneratedCardType> AmR = interfaceC37791pH.AmR();
            if (AmR != null) {
                arrayList5 = AbstractC167007dF.A0i(AmR);
                for (AutoGeneratedCardType autoGeneratedCardType : AmR) {
                    C14360o3.A0B(autoGeneratedCardType, 0);
                    arrayList5.add(autoGeneratedCardType.A00);
                }
            } else {
                arrayList5 = null;
            }
            A1I.put("carousel_transformation_cards_v2", arrayList5);
        }
        if (interfaceC37791pH.Anu() != null) {
            InterfaceC38021pm Anu = interfaceC37791pH.Anu();
            if (Anu != null) {
                treeUpdaterJNI24 = Anu.F7o();
            } else {
                treeUpdaterJNI24 = null;
            }
            A1I.put("client_gap_rules", treeUpdaterJNI24);
        }
        if (interfaceC37791pH.Ao0() != null) {
            A1I.put("client_prefetch_score", AbstractC166997dE.A0f(interfaceC37791pH.Ao0()));
        }
        if (interfaceC37791pH.Aqn() != null) {
            A1I.put(AbstractC58317Pt9.A00(746), interfaceC37791pH.Aqn());
        }
        if (interfaceC37791pH.Aqo() != null) {
            A1I.put(AbstractC58317Pt9.A00(747), interfaceC37791pH.Aqo());
        }
        if (interfaceC37791pH.Arc() != null) {
            InterfaceC38061pq Arc = interfaceC37791pH.Arc();
            if (Arc != null) {
                treeUpdaterJNI23 = Arc.F7o();
            } else {
                treeUpdaterJNI23 = null;
            }
            A1I.put("continue_shopping_in_story", treeUpdaterJNI23);
        }
        if (interfaceC37791pH.Ark() != null) {
            List<InterfaceC38791rB> Ark = interfaceC37791pH.Ark();
            if (Ark != null) {
                arrayList4 = AbstractC166987dD.A1E();
                for (InterfaceC38791rB interfaceC38791rB : Ark) {
                    if (interfaceC38791rB != null) {
                        arrayList4.add(interfaceC38791rB.F7o());
                    }
                }
            } else {
                arrayList4 = null;
            }
            A1I.put("cop_render_output", arrayList4);
        }
        if (interfaceC37791pH.AsP() != null) {
            InterfaceC38101pu AsP = interfaceC37791pH.AsP();
            if (AsP != null) {
                treeUpdaterJNI22 = AsP.F7o();
            } else {
                treeUpdaterJNI22 = null;
            }
            A1I.put("cover_media", treeUpdaterJNI22);
        }
        if (interfaceC37791pH.AsZ() != null) {
            A1I.put("created_at", interfaceC37791pH.AsZ());
        }
        if (interfaceC37791pH.Ay4() != null) {
            A1I.put(AbstractC58317Pt9.A00(762), interfaceC37791pH.Ay4());
        }
        if (interfaceC37791pH.B16() != null) {
            A1I.put("eligible_for_hype", interfaceC37791pH.B16());
        }
        if (interfaceC37791pH.B1O() != null) {
            InterfaceC38121pw B1O = interfaceC37791pH.B1O();
            if (B1O != null) {
                treeUpdaterJNI21 = B1O.F7o();
            } else {
                treeUpdaterJNI21 = null;
            }
            A1I.put("empty_story_state_data", treeUpdaterJNI21);
        }
        if (interfaceC37791pH.B3E() != null) {
            A1I.put("expiring_at", interfaceC37791pH.B3E());
        }
        if (interfaceC37791pH.B4Q() != null) {
            FanClubStoriesTeaserType B4Q = interfaceC37791pH.B4Q();
            if (B4Q != null) {
                str3 = B4Q.A00;
            } else {
                str3 = null;
            }
            A1I.put("fan_club_stories_teaser_type", str3);
        }
        if (interfaceC37791pH.B6b() != null) {
            A1I.put("first_item_photo_url", interfaceC37791pH.B6b());
        }
        if (interfaceC37791pH.BAs() != null) {
            HallpassDetailsDict BAs = interfaceC37791pH.BAs();
            if (BAs != null) {
                treeUpdaterJNI20 = BAs.F7o();
            } else {
                treeUpdaterJNI20 = null;
            }
            A1I.put("hallpass_data", treeUpdaterJNI20);
        }
        if (interfaceC37791pH.BBD() != null) {
            A1I.put(AbstractC58317Pt9.A00(797), interfaceC37791pH.BBD());
        }
        if (interfaceC37791pH.BBI() != null) {
            A1I.put("has_candid_media", interfaceC37791pH.BBI());
        }
        if (interfaceC37791pH.BBe() != null) {
            A1I.put(AbstractC58317Pt9.A00(798), interfaceC37791pH.BBe());
        }
        if (interfaceC37791pH.BC9() != null) {
            A1I.put("has_more_in_lately_attribution", interfaceC37791pH.BC9());
        }
        if (interfaceC37791pH.BCP() != null) {
            A1I.put("has_pride_media", interfaceC37791pH.BCP());
        }
        if (interfaceC37791pH.BCw() != null) {
            A1I.put("has_video", interfaceC37791pH.BCw());
        }
        if (interfaceC37791pH.BDi() != null) {
            A1I.put("hide_from_feed_unit", interfaceC37791pH.BDi());
        }
        if (interfaceC37791pH.BE5() != null) {
            HighlightReelTypeStr BE5 = interfaceC37791pH.BE5();
            if (BE5 != null) {
                str2 = BE5.A00;
            } else {
                str2 = null;
            }
            A1I.put(AbstractC58317Pt9.A00(804), str2);
        }
        List BER = interfaceC37791pH.BER();
        if (BER != null) {
            ArrayList A0i = AbstractC167007dF.A0i(BER);
            Iterator it = BER.iterator();
            while (it.hasNext()) {
                AbstractC31178DnM.A1U(A0i, it);
            }
            A1I.put(AbstractC58317Pt9.A00(809), A0i);
        }
        if (interfaceC37791pH.getId() != null) {
            AbstractC37300Gc1.A12(interfaceC37791pH.getId(), A1I);
        }
        if (interfaceC37791pH.BFO() != null) {
            InterfaceC38171q4 BFO = interfaceC37791pH.BFO();
            if (BFO != null) {
                treeUpdaterJNI19 = BFO.F7o();
            } else {
                treeUpdaterJNI19 = null;
            }
            A1I.put("ig_ads_story_interactive_media_info_data", treeUpdaterJNI19);
        }
        if (interfaceC37791pH.BH3() != null) {
            A1I.put("imbe_megaphone_reel_id", interfaceC37791pH.BH3());
        }
        if (interfaceC37791pH.BHN() != null) {
            A1I.put("includes_lately_only_unseen_media", interfaceC37791pH.BHN());
        }
        if (interfaceC37791pH.BIo() != null) {
            IntentAwareAdsInfoIntf BIo = interfaceC37791pH.BIo();
            if (BIo != null) {
                treeUpdaterJNI18 = BIo.F7o();
            } else {
                treeUpdaterJNI18 = null;
            }
            A1I.put("intent_aware_ads_info", treeUpdaterJNI18);
        }
        if (interfaceC37791pH.BIp() != null) {
            List<InterfaceC37791pH> BIp = interfaceC37791pH.BIp();
            if (BIp != null) {
                arrayList3 = AbstractC166987dD.A1E();
                for (InterfaceC37791pH interfaceC37791pH2 : BIp) {
                    if (interfaceC37791pH2 != null) {
                        arrayList3.add(interfaceC37791pH2.F7o());
                    }
                }
            } else {
                arrayList3 = null;
            }
            A1I.put("intent_aware_ads_reels", arrayList3);
        }
        if (interfaceC37791pH.BIt() != null) {
            A1I.put("interaction_timestamp", interfaceC37791pH.BIt());
        }
        if (interfaceC37791pH.BJK() != null) {
            InterfaceC38221qC BJK = interfaceC37791pH.BJK();
            if (BJK != null) {
                treeUpdaterJNI17 = BJK.F7o();
            } else {
                treeUpdaterJNI17 = null;
            }
            A1I.put("invalidation_rules", treeUpdaterJNI17);
        }
        if (interfaceC37791pH.CPa() != null) {
            A1I.put(AbstractC58317Pt9.A00(42), interfaceC37791pH.CPa());
        }
        if (interfaceC37791pH.CPe() != null) {
            A1I.put("is_ads_sensitive", interfaceC37791pH.CPe());
        }
        if (interfaceC37791pH.CQ1() != null) {
            A1I.put(AbstractC111324zv.A00(1032), interfaceC37791pH.CQ1());
        }
        if (interfaceC37791pH.CR1() != null) {
            A1I.put(AbstractC58317Pt9.A00(838), interfaceC37791pH.CR1());
        }
        if (interfaceC37791pH.CRn() != null) {
            A1I.put("is_converted_to_clips", interfaceC37791pH.CRn());
        }
        if (interfaceC37791pH.CS7() != null) {
            A1I.put(AbstractC111324zv.A00(4730), interfaceC37791pH.CS7());
        }
        if (interfaceC37791pH.CUX() != null) {
            A1I.put(AbstractC111324zv.A00(2610), interfaceC37791pH.CUX());
        }
        if (interfaceC37791pH.CUv() != null) {
            A1I.put("is_fit_green", interfaceC37791pH.CUv());
        }
        if (interfaceC37791pH.CZX() != null) {
            A1I.put("is_nux", interfaceC37791pH.CZX());
        }
        if (interfaceC37791pH.CaN() != null) {
            A1I.put(AbstractC58317Pt9.A00(845), interfaceC37791pH.CaN());
        }
        List items = interfaceC37791pH.getItems();
        if (items != null) {
            ArrayList A0i2 = AbstractC167007dF.A0i(items);
            Iterator it2 = items.iterator();
            while (it2.hasNext()) {
                AbstractC37303Gc4.A1S(A0i2, it2);
            }
            A1I.put(DialogModule.KEY_ITEMS, A0i2);
        }
        if (interfaceC37791pH.BM9() != null) {
            A1I.put(AbstractC58317Pt9.A00(852), AbstractC166997dE.A0f(interfaceC37791pH.BM9()));
        }
        if (interfaceC37791pH.BMD() != null) {
            A1I.put("latest_reel_media", interfaceC37791pH.BMD());
        }
        if (interfaceC37791pH.BMF() != null) {
            A1I.put("latest_tray_reel_media", interfaceC37791pH.BMF());
        }
        if (interfaceC37791pH.BQb() != null) {
            A1I.put("media_count", interfaceC37791pH.BQb());
        }
        if (interfaceC37791pH.BR1() != null) {
            A1I.put("media_ids", interfaceC37791pH.BR1());
        }
        if (interfaceC37791pH.BRO() != null) {
            InterfaceC38251qF BRO = interfaceC37791pH.BRO();
            if (BRO != null) {
                treeUpdaterJNI16 = BRO.F7o();
            } else {
                treeUpdaterJNI16 = null;
            }
            A1I.put("media_preview", treeUpdaterJNI16);
        }
        if (interfaceC37791pH.BTI() != null) {
            InterfaceC38281qI BTI = interfaceC37791pH.BTI();
            if (BTI != null) {
                treeUpdaterJNI15 = BTI.F7o();
            } else {
                treeUpdaterJNI15 = null;
            }
            A1I.put("meta_gallery_stories_midcard", treeUpdaterJNI15);
        }
        if (interfaceC37791pH.BVw() != null) {
            A1I.put("muted", interfaceC37791pH.BVw());
        }
        C38321qM BWX = interfaceC37791pH.BWX();
        if (BWX != null) {
            A1I.put("netego_background_media", BWX.A1D());
        }
        if (interfaceC37791pH.BWe() != null) {
            A1I.put("netego_type", interfaceC37791pH.BWe());
        }
        if (interfaceC37791pH.BWq() != null) {
            A1I.put("next_button_index", interfaceC37791pH.BWq());
        }
        if (interfaceC37791pH.Bag() != null) {
            InterfaceC38481qc Bag = interfaceC37791pH.Bag();
            if (Bag != null) {
                treeUpdaterJNI14 = Bag.F7o();
            } else {
                treeUpdaterJNI14 = null;
            }
            A1I.put("owner", treeUpdaterJNI14);
        }
        if (interfaceC37791pH.Baz() != null) {
            A1I.put("page_id", interfaceC37791pH.Baz());
        }
        if (interfaceC37791pH.Bf8() != null) {
            List<IGPostTriggerExperience> Bf8 = interfaceC37791pH.Bf8();
            if (Bf8 != null) {
                arrayList2 = AbstractC167007dF.A0i(Bf8);
                for (IGPostTriggerExperience iGPostTriggerExperience : Bf8) {
                    C14360o3.A0B(iGPostTriggerExperience, 0);
                    arrayList2.add(iGPostTriggerExperience.A00);
                }
            } else {
                arrayList2 = null;
            }
            A1I.put("post_trigger_experience_eligibilities", arrayList2);
        }
        if (interfaceC37791pH.BfS() != null) {
            A1I.put(AbstractC58317Pt9.A00(921), interfaceC37791pH.BfS());
        }
        if (interfaceC37791pH.BgY() != null) {
            A1I.put("priority_index", interfaceC37791pH.BgY());
        }
        if (interfaceC37791pH.Bib() != null) {
            A1I.put(AbstractC111324zv.A00(2929), interfaceC37791pH.Bib());
        }
        if (interfaceC37791pH.Bk9() != null) {
            A1I.put("ranked_position", interfaceC37791pH.Bk9());
        }
        if (interfaceC37791pH.BkB() != null) {
            InterfaceC38501qe BkB = interfaceC37791pH.BkB();
            if (BkB != null) {
                treeUpdaterJNI13 = BkB.F7o();
            } else {
                treeUpdaterJNI13 = null;
            }
            A1I.put(AbstractC58317Pt9.A00(934), treeUpdaterJNI13);
        }
        if (interfaceC37791pH.BlC() != null) {
            InterfaceC38061pq BlC = interfaceC37791pH.BlC();
            if (BlC != null) {
                treeUpdaterJNI12 = BlC.F7o();
            } else {
                treeUpdaterJNI12 = null;
            }
            A1I.put("reconsideration_injected_story", treeUpdaterJNI12);
        }
        if (interfaceC37791pH.Blr() != null) {
            InterfaceC38531qh Blr = interfaceC37791pH.Blr();
            if (Blr != null) {
                treeUpdaterJNI11 = Blr.F7o();
            } else {
                treeUpdaterJNI11 = null;
            }
            A1I.put("reel_toast", treeUpdaterJNI11);
        }
        if (interfaceC37791pH.Bls() != null) {
            ReelType Bls = interfaceC37791pH.Bls();
            if (Bls != null) {
                str = Bls.A00;
            } else {
                str = null;
            }
            A1I.put("reel_type", str);
        }
        if (interfaceC37791pH.BoN() != null) {
            InterfaceC38551qj BoN = interfaceC37791pH.BoN();
            if (BoN != null) {
                treeUpdaterJNI10 = BoN.F7o();
            } else {
                treeUpdaterJNI10 = null;
            }
            A1I.put("research_survey", treeUpdaterJNI10);
        }
        if (interfaceC37791pH.BpR() != null) {
            InterfaceC38571ql BpR = interfaceC37791pH.BpR();
            if (BpR != null) {
                treeUpdaterJNI9 = BpR.F7o();
            } else {
                treeUpdaterJNI9 = null;
            }
            A1I.put("ring_glyph", treeUpdaterJNI9);
        }
        if (interfaceC37791pH.BpS() != null) {
            RingSpec BpS = interfaceC37791pH.BpS();
            if (BpS != null) {
                treeUpdaterJNI8 = BpS.F7o();
            } else {
                treeUpdaterJNI8 = null;
            }
            A1I.put("ring_spec", treeUpdaterJNI8);
        }
        if (interfaceC37791pH.Bs8() != null) {
            A1I.put("seen", interfaceC37791pH.Bs8());
        }
        if (interfaceC37791pH.BsD() != null) {
            A1I.put("seen_ranked_position", interfaceC37791pH.BsD());
        }
        if (interfaceC37791pH.Bu6() != null) {
            InterfaceC38601qq Bu6 = interfaceC37791pH.Bu6();
            if (Bu6 != null) {
                treeUpdaterJNI7 = Bu6.F7o();
            } else {
                treeUpdaterJNI7 = null;
            }
            A1I.put("share_comment_to_story", treeUpdaterJNI7);
        }
        if (interfaceC37791pH.BvF() != null) {
            A1I.put(AbstractC58317Pt9.A00(975), interfaceC37791pH.BvF());
        }
        if (interfaceC37791pH.Bvr() != null) {
            A1I.put("should_treat_link_sticker_as_cta", interfaceC37791pH.Bvr());
        }
        if (interfaceC37791pH.BwG() != null) {
            A1I.put(AbstractC58317Pt9.A00(979), interfaceC37791pH.BwG());
        }
        if (interfaceC37791pH.Bwe() != null) {
            A1I.put("show_nux_tooltip", interfaceC37791pH.Bwe());
        }
        if (interfaceC37791pH.BxU() != null) {
            InterfaceC38621qt BxU = interfaceC37791pH.BxU();
            if (BxU != null) {
                treeUpdaterJNI6 = BxU.F7o();
            } else {
                treeUpdaterJNI6 = null;
            }
            A1I.put("simple_action", treeUpdaterJNI6);
        }
        if (interfaceC37791pH.Bxs() != null) {
            A1I.put("smart_reel_type", interfaceC37791pH.Bxs());
        }
        if (interfaceC37791pH.By7() != null) {
            InterfaceC38651qw By7 = interfaceC37791pH.By7();
            if (By7 != null) {
                treeUpdaterJNI5 = By7.F7o();
            } else {
                treeUpdaterJNI5 = null;
            }
            A1I.put("snapshot_data", treeUpdaterJNI5);
        }
        if (interfaceC37791pH.ByJ() != null) {
            A1I.put("social_context", interfaceC37791pH.ByJ());
        }
        if (interfaceC37791pH.Byt() != null) {
            A1I.put("source_token", interfaceC37791pH.Byt());
        }
        if (interfaceC37791pH.C1O() != null) {
            A1I.put(AbstractC58317Pt9.A00(991), interfaceC37791pH.C1O());
        }
        if (interfaceC37791pH.C2U() != null) {
            A1I.put("story_wedge_size", interfaceC37791pH.C2U());
        }
        if (interfaceC37791pH.getStrongId() != null) {
            A1I.put("strong_id__", interfaceC37791pH.getStrongId());
        }
        if (interfaceC37791pH.C3t() != null) {
            InterfaceC38671qy C3t = interfaceC37791pH.C3t();
            if (C3t != null) {
                treeUpdaterJNI4 = C3t.F7o();
            } else {
                treeUpdaterJNI4 = null;
            }
            A1I.put(AbstractC111324zv.A00(77), treeUpdaterJNI4);
        }
        if (interfaceC37791pH.C43() != null) {
            InterfaceC38691r1 C43 = interfaceC37791pH.C43();
            if (C43 != null) {
                treeUpdaterJNI3 = C43.F7o();
            } else {
                treeUpdaterJNI3 = null;
            }
            A1I.put("superlative_data", treeUpdaterJNI3);
        }
        if (interfaceC37791pH.C7t() != null) {
            InterfaceC38711r3 C7t = interfaceC37791pH.C7t();
            if (C7t != null) {
                treeUpdaterJNI2 = C7t.F7o();
            } else {
                treeUpdaterJNI2 = null;
            }
            A1I.put("threads_in_stories_unit_acquisition", treeUpdaterJNI2);
        }
        if (interfaceC37791pH.getTitle() != null) {
            AbstractC37300Gc1.A17(interfaceC37791pH.getTitle(), A1I);
        }
        if (interfaceC37791pH.CB0() != null) {
            InterfaceC38731r5 CB0 = interfaceC37791pH.CB0();
            if (CB0 != null) {
                treeUpdaterJNI = CB0.F7o();
            } else {
                treeUpdaterJNI = null;
            }
            A1I.put(AbstractC111324zv.A00(3258), treeUpdaterJNI);
        }
        if (interfaceC37791pH.CCf() != null) {
            A1I.put("unique_integer_reel_id", interfaceC37791pH.CCf());
        }
        if (interfaceC37791pH.CCw() != null) {
            A1I.put("unseen_media_ids", interfaceC37791pH.CCw());
        }
        if (interfaceC37791pH.CCy() != null) {
            A1I.put("unseen_tray_skipped_media_ids", interfaceC37791pH.CCy());
        }
        if (interfaceC37791pH.CDF() != null) {
            A1I.put("updated_timestamp", interfaceC37791pH.CDF());
        }
        AbstractC37302Gc3.A1T(interfaceC37791pH.CDj(), A1I);
        if (interfaceC37791pH.CFZ() != null) {
            List CFZ = interfaceC37791pH.CFZ();
            if (CFZ != null) {
                arrayList = AbstractC166987dD.A1E();
                Iterator it3 = CFZ.iterator();
                while (it3.hasNext()) {
                    AbstractC37303Gc4.A1X(arrayList, it3);
                }
            } else {
                arrayList = null;
            }
            A1I.put(AbstractC111324zv.A00(5561), arrayList);
        }
        if (interfaceC37791pH.CFa() != null) {
            List CFa = interfaceC37791pH.CFa();
            if (CFa != null) {
                arrayList6 = AbstractC166987dD.A1E();
                Iterator it4 = CFa.iterator();
                while (it4.hasNext()) {
                    AbstractC37303Gc4.A1Q(arrayList6, it4);
                }
            }
            A1I.put("video_to_carousel_cut_thumbnails", arrayList6);
        }
        return AbstractC06930Yk.A0B(A1I);
    }
}
