package X;

/* renamed from: X.Rwl, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC61975Rwl {
    public static String A00(int i) {
        return i != 1 ? i != 3 ? i != 1325 ? i != 2883 ? i != 7097 ? i != 8094 ? i != 11222 ? i != 11536 ? i != 13744 ? i != 22400 ? "UNDEFINED_QPL_EVENT" : "IG_STORIES_ENGAGEMENT_STORIES_TRAY_ITEM_WITH_PREVIEW_RENDER_LATENCY" : "IG_STORIES_ENGAGEMENT_RESHARE_TAGGED_STORY" : "IG_STORIES_ENGAGEMENT_VIEW_STORY_MEDIA" : "IG_STORIES_ENGAGEMENT_OPEN_STORY_VIEWER" : "IG_STORIES_ENGAGEMENT_TRAY_MEDIA_PREVIEW_VIEW_BIND" : "IG_STORIES_ENGAGEMENT_VIEWERS_LIST" : "IG_STORIES_ENGAGEMENT_CURRENT_STORY_INDEX_NOT_FOUND" : "IG_STORIES_ENGAGEMENT_STORIES_VIEWER_EXIT" : "IG_STORIES_ENGAGEMENT_STORIES_IFU_ITEM_LOAD_LATENCY" : "IG_STORIES_ENGAGEMENT_PRESENT_STORY_VIEWER";
    }
}
