package X;

/* renamed from: X.RvC, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC61880RvC {
    public static String A00(int i) {
        return i != 2073 ? i != 8276 ? i != 10019 ? i != 10054 ? i != 11838 ? i != 12314 ? i != 13040 ? i != 13834 ? i != 14368 ? i != 16315 ? "UNDEFINED_QPL_EVENT" : "DEEP_DATA_RESET_NATIVE_PROFILE_DATA" : "DEEP_DATA_RESET_MIP_RAWDATA" : "DEEP_DATA_DYNAMIC_ANALYSIS_DUMP_TRACE" : "DEEP_DATA_THREAD_WAIT_DUMP_TRACE" : "DEEP_DATA_THREAD_WAIT_DUMP_NATIVE_PROFILE_DATA" : "DEEP_DATA_THREAD_WAIT_DUMP_MIP_TRACE" : "DEEP_DATA_DUMP_NATIVE_PROFILE_DATA" : "DEEP_DATA_THREAD_WAIT_RESET_MIP_RAWDATA" : "DEEP_DATA_THREAD_WAIT_RESET_NATIVE_PROFILE_DATA" : "DEEP_DATA_DUMP_MIP_TRACE";
    }
}
