package X;

/* renamed from: X.Rxi, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62034Rxi {
    public static String A00(int i) {
        return i != 1866 ? i != 1882 ? i != 2854 ? i != 8894 ? i != 9360 ? i != 10512 ? i != 10929 ? i != 12519 ? i != 12757 ? "UNDEFINED_QPL_EVENT" : "MQTT_NETWORK_CONNECTIVITY_EVENT_LIGER_CONNECTED" : "MQTT_NETWORK_CONNECTIVITY_EVENT_MQTT_LIFE_CYCLE" : "MQTT_NETWORK_CONNECTIVITY_EVENT_MQTT_CONNECT_ATTEMPT" : "MQTT_NETWORK_CONNECTIVITY_EVENT_MQTT_PUBLISH" : "MQTT_NETWORK_CONNECTIVITY_EVENT_OS_DISCONNECTED" : "MQTT_NETWORK_CONNECTIVITY_EVENT_MQTT_CONNECTED" : "MQTT_NETWORK_CONNECTIVITY_EVENT_LIGER_DISCONNECTED" : "MQTT_NETWORK_CONNECTIVITY_EVENT_MQTT_DISCONNECTED" : "MQTT_NETWORK_CONNECTIVITY_EVENT_MQTT_SUBSCRIBE";
    }
}
