package X;

import com.instagram.model.reels.sponsored.AutoGeneratedCardType;

/* renamed from: X.4ol, reason: invalid class name and case insensitive filesystem */
/* loaded from: classes2.dex */
public abstract class AbstractC105314ol {
    public static final AutoGeneratedCardType A00(String str) {
        AutoGeneratedCardType autoGeneratedCardType = (AutoGeneratedCardType) AutoGeneratedCardType.A01.get(str);
        if (autoGeneratedCardType == null) {
            return AutoGeneratedCardType.A0J;
        }
        return autoGeneratedCardType;
    }
}
