package X;

/* renamed from: X.Rxx, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC62049Rxx {
    public static String A00(int i) {
        return i != 1 ? i != 8 ? i != 12 ? i != 4304 ? i != 4538 ? i != 5478 ? i != 14406 ? i != 15718 ? i != 16137 ? "UNDEFINED_QPL_EVENT" : "NATIVE_TEMPLATES_SCREENS_ITEM_DETAILS_SCREEN_TTRC" : "NATIVE_TEMPLATES_SCREENS_NT_WHATSAPP_AFTER_PARTY_TTRC" : "NATIVE_TEMPLATES_SCREENS_NT_SCREEN_MENU_TTRC" : "NATIVE_TEMPLATES_SCREENS_NT_SCREEN_VIC_TTRC" : "NATIVE_TEMPLATES_SCREENS_NT_SCREEN_CSIC_TTRC" : "NATIVE_TEMPLATES_SCREENS_FUNDRAISER_HUB_TTRC" : "NATIVE_TEMPLATES_SCREENS_NT_SCREEN_CORONAVIRUS_HUB_TTRC" : "NATIVE_TEMPLATES_SCREENS_NT_SCREEN_TTRC" : "NATIVE_TEMPLATES_SCREENS_NT_SCREEN_BIRTHDAY_CENTER_TTRC";
    }
}
