package X;

import android.animation.AnimatorSet;
import android.animation.ObjectAnimator;
import android.animation.ValueAnimator;
import android.content.Context;
import android.graphics.Path;
import android.graphics.PathMeasure;
import android.graphics.drawable.Drawable;
import android.util.Property;
import android.util.TypedValue;
import android.view.View;
import android.view.animation.PathInterpolator;
import android.widget.FrameLayout;
import android.widget.ImageView;
import java.util.List;

/* loaded from: classes5.dex */
public final class BZA extends FrameLayout {
    public boolean A00;
    public final AnimatorSet A01;
    public final PathMeasure A02;
    public final PathMeasure A03;
    public final PathMeasure A04;
    public final ImageView A05;
    public final ImageView A06;
    public final ImageView A07;
    public final Path A08;
    public final Path A09;
    public final Path A0A;
    public final Drawable A0B;
    public final Drawable A0C;
    public final Drawable A0D;
    public final PathInterpolator A0E;

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public BZA(Context context, Drawable drawable, Drawable drawable2, Drawable drawable3, int i, int i2) {
        super(context);
        AbstractC25233BEq.A0w(2, drawable, drawable2, drawable3);
        this.A0C = drawable;
        this.A0B = drawable2;
        this.A0D = drawable3;
        Context context2 = getContext();
        float f = i;
        int applyDimension = (int) TypedValue.applyDimension(1, f, AbstractC167007dF.A0K(context2));
        int applyDimension2 = (int) TypedValue.applyDimension(1, i2, AbstractC167007dF.A0K(context2));
        float f2 = f * 0.48f;
        this.A01 = new AnimatorSet();
        float A02 = AbstractC166987dD.A02(applyDimension);
        float f3 = (-A02) - f2;
        float f4 = A02 + f2;
        this.A0E = new PathInterpolator(0.0f, 0.0f, 0.55f, 1.0f);
        Path A0T = AbstractC166987dD.A0T();
        A0T.moveTo(0.0f, 0.0f);
        float f5 = f3 - 25.0f;
        A0T.cubicTo(f5, 20.0f, f5, 25.0f, f3, 0.0f);
        this.A08 = A0T;
        this.A02 = new PathMeasure(A0T, false);
        Path A0T2 = AbstractC166987dD.A0T();
        A0T2.moveTo(f3, 0.0f);
        A0T2.lineTo(f4, 0.0f);
        this.A09 = A0T2;
        this.A03 = new PathMeasure(A0T2, false);
        Path A0T3 = AbstractC166987dD.A0T();
        A0T3.moveTo(f4, 0.0f);
        float f6 = f4 + 25.0f;
        A0T3.cubicTo(f6, 20.0f, f6, 20.0f, 0.0f, 0.0f);
        this.A0A = A0T3;
        this.A04 = new PathMeasure(A0T3, false);
        ImageView imageView = new ImageView(context);
        this.A07 = imageView;
        imageView.setImageDrawable(drawable3);
        imageView.setLayoutParams(new FrameLayout.LayoutParams(applyDimension, applyDimension2, 17));
        imageView.setTranslationX(f3);
        imageView.setTranslationZ(-1.0f);
        imageView.setRotation(-20.0f);
        imageView.setScaleX(0.67f);
        imageView.setScaleY(0.67f);
        addView(imageView);
        ImageView imageView2 = new ImageView(context);
        this.A05 = imageView2;
        imageView2.setImageDrawable(drawable2);
        imageView2.setLayoutParams(new FrameLayout.LayoutParams(applyDimension, applyDimension2, 17));
        imageView2.setTranslationX(f4);
        imageView2.setTranslationZ(-1.0f);
        imageView2.setRotation(20.0f);
        imageView2.setScaleX(0.67f);
        imageView2.setScaleY(0.67f);
        addView(imageView2);
        ImageView imageView3 = new ImageView(context);
        this.A06 = imageView3;
        imageView3.setImageDrawable(drawable);
        imageView3.setLayoutParams(new FrameLayout.LayoutParams(applyDimension, applyDimension2, 17));
        addView(imageView3);
    }

    public static final List A00(ImageView imageView, BZA bza, int i) {
        int i2 = -i;
        int i3 = i2 % 3;
        long j = ((i3 + ((((i3 ^ 3) & ((-i3) | i3)) >> 31) & 3)) * 1600) + 1200;
        ValueAnimator ofFloat = ValueAnimator.ofFloat(0.0f, 1.0f);
        ofFloat.addUpdateListener(new C28524CiI(imageView, bza, new float[2], 4));
        PathInterpolator pathInterpolator = bza.A0E;
        ofFloat.setInterpolator(pathInterpolator);
        ofFloat.setDuration(400L);
        ofFloat.setStartDelay(j);
        ValueAnimator ofFloat2 = ValueAnimator.ofFloat(1.0f, 0.67f);
        ofFloat2.addUpdateListener(new BFF(imageView, 16));
        ofFloat2.setDuration(400L);
        ofFloat2.setStartDelay(j);
        ObjectAnimator ofFloat3 = ObjectAnimator.ofFloat(imageView, (Property<ImageView, Float>) View.ROTATION, 0.0f, -20.0f);
        ofFloat3.setDuration(400L);
        ofFloat3.setStartDelay(j);
        ofFloat3.setInterpolator(pathInterpolator);
        ObjectAnimator ofFloat4 = ObjectAnimator.ofFloat(imageView, (Property<ImageView, Float>) View.TRANSLATION_Z, 0.0f, -1.0f);
        ofFloat4.setDuration(10L);
        ofFloat4.setStartDelay(j);
        int i4 = (i2 + 1) % 3;
        long j2 = ((i4 + ((((i4 ^ 3) & ((-i4) | i4)) >> 31) & 3)) * 1600) + 1200;
        ValueAnimator ofFloat5 = ValueAnimator.ofFloat(0.0f, 1.0f);
        ofFloat5.addUpdateListener(new C28524CiI(imageView, bza, new float[2], 5));
        ofFloat5.setInterpolator(pathInterpolator);
        ofFloat5.setDuration(400L);
        ofFloat5.setStartDelay(j2);
        Property property = View.ROTATION;
        ObjectAnimator ofFloat6 = ObjectAnimator.ofFloat(imageView, (Property<ImageView, Float>) property, -20.0f, 20.0f);
        ofFloat6.setDuration(400L);
        ofFloat6.setStartDelay(j2);
        int i5 = (i2 + 2) % 3;
        long j3 = ((i5 + ((((i5 ^ 3) & ((-i5) | i5)) >> 31) & 3)) * 1600) + 1200;
        ValueAnimator ofFloat7 = ValueAnimator.ofFloat(0.0f, 1.0f);
        ofFloat7.addUpdateListener(new C28524CiI(imageView, bza, new float[2], 6));
        ofFloat7.setInterpolator(pathInterpolator);
        ofFloat7.setDuration(400L);
        ofFloat7.setStartDelay(j3);
        ObjectAnimator ofFloat8 = ObjectAnimator.ofFloat(imageView, (Property<ImageView, Float>) property, 20.0f, 0.0f);
        ofFloat8.setDuration(400L);
        ofFloat8.setStartDelay(j3);
        ofFloat8.setInterpolator(pathInterpolator);
        ValueAnimator ofFloat9 = ValueAnimator.ofFloat(0.67f, 1.0f);
        ofFloat9.addUpdateListener(new BFF(imageView, 17));
        ofFloat9.setDuration(400L);
        ofFloat9.setStartDelay(j3);
        ObjectAnimator ofFloat10 = ObjectAnimator.ofFloat(imageView, (Property<ImageView, Float>) View.TRANSLATION_Z, -1.0f, 0.0f);
        ofFloat10.setDuration(10L);
        ofFloat10.setStartDelay(j3);
        return AbstractC16960so.A1Q(ofFloat, ofFloat2, ofFloat3, ofFloat4, ofFloat5, ofFloat6, ofFloat7, ofFloat8, ofFloat9, ofFloat10);
    }
}
