package X;

/* renamed from: X.0CE, reason: invalid class name */
/* loaded from: classes.dex */
public abstract class C0CE extends AbstractC08740cc {
    public static final java.util.Set A00;
    public static final java.util.Set A01;
    public static final java.util.Set A04;
    public static final java.util.Set A05;
    public static final java.util.Set A06;
    public static final java.util.Set A07;
    public static final java.util.Set A03 = AnonymousClass090.A00(AbstractC009903n.A0K(new String[]{"com.facebook.mk", "com.oculus.horizon.dev", "com.oculus.panelapp.settings", "com.facebook.games", "com.facebook.home.dev", "com.facebook.bonfire", "com.facebook.workdev", "com.facebook.home", "com.facebook.phone", "com.facebook.stella_debug", "com.facebook.mlite", "com.facebook.akira", "com.facebook.appmanager.dev", "com.facebook.daykira", "com.facebook.wearable.monza", "com.instagram.direct", "com.facebook.wakizashi", "com.facebook.horizon", "com.facebook.react.panelapp", "com.facebook.together.together.stable", "com.facebook.together.together.release_nightly", "com.facebook.together.together.stable", "com.facebook.together.together.staging", "com.meta.mr.awe", "com.oculus.vrshell.home"}), AbstractC08740cc.A01);
    public static final java.util.Set A02 = AnonymousClass090.A00(AbstractC009903n.A0K(new String[]{"com.facebook.globalsecurity", "com.facebook.mlite_debug", "com.oculus.rooms", "com.facebook.horizon", "com.facebook.together.together.stable", "com.facebook.together.together.release_nightly", "com.facebook.together.together.stable", "com.facebook.together.together.staging"}), AbstractC08740cc.A00);

    static {
        String[] strArr = new String[54];
        System.arraycopy(new String[]{"com.facebook.adsmanager", "com.facebook.akira", "com.facebook.appmanager", "com.facebook.appmanager.dev", "com.facebook.arstudio.player", "com.facebook.assistantplayground", "com.facebook.bishop", "com.facebook.pages.app", "com.facebook.creatorstudio", "com.facebook.daykira", "com.instagram.direct", "com.facebook.lite", "com.facebook.games", "com.facebook.phone", "com.facebook.home", "com.facebook.home.dev", "com.instagram.android", "com.instagram.lite", "com.facebook.katana", "com.facebook.orca", "com.facebook.react.panelapp", "com.facebook.talk", "com.facebook.mk", "com.facebook.mlite", "com.facebook.wearable.monza", "com.oculus.assistant", "com.oculus.vrshell"}, 0, strArr, 0, 27);
        System.arraycopy(new String[]{"com.oculus.firsttimenux", "com.oculus.horizon", "com.oculus.horizon.dev", "com.oculus.gemini.upload", "com.oculus.metacam", "com.oculus.panelapp.settings", "com.oculus.vrshell.home", "com.oculus.ocms", "com.oculus.systemutilities", "com.oculus.twilight", "com.oculus.userserver2", "com.oculus.updater", "com.oculus.systemux", "com.oculus.xrstreamingclient", "com.facebook.bonfire", "com.facebook.stella", "com.facebook.stella_debug", "com.facebook.study", "com.instagram.barcelona", "com.facebook.wakizashi", "com.whatsapp", "com.whatsapp.w4b", "com.facebook.horizon", "com.facebook.together.together.stable", "com.facebook.together.together.release_nightly", "com.facebook.together.together.stable", "com.facebook.together.together.staging"}, 0, strArr, 27, 27);
        A01 = AbstractC009903n.A0K(strArr);
        String[] strArr2 = new String[63];
        System.arraycopy(new String[]{"com.facebook.adsmanager", "com.facebook.akira", "com.facebook.appmanager", "com.facebook.appmanager.dev", "com.facebook.arstudio.player", "com.facebook.assistantplayground", "com.instagram.barcelona", "com.facebook.bishop", "com.facebook.pages.app", "com.facebook.creatorstudio", "com.facebook.daykira", "com.instagram.direct", "com.facebook.lite", "com.facebook.games", "com.facebook.phone", "com.facebook.home", "com.facebook.home.dev", "com.instagram.android", "com.instagram.lite", "com.facebook.katana", "com.facebook.orca", "com.facebook.react.panelapp", "com.facebook.talk", "com.facebook.mk", "com.facebook.mlite", "com.facebook.wearable.system.data", "com.facebook.wearable.apps.mwear"}, 0, strArr2, 0, 27);
        System.arraycopy(new String[]{"com.facebook.wearable.system.notification", "com.facebook.wearable.monza", "com.oculus.assistant", "com.oculus.captionservice", "com.oculus.vrshell", "com.oculus.firsttimenux", "com.oculus.horizon", "com.oculus.horizon.dev", "com.oculus.gemini.upload", "com.oculus.metacam", "com.oculus.panelapp.settings", "com.oculus.vrshell.home", "com.oculus.ocms", "com.oculus.q4bservice", "com.oculus.systemutilities", "com.oculus.twilight", "com.oculus.userserver2", "com.oculus.updater", "com.oculus.systemux", "com.oculus.xrstreamingclient", "com.oculus.companion.server", "com.facebook.bonfire", "com.facebook.stella", "com.facebook.stella_debug", "com.facebook.study", "com.instagram.barcelona", "com.facebook.wakizashi"}, 0, strArr2, 27, 27);
        System.arraycopy(new String[]{"com.facebook.wearable.system.launcher", "com.whatsapp", "com.whatsapp.w4b", "com.facebook.horizon", "com.facebook.together.together.stable", "com.facebook.together.together.release_nightly", "com.facebook.together.together.stable", "com.facebook.together.together.staging", "com.facebook.react.panelapp"}, 0, strArr2, 54, 9);
        A00 = AbstractC009903n.A0K(strArr2);
        A07 = AbstractC009903n.A0K(new String[]{"com.facebook.work", "com.facebook.workdev", "com.facebook.workchat"});
        A04 = AbstractC009903n.A0K(new String[]{"com.instagram.direct", "com.instagram.android", "com.instagram.lite", "com.instagram.barcelona"});
        A06 = AbstractC009903n.A0K(new String[]{"com.whatsapp", "com.whatsapp.w4b"});
        A05 = AbstractC009903n.A0K(new String[]{"com.oculus.assistant", "com.oculus.browser", "com.oculus.captionservice", "com.oculus.companion.server", "com.oculus.explore", "com.oculus.firsttimenux", "com.oculus.vrshell.home", "com.oculus.horizon", "com.oculus.horizon.dev", "com.oculus.metacam", "com.oculus.nux.ota", "com.oculus.ocms", "com.oculus.panelapp.settings", "com.oculus.updater", "com.oculus.q4bservice", "com.oculus.store", "com.oculus.systemux", "com.oculus.xrstreamingclient", "com.oculus.systemutilities", "com.oculus.twilight", "com.oculus.userserver2"});
    }
}
