package X;

/* renamed from: X.5Hl, reason: invalid class name and case insensitive filesystem */
/* loaded from: classes3.dex */
public final class C114955Hl extends AbstractC53312cF {
    public final int A00;
    public final int A01;
    public final int A02;
    public final int A03;
    public final int A04;
    public final int A05;
    public final int A06;
    public final int A07;
    public final int A08;
    public final int A09;
    public final int A0A;
    public final int A0B;
    public final long A0C;
    public final long A0D;
    public final long A0E;
    public final long A0F;
    public final long A0G;
    public final long A0H;
    public final long A0I;
    public final long A0J;
    public final long A0K;
    public final long A0L;
    public final long A0M;
    public final long A0N;
    public final long A0O;
    public final long A0P;
    public final long A0Q;
    public final long A0R;
    public final long A0S;
    public final long A0T;
    public final EnumC92424Bx A0U;
    public final Long A0V;
    public final Long A0W;
    public final String A0X;
    public final String A0Y;
    public final String A0Z;
    public final String A0a;
    public final String A0b;
    public final String A0c;
    public final String A0d;
    public final String A0e;
    public final String A0f;
    public final String A0g;
    public final String A0h;
    public final String A0i;
    public final String A0j;
    public final String A0k;
    public final String A0l;
    public final String A0m;
    public final String A0n;
    public final String A0o;
    public final String A0p;
    public final String A0q;
    public final String A0r;
    public final boolean A0s;
    public final boolean A0t;
    public final boolean A0u;
    public final boolean A0v;
    public final boolean A0w;
    public final boolean A0x;
    public final boolean A0y;
    public final boolean A0z;
    public final boolean A10;
    public final boolean A11;
    public final boolean A12;
    public final boolean A13;
    public final boolean A14;
    public final boolean A15;

    public final String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(AnonymousClass001.A0Q("timeMs=", this.A0R));
        sb.append(AnonymousClass001.A0R(", videoId=", this.A0q));
        sb.append(AnonymousClass001.A0Q(", playerId=", this.A0K));
        sb.append(AnonymousClass001.A0R(", url=", this.A0o));
        sb.append(AnonymousClass001.A0R(", exception=", this.A0d));
        sb.append(AnonymousClass001.A1D(", isPrefetch=", this.A11));
        sb.append(AnonymousClass001.A0R(", prefetchSource=", this.A0m));
        sb.append(AnonymousClass001.A0Q(", queueDuration=", this.A0L));
        sb.append(AnonymousClass001.A0Q(", startDuration=", this.A0S));
        sb.append(AnonymousClass001.A0O(", seqNum=", this.A0B));
        sb.append(AnonymousClass001.A0R(", cacheType=", this.A0U.A01));
        sb.append(AnonymousClass001.A1D(", isFirstPlay=", this.A0w));
        sb.append(AnonymousClass001.A0R(", playOrigin=", this.A0j));
        sb.append(AnonymousClass001.A0Q(", startingByteOffset=", this.A0Q));
        sb.append(AnonymousClass001.A0Q(", requestedLength=", this.A0M));
        sb.append(AnonymousClass001.A0O(", streamType=", this.A0A));
        sb.append(AnonymousClass001.A0Q(", segmentStart=", this.A0N));
        sb.append(AnonymousClass001.A0O(", segmentDuration=", this.A09));
        sb.append(AnonymousClass001.A0R(", dataSourceFactory=", this.A0b));
        sb.append(AnonymousClass001.A0R(", qualityLabel=", this.A0n));
        sb.append(AnonymousClass001.A0R(", connQual=", this.A0Z));
        sb.append(AnonymousClass001.A0O(", networkPriority=", this.A07));
        sb.append(AnonymousClass001.A0O(", bufferedDurationMs=", this.A00));
        sb.append(AnonymousClass001.A0Q(", startVideoBandwidth=", this.A0O));
        sb.append(AnonymousClass001.A0Q(", startVideoTTFB=", this.A0P));
        sb.append(AnonymousClass001.A0R(", videoBandwidthEstimateStr=", this.A0p));
        sb.append(AnonymousClass001.A0Q(", upstreamTTFB=", this.A0T));
        sb.append(AnonymousClass001.A0R(", tigonSessionId=", null));
        sb.append(AnonymousClass001.A0R(", tigonTransactionId=", null));
        sb.append(AnonymousClass001.A0R(", appNetSesssionId=", this.A0X));
        sb.append(AnonymousClass001.A0Q(", manifestFirstSegmentStartTs=", this.A0G));
        sb.append(AnonymousClass001.A0Q(", manifestLastSegmentEndTs=", this.A0H));
        sb.append(AnonymousClass001.A0Q(", manifestNumSegments=", this.A0I));
        sb.append(AnonymousClass001.A0O(", bufferedDurationMsAtDataSpecCreation=", this.A01));
        sb.append(AnonymousClass001.A0Q(", dataSpecCreationTimeMs=", this.A0F));
        sb.append(AnonymousClass001.A0R(", playSubOrigin=", this.A0k));
        sb.append(AnonymousClass001.A1D(", isFBMS=", this.A0u));
        sb.append(AnonymousClass001.A1D(", isFbPredictiveDASH=", this.A0v));
        sb.append(AnonymousClass001.A1D(", isSkipAheadChunk=", this.A12));
        sb.append(AnonymousClass001.A1D(", inRewoundState=", this.A0s));
        sb.append(AnonymousClass001.A1D(", isManifestDynamic=", this.A0z));
        sb.append(AnonymousClass001.A1D(", isChunkedTransfer=", this.A0t));
        sb.append(AnonymousClass001.A1D(", isPredictedURL=", this.A10));
        sb.append(AnonymousClass001.A0O(", expectedPredictedNumber=", this.A03));
        sb.append(AnonymousClass001.A0O(", predictedNumberMapping=", this.A08));
        sb.append(AnonymousClass001.A0Q(", numSegmentsToEndOfManifest= ", this.A0J));
        sb.append(AnonymousClass001.A0R(", edgeHit= ", this.A0c));
        sb.append(AnonymousClass001.A0R(", originHit= ", this.A0i));
        sb.append(AnonymousClass001.A0R(", codec= ", this.A0Y));
        sb.append(AnonymousClass001.A0Q(", cdnResponseTime= ", this.A0D));
        sb.append(AnonymousClass001.A0R(", contentType= ", this.A0a));
        sb.append(AnonymousClass001.A0O(", latestSegmentId= ", this.A05));
        sb.append(AnonymousClass001.A0Q(", confidenceBasedBitrateEstimate=", this.A0E));
        sb.append(AnonymousClass001.A0O(", confidencePctForBitrateEstimate=", this.A02));
        sb.append(AnonymousClass001.A0O(", minimumLoadPositionMs=", this.A06));
        sb.append(AnonymousClass001.A0R(", oneReqWave=", this.A0f));
        sb.append(AnonymousClass001.A0R(", oneResWave=", this.A0g));
        sb.append(AnonymousClass001.A0R(", oneObserved=", this.A0e));
        sb.append(AnonymousClass001.A0R(", oneVariant=", this.A0h));
        sb.append(AnonymousClass001.A0R(", playerType=", this.A0l));
        sb.append(AnonymousClass001.A0O(", positionInUnit=", -1));
        sb.append(AnonymousClass001.A0R(", vpSessionId=", this.A0r));
        sb.append(AnonymousClass001.A0O(", firstChunkSize=", this.A04));
        StringBuilder sb2 = new StringBuilder();
        sb2.append(", clientWallClockOffsetMs=");
        sb2.append(this.A0V);
        sb.append(sb2.toString());
        StringBuilder sb3 = new StringBuilder();
        sb3.append(", contentLength=");
        sb3.append(this.A0W);
        sb.append(sb3.toString());
        return sb.toString();
    }

    public C114955Hl(EnumC92424Bx enumC92424Bx, Long l, Long l2, String str, String str2, String str3, String str4, String str5, String str6, String str7, String str8, String str9, String str10, String str11, String str12, String str13, String str14, String str15, String str16, String str17, String str18, String str19, String str20, String str21, int i, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10, int i11, int i12, long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12, boolean z13, boolean z14) {
        super(EnumC53322cG.A0I);
        this.A0R = j;
        this.A0q = str;
        this.A0K = j2;
        this.A0o = str2;
        this.A0d = str3;
        this.A11 = z;
        this.A0m = str4;
        this.A0L = j3;
        this.A0S = j4;
        this.A0B = i;
        this.A0U = enumC92424Bx;
        this.A0w = z2;
        this.A0x = z3;
        this.A0j = str5;
        this.A0k = str11;
        this.A0Q = j5;
        this.A0M = j6;
        this.A0A = i2;
        this.A0N = j7;
        this.A09 = i3;
        this.A0b = str6;
        this.A0n = str7;
        this.A0Z = str8;
        this.A07 = i4;
        this.A0C = j8;
        this.A0y = z4;
        this.A00 = i5;
        this.A0O = j9;
        this.A0P = j10;
        this.A13 = z5;
        this.A14 = z6;
        this.A15 = z7;
        this.A0p = str9;
        this.A0T = j11;
        this.A0X = str10;
        this.A0G = j12;
        this.A0H = j13;
        this.A0I = j14;
        this.A01 = i6;
        this.A0F = j15;
        this.A0u = z8;
        this.A0v = z9;
        this.A12 = z10;
        this.A0s = z11;
        this.A0z = z12;
        this.A0t = z13;
        this.A10 = z14;
        this.A03 = i8;
        this.A08 = i7;
        this.A0J = j16;
        this.A0c = str12;
        this.A0i = str13;
        this.A0Y = str14;
        this.A0D = j17;
        this.A0a = str15;
        this.A05 = i9;
        this.A0E = j18;
        this.A02 = i10;
        this.A06 = i11;
        this.A0f = str16;
        this.A0g = str17;
        this.A0e = str18;
        this.A0h = str19;
        this.A0l = str20;
        this.A0r = str21;
        this.A04 = i12;
        this.A0V = l;
        this.A0W = l2;
    }
}
