package X;

import com.instagram.model.reels.sponsored.AutoGeneratedCardType;
import java.util.Locale;

/* renamed from: X.6Oy, reason: invalid class name and case insensitive filesystem */
/* loaded from: classes3.dex */
public final class C138426Oy extends C0YY implements InterfaceC16660sJ {
    public static final C138426Oy A00 = new C138426Oy();

    public C138426Oy() {
        super(1);
    }

    @Override // X.InterfaceC16660sJ
    public final /* bridge */ /* synthetic */ Object invoke(Object obj) {
        AutoGeneratedCardType autoGeneratedCardType = (AutoGeneratedCardType) obj;
        C14360o3.A0B(autoGeneratedCardType, 0);
        String lowerCase = autoGeneratedCardType.A00.toLowerCase(Locale.ROOT);
        C14360o3.A07(lowerCase);
        return lowerCase;
    }
}
