package X;

import com.instagram.common.typedurl.ImageUrl;
import java.util.List;

/* renamed from: X.7nE, reason: invalid class name and case insensitive filesystem */
/* loaded from: classes4.dex */
public final class C173007nE {
    public boolean A00;
    public final int A01;
    public final int A02;
    public final int A03;
    public final long A04;
    public final long A05;
    public final long A06;
    public final ImageUrl A07;
    public final ImageUrl A08;
    public final ImageUrl A09;
    public final ImageUrl A0A;
    public final String A0B;
    public final String A0C;
    public final String A0D;
    public final String A0E;
    public final String A0F;
    public final String A0G;
    public final String A0H;
    public final String A0I;
    public final String A0J;
    public final String A0K;
    public final String A0L;
    public final String A0M;
    public final String A0N;
    public final String A0O;
    public final String A0P;
    public final String A0Q;
    public final String A0R;
    public final String A0S;
    public final String A0T;
    public final String A0U;
    public final String A0V;
    public final List A0W;
    public final List A0X;
    public final List A0Y;
    public final List A0Z;
    public final List A0a;
    public final List A0b;
    public final java.util.Set A0c;
    public final java.util.Set A0d;
    public final boolean A0e;
    public final boolean A0f;
    public final boolean A0g;
    public final boolean A0h;
    public final boolean A0i;
    public final boolean A0j;
    public final boolean A0k;
    public final boolean A0l;

    public C173007nE(ImageUrl imageUrl, ImageUrl imageUrl2, ImageUrl imageUrl3, ImageUrl imageUrl4, String str, String str2, String str3, String str4, String str5, String str6, String str7, String str8, String str9, String str10, String str11, String str12, String str13, String str14, String str15, String str16, String str17, String str18, String str19, String str20, String str21, List list, List list2, List list3, List list4, List list5, List list6, java.util.Set set, java.util.Set set2, int i, int i2, int i3, long j, long j2, long j3, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9) {
        C14360o3.A0B(str, 1);
        C14360o3.A0B(str3, 3);
        C14360o3.A0B(str5, 10);
        C14360o3.A0B(str6, 11);
        C14360o3.A0B(str7, 12);
        C14360o3.A0B(imageUrl, 16);
        C14360o3.A0B(list, 18);
        C14360o3.A0B(set, 19);
        C14360o3.A0B(set2, 21);
        C14360o3.A0B(str9, 22);
        C14360o3.A0B(list3, 28);
        C14360o3.A0B(list4, 29);
        this.A0L = str;
        this.A0N = str2;
        this.A0K = str3;
        this.A0g = z;
        this.A0j = z2;
        this.A00 = z3;
        this.A0l = z4;
        this.A0e = z5;
        this.A0H = str4;
        this.A0I = str5;
        this.A0U = str6;
        this.A0B = str7;
        this.A04 = j;
        this.A06 = j2;
        this.A0R = str8;
        this.A09 = imageUrl;
        this.A0A = imageUrl2;
        this.A0a = list;
        this.A0d = set;
        this.A0i = z6;
        this.A0c = set2;
        this.A0V = str9;
        this.A01 = i;
        this.A0C = str10;
        this.A0D = str11;
        this.A07 = imageUrl3;
        this.A0W = list2;
        this.A0Y = list3;
        this.A0Z = list4;
        this.A03 = i2;
        this.A0M = str12;
        this.A08 = imageUrl4;
        this.A0X = list5;
        this.A0k = z7;
        this.A02 = i3;
        this.A0f = z8;
        this.A0J = str13;
        this.A0h = z9;
        this.A05 = j3;
        this.A0T = str14;
        this.A0b = list6;
        this.A0O = str15;
        this.A0P = str16;
        this.A0Q = str17;
        this.A0E = str18;
        this.A0S = str19;
        this.A0G = str20;
        this.A0F = str21;
    }
}
