package X;

import com.instagram.api.schemas.AudioFilterInfoIntf;
import com.instagram.api.schemas.AudioMutingInfo;
import com.instagram.api.schemas.AudioMutingInfoIntf;
import com.instagram.api.schemas.MusicMuteAudioReason;
import com.instagram.api.schemas.MusicProduct;
import com.instagram.common.typedurl.ImageUrl;
import com.instagram.music.common.model.MusicOverlayStickerModel;
import com.instagram.music.common.model.MusicOverlayStickerModelIntf;
import com.instagram.user.model.User;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/* renamed from: X.ABz, reason: case insensitive filesystem */
/* loaded from: classes4.dex */
public final class C23000ABz {
    public AudioMutingInfoIntf A00;
    public MusicMuteAudioReason A01;
    public MusicProduct A02;
    public ImageUrl A03;
    public ImageUrl A04;
    public User A05;
    public Boolean A06;
    public Boolean A07;
    public Boolean A08;
    public Boolean A09;
    public Boolean A0A;
    public Boolean A0B;
    public Boolean A0C;
    public Boolean A0D;
    public Boolean A0E;
    public Boolean A0F;
    public Boolean A0G;
    public Boolean A0H;
    public Boolean A0I;
    public Boolean A0J;
    public Integer A0K;
    public Integer A0L;
    public Integer A0M;
    public Integer A0N;
    public Integer A0O;
    public Integer A0P;
    public String A0Q;
    public String A0R;
    public String A0S;
    public String A0T;
    public String A0U;
    public String A0V;
    public String A0W;
    public String A0X;
    public String A0Y;
    public String A0Z;
    public String A0a;
    public String A0b;
    public String A0c;
    public String A0d;
    public String A0e;
    public String A0f;
    public String A0g;
    public String A0h;
    public String A0i;
    public String A0j;
    public String A0k;
    public String A0l;
    public String A0m;
    public String A0n;
    public List A0o;
    public List A0p;
    public List A0q;
    public boolean A0r;
    public boolean A0s;
    public boolean A0t;
    public final MusicOverlayStickerModelIntf A0u;

    public final MusicOverlayStickerModel A00() {
        ArrayList arrayList = null;
        new C1DY((C1DV) new C37761pD(null), 6, false);
        String str = this.A0Q;
        Boolean bool = this.A06;
        boolean z = this.A0r;
        String str2 = this.A0R;
        String str3 = this.A0S;
        Integer num = this.A0K;
        Integer num2 = this.A0L;
        String str4 = this.A0T;
        List list = this.A0o;
        if (list != null) {
            arrayList = AbstractC167017dG.A0q(list);
            Iterator it = list.iterator();
            while (it.hasNext()) {
                arrayList.add(((AudioFilterInfoIntf) it.next()).Er1());
            }
        }
        AudioMutingInfoIntf audioMutingInfoIntf = this.A00;
        AudioMutingInfo Er4 = audioMutingInfoIntf != null ? audioMutingInfoIntf.Er4() : null;
        String str5 = this.A0U;
        Boolean bool2 = this.A07;
        ImageUrl imageUrl = this.A03;
        ImageUrl imageUrl2 = this.A04;
        String str6 = this.A0V;
        String str7 = this.A0W;
        String str8 = this.A0X;
        Integer num3 = this.A0M;
        String str9 = this.A0Y;
        List list2 = this.A0p;
        Integer num4 = this.A0N;
        String str10 = this.A0Z;
        String str11 = this.A0a;
        Boolean bool3 = this.A08;
        Boolean bool4 = this.A09;
        List list3 = this.A0q;
        String str12 = this.A0b;
        User user = this.A05;
        String str13 = this.A0c;
        Boolean bool5 = this.A0A;
        Boolean bool6 = this.A0B;
        Boolean bool7 = this.A0C;
        boolean z2 = this.A0s;
        Boolean bool8 = this.A0D;
        Boolean bool9 = this.A0E;
        Boolean bool10 = this.A0F;
        String str14 = this.A0d;
        MusicProduct musicProduct = this.A02;
        String str15 = this.A0e;
        Integer num5 = this.A0O;
        Boolean bool11 = this.A0G;
        String str16 = this.A0f;
        String str17 = this.A0g;
        String str18 = this.A0h;
        String str19 = this.A0i;
        Boolean bool12 = this.A0H;
        boolean z3 = this.A0t;
        return new MusicOverlayStickerModel(Er4, this.A01, musicProduct, imageUrl, imageUrl2, user, bool, bool2, bool3, bool4, bool5, bool6, bool7, bool8, bool9, bool10, bool11, bool12, this.A0I, this.A0J, num, num2, num3, num4, num5, this.A0P, str, str2, str3, str4, str5, str6, str7, str8, str9, str10, str11, str12, str13, str14, str15, str16, str17, str18, str19, this.A0j, this.A0k, this.A0l, this.A0m, this.A0n, arrayList, list2, list3, z, z2, z3);
    }

    public C23000ABz(MusicOverlayStickerModel musicOverlayStickerModel) {
        this.A0u = musicOverlayStickerModel;
        this.A0Q = musicOverlayStickerModel.Aal();
        this.A06 = musicOverlayStickerModel.AbG();
        this.A0r = musicOverlayStickerModel.getAllowsSaving();
        this.A0R = musicOverlayStickerModel.getArtistId();
        this.A0S = musicOverlayStickerModel.getAudioAssetId();
        this.A0K = musicOverlayStickerModel.Adg();
        this.A0L = musicOverlayStickerModel.Adh();
        this.A0T = musicOverlayStickerModel.getAudioClusterId();
        this.A0o = musicOverlayStickerModel.Ado();
        this.A00 = musicOverlayStickerModel.Adu();
        this.A0U = musicOverlayStickerModel.AiR();
        this.A07 = musicOverlayStickerModel.Aql();
        this.A03 = musicOverlayStickerModel.AsE();
        this.A04 = musicOverlayStickerModel.AsF();
        this.A0V = musicOverlayStickerModel.AvV();
        this.A0W = musicOverlayStickerModel.getDashManifest();
        this.A0X = musicOverlayStickerModel.getDerivedContentId();
        this.A0M = musicOverlayStickerModel.Awp();
        this.A0Y = musicOverlayStickerModel.getDisplayArtist();
        this.A0p = musicOverlayStickerModel.AyW();
        this.A0N = musicOverlayStickerModel.Azi();
        this.A0Z = musicOverlayStickerModel.getFastStartProgressiveDownloadUrl();
        this.A0a = musicOverlayStickerModel.getFormattedClipsMediaCount();
        this.A08 = musicOverlayStickerModel.BC4();
        this.A09 = musicOverlayStickerModel.BDn();
        this.A0q = musicOverlayStickerModel.BE6();
        this.A0b = musicOverlayStickerModel.getId();
        this.A05 = musicOverlayStickerModel.BFU();
        this.A0c = musicOverlayStickerModel.getIgUsername();
        this.A0A = musicOverlayStickerModel.CQj();
        this.A0B = musicOverlayStickerModel.CT1();
        this.A0C = musicOverlayStickerModel.CTb();
        this.A0s = musicOverlayStickerModel.isExplicit();
        this.A0D = musicOverlayStickerModel.CXk();
        this.A0E = musicOverlayStickerModel.CZu();
        this.A0F = musicOverlayStickerModel.Cer();
        this.A0d = musicOverlayStickerModel.BOF();
        this.A02 = musicOverlayStickerModel.BVj();
        this.A0e = musicOverlayStickerModel.getOriginalMediaId();
        this.A0O = musicOverlayStickerModel.BaR();
        this.A0G = musicOverlayStickerModel.Bd5();
        this.A0f = musicOverlayStickerModel.getPlaceholderProfilePicUrl();
        this.A0g = musicOverlayStickerModel.getProgressiveDownloadUrl();
        this.A0h = musicOverlayStickerModel.Bkl();
        this.A0i = musicOverlayStickerModel.BqC();
        this.A0H = musicOverlayStickerModel.Buu();
        this.A0t = musicOverlayStickerModel.getShouldMuteAudio();
        this.A0j = musicOverlayStickerModel.getShouldMuteAudioReason();
        this.A01 = musicOverlayStickerModel.BvC();
        this.A0I = musicOverlayStickerModel.BvQ();
        this.A0J = musicOverlayStickerModel.Bvn();
        this.A0k = musicOverlayStickerModel.getSubtitle();
        this.A0l = musicOverlayStickerModel.getTag();
        this.A0m = musicOverlayStickerModel.getTitle();
        this.A0P = musicOverlayStickerModel.CAx();
        this.A0n = musicOverlayStickerModel.CHM();
    }
}
