package X;

import android.content.Context;
import com.facebook.proxygen.TraceFieldType;
import com.instagram.api.schemas.IntentAwareAdsInfoIntf;
import com.instagram.common.session.UserSession;
import com.instagram.model.effect.AttributedAREffect;
import com.instagram.model.reels.Reel;
import com.instagram.model.reels.sponsored.AutoGeneratedCardType;
import java.util.Collections;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import kotlin.Deprecated;

/* renamed from: X.3R6, reason: invalid class name */
/* loaded from: classes2.dex */
public final class C3R6 {
    public static final C3R6 A00 = new Object();

    public static final C41181vS A00(UserSession userSession, C1NI c1ni) {
        C14360o3.A0B(userSession, 1);
        if (c1ni instanceof Reel) {
            Reel reel = (Reel) c1ni;
            C14360o3.A07(reel.A0O(userSession));
            if (!r0.isEmpty()) {
                return reel.A0A(userSession, 0);
            }
            return null;
        }
        if (c1ni instanceof C41181vS) {
            return (C41181vS) c1ni;
        }
        return null;
    }

    public static final LinkedHashMap A02(List list) {
        if (list != null) {
            LinkedHashMap linkedHashMap = new LinkedHashMap();
            Iterator it = list.iterator();
            while (it.hasNext()) {
                C84823qW c84823qW = (C84823qW) it.next();
                if (c84823qW.A12.ordinal() == 29) {
                    C101394gx A0D = c84823qW.A0D();
                    if (A0D != null) {
                        String A002 = AbstractC37865GlK.A00(A0D);
                        if ("poll".length() != 0 && A002 != null) {
                            linkedHashMap.put("poll", A002);
                        }
                    } else {
                        throw new IllegalStateException("Required value was null.");
                    }
                }
            }
            if (!linkedHashMap.isEmpty()) {
                return linkedHashMap;
            }
        }
        return null;
    }

    public static final void A03(Context context, InterfaceC82723ma interfaceC82723ma) {
        C14360o3.A0B(context, 1);
        float A01 = AbstractC13880nE.A01(context, AbstractC13880nE.A0A(context));
        float A012 = AbstractC13880nE.A01(context, AbstractC13880nE.A09(context));
        float f = AbstractC13880nE.A0I(context).density;
        interfaceC82723ma.Ed9(A01, A012, AbstractC13880nE.A07(context) / f, AbstractC13880nE.A06(context) / f, f);
    }

    public static final void A05(InterfaceC11380iw interfaceC11380iw, UserSession userSession, Long l, String str, String str2, String str3, String str4) {
        C14360o3.A0B(userSession, 0);
        C14360o3.A0B(str, 1);
        AbstractC40751I4f.A00(interfaceC11380iw, AbstractC12220kQ.A01(interfaceC11380iw, userSession), userSession, l, str, str2, str3, str4);
    }

    public static final void A04(IntentAwareAdsInfoIntf intentAwareAdsInfoIntf, C82713mZ c82713mZ) {
        if (intentAwareAdsInfoIntf != null) {
            c82713mZ.A1h = true;
            if (intentAwareAdsInfoIntf.BVJ() != null) {
                c82713mZ.A3s = Long.valueOf(r0.intValue());
            }
            String Brx = intentAwareAdsInfoIntf.Brx();
            if (Brx != null) {
                c82713mZ.A5g = Brx;
            }
            String BVL = intentAwareAdsInfoIntf.BVL();
            if (BVL != null) {
                c82713mZ.A69 = BVL;
                c82713mZ.A6B = BVL;
                c82713mZ.A69 = BVL;
                c82713mZ.A6B = BVL;
            }
            String CB4 = intentAwareAdsInfoIntf.CB4();
            if (CB4 != null) {
                c82713mZ.A5q = CB4;
            }
            if (intentAwareAdsInfoIntf.CcZ() != null) {
                c82713mZ.A1x = intentAwareAdsInfoIntf.CcZ();
            }
            if (intentAwareAdsInfoIntf.BIG() != null) {
                c82713mZ.A6A = intentAwareAdsInfoIntf.BIG();
            }
        }
    }

    /* JADX WARN: Failed to find 'out' block for switch in B:4:0x0014. Please report as an issue. */
    /* JADX WARN: Removed duplicated region for block: B:19:0x00aa  */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
        To view partially-correct add '--show-bad-code' argument
    */
    public static final void A06(X.C82713mZ r2, com.instagram.model.reels.Reel r3) {
        /*
            Method dump skipped, instructions count: 252
            To view this dump add '--comments-level debug' option
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C3R6.A06(X.3mZ, com.instagram.model.reels.Reel):void");
    }

    public static final void A07(C82713mZ c82713mZ, C41181vS c41181vS, C41551w4 c41551w4, C146306iT c146306iT, C141596ac c141596ac, int i, boolean z) {
        List list;
        String str;
        InterfaceC107774tM BEB;
        List AZh;
        InterfaceC107754tK interfaceC107754tK;
        A09(c82713mZ, new C37948Gmq(c146306iT.A01, c41551w4.A0H, c41181vS, c41551w4, c141596ac, i, z));
        c82713mZ.A6n = c146306iT.A08;
        c82713mZ.A7X = c146306iT.A06.getSessionId();
        c82713mZ.A79 = c146306iT.A07;
        c82713mZ.A2w = Integer.valueOf(AbstractC19730y1.A00(AbstractC12960li.A00).A00());
        c82713mZ.A30 = Integer.valueOf(C1H6.A03() ? 1 : 0);
        c82713mZ.A71 = c146306iT.A00;
        List unmodifiableList = Collections.unmodifiableList(c141596ac.A1D);
        if (unmodifiableList != null) {
            list = AbstractC001800i.A0a(unmodifiableList);
        } else {
            list = null;
        }
        c82713mZ.A7r = list;
        C38321qM c38321qM = c41181vS.A0b;
        if (c38321qM != null && (BEB = c38321qM.A0C.BEB()) != null && (AZh = BEB.AZh()) != null && (interfaceC107754tK = (InterfaceC107754tK) AbstractC001800i.A0O(AZh, 0)) != null) {
            str = interfaceC107754tK.BlW();
        } else {
            str = null;
        }
        c82713mZ.A5c = str;
    }

    public static final void A08(C82713mZ c82713mZ, C41181vS c41181vS, C149716oO c149716oO, C146306iT c146306iT) {
        A07(c82713mZ, c41181vS, c149716oO.A00, c146306iT, c149716oO.A02, c149716oO.A01.A00(c41181vS), c149716oO.A03);
    }

    public static final void A09(C82713mZ c82713mZ, C37948Gmq c37948Gmq) {
        int i;
        Map map;
        int i2;
        C84823qW c84823qW;
        String str;
        String str2;
        Reel reel = c37948Gmq.A02;
        String id = reel.getId();
        C14360o3.A07(id);
        c82713mZ.A6j = id;
        c82713mZ.A4H = Long.valueOf(c37948Gmq.A00);
        UserSession userSession = c37948Gmq.A01;
        c82713mZ.A4B = Long.valueOf(reel.A0O(userSession).size());
        C41551w4 c41551w4 = c37948Gmq.A04;
        if (c41551w4.A0L) {
            i = 0;
        } else {
            i = c41551w4.A00;
        }
        c82713mZ.A4C = Long.valueOf(i);
        c82713mZ.A4A = Long.valueOf(c37948Gmq.A00());
        c82713mZ.A6o = reel.A0H(userSession);
        C141596ac c141596ac = c37948Gmq.A05;
        c82713mZ.A4E = Long.valueOf(c141596ac.A0I);
        C41181vS c41181vS = c37948Gmq.A03;
        LinkedHashMap A02 = A02(c41181vS.A0c());
        if (A02 != null) {
            map = Collections.unmodifiableMap(A02);
        } else {
            map = null;
        }
        c82713mZ.A8G = map;
        if (reel.A17(userSession)) {
            i2 = reel.A00;
        } else {
            i2 = -1;
        }
        c82713mZ.A3T = Long.valueOf(i2);
        c82713mZ.A26 = Boolean.valueOf(c37948Gmq.A07);
        c82713mZ.A1c = Boolean.valueOf(AbstractC130925vf.A0k(c41181vS, c41551w4));
        EnumC75383a5 enumC75383a5 = EnumC75383a5.A19;
        c82713mZ.A1A = Boolean.valueOf(c41181vS.A1v(enumC75383a5));
        if (reel.A0g != null) {
            c82713mZ.A3a = Long.valueOf(r0.intValue());
        }
        AttributedAREffect attributedAREffect = reel.A0G;
        if (attributedAREffect != null && (str2 = attributedAREffect.A09) != null) {
            try {
                c82713mZ.A3b = AbstractC003100w.A0k(10, str2);
            } catch (NumberFormatException unused) {
                C0w9.A03("ReelLoggerUtil", "Unable to convert invalid effect id into Long");
            }
        }
        Reel reel2 = c41551w4.A0H;
        List list = reel2.A0w;
        if (list != null) {
            int A002 = c37948Gmq.A00();
            if (!list.isEmpty()) {
                c82713mZ.A7u = list;
            }
            c82713mZ.A4B = Long.valueOf(AbstractC130925vf.A03(list));
            c82713mZ.A4A = Long.valueOf(AbstractC130925vf.A04(list, A002));
            c82713mZ.A4G = Long.valueOf(A002);
            if (A002 == 1 && list.get(A002) == AutoGeneratedCardType.A0B) {
                c82713mZ.A0j = reel2.A06();
            }
        }
        c82713mZ.A2Z = Double.valueOf((c141596ac.A0A * c141596ac.A0B) / 1000.0d);
        boolean CdW = c41181vS.CdW();
        Long valueOf = Long.valueOf(c41551w4.A0E);
        if (CdW) {
            c82713mZ.A3N = valueOf;
        } else {
            c82713mZ.A4M = valueOf;
        }
        List BlY = c41181vS.BlY(enumC75383a5);
        if (BlY != null && (c84823qW = (C84823qW) AbstractC001800i.A0J(BlY)) != null && (str = c84823qW.A1d) != null) {
            c82713mZ.A6u = str;
        }
        A04(reel.A0B, c82713mZ);
        if (AbstractC130925vf.A0n(c41551w4)) {
            c82713mZ.A3u = Long.valueOf(reel.A0O(userSession).size());
            c82713mZ.A43 = Long.valueOf(c37948Gmq.A00());
        }
    }

    public final void A0B(Context context, C82713mZ c82713mZ, C41181vS c41181vS, C6YY c6yy, C149716oO c149716oO, C146306iT c146306iT) {
        UserSession userSession = c146306iT.A01;
        C41551w4 c41551w4 = c149716oO.A00;
        A0A(context, userSession, c82713mZ, c41181vS, c146306iT.A03, new C37948Gmq(userSession, c41551w4.A0H, c41181vS, c41551w4, c149716oO.A02, c149716oO.A01.A00(c41181vS), c149716oO.A03), c6yy);
    }

    public final void A0C(InterfaceC11380iw interfaceC11380iw, UserSession userSession, C70873Fz c70873Fz, C61252qn c61252qn, Double d, Integer num, Integer num2, String str, String str2, long j, boolean z, boolean z2) {
        long j2;
        String str3;
        int i;
        Long l;
        String str4 = str2;
        C14360o3.A0B(userSession, 0);
        C14360o3.A0B(interfaceC11380iw, 1);
        C18920wW A01 = AbstractC12220kQ.A01(interfaceC11380iw, userSession);
        InterfaceC02590Ai A002 = A01.A00(A01.A00, "reel_tray_refresh");
        if (A002.isSampled()) {
            C3G0 c3g0 = c70873Fz.A01;
            if (c3g0.A01.A02 != 0) {
                j2 = 1;
            } else {
                j2 = 0;
            }
            A002.A9K("has_my_reel", Long.valueOf(j2));
            if (str != null) {
                A002.AAP("tray_session_id", str);
                A002.A9K("new_reel_count", Long.valueOf(r3.A01));
                A002.A9K("viewed_reel_count", Long.valueOf(r3.A03));
                A002.A8I("tray_refresh_time", Double.valueOf(j / 1000.0d));
                if (z) {
                    str3 = "disk";
                } else {
                    str3 = "network";
                }
                A002.AAP("tray_refresh_type", str3);
                A002.A7v("was_successful", Boolean.valueOf(z2));
                C3G1 c3g1 = c3g0.A00;
                A002.A9K("live_reel_count", Long.valueOf(c3g1.A01));
                A002.A9K("muted_reel_count", Long.valueOf(r3.A00));
                A002.A9K("muted_live_reel_count", Long.valueOf(c3g1.A00));
                if (c61252qn != null) {
                    i = c61252qn.A0R.size();
                } else {
                    i = 0;
                }
                A002.A9K("unfetched_reel_count", Long.valueOf(i));
                if (str2 == null) {
                    str4 = "";
                }
                A002.AAP("story_ranking_token", str4);
                A002.AAP("tray_refresh_reason", AbstractC25631Mt.A00(num));
                if (num2 != null) {
                    l = Long.valueOf(num2.intValue());
                } else {
                    l = null;
                }
                A002.A9K(TraceFieldType.StatusCode, l);
                A002.A8I("num_of_pogs_visible", d);
                A002.Cht();
                return;
            }
            throw new IllegalStateException("Required value was null.");
        }
    }

    @Deprecated(message = "Viewed Impression logging in ReelViewerLogger is being deprecated. ")
    public final void A0D(C82713mZ c82713mZ, C37948Gmq c37948Gmq) {
        if (c37948Gmq != null) {
            C141596ac c141596ac = c37948Gmq.A05;
            float f = c141596ac.A0A;
            float f2 = c141596ac.A0B;
            c82713mZ.A2T = Double.valueOf((f * f2) / 1000.0d);
            float f3 = 1.0f - f2;
            float f4 = 0.0f;
            if (0.0f < f3) {
                f4 = f3;
            }
            c82713mZ.A2U = Double.valueOf((f * f4) / 1000.0d);
            c82713mZ.A2P = Double.valueOf(c141596ac.A00);
            c82713mZ.A2R = Double.valueOf(c141596ac.A03);
            c82713mZ.A2Q = Double.valueOf(c141596ac.A01);
        }
    }

    /* JADX WARN: Code restructure failed: missing block: B:134:0x027c, code lost:
    
        if (r7.A0C.C16() == null) goto L112;
     */
    /* JADX WARN: Code restructure failed: missing block: B:150:0x02ce, code lost:
    
        if (r1 == null) goto L129;
     */
    /* JADX WARN: Code restructure failed: missing block: B:181:0x035b, code lost:
    
        if (r3.A16() != false) goto L161;
     */
    /* JADX WARN: Code restructure failed: missing block: B:199:0x03ad, code lost:
    
        if (X.AbstractC130925vf.A0P(r11, r2, r14) != false) goto L180;
     */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
        To view partially-correct add '--show-bad-code' argument
    */
    public final void A0A(android.content.Context r10, com.instagram.common.session.UserSession r11, X.C82713mZ r12, X.C1NI r13, X.C3G2 r14, X.C37948Gmq r15, X.C6YY r16) {
        /*
            Method dump skipped, instructions count: 1267
            To view this dump add '--comments-level debug' option
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C3R6.A0A(android.content.Context, com.instagram.common.session.UserSession, X.3mZ, X.1NI, X.3G2, X.Gmq, X.6YY):void");
    }

    /* JADX WARN: Code restructure failed: missing block: B:16:0x00d4, code lost:
    
        if (r12 > r2) goto L18;
     */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
        To view partially-correct add '--show-bad-code' argument
    */
    public static final java.lang.String A01(com.instagram.common.session.UserSession r19, X.AnonymousClass318 r20, X.InterfaceC60442pS r21, X.C41551w4 r22, X.C1PZ r23, java.lang.Integer r24, java.lang.Integer r25, java.lang.Integer r26, java.lang.String r27, java.lang.String r28, java.lang.String r29, java.util.List r30, int r31, int r32, boolean r33, boolean r34) {
        /*
            Method dump skipped, instructions count: 563
            To view this dump add '--comments-level debug' option
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C3R6.A01(com.instagram.common.session.UserSession, X.318, X.2pS, X.1w4, X.1PZ, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.util.List, int, int, boolean, boolean):java.lang.String");
    }
}
