package X;

import android.content.Context;
import android.text.TextUtils;
import com.facebook.catalyst.modules.cameraroll.CameraRollManager;
import com.facebook.common.dextricks.JITProfilePQR;
import com.facebook.forker.Process;
import com.instagram.api.schemas.CameraTool;
import com.instagram.api.schemas.FanClubStoriesTeaserType;
import com.instagram.api.schemas.FeedItemType;
import com.instagram.api.schemas.GenAIToolInfoDictIntf;
import com.instagram.api.schemas.IGAdCreativeStory9x16CaptionData;
import com.instagram.api.schemas.IGAdTransparencyDisclaimerPlacement;
import com.instagram.api.schemas.StoryMusicPickTappableDataIntf;
import com.instagram.api.schemas.StoryPromptTappableDataIntf;
import com.instagram.api.schemas.StoryPromptType;
import com.instagram.common.session.UserSession;
import com.instagram.common.typedurl.ImageUrl;
import com.instagram.feed.media.ReelCTAIntf;
import com.instagram.model.effect.AttributedAREffect;
import com.instagram.model.reels.sponsored.AutoGeneratedCardType;
import com.instagram.model.venue.Venue;
import com.instagram.react.modules.base.IgReactQEModule;
import com.instagram.reels.prompt.model.PromptStickerModel;
import com.instagram.user.model.User;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;

/* renamed from: X.1vS, reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C41181vS implements InterfaceC41201vU, C1NI, InterfaceC41211vV {
    public int A00;
    public int A01;
    public FanClubStoriesTeaserType A02;
    public C38641qv A03;
    public C35003Fba A04;
    public AttributedAREffect A05;
    public JMY A06;
    public C105864px A07;
    public C37771pE A08;
    public C104294ms A09;
    public C105874py A0A;
    public C105774po A0B;
    public C105804pr A0C;
    public C105794pq A0D;
    public C41618Ib8 A0E;
    public Boolean A0F;
    public Boolean A0G;
    public Long A0H;
    public String A0I;
    public String A0J;
    public List A0K;
    public List A0L;
    public List A0M;
    public boolean A0N;
    public boolean A0O;
    public boolean A0P;
    public boolean A0Q;
    public boolean A0R;
    public boolean A0S;
    public boolean A0T;
    public boolean A0U;
    public boolean A0V;
    public boolean A0W;
    public long A0X;
    public long A0Y;
    public C105784pp A0Z;
    public String A0a;
    public final C38321qM A0b;
    public final C105824pt A0c;
    public final C105814ps A0d;
    public final EnumC41231vY A0e;
    public final C105844pv A0f;
    public final C40971v4 A0g;
    public final C105854pw A0h;
    public final User A0i;
    public final String A0j;
    public final String A0k;
    public final List A0l;
    public final List A0m;
    public final List A0n;
    public final List A0o;
    public final List A0p;
    public final java.util.Set A0q;
    public final java.util.Set A0r;
    public C38541qi mBrandResearchSurvey;
    public final C105834pu mBrandSurveyImpression;

    public final String A0W(UserSession userSession) {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            InterfaceC104904o2 A02 = AbstractC41071vF.A02(userSession, c38321qM);
            if (A02 != null) {
                return AbstractC87103uT.A00(IGAdTransparencyDisclaimerPlacement.A05, A02);
            }
        }
        return null;
    }

    public final float A00() {
        int ordinal = this.A0e.ordinal();
        if (ordinal != 0) {
            if (ordinal != 1 && ordinal != 9) {
                return 0.0f;
            }
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return c38321qM.A0m();
        }
        C105814ps c105814ps = this.A0d;
        c105814ps.getClass();
        return c105814ps.A00.A02;
    }

    public final int A01() {
        if (this.A0e.ordinal() != 1) {
            return 0;
        }
        C38321qM c38321qM = this.A0b;
        c38321qM.getClass();
        return c38321qM.A11();
    }

    public final long A02() {
        Long l;
        C38321qM c38321qM = this.A0b;
        if (c38321qM != null) {
            long A18 = c38321qM.A18();
            if (A18 > 0 && A18 < Long.MAX_VALUE) {
                return c38321qM.A18();
            }
        }
        C105824pt c105824pt = this.A0c;
        if (c105824pt == null || (l = c105824pt.A0S) == null) {
            return Long.MAX_VALUE;
        }
        long longValue = l.longValue();
        if (longValue <= 0 || longValue >= Long.MAX_VALUE) {
            return Long.MAX_VALUE;
        }
        return TimeUnit.SECONDS.toMillis(longValue);
    }

    public final long A03() {
        Long l;
        Long l2;
        EnumC41231vY enumC41231vY = this.A0e;
        C14360o3.A0B(enumC41231vY, 0);
        if (AbstractC41591w9.A00.containsValue(enumC41231vY)) {
            return this.A0Y;
        }
        int ordinal = enumC41231vY.ordinal();
        if (ordinal != 0) {
            if (ordinal != 1) {
                if (ordinal != 3 && ordinal != 4) {
                    if (ordinal != 31) {
                        if (ordinal != 33) {
                            if (ordinal != 23 || (l2 = this.A0H) == null) {
                                return 0L;
                            }
                            return l2.longValue();
                        }
                        C38641qv c38641qv = this.A03;
                        if (c38641qv == null || (l = c38641qv.A04) == null) {
                            return 0L;
                        }
                        return l.longValue();
                    }
                    return this.A0X;
                }
                C105824pt c105824pt = this.A0c;
                if (c105824pt == null) {
                    return 0L;
                }
                return c105824pt.A01();
            }
            C38321qM c38321qM = this.A0b;
            if (c38321qM == null) {
                return 0L;
            }
            return c38321qM.A1B();
        }
        C105814ps c105814ps = this.A0d;
        c105814ps.getClass();
        long j = c105814ps.A00.A0e;
        if (j != 0) {
            return j;
        }
        return System.currentTimeMillis() / 1000;
    }

    public final InterfaceC108064tp A04() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return c38321qM.A0C.BMr();
        }
        return null;
    }

    public final InterfaceC37274GbR A05() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return c38321qM.A0C.BpQ();
        }
        return null;
    }

    public final ImageUrl A06() {
        int ordinal = this.A0e.ordinal();
        if (ordinal != 0) {
            if (ordinal != 1 && ordinal != 9 && ordinal != 6 && ordinal != 5 && ordinal != 10) {
                return null;
            }
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return c38321qM.A1S();
        }
        C105814ps c105814ps = this.A0d;
        c105814ps.getClass();
        String str = c105814ps.A00.A33;
        str.getClass();
        return AbstractC81033jX.A01(new File(str));
    }

    public final ImageUrl A07(int i) {
        C105824pt c105824pt;
        int ordinal = this.A0e.ordinal();
        if (ordinal != 0) {
            if (ordinal != 1 && ordinal != 9) {
                if ((ordinal == 3 || ordinal == 4) && (c105824pt = this.A0c) != null) {
                    return c105824pt.A02();
                }
            } else {
                C38321qM c38321qM = this.A0b;
                c38321qM.getClass();
                if (c38321qM.A4w()) {
                    android.net.Uri uri = c38321qM.A05;
                    uri.getClass();
                    return AbstractC81033jX.A00(uri, -1, -1);
                }
                return c38321qM.A1o(i);
            }
        } else {
            C105814ps c105814ps = this.A0d;
            c105814ps.getClass();
            C47Z c47z = c105814ps.A00;
            if (c47z.A0p()) {
                String str = c47z.A33;
                str.getClass();
                return AbstractC81033jX.A02(new File(str), -1, -1);
            }
        }
        return null;
    }

    public final ImageUrl A08(Context context) {
        User user;
        int ordinal = this.A0e.ordinal();
        if (ordinal != 0) {
            if (ordinal != 1 && ordinal != 9) {
                if (ordinal != 3 && ordinal != 4) {
                    if (ordinal != 6) {
                        if (ordinal != 31 || (user = this.A0i) == null) {
                            return null;
                        }
                        return user.Bhu();
                    }
                } else {
                    C105824pt c105824pt = this.A0c;
                    if (c105824pt == null) {
                        return null;
                    }
                    return c105824pt.A02();
                }
            }
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (c38321qM.A4w()) {
                android.net.Uri uri = c38321qM.A05;
                uri.getClass();
                return AbstractC81033jX.A00(uri, -1, -1);
            }
            return c38321qM.A1q(context);
        }
        C105814ps c105814ps = this.A0d;
        c105814ps.getClass();
        C47Z c47z = c105814ps.A00;
        if (!c47z.A0p()) {
            return null;
        }
        String str = c47z.A33;
        str.getClass();
        return AbstractC81033jX.A02(new File(str), -1, -1);
    }

    public final C1NI A09() {
        String str;
        EnumC41231vY enumC41231vY = this.A0e;
        C14360o3.A0B(enumC41231vY, 0);
        if (AbstractC41591w9.A00.containsValue(enumC41231vY)) {
            return new C42550IsT(this);
        }
        switch (enumC41231vY.ordinal()) {
            case 0:
                C105814ps c105814ps = this.A0d;
                c105814ps.getClass();
                return c105814ps;
            case 1:
                C105844pv c105844pv = this.A0f;
                if (c105844pv == null) {
                    return this.A0b;
                }
                return c105844pv;
            case 2:
            case 21:
            case 23:
            case 24:
            case 25:
            case 26:
            case 27:
            case 28:
            case CameraRollManager.IMAGES_MEDIA_LATITUDE_LONGITUDE_DEPRECATED_API_LEVEL /* 29 */:
            case 30:
            default:
                throw new UnsupportedOperationException(AnonymousClass001.A0R("This item does not represent an ImpressionItem. Item type: ", enumC41231vY.toString()));
            case 3:
            case 4:
                C105824pt c105824pt = this.A0c;
                if (c105824pt != null) {
                    C109114vb c109114vb = c105824pt.A0o;
                    if (c109114vb.A00 == null && (str = c105824pt.A0e) != null) {
                        c109114vb.A00 = str;
                    }
                    return c109114vb;
                }
                return null;
            case 5:
            case 6:
            case 10:
            case 14:
            case Process.SIGTERM /* 15 */:
                return this.A0h;
            case 7:
                return this.A09;
            case 8:
            case 11:
            case IgReactQEModule.CONFIG_KEY_OFFSET /* 12 */:
            case JITProfilePQR.HEADER_COMPRESSED_SIZE_OFFSET /* 13 */:
                return null;
            case 9:
                return this.A0b;
            case 16:
                return this.A0A;
            case 17:
                return this.A07;
            case 18:
                return this.A0B;
            case Process.SIGSTOP /* 19 */:
                return this.A0D;
            case 20:
                return this.A0C;
            case 22:
            case 34:
            case 35:
                return new C42549IsS();
            case 31:
                return this.A0Z;
            case 32:
                return this.mBrandSurveyImpression;
            case 33:
                return new C42551IsU(this);
        }
    }

    public final ReelCTAIntf A0A() {
        int ordinal = this.A0e.ordinal();
        if (ordinal != 0) {
            if (ordinal != 1 && ordinal != 9) {
                return null;
            }
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return c38321qM.A1j();
        }
        C105814ps c105814ps = this.A0d;
        c105814ps.getClass();
        List list = c105814ps.A00.A4Z;
        Object obj = null;
        if (list == null) {
            return null;
        }
        Iterator it = list.iterator();
        while (true) {
            if (!it.hasNext()) {
                break;
            }
            Object next = it.next();
            if (C6T4.A00((ReelCTAIntf) next) != null) {
                obj = next;
                break;
            }
        }
        return (ReelCTAIntf) obj;
    }

    public final EnumC76383bi A0B() {
        int ordinal = this.A0e.ordinal();
        if (ordinal != 0) {
            if (ordinal != 1) {
                return EnumC76383bi.A06;
            }
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return c38321qM.A1x();
        }
        C105814ps c105814ps = this.A0d;
        c105814ps.getClass();
        return c105814ps.A00.A1F;
    }

    public final EnumC40111tc A0C() {
        EnumC41231vY enumC41231vY = this.A0e;
        C14360o3.A0B(enumC41231vY, 0);
        if (AbstractC41591w9.A00.containsValue(enumC41231vY)) {
            return EnumC40111tc.A0a;
        }
        int ordinal = enumC41231vY.ordinal();
        if (ordinal != 0) {
            if (ordinal != 1 && ordinal != 9) {
                if (ordinal != 3 && ordinal != 4) {
                    return null;
                }
                return EnumC40111tc.A0L;
            }
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return c38321qM.BRp();
        }
        C105814ps c105814ps = this.A0d;
        c105814ps.getClass();
        return c105814ps.A00.A1G;
    }

    public final InterfaceC105354oy A0D() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return c38321qM.A0C.B9d();
        }
        return null;
    }

    public final YQS A0E() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return c38321qM.A0C.BMk();
        }
        return null;
    }

    public final C40I A0F() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return c38321qM.A0C.C1S();
        }
        return null;
    }

    /* JADX WARN: Type inference failed for: r1v3, types: [java.lang.Object, X.6QX] */
    public final C6QX A0G() {
        if (this.A0e.ordinal() == 1) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            C84923qg A1V = c38321qM.A1V();
            if (A1V != null) {
                ?? obj = new Object();
                obj.A06 = A1V.A0e;
                obj.A03 = A1V.A0b;
                obj.A04 = A1V.A0c;
                obj.A08 = A1V.A0h;
                obj.A07 = A1V.A0f;
                obj.A02 = Integer.valueOf(A1V.A0S);
                obj.A00 = A1V.A0Y;
                obj.A01 = A1V.A0Z;
                return obj;
            }
            return null;
        }
        return null;
    }

    public final C6QX A0H() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return c38321qM.A21();
        }
        return null;
    }

    /* JADX WARN: Type inference failed for: r1v4, types: [X.AAa, java.lang.Object] */
    public final C22956AAa A0I() {
        IGAdCreativeStory9x16CaptionData iGAdCreativeStory9x16CaptionData;
        float f;
        if (this.A0e.ordinal() == 1) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            C84923qg A1V = c38321qM.A1V();
            InterfaceC39541sb injected = c38321qM.A0C.getInjected();
            if (injected != null) {
                iGAdCreativeStory9x16CaptionData = injected.C4k();
            } else {
                iGAdCreativeStory9x16CaptionData = null;
            }
            if (A1V != null && iGAdCreativeStory9x16CaptionData != null) {
                ?? obj = new Object();
                obj.A0B = A1V.A0e;
                obj.A0A = iGAdCreativeStory9x16CaptionData.Alk();
                obj.A08 = iGAdCreativeStory9x16CaptionData.Alf();
                obj.A09 = iGAdCreativeStory9x16CaptionData.Alg();
                obj.A04 = iGAdCreativeStory9x16CaptionData.Ali();
                obj.A05 = iGAdCreativeStory9x16CaptionData.Alj();
                obj.A00 = iGAdCreativeStory9x16CaptionData.Alm();
                obj.A07 = iGAdCreativeStory9x16CaptionData.Alp();
                Integer All = iGAdCreativeStory9x16CaptionData.All();
                if (All != null) {
                    f = All.intValue();
                } else {
                    f = 16.0f;
                }
                obj.A03 = Float.valueOf(f);
                obj.A01 = iGAdCreativeStory9x16CaptionData.Alq();
                obj.A02 = iGAdCreativeStory9x16CaptionData.Alr();
                obj.A06 = iGAdCreativeStory9x16CaptionData.Alh();
                return obj;
            }
            return null;
        }
        return null;
    }

    public final User A0L() {
        C38321qM c38321qM = this.A0b;
        if (c38321qM == null || this.A0e != EnumC41231vY.A09) {
            return null;
        }
        return c38321qM.A2D();
    }

    /* JADX WARN: Code restructure failed: missing block: B:10:0x0015, code lost:
    
        if (r2 != 6) goto L12;
     */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
        To view partially-correct add '--show-bad-code' argument
    */
    public final X.C75363a3 A0M(com.instagram.common.session.UserSession r4) {
        /*
            r3 = this;
            X.1vY r0 = r3.A0e
            int r2 = r0.ordinal()
            r0 = 1
            if (r2 == r0) goto L21
            r0 = 9
            if (r2 == r0) goto L21
            r0 = 3
            r1 = 0
            if (r2 == r0) goto L18
            r0 = 4
            if (r2 == r0) goto L18
            r0 = 6
            if (r2 == r0) goto L21
        L17:
            return r1
        L18:
            X.4pt r0 = r3.A0c
            if (r0 == 0) goto L17
            X.3a3 r1 = r0.A04(r4)
            return r1
        L21:
            X.1qM r0 = r3.A0b
            r0.getClass()
            X.3a3 r1 = r0.A2H()
            return r1
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C41181vS.A0M(com.instagram.common.session.UserSession):X.3a3");
    }

    /* JADX WARN: Code restructure failed: missing block: B:4:0x000d, code lost:
    
        if (r1 != false) goto L6;
     */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
        To view partially-correct add '--show-bad-code' argument
    */
    public final java.lang.Boolean A0N() {
        /*
            r2 = this;
            X.3a5 r0 = X.EnumC75383a5.A0q
            java.util.List r0 = r2.BlY(r0)
            if (r0 == 0) goto Lf
            boolean r1 = r0.isEmpty()
            r0 = 1
            if (r1 == 0) goto L10
        Lf:
            r0 = 0
        L10:
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            return r0
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C41181vS.A0N():java.lang.Boolean");
    }

    public final Long A0O(UserSession userSession) {
        int ordinal = this.A0e.ordinal();
        if (ordinal != 0) {
            if (ordinal != 1) {
                return null;
            }
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return c38321qM.A0C.AcZ();
        }
        if (!A1e()) {
            return null;
        }
        C1DX A00 = C1DW.A00(userSession);
        C105814ps c105814ps = this.A0d;
        c105814ps.getClass();
        C38321qM A02 = A00.A02(c105814ps.A00.A2K);
        if (A02 == null) {
            return null;
        }
        return Long.valueOf(A02.A1B());
    }

    public final String A0P() {
        List A0k;
        C84823qW c84823qW;
        C24012Akq A0A;
        C38321qM c38321qM = this.A0b;
        if (c38321qM != null && (A0k = C38321qM.A0k(c38321qM)) != null && (c84823qW = (C84823qW) AbstractC001800i.A0J(A0k)) != null && (A0A = c84823qW.A0A()) != null) {
            return A0A.A02();
        }
        return null;
    }

    public final String A0Q() {
        InterfaceC43507JJt BH4;
        InterfaceC43510JJw Bcm;
        C38321qM c38321qM = this.A0b;
        if (c38321qM != null && (BH4 = c38321qM.A0C.BH4()) != null && (Bcm = BH4.Bcm()) != null) {
            return Bcm.getUrl();
        }
        return null;
    }

    public final String A0R() {
        EnumC41231vY enumC41231vY = this.A0e;
        C14360o3.A0B(enumC41231vY, 0);
        if (AbstractC41591w9.A00.containsValue(enumC41231vY)) {
            C41618Ib8 c41618Ib8 = this.A0E;
            c41618Ib8.getClass();
            return (String) AbstractC47902LDw.A01.get(c41618Ib8.A04);
        }
        int ordinal = enumC41231vY.ordinal();
        if (ordinal != 0) {
            if (ordinal != 1 && ordinal != 9) {
                return null;
            }
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return c38321qM.A0M;
        }
        C105814ps c105814ps = this.A0d;
        c105814ps.getClass();
        return c105814ps.A00.A3V;
    }

    public final String A0S() {
        int ordinal = this.A0e.ordinal();
        if (ordinal != 1 && ordinal != 9) {
            return null;
        }
        C38321qM c38321qM = this.A0b;
        c38321qM.getClass();
        return c38321qM.A0C.getPreview();
    }

    /* JADX WARN: Failed to find 'out' block for switch in B:11:0x0017. Please report as an issue. */
    public final String A0T() {
        String AYe;
        Object obj;
        String str;
        int ordinal = this.A0e.ordinal();
        if (ordinal != 1) {
            if (ordinal != 20) {
                if (ordinal != 6 && ordinal != 5 && ordinal != 10) {
                    switch (ordinal) {
                        case 7:
                            C104294ms c104294ms = this.A09;
                            C18C.A07(c104294ms, "Netego SU unit needs to have an SU object");
                            return c104294ms.A00.A03;
                        case 8:
                            obj = null;
                            str = "Netego suggested clips unit needs to have an suggested clips object";
                            C18C.A07(obj, str);
                            throw C00O.createAndThrow();
                        case 9:
                        case 10:
                        default:
                            throw new UnsupportedOperationException("Reel item isn't a netego unit with an action");
                        case 11:
                        case IgReactQEModule.CONFIG_KEY_OFFSET /* 12 */:
                            obj = null;
                            str = "Netego products for you unit needs to have an suggested products object";
                            C18C.A07(obj, str);
                            throw C00O.createAndThrow();
                        case JITProfilePQR.HEADER_COMPRESSED_SIZE_OFFSET /* 13 */:
                            obj = null;
                            str = "Netego shops for you unit needs to have an suggested shops object";
                            C18C.A07(obj, str);
                            throw C00O.createAndThrow();
                        case 14:
                        case Process.SIGTERM /* 15 */:
                            break;
                        case 16:
                            C105874py c105874py = this.A0A;
                            C18C.A07(c105874py, "Bloks Netego unit needs to have a bloks netego object.");
                            AYe = c105874py.A01.A04;
                            break;
                        case 17:
                            C105864px c105864px = this.A07;
                            C18C.A07(c105864px, "Netego trending prompt unit needs to have an prompts in story object");
                            return c105864px.A04;
                        case 18:
                            C105774po c105774po = this.A0B;
                            C18C.A07(c105774po, "Share Comment to Story Netego needs to have a CommentShareNetego");
                            AYe = c105774po.A00.getCtaText();
                            break;
                        case Process.SIGSTOP /* 19 */:
                            C105794pq c105794pq = this.A0D;
                            C18C.A07(c105794pq, "Threads in stories unit Netego needs to have a ThreadsInStoriesUnitNetego");
                            AYe = c105794pq.A00.getCtaText();
                            break;
                    }
                }
                C105854pw c105854pw = this.A0h;
                C18C.A07(c105854pw, "Netego bakeoff units, quality surveys, story creation upsells and ads consent growth need to have a SimpleAction");
                String Aj7 = c105854pw.A00.Aj7();
                C18C.A07(Aj7, "Netego's SimpleAction will always have button text");
                return Aj7;
            }
            C105804pr c105804pr = this.A0C;
            C18C.A07(c105804pr, "Meta Gallery Stories Netego needs to have a MetaGalleryNetegoInfo");
            String ctaText = c105804pr.A01.getCtaText();
            if (ctaText == null) {
                throw new IllegalStateException("Required value was null.");
            }
            return ctaText;
        }
        C105844pv c105844pv = this.A0f;
        C18C.A07(c105844pv, "Netego ad4ad unit needs to have an Ad4ad object");
        AYe = c105844pv.A00.AYe();
        if (AYe == null) {
            return "";
        }
        return AYe;
    }

    public final String A0U() {
        Object obj;
        StoryPromptTappableDataIntf Bii;
        String id;
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            List C1y = c38321qM.A0C.C1y();
            if (C1y != null) {
                Iterator it = C1y.iterator();
                while (true) {
                    obj = null;
                    if (!it.hasNext()) {
                        break;
                    }
                    Object next = it.next();
                    StoryPromptTappableDataIntf Bii2 = ((InterfaceC109364wL) next).Bii();
                    if (Bii2 != null) {
                        obj = Bii2.Bio();
                    }
                    if (obj == StoryPromptType.A0G) {
                        obj = next;
                        break;
                    }
                }
                InterfaceC109364wL interfaceC109364wL = (InterfaceC109364wL) obj;
                if (interfaceC109364wL != null && (Bii = interfaceC109364wL.Bii()) != null && (id = Bii.getId()) != null) {
                    return id;
                }
                return "";
            }
            return "";
        }
        return "";
    }

    public final String A0V(UserSession userSession) {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return AbstractC41071vF.A07(userSession, c38321qM);
        }
        return null;
    }

    public final String A0X(UserSession userSession) {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            C40971v4 A00 = AbstractC41561w6.A00(userSession).A00(c38321qM);
            if (A00 != null) {
                return A00.A0X;
            }
            return c38321qM.A0C.AyB();
        }
        return null;
    }

    public final String A0Y(UserSession userSession) {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return AbstractC41071vF.A0B(userSession, c38321qM);
        }
        return null;
    }

    public final String A0Z(UserSession userSession) {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return AbstractC41071vF.A0D(userSession, c38321qM);
        }
        return null;
    }

    public final String A0a(UserSession userSession) {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return AbstractC41071vF.A0E(userSession, c38321qM);
        }
        return null;
    }

    public final List A0b() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            List BVM = c38321qM.A0C.BVM();
            if (BVM == null) {
                ArrayList arrayList = new ArrayList();
                c38321qM.A0C.EZJ(arrayList);
                return arrayList;
            }
            return BVM;
        }
        return new ArrayList();
    }

    public final List A0c() {
        int ordinal = this.A0e.ordinal();
        if (ordinal != 0) {
            if (ordinal != 1 && ordinal != 6) {
                return null;
            }
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return c38321qM.A3N();
        }
        C105814ps c105814ps = this.A0d;
        c105814ps.getClass();
        return c105814ps.A00.A4b;
    }

    public final List A0d() {
        List CGP;
        if (this.A0e.ordinal() != 1) {
            return new ArrayList();
        }
        C38321qM c38321qM = this.A0b;
        c38321qM.getClass();
        synchronized (c38321qM) {
            CGP = c38321qM.A0C.CGP();
            if (CGP == null) {
                CGP = new ArrayList();
                c38321qM.A0C.EhA(CGP);
            }
        }
        return CGP;
    }

    public final void A0e() {
        this.A0p.clear();
        this.A0r.clear();
        this.A0n.clear();
        this.A0q.clear();
        this.A0o.clear();
        this.A0N = false;
    }

    /* JADX WARN: Removed duplicated region for block: B:14:0x002a  */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
        To view partially-correct add '--show-bad-code' argument
    */
    public final void A0f(java.lang.String r4) {
        /*
            r3 = this;
            if (r4 == 0) goto Le
            int r0 = r4.hashCode()
            r2 = 1
            r1 = 0
            switch(r0) {
                case -1077756671: goto L21;
                case 3083677: goto L1d;
                case 1843485230: goto Lf;
                default: goto Lb;
            }
        Lb:
            r0 = 0
        Lc:
            r3.A0G = r0
        Le:
            return
        Lf:
            java.lang.String r0 = "network"
            boolean r0 = r4.equals(r0)
            if (r0 == 0) goto Lb
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r1)
            goto Lc
        L1d:
            java.lang.String r0 = "disk"
            goto L24
        L21:
            java.lang.String r0 = "memory"
        L24:
            boolean r0 = r4.equals(r0)
            if (r0 == 0) goto Lb
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r2)
            goto Lc
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C41181vS.A0f(java.lang.String):void");
    }

    public final boolean A0g() {
        Boolean Akk;
        C38321qM c38321qM = this.A0b;
        if (c38321qM != null && (Akk = c38321qM.A0C.Akk()) != null && Akk.booleanValue()) {
            return true;
        }
        return false;
    }

    public final boolean A0i() {
        int ordinal = this.A0e.ordinal();
        if (ordinal != 0) {
            if (ordinal == 1) {
                C38321qM c38321qM = this.A0b;
                c38321qM.getClass();
                Boolean Caz = c38321qM.A0C.Caz();
                if (Caz != null) {
                    return Caz.booleanValue();
                }
                return false;
            }
            return false;
        }
        C105814ps c105814ps = this.A0d;
        c105814ps.getClass();
        return c105814ps.A00.A4z;
    }

    public final boolean A0j() {
        C38321qM c38321qM = this.A0b;
        if (c38321qM != null && c38321qM.A0C.Apn() != null) {
            return true;
        }
        return false;
    }

    public final boolean A0k() {
        C38321qM c38321qM = this.A0b;
        if (c38321qM != null && c38321qM.A4k()) {
            return true;
        }
        return false;
    }

    public final boolean A0l() {
        C38321qM c38321qM = this.A0b;
        if (c38321qM != null && C14360o3.A0K(c38321qM.A0C.AkV(), true)) {
            return true;
        }
        return false;
    }

    public final boolean A0n() {
        C38321qM c38321qM = this.A0b;
        if (c38321qM != null) {
            return c38321qM.A4g();
        }
        C105824pt c105824pt = this.A0c;
        if (c105824pt == null) {
            return false;
        }
        Boolean bool = c105824pt.A0L;
        if (bool != null && bool.booleanValue()) {
            return false;
        }
        return true;
    }

    public final boolean A0o() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (c38321qM.A4h()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A0p() {
        String str;
        int ordinal = this.A0e.ordinal();
        if (ordinal != 0) {
            if (ordinal != 1) {
                return false;
            }
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            str = c38321qM.A2q();
        } else {
            C105814ps c105814ps = this.A0d;
            c105814ps.getClass();
            List list = c105814ps.A00.A4Z;
            if (list != null) {
                str = C6T4.A01((ReelCTAIntf) list.get(0));
            } else {
                str = null;
            }
        }
        return !TextUtils.isEmpty(str);
    }

    public final boolean A0q() {
        ReelCTAIntf reelCTAIntf;
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            List C1N = c38321qM.A0C.C1N();
            if (C1N != null && (reelCTAIntf = (ReelCTAIntf) AbstractC001800i.A0J(C1N)) != null && C14360o3.A0K(reelCTAIntf.BBv(), true)) {
                return true;
            }
        }
        return false;
    }

    public final boolean A0r() {
        if (!A1v(EnumC75383a5.A0x) && !A1v(EnumC75383a5.A14) && !A1v(EnumC75383a5.A16) && !A1v(EnumC75383a5.A1C)) {
            return false;
        }
        return true;
    }

    public final boolean A0s() {
        List list;
        ReelCTAIntf reelCTAIntf;
        int ordinal = this.A0e.ordinal();
        if (ordinal != 0) {
            if (ordinal != 1) {
                return false;
            }
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (!AbstractC83893oY.A00(c38321qM.A3p()) || (!c38321qM.A3Y().isEmpty())) {
                return true;
            }
            return false;
        }
        C105814ps c105814ps = this.A0d;
        c105814ps.getClass();
        List list2 = c105814ps.A00.A4Z;
        if (list2 != null && (reelCTAIntf = (ReelCTAIntf) AbstractC001800i.A0O(list2, 0)) != null) {
            list = reelCTAIntf.BNi();
        } else {
            list = null;
        }
        return !AbstractC83893oY.A00(list);
    }

    public final boolean A0t() {
        int ordinal;
        EnumC41231vY enumC41231vY = this.A0e;
        C14360o3.A0B(enumC41231vY, 0);
        if (AbstractC41591w9.A00.containsValue(enumC41231vY) || (ordinal = enumC41231vY.ordinal()) == 0) {
            return true;
        }
        if (ordinal != 1 && ordinal != 9) {
            return false;
        }
        C38321qM c38321qM = this.A0b;
        c38321qM.getClass();
        return c38321qM.A4x();
    }

    public final boolean A0u() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (c38321qM.A24() != null) {
                return true;
            }
        }
        return false;
    }

    public final boolean A0x() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (c38321qM.A22() != null) {
                return true;
            }
        }
        return false;
    }

    public final boolean A0y() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (c38321qM.A25() != null) {
                return true;
            }
        }
        return false;
    }

    public final boolean A0z() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (c38321qM.A23() != null) {
                return true;
            }
        }
        return false;
    }

    public final boolean A10() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (c38321qM.A58()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A11() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            Boolean BCr = c38321qM.A0C.BCr();
            if (BCr != null && BCr.booleanValue()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A12() {
        Venue A28;
        C38321qM c38321qM = this.A0b;
        if (c38321qM != null && (A28 = c38321qM.A28()) != null && A28.A00() != null && A28.A01() != null) {
            return true;
        }
        return false;
    }

    public final boolean A13() {
        if (this.A0e == EnumC41231vY.A01 && this.A05 != null) {
            return true;
        }
        return false;
    }

    public final boolean A14() {
        StoryPromptType storyPromptType;
        StoryPromptTappableDataIntf Bii;
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            List<InterfaceC109364wL> C1y = c38321qM.A0C.C1y();
            if (C1y != null) {
                if ((C1y instanceof Collection) && C1y.isEmpty()) {
                    return false;
                }
                for (InterfaceC109364wL interfaceC109364wL : C1y) {
                    StoryPromptTappableDataIntf Bii2 = interfaceC109364wL.Bii();
                    if (Bii2 != null) {
                        storyPromptType = Bii2.Bio();
                    } else {
                        storyPromptType = null;
                    }
                    if (storyPromptType == StoryPromptType.A0G && (Bii = interfaceC109364wL.Bii()) != null && C14360o3.A0K(Bii.Cfw(), true)) {
                        return true;
                    }
                }
                return false;
            }
            return false;
        }
        return false;
    }

    public final boolean A15() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (AutoGeneratedCardType.A04 == c38321qM.A0C.AeF()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A16() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (c38321qM.A0C.AeF() != null && c38321qM.A0C.AeF() != AutoGeneratedCardType.A0J) {
                return true;
            }
        }
        return false;
    }

    public final boolean A18() {
        if (this.A0e != EnumC41231vY.A03) {
            return false;
        }
        return true;
    }

    public final boolean A19() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (AutoGeneratedCardType.A05 == c38321qM.A0C.AeF()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A1A() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (AutoGeneratedCardType.A06 == c38321qM.A0C.AeF()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A1B() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (c38321qM.A5Q()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A1C() {
        EnumC41231vY enumC41231vY = this.A0e;
        if (enumC41231vY != EnumC41231vY.A05 && enumC41231vY != EnumC41231vY.A06) {
            return false;
        }
        return true;
    }

    public final boolean A1D() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (c38321qM.A5V()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A1E() {
        C38321qM c38321qM = this.A0b;
        if (c38321qM != null && c38321qM.A5X()) {
            return true;
        }
        return false;
    }

    public final boolean A1F() {
        if (this.A0e != EnumC41231vY.A0R) {
            return false;
        }
        return true;
    }

    public final boolean A1G() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (AutoGeneratedCardType.A09 == c38321qM.A0C.AeF()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A1H() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (AutoGeneratedCardType.A0A == c38321qM.A0C.AeF()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A1J() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (AutoGeneratedCardType.A0B == c38321qM.A0C.AeF()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A1K() {
        if (!this.A0Q) {
            C38321qM c38321qM = this.A0b;
            if (c38321qM != null && c38321qM.A0C.B3E() == null) {
                return true;
            }
            return false;
        }
        return true;
    }

    public final boolean A1L() {
        StoryPromptType storyPromptType;
        GenAIToolInfoDictIntf B9Z;
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            List<InterfaceC109364wL> C1y = c38321qM.A0C.C1y();
            if (C1y != null) {
                if ((C1y instanceof Collection) && C1y.isEmpty()) {
                    return false;
                }
                for (InterfaceC109364wL interfaceC109364wL : C1y) {
                    StoryPromptTappableDataIntf Bii = interfaceC109364wL.Bii();
                    CameraTool cameraTool = null;
                    if (Bii != null) {
                        storyPromptType = Bii.Bio();
                    } else {
                        storyPromptType = null;
                    }
                    if (storyPromptType == StoryPromptType.A0G) {
                        StoryPromptTappableDataIntf Bii2 = interfaceC109364wL.Bii();
                        if (Bii2 != null && (B9Z = Bii2.B9Z()) != null) {
                            cameraTool = B9Z.C9G();
                        }
                        if (cameraTool == CameraTool.A1F) {
                            return true;
                        }
                    }
                }
                return false;
            }
            return false;
        }
        return false;
    }

    public final boolean A1M() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (c38321qM.A5j()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A1N() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (AutoGeneratedCardType.A0C == c38321qM.A0C.AeF()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A1O() {
        if (this.A0e != EnumC41231vY.A08) {
            return false;
        }
        return true;
    }

    public final boolean A1P() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (c38321qM.A5m()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A1Q() {
        EnumC41231vY enumC41231vY = this.A0e;
        if (enumC41231vY != EnumC41231vY.A0A && this.A0f == null && !A1V() && !A1T() && !A1U() && enumC41231vY != EnumC41231vY.A0O && enumC41231vY != EnumC41231vY.A0B && !A1R() && !A1S() && !A1W() && enumC41231vY != EnumC41231vY.A0E) {
            return false;
        }
        return true;
    }

    public final boolean A1R() {
        if (this.A0e != EnumC41231vY.A0N) {
            return false;
        }
        return true;
    }

    public final boolean A1S() {
        if (this.A0e != EnumC41231vY.A0I) {
            return false;
        }
        return true;
    }

    public final boolean A1T() {
        if (this.A0e != EnumC41231vY.A0K) {
            return false;
        }
        return true;
    }

    public final boolean A1U() {
        EnumC41231vY enumC41231vY = this.A0e;
        if (enumC41231vY != EnumC41231vY.A0G && enumC41231vY != EnumC41231vY.A0H) {
            return false;
        }
        return true;
    }

    public final boolean A1V() {
        if (this.A0e != EnumC41231vY.A0L) {
            return false;
        }
        return true;
    }

    public final boolean A1W() {
        if (this.A0e != EnumC41231vY.A0M) {
            return false;
        }
        return true;
    }

    /* JADX WARN: Code restructure failed: missing block: B:26:0x0043, code lost:
    
        if (r0.A01.A09 == false) goto L28;
     */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
        To view partially-correct add '--show-bad-code' argument
    */
    public final boolean A1X() {
        /*
            r3 = this;
            X.1vY r1 = r3.A0e
            X.1vY r0 = X.EnumC41231vY.A0A
            if (r1 == r0) goto L56
            X.4pv r0 = r3.A0f
            if (r0 != 0) goto L56
            boolean r0 = r3.A1V()
            if (r0 != 0) goto L56
            X.1vY r0 = X.EnumC41231vY.A0F
            if (r1 == r0) goto L56
            X.1vY r0 = X.EnumC41231vY.A0D
            if (r1 == r0) goto L56
            X.1vY r0 = X.EnumC41231vY.A0J
            if (r1 == r0) goto L56
            boolean r0 = r3.A1T()
            if (r0 != 0) goto L56
            boolean r0 = r3.A1U()
            if (r0 != 0) goto L56
            X.1vY r0 = X.EnumC41231vY.A0O
            if (r1 == r0) goto L56
            boolean r0 = r3.A1R()
            if (r0 != 0) goto L56
            X.1vY r0 = X.EnumC41231vY.A0C
            if (r1 == r0) goto L56
            X.1vY r0 = X.EnumC41231vY.A0B
            if (r1 != r0) goto L45
            X.4py r0 = r3.A0A
            r0.getClass()
            X.1pZ r0 = r0.A01
            boolean r0 = r0.A09
            if (r0 != 0) goto L56
        L45:
            boolean r0 = r3.A1S()
            if (r0 != 0) goto L56
            boolean r0 = r3.A1W()
            if (r0 != 0) goto L56
            X.1vY r0 = X.EnumC41231vY.A0E
            r2 = 0
            if (r1 != r0) goto L57
        L56:
            r2 = 1
        L57:
            return r2
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C41181vS.A1X():boolean");
    }

    public final boolean A1Y() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (AutoGeneratedCardType.A0E == c38321qM.A0C.AeF()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A1Z() {
        if (this.A0e == EnumC41231vY.A0P && this.A0d != null) {
            return true;
        }
        return false;
    }

    public final boolean A1a() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (c38321qM.A5w()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A1b() {
        int ordinal = this.A0e.ordinal();
        if (ordinal != 3 && ordinal != 4) {
            return A1o();
        }
        if (A1o() && this.A0c != null) {
            return true;
        }
        return false;
    }

    public final boolean A1d() {
        C38321qM c38321qM = this.A0b;
        if (c38321qM != null && C14360o3.A0K(c38321qM.A0C.Cdy(), true)) {
            return true;
        }
        return false;
    }

    public final boolean A1e() {
        Comparable comparable;
        int ordinal = this.A0e.ordinal();
        if (ordinal != 0) {
            if (ordinal != 1) {
                return false;
            }
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            comparable = c38321qM.A0C.AcZ();
        } else {
            C105814ps c105814ps = this.A0d;
            c105814ps.getClass();
            comparable = c105814ps.A00.A2K;
        }
        if (comparable == null) {
            return false;
        }
        return true;
    }

    public final boolean A1f() {
        C38321qM c38321qM = this.A0b;
        if (c38321qM != null && C14360o3.A0K(c38321qM.A0C.CcB(), true)) {
            return true;
        }
        return false;
    }

    public final boolean A1g() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (c38321qM.A67()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A1i() {
        int ordinal = this.A0e.ordinal();
        if (ordinal != 0) {
            if (ordinal != 1) {
                return false;
            }
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return c38321qM.A69();
        }
        C105814ps c105814ps = this.A0d;
        c105814ps.getClass();
        if (c105814ps.A00.A1F != EnumC76383bi.A04) {
            return false;
        }
        return true;
    }

    public final boolean A1j() {
        C38321qM c38321qM = this.A0b;
        if (c38321qM != null && !c38321qM.CdW() && ((c38321qM.A53() || c38321qM.A3w(EnumC75383a5.A0q) != null || c38321qM.A2A() != null) && !c38321qM.A3N().isEmpty())) {
            return true;
        }
        return false;
    }

    public final boolean A1k() {
        if (this.A0e != EnumC41231vY.A0U) {
            return false;
        }
        return true;
    }

    public final boolean A1l() {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (c38321qM.A6G()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A1m() {
        EnumC41231vY enumC41231vY = this.A0e;
        C14360o3.A0B(enumC41231vY, 0);
        return AbstractC41591w9.A00.containsValue(enumC41231vY);
    }

    public final boolean A1n() {
        EnumC41231vY enumC41231vY = this.A0e;
        C14360o3.A0B(enumC41231vY, 0);
        if (AbstractC41591w9.A00.containsValue(enumC41231vY)) {
            C41618Ib8 c41618Ib8 = this.A0E;
            c41618Ib8.getClass();
            if (AbstractC47902LDw.A01.get(c41618Ib8.A04) == null) {
                return true;
            }
        }
        return false;
    }

    public final boolean A1o() {
        EnumC41231vY enumC41231vY = this.A0e;
        C14360o3.A0B(enumC41231vY, 0);
        if (AbstractC41591w9.A00.containsValue(enumC41231vY)) {
            return true;
        }
        int ordinal = enumC41231vY.ordinal();
        if (ordinal != 0) {
            if (ordinal != 1 && ordinal != 9) {
                if (ordinal == 3 || ordinal == 4) {
                    return true;
                }
                return false;
            }
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return c38321qM.Cff();
        }
        C105814ps c105814ps = this.A0d;
        c105814ps.getClass();
        return c105814ps.A00.A11();
    }

    public final boolean A1p(UserSession userSession) {
        String str;
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            C14360o3.A0B(userSession, 0);
            List C1n = c38321qM.A0C.C1n();
            if (C1n != null) {
                if ((C1n instanceof Collection) && C1n.isEmpty()) {
                    return false;
                }
                Iterator it = C1n.iterator();
                while (it.hasNext()) {
                    StoryMusicPickTappableDataIntf BVg = ((InterfaceC73625YQn) it.next()).BVg();
                    if (BVg != null) {
                        str = BVg.AeC();
                    } else {
                        str = null;
                    }
                    if (C14360o3.A0K(str, C08730cb.A00(userSession).A00().getId())) {
                        return true;
                    }
                }
                return false;
            }
            return false;
        }
        return false;
    }

    public final boolean A1q(UserSession userSession) {
        if (this.A0e == EnumC41231vY.A02 && C18U.A06(C06090Tz.A05, userSession, 36318080246421381L)) {
            return true;
        }
        return false;
    }

    public final boolean A1r(UserSession userSession) {
        if (this.A0e == EnumC41231vY.A02 && C18U.A06(C06090Tz.A05, userSession, 36318080246421381L)) {
            return true;
        }
        return false;
    }

    public final boolean A1s(UserSession userSession) {
        EnumC41231vY enumC41231vY = this.A0e;
        if (enumC41231vY != EnumC41231vY.A0A && enumC41231vY != EnumC41231vY.A0L && enumC41231vY != EnumC41231vY.A0F && enumC41231vY != EnumC41231vY.A0D && enumC41231vY != EnumC41231vY.A0J && enumC41231vY != EnumC41231vY.A0C && enumC41231vY != EnumC41231vY.A0H && enumC41231vY != EnumC41231vY.A0G && enumC41231vY != EnumC41231vY.A0K && enumC41231vY != EnumC41231vY.A0N && enumC41231vY != EnumC41231vY.A0O && enumC41231vY != EnumC41231vY.A0B && enumC41231vY != EnumC41231vY.A0S && ((enumC41231vY != EnumC41231vY.A0T || !C18U.A06(C06090Tz.A06, userSession, 36327932901604318L)) && enumC41231vY != EnumC41231vY.A0R && enumC41231vY != EnumC41231vY.A0I && enumC41231vY != EnumC41231vY.A0M && enumC41231vY != EnumC41231vY.A0E && enumC41231vY != EnumC41231vY.A0U && enumC41231vY != EnumC41231vY.A05 && enumC41231vY != EnumC41231vY.A06)) {
            return false;
        }
        return true;
    }

    public final boolean A1t(UserSession userSession) {
        if (this.A0e == EnumC41231vY.A09) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            C40971v4 A00 = AbstractC41561w6.A00(userSession).A00(c38321qM);
            if (A00 != null) {
                return A00.A0n;
            }
            return c38321qM.A6R();
        }
        return false;
    }

    public final boolean A1u(UserSession userSession) {
        C38321qM c38321qM = this.A0b;
        if (c38321qM != null && C2TN.A02(userSession, c38321qM) && c38321qM.A6i(userSession) && C18U.A06(C06090Tz.A05, userSession, 36327151217228098L)) {
            return true;
        }
        return false;
    }

    @Override // X.InterfaceC41201vU
    public final C38321qM BQN() {
        return this.A0b;
    }

    @Override // X.InterfaceC41201vU
    public final List BlY(EnumC75383a5 enumC75383a5) {
        int ordinal = this.A0e.ordinal();
        if (ordinal != 0) {
            if (ordinal != 1) {
                return null;
            }
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            return c38321qM.A3w(enumC75383a5);
        }
        C105814ps c105814ps = this.A0d;
        c105814ps.getClass();
        return C48r.A01(enumC75383a5, c105814ps.A00.A4b);
    }

    @Override // X.InterfaceC41201vU
    public final /* bridge */ /* synthetic */ User CDj() {
        return this.A0i;
    }

    @Override // X.InterfaceC41201vU
    public final String CGe() {
        String str = this.A0a;
        if (str == null) {
            String A06 = AbstractC13670mt.A06("%s_%s", this.A0j, this.A0k);
            this.A0a = A06;
            return A06;
        }
        return str;
    }

    @Override // X.InterfaceC41201vU
    public final boolean CY4() {
        if (this.A0e == EnumC41231vY.A09 && this.A0b != null) {
            return true;
        }
        return false;
    }

    @Override // X.C1NI
    public final boolean CZq() {
        if (this.A0e != EnumC41231vY.A0Q && A09() != null && A09().CZq()) {
            return true;
        }
        return false;
    }

    public final boolean equals(Object obj) {
        if ((obj instanceof C41181vS) && AbstractC50102Ry.A00(((C41181vS) obj).A0j, this.A0j)) {
            return true;
        }
        return false;
    }

    @Override // X.C1NI, X.InterfaceC38381qS, X.InterfaceC38411qV
    public final String getId() {
        return this.A0j;
    }

    public final int hashCode() {
        return Arrays.hashCode(new Object[]{this.A0j});
    }

    public final PromptStickerModel A0J() {
        List A0c = A0c();
        if (A0c != null) {
            Iterator it = A0c.iterator();
            while (it.hasNext()) {
                PromptStickerModel A0E = ((C84823qW) it.next()).A0E();
                if (A0E != null) {
                    return A0E;
                }
            }
        }
        return null;
    }

    public final PromptStickerModel A0K() {
        List A0c = A0c();
        if (A0c != null) {
            Iterator it = A0c.iterator();
            while (it.hasNext()) {
                PromptStickerModel A0E = ((C84823qW) it.next()).A0E();
                if (A0E != null && A0E.A0M()) {
                    return A0E;
                }
            }
        }
        return null;
    }

    public final boolean A0h() {
        if (CY4()) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (c38321qM.A4V()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A0m() {
        String str;
        ReelCTAIntf A0A = A0A();
        if (A0A != null) {
            str = C6T4.A00(A0A);
        } else {
            str = null;
        }
        if (!TextUtils.isEmpty(str) && !A13()) {
            return true;
        }
        return false;
    }

    public final boolean A0v() {
        C84823qW A00 = C48r.A00(EnumC75383a5.A0s, A0c());
        if (C48r.A00(EnumC75383a5.A0r, A0c()) != null || A00 == null || !AbstractC13670mt.A0B(A00.A1h)) {
            return false;
        }
        return true;
    }

    public final boolean A0w() {
        if (A0u()) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (!c38321qM.CdW()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A17() {
        if (A1Z()) {
            C105814ps c105814ps = this.A0d;
            c105814ps.getClass();
            C47Z c47z = c105814ps.A00;
            if (!c47z.A0z() && !AbstractC50707Ma2.A03(c47z)) {
                if ((c47z.A11() && c47z.A3V == null) || c47z.A33 == null) {
                    return true;
                }
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A1I() {
        if (A05() == null) {
            return false;
        }
        return true;
    }

    public final boolean A1c() {
        if (!A1o() && this.A0e == EnumC41231vY.A09) {
            return true;
        }
        return false;
    }

    public final boolean A1h() {
        if (A05() != null) {
            if (A05().Buy() != null && !A05().Buy().booleanValue()) {
                return true;
            }
            return false;
        }
        return true;
    }

    public final boolean A1v(EnumC75383a5 enumC75383a5) {
        List BlY = BlY(enumC75383a5);
        if (BlY != null && !BlY.isEmpty()) {
            return true;
        }
        return false;
    }

    @Override // X.InterfaceC41201vU
    public final float Ack(UserSession userSession) {
        return A00();
    }

    @Override // X.C1NI
    public final String BzL(UserSession userSession) {
        return AbstractC41071vF.A06(userSession, A09());
    }

    @Override // X.C1NI
    public final boolean CW9() {
        if (A09() != null && A09().CW9()) {
            return true;
        }
        return false;
    }

    @Override // X.C1NI
    public final boolean CdW() {
        if (CY4()) {
            C38321qM c38321qM = this.A0b;
            c38321qM.getClass();
            if (c38321qM.CdW()) {
                return true;
            }
        }
        return false;
    }

    public C41181vS(C38321qM c38321qM, C40971v4 c40971v4, User user, String str) {
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0L;
        this.A0X = 0L;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0b = c38321qM;
        this.A0g = c40971v4;
        this.A0d = null;
        this.A0e = EnumC41231vY.A09;
        this.A0j = c38321qM.getId();
        this.A0i = user;
        this.A0c = null;
        this.A0h = null;
        this.A0f = null;
        this.A09 = null;
        this.A0F = null;
        this.A07 = null;
        this.A00 = 0;
        this.mBrandSurveyImpression = null;
        if (!c38321qM.A3N().isEmpty()) {
            Iterator it = c38321qM.A3N().iterator();
            while (it.hasNext()) {
                ((C84823qW) it.next()).A1e = str;
            }
        }
    }

    public C41181vS(C38321qM c38321qM, EnumC41231vY enumC41231vY, User user, String str) {
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0L;
        this.A0X = 0L;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0b = c38321qM;
        this.A0g = null;
        this.A0d = null;
        this.A0e = enumC41231vY;
        this.A0j = c38321qM.getId();
        this.A0i = user;
        this.A0c = null;
        this.A0h = null;
        this.A0f = null;
        this.A09 = null;
        this.A0F = null;
        this.A00 = 0;
        if (!c38321qM.A3N().isEmpty()) {
            Iterator it = c38321qM.A3N().iterator();
            while (it.hasNext()) {
                ((C84823qW) it.next()).A1e = str;
            }
        }
        this.mBrandSurveyImpression = null;
    }

    public C41181vS(C38321qM c38321qM, C105864px c105864px, C104294ms c104294ms, C105844pv c105844pv, C105874py c105874py, C105774po c105774po, C105804pr c105804pr, C105794pq c105794pq, C105854pw c105854pw, User user, Integer num, String str) {
        EnumC41231vY enumC41231vY;
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0L;
        this.A0X = 0L;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0d = null;
        this.A0c = null;
        this.mBrandSurveyImpression = null;
        switch (num.intValue()) {
            case 0:
                C18C.A07(c105854pw, "Netego bakeoff units needs to have a SimpleAction");
                this.A0j = c105854pw.getId();
                this.A0e = EnumC41231vY.A0A;
                this.A0h = c105854pw;
                this.A0f = null;
                this.A09 = null;
                this.A07 = null;
                this.A0b = c38321qM;
                this.A0g = null;
                this.A0i = null;
                this.A0A = null;
                this.A0D = null;
                return;
            case 1:
                C18C.A07(c105844pv, "Netego ad4ad unit needs to have an Ad4ad object");
                this.A0j = c105844pv.getId();
                this.A0e = EnumC41231vY.A09;
                this.A0f = c105844pv;
                this.A09 = null;
                this.A0h = null;
                this.A07 = null;
                this.A0b = c38321qM;
                this.A0g = null;
                this.A0i = user;
                this.A0A = null;
                this.A0D = null;
                return;
            case 2:
                C18C.A07(c104294ms, "Netego SU unit needs to have an SU object");
                this.A0j = c104294ms.getId();
                this.A0e = EnumC41231vY.A0L;
                this.A0f = null;
                this.A09 = c104294ms;
                this.A0h = null;
                this.A07 = null;
                this.A0b = null;
                this.A0g = null;
                this.A0i = null;
                this.A0A = null;
                this.A0D = null;
                return;
            case 3:
                C18C.A07(c105854pw, "Netego quality survey needs to have a SimpleAction");
                this.A0j = c105854pw.getId();
                enumC41231vY = EnumC41231vY.A0F;
                break;
            case 4:
                C18C.A07(c105854pw, "Story creation upsell needs to have a SimpleAction");
                this.A0j = c105854pw.getId();
                enumC41231vY = EnumC41231vY.A0J;
                break;
            case 5:
                C18C.A07(null, "Netego suggested clips unit needs to have an suggested clips object");
                throw C00O.createAndThrow();
            case 6:
            case 7:
                C18C.A07(null, "Netego PFY unit needs to have an suggested products object");
                throw C00O.createAndThrow();
            case 8:
                C18C.A07(null, "Netego shops for you unit needs to have an suggested shops object");
                throw C00O.createAndThrow();
            case 9:
                C18C.A07(c105854pw, "Ads consent growth story needs to have a SimpleAction");
                this.A0j = c105854pw.getId();
                this.A0e = EnumC41231vY.A0C;
                this.A0h = c105854pw;
                this.A0f = null;
                this.A09 = null;
                this.A0b = null;
                this.A0g = null;
                this.A0i = null;
                this.A07 = null;
                this.A0D = null;
                return;
            case 10:
                C18C.A07(c105874py, "Bloks netego needs to have a BloksStoryNetego.");
                this.A0j = c105874py.A01.A05;
                this.A0e = EnumC41231vY.A0B;
                this.A0f = null;
                this.A09 = null;
                this.A0h = null;
                this.A0b = null;
                this.A0g = null;
                this.A0i = null;
                this.A07 = null;
                this.A0A = c105874py;
                this.A0D = null;
                return;
            case 11:
                C18C.A07(c105864px, "Netego trending prompts unit needs to have a prompts in story object");
                this.A0j = c105864px.getId();
                this.A0e = EnumC41231vY.A0N;
                this.A0f = null;
                this.A09 = null;
                this.A0h = null;
                this.A0b = null;
                this.A0g = null;
                this.A0i = null;
                this.A07 = c105864px;
                this.A0A = null;
                this.A0D = null;
                return;
            case IgReactQEModule.CONFIG_KEY_OFFSET /* 12 */:
                C18C.A07(c105854pw, "Insights netego needs to have a SimpleAction");
                this.A0j = c105854pw.getId();
                enumC41231vY = EnumC41231vY.A0D;
                break;
            case JITProfilePQR.HEADER_COMPRESSED_SIZE_OFFSET /* 13 */:
                C18C.A07(c105774po, "Share Comment to Story Netego needs to have a CommentShareNetego");
                this.A0j = c105774po.getId();
                this.A0e = EnumC41231vY.A0I;
                this.A0h = null;
                this.A0f = null;
                this.A09 = null;
                this.A0b = null;
                this.A0g = null;
                this.A0i = null;
                this.A07 = null;
                this.A0B = c105774po;
                this.A0D = null;
                return;
            case 14:
                C18C.A07(c105804pr, "Meta Gallery Stories Netegos need to have a MetaGalleryNetegoInfo");
                this.A0j = c105804pr.getId();
                this.A0e = EnumC41231vY.A0E;
                this.A0f = null;
                this.A09 = null;
                this.A0h = null;
                this.A0b = null;
                this.A0g = null;
                this.A0i = null;
                this.A07 = null;
                this.A0A = null;
                this.A0C = c105804pr;
                this.A0D = null;
                return;
            case Process.SIGTERM /* 15 */:
                C18C.A07(c105794pq, "Threads in stories unit Netego needs to have a ThreadsInStoriesUnitNetego");
                this.A0j = c105794pq.getId();
                this.A0e = EnumC41231vY.A0M;
                this.A0h = null;
                this.A0f = null;
                this.A09 = null;
                this.A0b = null;
                this.A0g = null;
                this.A0i = null;
                this.A07 = null;
                this.A0B = null;
                this.A0D = c105794pq;
                return;
            default:
                this.A0h = null;
                this.A0f = null;
                this.A09 = null;
                this.A0b = null;
                this.A0g = null;
                this.A0i = null;
                this.A0A = null;
                this.A07 = null;
                this.A0D = null;
                throw new IllegalArgumentException("Unsupported netego type");
        }
        this.A0e = enumC41231vY;
        this.A0h = c105854pw;
        this.A0f = null;
        this.A09 = null;
        this.A0b = null;
        this.A0g = null;
        this.A0i = null;
        this.A07 = null;
        this.A0A = null;
        this.A0D = null;
    }

    public C41181vS(C38321qM c38321qM, User user, String str) {
        this(c38321qM, EnumC41231vY.A09, user, str);
    }

    /* JADX WARN: Type inference failed for: r0v10, types: [X.4pu] */
    /* JADX WARN: Type inference failed for: r2v1, types: [X.1rF, java.lang.Object] */
    public C41181vS(C38541qi c38541qi, String str) {
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0L;
        this.A0X = 0L;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0e = EnumC41231vY.A02;
        this.mBrandResearchSurvey = c38541qi;
        final String str2 = c38541qi.A04;
        str2.getClass();
        final String str3 = c38541qi.A08;
        this.mBrandSurveyImpression = new C1NI(str2, str3) { // from class: X.4pu
            public final String A00;
            public final String A01;

            @Override // X.C1NI
            public final boolean CdW() {
                return true;
            }

            @Override // X.C1NI
            public final boolean CW9() {
                return true;
            }

            @Override // X.C1NI
            public final boolean CZq() {
                return false;
            }

            @Override // X.C1NI, X.InterfaceC38381qS, X.InterfaceC38411qV
            public final String getId() {
                return this.A00;
            }

            {
                this.A00 = str2;
                this.A01 = str3;
            }

            @Override // X.C1NI
            public final String BzL(UserSession userSession) {
                return this.A01;
            }
        };
        this.A0g = null;
        AtomicBoolean atomicBoolean = C38321qM.A0i;
        C38321qM c38321qM = new C38321qM(new C37761pD(null), new Object());
        this.A0b = c38321qM;
        c38321qM.A4P(str);
        c38321qM.A0C.EaD(str3);
        this.A0c = null;
        this.A0h = null;
        this.A0f = null;
        this.A0d = null;
        this.A09 = null;
        this.A07 = null;
        this.A0j = str2;
        this.A0i = null;
    }

    public C41181vS(C38641qv c38641qv, User user, String str, String str2) {
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0L;
        this.A0X = 0L;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0j = str2;
        this.A0e = EnumC41231vY.A0U;
        this.A0i = user;
        this.A0b = null;
        this.A0g = null;
        this.A0d = null;
        this.A0c = null;
        this.A0h = null;
        this.A0f = null;
        this.A09 = null;
        this.A07 = null;
        this.mBrandSurveyImpression = null;
        this.A03 = c38641qv;
    }

    public C41181vS(EnumC41231vY enumC41231vY, User user, String str, String str2) {
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0L;
        this.A0X = 0L;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0b = null;
        this.A0g = null;
        this.A0d = null;
        this.A0c = null;
        this.A0e = enumC41231vY;
        this.A0j = str2;
        this.A0i = user;
        this.A0h = null;
        this.A0f = null;
        this.A09 = null;
        this.A07 = null;
        this.mBrandSurveyImpression = null;
    }

    public C41181vS(C105814ps c105814ps, User user, String str) {
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0L;
        this.A0X = 0L;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0d = c105814ps;
        this.A0b = null;
        this.A0g = null;
        this.A0e = EnumC41231vY.A0P;
        this.A0j = c105814ps.A00.A3t;
        this.A0i = user;
        this.A0c = null;
        this.A0h = null;
        this.A0f = null;
        this.A09 = null;
        this.A07 = null;
        this.mBrandSurveyImpression = null;
    }

    public C41181vS(C105824pt c105824pt, EnumC41231vY enumC41231vY, String str) {
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0L;
        this.A0X = 0L;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0c = c105824pt;
        String str2 = c105824pt.A0e;
        str2.getClass();
        this.A0j = str2;
        this.A0i = c105824pt.A03();
        this.A0e = enumC41231vY;
        this.A0b = null;
        this.A0g = null;
        this.A0d = null;
        this.A0h = null;
        this.A0f = null;
        this.A09 = null;
        this.A07 = null;
        this.mBrandSurveyImpression = null;
    }

    /* JADX WARN: Type inference failed for: r1v2, types: [X.4ms, java.lang.Object] */
    public C41181vS(JMY jmy, String str, String str2) {
        EnumC41231vY enumC41231vY;
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        boolean z = false;
        this.A0W = false;
        this.A0Y = 0L;
        this.A0X = 0L;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0j = str2;
        if (jmy.C5f().equals("suggested_users_contact_import")) {
            enumC41231vY = EnumC41231vY.A05;
            this.A0e = enumC41231vY;
        } else if (jmy.C5f().equals("suggested_users_ayml_card")) {
            enumC41231vY = EnumC41231vY.A06;
            this.A0e = enumC41231vY;
        } else {
            enumC41231vY = EnumC41231vY.A07;
            this.A0e = enumC41231vY;
        }
        this.A0i = null;
        this.A0b = null;
        this.A0g = null;
        this.A0d = null;
        this.A0c = null;
        this.A0h = null;
        this.A0f = null;
        if (enumC41231vY == EnumC41231vY.A06 && jmy.BHh() != null) {
            ArrayList arrayList = new ArrayList();
            for (C47N c47n : jmy.BHh()) {
                C14360o3.A0B(c47n, 0);
                String algorithm = c47n.getAlgorithm();
                algorithm = algorithm == null ? "unknown" : algorithm;
                String ByJ = c47n.ByJ();
                ByJ = ByJ == null ? "" : ByJ;
                User CDj = c47n.CDj();
                if (CDj != null) {
                    int i = 6;
                    new C1DY(new C37761pD(null), i, z);
                    Boolean B7Q = c47n.B7Q();
                    Integer BQb = c47n.BQb();
                    List ByM = c47n.ByM();
                    String CEI = c47n.CEI();
                    new C1DY(new C37761pD(null), i, z);
                    arrayList.add(new C47G(null, null, CDj, B7Q, null, false, null, null, BQb, algorithm, null, null, null, ByJ, CEI, null, null, null, ByM, null));
                } else {
                    throw new IllegalStateException("Required value was null.");
                }
            }
            C38661qx c38661qx = new C38661qx(FeedItemType.A2L, "", "", "Suggested for you", "", arrayList, 15, 0L, false, true, true, true, true, false, true, true, true);
            ?? obj = new Object();
            obj.A00 = c38661qx;
            this.A09 = obj;
        } else {
            this.A09 = null;
        }
        this.A07 = null;
        this.mBrandSurveyImpression = null;
        this.A06 = jmy;
    }

    /* JADX WARN: Multi-variable type inference failed */
    public C41181vS(FanClubStoriesTeaserType fanClubStoriesTeaserType, UserSession userSession, User user, String str, long j) {
        C105784pp c105784pp;
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0L;
        this.A0X = 0L;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0b = null;
        this.A0g = null;
        this.A0d = null;
        this.A0c = null;
        this.A0e = EnumC41231vY.A0R;
        C06090Tz c06090Tz = C06090Tz.A06;
        this.A0S = C18U.A06(c06090Tz, userSession, 36326988008405218L);
        if (C18U.A06(c06090Tz, userSession, 36321563464836720L)) {
            c105784pp = new Object();
        } else {
            c105784pp = null;
        }
        this.A0Z = c105784pp;
        this.A0j = "fan_club_stories_teaser";
        this.A0i = user;
        this.A0h = null;
        this.A0f = null;
        this.A09 = null;
        this.A07 = null;
        this.mBrandSurveyImpression = null;
        this.A0X = j;
        this.A02 = fanClubStoriesTeaserType;
    }

    public C41181vS(UserSession userSession, EnumC41231vY enumC41231vY, C41023IEs c41023IEs, User user, String str, String str2) {
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0L;
        this.A0X = 0L;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0j = str2;
        this.A0e = enumC41231vY;
        this.A0i = user;
        this.A0b = null;
        this.A0g = null;
        this.A0d = null;
        this.A0c = null;
        this.A0h = null;
        this.A0f = null;
        this.A09 = null;
        this.A07 = null;
        if (AbstractC47902LDw.A02.compareAndSet(false, true)) {
            C14120nc.A00().ATO(new KLI());
        }
        this.A0E = new C41618Ib8(userSession, c41023IEs);
        this.mBrandSurveyImpression = null;
        Integer num = c41023IEs.A00.A01;
        if (num != null) {
            this.A0Y = num.longValue();
        }
    }

    public C41181vS(Integer num, List list, List list2) {
        String str;
        EnumC41231vY enumC41231vY;
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0L;
        this.A0X = 0L;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        int intValue = num.intValue();
        switch (intValue) {
            case 1:
                str = "story_interstitial_roll_call";
                break;
            case 2:
                str = "story_interstitial_fan_club_teaser";
                break;
            case 3:
                str = "story_interstitial_pog_garden_chaining";
                break;
            default:
                str = "story_interstitial_chaining";
                break;
        }
        this.A0k = str;
        this.A0b = null;
        this.A0g = null;
        this.A0d = null;
        this.A0c = null;
        this.A0i = null;
        this.A0j = str;
        this.A0h = null;
        this.A0f = null;
        this.mBrandSurveyImpression = null;
        if (intValue == 0) {
            this.A0K = list;
            this.A0L = list2;
            enumC41231vY = EnumC41231vY.A0S;
        } else if (intValue == 3) {
            this.A0K = list;
            this.A0L = list2;
            enumC41231vY = EnumC41231vY.A0T;
        } else if (intValue == 1) {
            enumC41231vY = EnumC41231vY.A0Q;
        } else if (intValue == 2) {
            enumC41231vY = EnumC41231vY.A0R;
        } else {
            this.A0K = null;
            this.A0L = null;
            throw new IllegalArgumentException("unsupported story interstitial type");
        }
        this.A0e = enumC41231vY;
    }
}
