package X;

import java.io.Serializable;

/* renamed from: X.1wa, reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C41861wa implements Serializable {
    public final int A00;
    public final int A01;
    public final long A02;
    public final boolean A03;
    public final boolean A04;
    public final boolean A05;
    public final boolean A06;
    public final boolean A07;
    public final boolean A08;
    public final boolean A09;
    public final boolean A0A;
    public final boolean A0B;
    public final boolean A0C;
    public final boolean A0D;
    public final boolean A0E;
    public final boolean A0F;
    public final boolean A0G;
    public final boolean A0H;
    public final boolean A0I;
    public final boolean A0J;
    public final boolean A0K;
    public final boolean A0L;
    public final boolean A0M;
    public final boolean A0N;
    public final boolean A0O;
    public final boolean A0P;
    public final boolean A0Q;
    public final boolean A0R;
    public final boolean A0S;
    public final boolean A0T;
    public final boolean A0U;
    public final boolean A0V;
    public final boolean A0W;
    public final boolean A0X;
    public final boolean A0Y;
    public final boolean A0Z;
    public final boolean A0a;
    public final boolean A0b;
    public final boolean A0c;
    public final boolean A0d;
    public final boolean A0e;
    public final boolean A0f;
    public final boolean A0g;
    public final boolean A0h;
    public final boolean A0i;
    public final boolean A0j;
    public final boolean A0k;
    public final boolean A0l;

    public C41861wa(int i, int i2, long j, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12, boolean z13, boolean z14, boolean z15, boolean z16, boolean z17, boolean z18, boolean z19, boolean z20, boolean z21, boolean z22, boolean z23, boolean z24, boolean z25, boolean z26, boolean z27, boolean z28, boolean z29, boolean z30, boolean z31, boolean z32, boolean z33, boolean z34, boolean z35, boolean z36, boolean z37, boolean z38, boolean z39, boolean z40, boolean z41, boolean z42, boolean z43, boolean z44, boolean z45) {
        this.A0X = z;
        this.A0Q = z2;
        this.A0l = z3;
        this.A0k = z4;
        this.A0j = z5;
        this.A0i = z6;
        this.A0I = z7;
        this.A0O = z8;
        this.A0U = z9;
        this.A0V = z10;
        this.A0F = z11;
        this.A0G = z12;
        this.A0T = z13;
        this.A0g = z14;
        this.A0N = z15;
        this.A0P = z16;
        this.A0M = z17;
        this.A08 = z18;
        this.A0L = z19;
        this.A0C = z20;
        this.A02 = j;
        this.A0J = z21;
        this.A01 = i;
        this.A0H = z22;
        this.A07 = z23;
        this.A0E = z24;
        this.A0S = z25;
        this.A0W = z26;
        this.A0Y = z27;
        this.A0B = z28;
        this.A06 = z29;
        this.A0D = z30;
        this.A0R = z31;
        this.A0d = z32;
        this.A04 = z33;
        this.A0h = z34;
        this.A0c = z35;
        this.A0f = z36;
        this.A0K = z37;
        this.A09 = z38;
        this.A03 = z39;
        this.A00 = i2;
        this.A0b = z40;
        this.A0a = z41;
        this.A05 = z42;
        this.A0A = z43;
        this.A0Z = z44;
        this.A0e = z45;
    }
}
