package X;

import com.facebook.common.dextricks.Constants;
import com.facebook.video.heroplayer.setting.FbAutogeneratedSettings;
import com.facebook.video.heroplayer.setting.HeroPlayerSetting;
import com.instagram.direct.stella.StellaIpcDirectMessagingServiceClient;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Locale;
import java.util.Map;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.webrtc.CameraVideoCapturer;

/* renamed from: X.1wX, reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C41831wX {
    public int A02;
    public int A0W;
    public int A0c;
    public long A0h;
    public C42301xK A0i;
    public C42301xK A0j;
    public C42301xK A0k;
    public C42301xK A0m;
    public C42301xK A0n;
    public C42301xK A0p;
    public C22Z A11;
    public String A15;
    public boolean A1N;
    public boolean A1Z;
    public boolean A1c;
    public boolean A1j;
    public boolean A1n;
    public boolean A1t;
    public boolean A1u;
    public boolean A22;
    public boolean A25;
    public boolean A2A;
    public boolean A2G;
    public boolean A2I;
    public boolean A2L;
    public boolean A2M;
    public boolean A2W;
    public boolean A2c;
    public boolean A2f;
    public boolean A2j;
    public boolean A2k;
    public boolean A2l;
    public boolean A2r;
    public boolean A2z;
    public boolean A31;
    public boolean A33;
    public boolean A38;
    public boolean A3E;
    public boolean A3I;
    public boolean A3P;
    public boolean A3X;
    public C41861wa A0w = new C41861wa(0, 100, -1, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false);
    public FbAutogeneratedSettings A0x = HeroPlayerSetting.A3d;
    public boolean A2e = false;
    public boolean A1k = false;
    public boolean A2Q = true;
    public boolean A1b = false;
    public String A16 = "ExoService";
    public boolean A3N = true;
    public boolean A2J = true;
    public boolean A3U = false;
    public C41961wm A0v = new C41961wm(null, null, 0.3d, 0.1d, 104857600, 1048576, 0, 0, -1, -1, 10, 1, 0, StellaIpcDirectMessagingServiceClient.KEEP_CONNECTION_ALIVE_MS, 3600000, 0, false, true, false, false, false, false, false, false, false, false, false, false, false);
    public boolean A37 = true;
    public boolean A2K = false;
    public C41991wp A12 = new C41991wp(500, CameraVideoCapturer.CameraStatistics.CAMERA_OBSERVER_PERIOD_MS);
    public C41991wp A13 = new C41991wp(0, 0);
    public boolean A1Q = false;
    public C42011wr A0z = new C42011wr(0.0f, 0.0f, 0, 0, 0, 0, 0, 0);
    public boolean A30 = false;
    public boolean A34 = false;
    public C42081wy A0t = new C42081wy();
    public C42121x2 A0s = C42121x2.A00;
    public C42181x8 A0r = new Object();
    public C42191x9 A0q = new Object();
    public boolean A2p = false;
    public boolean A1X = false;
    public C42231xD A0u = new C42231xD();
    public boolean A28 = false;
    public C42261xG A14 = new Object();
    public int A07 = 12323;
    public int A06 = 14151;
    public boolean A24 = false;
    public boolean A2q = false;
    public boolean A2Y = false;
    public boolean A35 = false;
    public boolean A1L = false;
    public boolean A1p = false;
    public int A05 = 0;
    public int A0I = 3;
    public int A0d = 3;
    public boolean A2y = false;
    public C42301xK A0l = new C42301xK(100000, C8S8.DEFAULT_SWIPE_ANIMATION_DURATION, 500, 1000);
    public C42301xK A0o = new C42301xK(CameraVideoCapturer.CameraStatistics.CAMERA_OBSERVER_PERIOD_MS, 2000000, 550000, 150000);
    public boolean A1x = false;
    public boolean A3Z = false;
    public boolean A3M = false;
    public boolean A2V = false;
    public boolean A1K = false;
    public boolean A3D = false;
    public boolean A1l = false;
    public boolean A1w = false;
    public boolean A3A = false;
    public boolean A2n = false;
    public boolean A1H = false;
    public boolean A2F = false;
    public boolean A2E = false;
    public boolean A3S = false;
    public int A0L = 2;
    public int A0M = 4;
    public boolean A2g = false;
    public boolean A2h = false;
    public boolean A3T = false;
    public boolean A2a = false;
    public boolean A2Z = false;
    public boolean A3b = false;
    public boolean A3a = false;
    public boolean A2s = false;
    public boolean A3J = false;
    public boolean A3C = false;
    public boolean A2T = false;
    public boolean A3Y = false;
    public boolean A3R = false;
    public int A0F = CameraVideoCapturer.CameraStatistics.CAMERA_FREEZE_REPORT_TIMOUT_MS;
    public boolean A3H = false;
    public boolean A3G = false;
    public boolean A2i = false;
    public int A0Y = 1;
    public boolean A3W = false;
    public boolean A3V = false;
    public boolean A1S = false;
    public boolean A2o = false;
    public boolean A2H = false;
    public boolean A3O = false;
    public int A0S = 0;
    public boolean A36 = false;
    public int A0T = CameraVideoCapturer.CameraStatistics.CAMERA_FREEZE_REPORT_TIMOUT_MS;
    public boolean A2u = true;
    public boolean A1m = false;
    public boolean A39 = false;
    public boolean A3c = false;
    public boolean A2P = false;
    public int A0K = Constants.LOAD_RESULT_DEX2OAT_TRY_PERIODIC_PGO_COMP;
    public int A0J = Constants.LOAD_RESULT_PGO_ATTEMPTED;
    public int A0H = 0;
    public int A0G = 12000;
    public boolean A2X = true;
    public boolean A2B = false;
    public boolean A1h = false;
    public boolean A32 = false;
    public boolean A2O = false;
    public boolean A1W = false;
    public int A0U = 0;
    public int A0V = 0;
    public int A04 = 0;
    public boolean A1M = false;
    public boolean A2w = false;
    public boolean A2x = false;
    public HashMap A17 = new HashMap();
    public boolean A1I = false;
    public int A0B = 1;
    public int A09 = 1;
    public int A0A = 100;
    public boolean A1O = false;
    public long A0f = 0;
    public boolean A1J = false;
    public int A0R = 0;
    public int A0O = -1;
    public int A0X = 8500;
    public boolean A1g = false;
    public boolean A1f = false;
    public boolean A2t = false;
    public boolean A3B = false;
    public double A00 = 1.0d;
    public boolean A3K = false;
    public int A0N = 0;
    public boolean A29 = false;
    public java.util.Set A19 = new HashSet();
    public boolean A27 = false;
    public Map A18 = new HashMap();
    public boolean A2D = false;
    public int A0D = 1;
    public int A0Q = 0;
    public boolean A1q = false;
    public boolean A2N = false;
    public int A0e = 64;
    public boolean A2C = false;
    public int A0E = 30000;
    public int A0a = -1;
    public int A0C = CameraVideoCapturer.CameraStatistics.CAMERA_FREEZE_REPORT_TIMOUT_MS;
    public int A01 = CameraVideoCapturer.CameraStatistics.CAMERA_FREEZE_REPORT_TIMOUT_MS;
    public java.util.Set A1D = new HashSet();
    public java.util.Set A1C = new HashSet();
    public java.util.Set A1E = new HashSet();
    public boolean A2m = false;
    public boolean A1G = false;
    public int A0Z = 3;
    public boolean A3F = false;
    public boolean A1P = false;
    public boolean A2d = false;
    public boolean A1o = false;
    public boolean A21 = false;
    public boolean A23 = false;
    public boolean A1a = false;
    public boolean A2v = false;
    public boolean A2b = false;
    public C42351xP A10 = new C42351xP();
    public boolean A1T = false;
    public boolean A3Q = false;
    public int A0b = 0;
    public java.util.Set A1B = new HashSet();
    public java.util.Set A1A = new HashSet();
    public java.util.Set A1F = new HashSet();
    public boolean A2U = false;
    public int A0P = 1000;
    public boolean A1v = true;
    public boolean A1s = false;
    public boolean A2R = false;
    public boolean A1y = false;
    public boolean A1z = false;
    public long A0g = 0;
    public boolean A1r = false;
    public int A08 = 0;
    public int A03 = 0;
    public boolean A1V = false;
    public boolean A3L = false;
    public boolean A1R = false;
    public boolean A1e = false;
    public boolean A1d = false;
    public boolean A26 = false;
    public boolean A1Y = false;
    public boolean A2S = false;
    public boolean A1i = false;
    public boolean A1U = false;
    public boolean A20 = false;
    public C42361xQ A0y = null;

    public final void A01() {
        this.A1b = true;
    }

    public final void A02() {
        this.A1K = true;
    }

    public final void A03() {
        this.A1L = true;
    }

    public final void A04() {
        this.A1R = true;
    }

    public final void A07() {
        this.A1S = true;
    }

    public final void A08() {
        this.A1U = true;
    }

    public final void A09() {
        this.A1X = true;
    }

    public final void A0A() {
        this.A1G = true;
    }

    public final void A0B() {
        this.A1j = true;
    }

    public final void A0C() {
        this.A1l = true;
    }

    public final void A0D() {
        this.A1o = true;
    }

    public final void A0E() {
        this.A1q = true;
    }

    public final void A0F() {
        this.A21 = true;
    }

    public final void A0G() {
        this.A22 = true;
    }

    public final void A0H() {
        this.A23 = true;
    }

    public final void A0I() {
        this.A24 = true;
    }

    public final void A0J() {
        this.A28 = true;
    }

    public final void A0K() {
        this.A2I = true;
    }

    public final void A0L() {
        this.A2K = true;
    }

    public final void A0M() {
        this.A2L = true;
    }

    public final void A0N() {
        this.A2M = true;
    }

    public final void A0O() {
        this.A2X = false;
    }

    public final void A0P() {
        this.A2V = true;
    }

    public final void A0Q() {
        this.A2i = true;
    }

    public final void A0R() {
        this.A2j = true;
    }

    public final void A0S() {
        this.A2k = true;
    }

    public final void A0T() {
        this.A3c = true;
    }

    public final void A0U() {
        this.A2b = true;
    }

    public final void A0V() {
        this.A2c = true;
    }

    public final void A0W() {
        this.A2e = true;
    }

    public final void A0X() {
        this.A2g = true;
    }

    public final void A0Y() {
        this.A2m = true;
    }

    public final void A0Z() {
        this.A2n = true;
    }

    public final void A0e() {
        this.A2p = true;
    }

    public final void A0f() {
        this.A2r = true;
    }

    public final void A0g() {
        this.A2u = false;
    }

    public final void A0h() {
        this.A2v = true;
    }

    public final void A0i() {
        this.A31 = true;
    }

    public final void A0j() {
        this.A33 = true;
    }

    public final void A0k() {
        this.A38 = true;
    }

    public final void A0l() {
        this.A39 = true;
    }

    public final void A0m() {
        this.A3G = true;
    }

    public final void A0n() {
        this.A3H = true;
    }

    public final void A0o() {
        this.A3I = true;
    }

    public final void A0p() {
        this.A3K = true;
    }

    public final void A0q() {
        this.A3N = false;
    }

    public final void A0r() {
        this.A3T = true;
    }

    public final void A0s() {
        this.A3U = true;
    }

    public final void A0t() {
        this.A3V = true;
    }

    public final void A0u() {
        this.A3b = true;
    }

    public final HeroPlayerSetting A00() {
        return new HeroPlayerSetting(this);
    }

    public final void A05() {
        this.A06 = 12000;
    }

    public final void A06() {
        this.A07 = 6000;
    }

    public final void A0c() {
        this.A0J = 1048576;
    }

    public final void A0d() {
        this.A0K = 1048576;
    }

    public final void A0v() {
        this.A0e = 56;
    }

    public final void A0w(double d) {
        this.A00 = d;
    }

    public final void A0x(int i) {
        this.A01 = i;
    }

    public final void A0y(int i) {
        this.A02 = i;
    }

    public final void A0z(int i) {
        this.A03 = i;
    }

    public final void A10(int i) {
        this.A04 = i;
    }

    public final void A11(int i) {
        this.A05 = i;
    }

    public final void A12(int i) {
        this.A08 = i;
    }

    public final void A13(int i) {
        this.A09 = i;
    }

    public final void A14(int i) {
        this.A0A = i;
    }

    public final void A15(int i) {
        this.A0B = i;
    }

    public final void A16(int i) {
        this.A0C = i;
    }

    public final void A17(int i) {
        this.A0D = i;
    }

    public final void A18(int i) {
        this.A0E = i;
    }

    public final void A19(int i) {
        this.A0F = i;
    }

    public final void A1A(int i) {
        this.A0I = i;
    }

    public final void A1B(int i) {
        this.A0L = i;
    }

    public final void A1C(int i) {
        this.A0M = i;
    }

    public final void A1D(int i) {
        this.A0N = i;
    }

    public final void A1E(int i) {
        this.A0O = i;
    }

    public final void A1F(int i) {
        this.A0P = i;
    }

    public final void A1G(int i) {
        this.A0Q = i;
    }

    public final void A1H(int i) {
        this.A0R = i;
    }

    public final void A1I(int i) {
        this.A0S = i;
    }

    public final void A1J(int i) {
        this.A0T = i;
    }

    public final void A1K(int i) {
        this.A0U = i;
    }

    public final void A1L(int i) {
        this.A0V = i;
    }

    public final void A1M(int i) {
        this.A0W = i;
    }

    public final void A1N(int i) {
        this.A0X = i;
    }

    public final void A1O(int i) {
        this.A0Y = i;
    }

    public final void A1P(int i) {
        this.A0Z = i;
    }

    public final void A1Q(int i) {
        this.A0a = i;
    }

    public final void A1R(int i) {
        this.A0b = i;
    }

    public final void A1S(int i) {
        this.A0c = i;
    }

    public final void A1T(int i) {
        this.A0d = i;
    }

    public final void A1U(long j) {
        this.A0f = j;
    }

    public final void A1V(long j) {
        this.A0g = j;
    }

    public final void A1W(long j) {
        this.A0h = j;
    }

    public final void A1X(C42301xK c42301xK) {
        this.A0i = c42301xK;
    }

    public final void A1Y(C42301xK c42301xK) {
        this.A0j = c42301xK;
    }

    public final void A1Z(C42301xK c42301xK) {
        this.A0k = c42301xK;
    }

    public final void A1a(C42301xK c42301xK) {
        this.A0m = c42301xK;
    }

    public final void A1b(C42301xK c42301xK) {
        this.A0n = c42301xK;
    }

    public final void A1c(C42301xK c42301xK) {
        this.A0o = c42301xK;
    }

    public final void A1d(C42301xK c42301xK) {
        this.A0p = c42301xK;
    }

    public final void A1e(C42121x2 c42121x2) {
        this.A0s = c42121x2;
    }

    public final void A1f(C42081wy c42081wy) {
        this.A0t = c42081wy;
    }

    public final void A1g(C42231xD c42231xD) {
        this.A0u = c42231xD;
    }

    public final void A1h(C41961wm c41961wm) {
        this.A0v = c41961wm;
    }

    public final void A1i(C41861wa c41861wa) {
        this.A0w = c41861wa;
    }

    public final void A1j(C42361xQ c42361xQ) {
        this.A0y = c42361xQ;
    }

    public final void A1k(C42011wr c42011wr) {
        this.A0z = c42011wr;
    }

    public final void A1l(C42351xP c42351xP) {
        this.A10 = c42351xP;
    }

    public final void A1m(C22Z c22z) {
        this.A11 = c22z;
    }

    public final void A1o(String str) {
        this.A15 = str;
    }

    public final void A1p(Map map) {
        this.A18 = map;
    }

    public final void A1q(java.util.Set set) {
        this.A1F = set;
    }

    public final void A1r(boolean z) {
        this.A1H = z;
    }

    public final void A1s(boolean z) {
        this.A1I = z;
    }

    public final void A1t(boolean z) {
        this.A1J = z;
    }

    public final void A1u(boolean z) {
        this.A1M = z;
    }

    public final void A1v(boolean z) {
        this.A1N = z;
    }

    public final void A1w(boolean z) {
        this.A1O = z;
    }

    public final void A1x(boolean z) {
        this.A1P = z;
    }

    public final void A1y(boolean z) {
        this.A1Q = z;
    }

    public final void A1z(boolean z) {
        this.A1T = z;
    }

    public final void A20(boolean z) {
        this.A1V = z;
    }

    public final void A21(boolean z) {
        this.A1W = z;
    }

    public final void A22(boolean z) {
        this.A1Z = z;
    }

    public final void A23(boolean z) {
        this.A1a = z;
    }

    public final void A24(boolean z) {
        this.A1c = z;
    }

    public final void A25(boolean z) {
        this.A1d = z;
    }

    public final void A26(boolean z) {
        this.A1e = z;
    }

    public final void A27(boolean z) {
        this.A1f = z;
    }

    public final void A28(boolean z) {
        this.A1g = z;
    }

    public final void A29(boolean z) {
        this.A1h = z;
    }

    public final void A2A(boolean z) {
        this.A1i = z;
    }

    public final void A2B(boolean z) {
        this.A1k = z;
    }

    public final void A2C(boolean z) {
        this.A1m = z;
    }

    public final void A2D(boolean z) {
        this.A1n = z;
    }

    public final void A2E(boolean z) {
        this.A1p = z;
    }

    public final void A2F(boolean z) {
        this.A1r = z;
    }

    public final void A2G(boolean z) {
        this.A1s = z;
    }

    public final void A2H(boolean z) {
        this.A1t = z;
    }

    public final void A2I(boolean z) {
        this.A1u = z;
    }

    public final void A2J(boolean z) {
        this.A1v = z;
    }

    public final void A2K(boolean z) {
        this.A1w = z;
    }

    public final void A2L(boolean z) {
        this.A1x = z;
    }

    public final void A2M(boolean z) {
        this.A1y = z;
    }

    public final void A2N(boolean z) {
        this.A1z = z;
    }

    public final void A2O(boolean z) {
        this.A20 = z;
    }

    public final void A2P(boolean z) {
        this.A25 = z;
    }

    public final void A2Q(boolean z) {
        this.A26 = z;
    }

    public final void A2R(boolean z) {
        this.A27 = z;
    }

    public final void A2S(boolean z) {
        this.A29 = z;
    }

    public final void A2T(boolean z) {
        this.A2A = z;
    }

    public final void A2U(boolean z) {
        this.A2B = z;
    }

    public final void A2V(boolean z) {
        this.A2C = z;
    }

    public final void A2W(boolean z) {
        this.A2D = z;
    }

    public final void A2X(boolean z) {
        this.A2E = z;
    }

    public final void A2Y(boolean z) {
        this.A2F = z;
    }

    public final void A2Z(boolean z) {
        this.A2G = z;
    }

    public final void A2a(boolean z) {
        this.A2H = z;
    }

    public final void A2b(boolean z) {
        this.A2J = z;
    }

    public final void A2c(boolean z) {
        this.A2N = z;
    }

    public final void A2d(boolean z) {
        this.A2O = z;
    }

    public final void A2e(boolean z) {
        this.A2P = z;
    }

    public final void A2f(boolean z) {
        this.A2Q = z;
    }

    public final void A2g(boolean z) {
        this.A2R = z;
    }

    public final void A2h(boolean z) {
        this.A2S = z;
    }

    public final void A2i(boolean z) {
        this.A2T = z;
    }

    public final void A2j(boolean z) {
        this.A2U = z;
    }

    public final void A2k(boolean z) {
        this.A2W = z;
    }

    public final void A2l(boolean z) {
        this.A2Y = z;
    }

    public final void A2m(boolean z) {
        this.A2Z = z;
    }

    public final void A2n(boolean z) {
        this.A2a = z;
    }

    public final void A2o(boolean z) {
        this.A2d = z;
    }

    public final void A2p(boolean z) {
        this.A2f = z;
    }

    public final void A2q(boolean z) {
        this.A2h = z;
    }

    public final void A2r(boolean z) {
        this.A2l = z;
    }

    public final void A2s(boolean z) {
        this.A2o = z;
    }

    public final void A2t(boolean z) {
        this.A2q = z;
    }

    public final void A2u(boolean z) {
        this.A37 = z;
    }

    public final void A2v(boolean z) {
        this.A2s = z;
    }

    public final void A2w(boolean z) {
        this.A2t = z;
    }

    public final void A2x(boolean z) {
        this.A2w = z;
    }

    public final void A2y(boolean z) {
        this.A2x = z;
    }

    public final void A2z(boolean z) {
        this.A2y = z;
    }

    public final void A30(boolean z) {
        this.A2z = z;
    }

    public final void A31(boolean z) {
        this.A30 = z;
    }

    public final void A32(boolean z) {
        this.A32 = z;
    }

    public final void A33(boolean z) {
        this.A34 = z;
    }

    public final void A34(boolean z) {
        this.A35 = z;
    }

    public final void A35(boolean z) {
        this.A36 = z;
    }

    public final void A36(boolean z) {
        this.A3A = z;
    }

    public final void A37(boolean z) {
        this.A3B = z;
    }

    public final void A38(boolean z) {
        this.A3C = z;
    }

    public final void A39(boolean z) {
        this.A3D = z;
    }

    public final void A3A(boolean z) {
        this.A3E = z;
    }

    public final void A3B(boolean z) {
        this.A3F = z;
    }

    public final void A3C(boolean z) {
        this.A3J = z;
    }

    public final void A3D(boolean z) {
        this.A3L = z;
    }

    public final void A3E(boolean z) {
        this.A3M = z;
    }

    public final void A3F(boolean z) {
        this.A3O = z;
    }

    public final void A3G(boolean z) {
        this.A3P = z;
    }

    public final void A3H(boolean z) {
        this.A3Q = z;
    }

    public final void A3I(boolean z) {
        this.A3S = z;
    }

    public final void A3J(boolean z) {
        this.A3W = z;
    }

    public final void A3K(boolean z) {
        this.A3X = z;
    }

    public final void A3L(boolean z) {
        this.A3Z = z;
    }

    public final void A3M(boolean z) {
        this.A3a = z;
    }

    public final void A3N(boolean z) {
        this.A3R = z;
    }

    public final void A3O(boolean z) {
        this.A3Y = z;
    }

    public final void A0a() {
        this.A0G = 45000;
    }

    public final void A0b() {
        this.A0H = 33000;
    }

    public final void A1n(String str) {
        int i;
        if (str.isEmpty()) {
            this.A17 = new HashMap();
        }
        HashMap hashMap = new HashMap();
        try {
            JSONArray jSONArray = (JSONArray) new JSONObject(str).get("blocklist");
            for (int i2 = 0; i2 < jSONArray.length(); i2++) {
                JSONObject jSONObject = jSONArray.getJSONObject(i2);
                try {
                    String lowerCase = jSONObject.getString("decoderName").toLowerCase(Locale.ROOT);
                    if (jSONObject.has("minSdkVersion")) {
                        i = jSONObject.getInt("minSdkVersion");
                    } else {
                        i = -1;
                    }
                    hashMap.put(lowerCase, Integer.valueOf(i));
                } catch (ExceptionInInitializerError | RuntimeException | JSONException unused) {
                }
            }
        } catch (ExceptionInInitializerError | RuntimeException | JSONException unused2) {
        }
        this.A17 = hashMap;
    }
}
