package X;

import com.instagram.model.reels.sponsored.AutoGeneratedCardType;

/* renamed from: X.JCf, reason: case insensitive filesystem */
/* loaded from: classes7.dex */
public final class C43312JCf extends C0YY implements InterfaceC16660sJ {
    public static final C43312JCf A00 = new C43312JCf();

    public C43312JCf() {
        super(1);
    }

    @Override // X.InterfaceC16660sJ
    public final /* bridge */ /* synthetic */ Object invoke(Object obj) {
        AutoGeneratedCardType autoGeneratedCardType = (AutoGeneratedCardType) obj;
        C14360o3.A0B(autoGeneratedCardType, 0);
        return autoGeneratedCardType.A00;
    }
}
