package X;

/* renamed from: X.2Xa, reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C51272Xa {
    public final int A00;
    public final String A01;
    public final String A02;
    public final int A03;

    public final boolean equals(Object obj) {
        if (this != obj) {
            if (obj == null || getClass() != obj.getClass()) {
                return false;
            }
            C51272Xa c51272Xa = (C51272Xa) obj;
            if (this.A00 == c51272Xa.A00) {
                String str = this.A02;
                String str2 = c51272Xa.A02;
                if (str == str2 || str.equals(str2)) {
                    String str3 = this.A01;
                    String str4 = c51272Xa.A01;
                    if (str3 != str4 && (str3 == null || !str3.equals(str4))) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                return false;
            }
        }
        return true;
    }

    public final int hashCode() {
        return this.A03;
    }

    public final String toString() {
        String str;
        StringBuilder sb = new StringBuilder();
        sb.append("TransitionId{");
        sb.append("\"");
        sb.append(this.A02);
        sb.append("\", ");
        int i = this.A00;
        if (i != 1) {
            if (i != 2) {
                str = "AUTOGENERATED";
            } else {
                sb.append("SCOPED(");
                sb.append(this.A01);
                str = ")";
            }
        } else {
            str = "GLOBAL";
        }
        sb.append(str);
        sb.append("}");
        return sb.toString();
    }

    public C51272Xa(int i, String str, String str2) {
        int hashCode;
        this.A00 = i;
        this.A02 = str;
        this.A01 = str2;
        int hashCode2 = str.hashCode() * 31 * 31;
        if (str2 == null) {
            hashCode = 0;
        } else {
            hashCode = str2.hashCode();
        }
        this.A03 = hashCode2 + (hashCode * 31) + i;
    }
}
