package X;

import android.R;

/* renamed from: X.65N, reason: invalid class name */
/* loaded from: classes3.dex */
public abstract class C65N {
    public static final int[] A00 = {R.attr.background, R.attr.touchscreenBlocksFocus, R.attr.keyboardNavigationCluster, com.facebook.R.attr.elevation, com.facebook.R.attr.expanded, com.facebook.R.attr.liftOnScroll, com.facebook.R.attr.liftOnScrollTargetViewId, com.facebook.R.attr.statusBarForeground};
    public static final int[] A01 = {com.facebook.R.attr.layout_scrollFlags, com.facebook.R.attr.layout_scrollInterpolator};
    public static final int[] A02 = {com.facebook.R.attr.backgroundColor, com.facebook.R.attr.badgeGravity, com.facebook.R.attr.badgeTextColor, com.facebook.R.attr.horizontalOffset, com.facebook.R.attr.maxCharacterCount, com.facebook.R.attr.number, com.facebook.R.attr.verticalOffset};
    public static final int[] A03 = {R.attr.indeterminate, com.facebook.R.attr.hideAnimationBehavior, com.facebook.R.attr.indicatorColor, com.facebook.R.attr.minHideDelay, com.facebook.R.attr.showAnimationBehavior, com.facebook.R.attr.showDelay, com.facebook.R.attr.trackColor, com.facebook.R.attr.trackCornerRadius, com.facebook.R.attr.trackThickness};
    public static final int[] A04 = {R.attr.maxWidth, R.attr.elevation, com.facebook.R.attr.backgroundTint, com.facebook.R.attr.behavior_draggable, com.facebook.R.attr.behavior_expandedOffset, com.facebook.R.attr.behavior_fitToContents, com.facebook.R.attr.behavior_halfExpandedRatio, com.facebook.R.attr.behavior_hideable, com.facebook.R.attr.behavior_peekHeight, com.facebook.R.attr.behavior_saveFlags, com.facebook.R.attr.behavior_skipCollapsed, com.facebook.R.attr.gestureInsetBottomIgnored, com.facebook.R.attr.paddingBottomSystemWindowInsets, com.facebook.R.attr.paddingLeftSystemWindowInsets, com.facebook.R.attr.paddingRightSystemWindowInsets, com.facebook.R.attr.paddingTopSystemWindowInsets, com.facebook.R.attr.shapeAppearance, com.facebook.R.attr.shapeAppearanceOverlay};
    public static final int[] A05 = {R.attr.minWidth, R.attr.minHeight, com.facebook.R.attr.cardBackgroundColor, com.facebook.R.attr.cardCornerRadius, com.facebook.R.attr.cardElevation, com.facebook.R.attr.cardMaxElevation, com.facebook.R.attr.cardPreventCornerOverlap, com.facebook.R.attr.cardUseCompatPadding, com.facebook.R.attr.contentPadding, com.facebook.R.attr.contentPaddingBottom, com.facebook.R.attr.contentPaddingLeft, com.facebook.R.attr.contentPaddingRight, com.facebook.R.attr.contentPaddingTop};
    public static final int[] A06 = {R.attr.textAppearance, R.attr.textSize, R.attr.textColor, R.attr.ellipsize, R.attr.maxWidth, R.attr.text, R.attr.checkable, com.facebook.R.attr.checkedIcon, com.facebook.R.attr.checkedIconEnabled, com.facebook.R.attr.checkedIconTint, com.facebook.R.attr.checkedIconVisible, com.facebook.R.attr.chipBackgroundColor, com.facebook.R.attr.chipCornerRadius, com.facebook.R.attr.chipEndPadding, com.facebook.R.attr.chipIcon, com.facebook.R.attr.chipIconEnabled, com.facebook.R.attr.chipIconSize, com.facebook.R.attr.chipIconTint, com.facebook.R.attr.chipIconVisible, com.facebook.R.attr.chipMinHeight, com.facebook.R.attr.chipMinTouchTargetSize, com.facebook.R.attr.chipStartPadding, com.facebook.R.attr.chipStrokeColor, com.facebook.R.attr.chipStrokeWidth, com.facebook.R.attr.chipSurfaceColor, com.facebook.R.attr.closeIcon, com.facebook.R.attr.closeIconEnabled, com.facebook.R.attr.closeIconEndPadding, com.facebook.R.attr.closeIconSize, com.facebook.R.attr.closeIconStartPadding, com.facebook.R.attr.closeIconTint, com.facebook.R.attr.closeIconVisible, com.facebook.R.attr.ensureMinTouchTargetSize, com.facebook.R.attr.hideMotionSpec, com.facebook.R.attr.iconEndPadding, com.facebook.R.attr.iconStartPadding, com.facebook.R.attr.rippleColor, com.facebook.R.attr.shapeAppearance, com.facebook.R.attr.shapeAppearanceOverlay, com.facebook.R.attr.showMotionSpec, com.facebook.R.attr.textEndPadding, com.facebook.R.attr.textStartPadding};
    public static final int[] A07 = {com.facebook.R.attr.checkedChip, com.facebook.R.attr.chipSpacing, com.facebook.R.attr.chipSpacingHorizontal, com.facebook.R.attr.chipSpacingVertical, com.facebook.R.attr.selectionRequired, com.facebook.R.attr.singleLine, com.facebook.R.attr.singleSelection};
    public static final int[] A08 = {com.facebook.R.attr.indicatorDirectionCircular, com.facebook.R.attr.indicatorInset, com.facebook.R.attr.indicatorSize};
    public static final int[] A09 = {com.facebook.R.attr.clockFaceBackgroundColor, com.facebook.R.attr.clockNumberTextColor};
    public static final int[] A0A = {com.facebook.R.attr.clockHandColor, com.facebook.R.attr.materialCircleRadius, com.facebook.R.attr.selectorSize};
    public static final int[] A0B = {com.facebook.R.attr.collapsedTitleGravity, com.facebook.R.attr.collapsedTitleTextAppearance, com.facebook.R.attr.contentScrim, com.facebook.R.attr.expandedTitleGravity, com.facebook.R.attr.expandedTitleMargin, com.facebook.R.attr.expandedTitleMarginBottom, com.facebook.R.attr.expandedTitleMarginEnd, com.facebook.R.attr.expandedTitleMarginStart, com.facebook.R.attr.expandedTitleMarginTop, com.facebook.R.attr.expandedTitleTextAppearance, com.facebook.R.attr.extraMultilineHeightEnabled, com.facebook.R.attr.forceApplySystemWindowInsetTop, com.facebook.R.attr.maxLines, com.facebook.R.attr.scrimAnimationDuration, com.facebook.R.attr.scrimVisibleHeightTrigger, com.facebook.R.attr.statusBarScrim, com.facebook.R.attr.title, com.facebook.R.attr.titleCollapseMode, com.facebook.R.attr.titleEnabled, com.facebook.R.attr.toolbarId};
    public static final int[] A0C = {com.facebook.R.attr.layout_collapseMode, com.facebook.R.attr.layout_collapseParallaxMultiplier};
    public static final int[] A0D = {com.facebook.R.attr.behavior_autoHide, com.facebook.R.attr.behavior_autoShrink};
    public static final int[] A0E = {com.facebook.R.attr.behavior_autoHide};
    public static final int[] A0F = {com.facebook.R.attr.itemSpacing, com.facebook.R.attr.lineSpacing};
    public static final int[] A0G = {R.attr.foreground, R.attr.foregroundGravity, com.facebook.R.attr.foregroundInsidePadding};
    public static final int[] A0H = {com.facebook.R.attr.indeterminateAnimationType, com.facebook.R.attr.indicatorDirectionLinear};
    public static final int[] A0I = {R.attr.inputType};
    public static final int[] A0J = {R.attr.background, R.attr.insetLeft, R.attr.insetRight, R.attr.insetTop, R.attr.insetBottom, R.attr.checkable, com.facebook.R.attr.backgroundTint, com.facebook.R.attr.backgroundTintMode, com.facebook.R.attr.cornerRadius, com.facebook.R.attr.elevation, com.facebook.R.attr.icon, com.facebook.R.attr.iconGravity, com.facebook.R.attr.iconPadding, com.facebook.R.attr.iconSize, com.facebook.R.attr.iconTint, com.facebook.R.attr.iconTintMode, com.facebook.R.attr.rippleColor, com.facebook.R.attr.shapeAppearance, com.facebook.R.attr.shapeAppearanceOverlay, com.facebook.R.attr.strokeColor, com.facebook.R.attr.strokeWidth};
    public static final int[] A0K = {com.facebook.R.attr.checkedButton, com.facebook.R.attr.selectionRequired, com.facebook.R.attr.singleSelection};
    public static final int[] A0L = {R.attr.windowFullscreen, com.facebook.R.attr.dayInvalidStyle, com.facebook.R.attr.daySelectedStyle, com.facebook.R.attr.dayStyle, com.facebook.R.attr.dayTodayStyle, com.facebook.R.attr.nestedScrollable, com.facebook.R.attr.rangeFillColor, com.facebook.R.attr.yearSelectedStyle, com.facebook.R.attr.yearStyle, com.facebook.R.attr.yearTodayStyle};
    public static final int[] A0M = {R.attr.insetLeft, R.attr.insetRight, R.attr.insetTop, R.attr.insetBottom, com.facebook.R.attr.itemFillColor, com.facebook.R.attr.itemShapeAppearance, com.facebook.R.attr.itemShapeAppearanceOverlay, com.facebook.R.attr.itemStrokeColor, com.facebook.R.attr.itemStrokeWidth, com.facebook.R.attr.itemTextColor};
    public static final int[] A0N = {R.attr.checkable, com.facebook.R.attr.cardForegroundColor, com.facebook.R.attr.checkedIcon, com.facebook.R.attr.checkedIconMargin, com.facebook.R.attr.checkedIconSize, com.facebook.R.attr.checkedIconTint, com.facebook.R.attr.rippleColor, com.facebook.R.attr.shapeAppearance, com.facebook.R.attr.shapeAppearanceOverlay, com.facebook.R.attr.state_dragged, com.facebook.R.attr.strokeColor, com.facebook.R.attr.strokeWidth};
    public static final int[] A0O = {com.facebook.R.attr.buttonTint, com.facebook.R.attr.useMaterialThemeColors};
    public static final int[] A0P = {com.facebook.R.attr.buttonTint, com.facebook.R.attr.useMaterialThemeColors};
    public static final int[] A0Q = {com.facebook.R.attr.shapeAppearance, com.facebook.R.attr.shapeAppearanceOverlay};
    public static final int[] A0R = {R.attr.letterSpacing, R.attr.lineHeight, com.facebook.R.attr.lineHeight};
    public static final int[] A0S = {R.attr.textAppearance, R.attr.lineHeight, com.facebook.R.attr.lineHeight};
    public static final int[] A0T = {com.facebook.R.attr.navigationIconTint, com.facebook.R.attr.subtitleCentered, com.facebook.R.attr.titleCentered};
    public static final int[] A0U = {com.facebook.R.attr.materialCircleRadius};
    public static final int[] A0V = {com.facebook.R.attr.behavior_overlapTop};
    public static final int[] A0W = {com.facebook.R.attr.cornerFamily, com.facebook.R.attr.cornerFamilyBottomLeft, com.facebook.R.attr.cornerFamilyBottomRight, com.facebook.R.attr.cornerFamilyTopLeft, com.facebook.R.attr.cornerFamilyTopRight, com.facebook.R.attr.cornerSize, com.facebook.R.attr.cornerSizeBottomLeft, com.facebook.R.attr.cornerSizeBottomRight, com.facebook.R.attr.cornerSizeTopLeft, com.facebook.R.attr.cornerSizeTopRight};
    public static final int[] A0X = {com.facebook.R.attr.contentPadding, com.facebook.R.attr.contentPaddingBottom, com.facebook.R.attr.contentPaddingEnd, com.facebook.R.attr.contentPaddingLeft, com.facebook.R.attr.contentPaddingRight, com.facebook.R.attr.contentPaddingStart, com.facebook.R.attr.contentPaddingTop, com.facebook.R.attr.shapeAppearance, com.facebook.R.attr.shapeAppearanceOverlay, com.facebook.R.attr.strokeColor, com.facebook.R.attr.strokeWidth};
    public static final int[] A0Y = {R.attr.maxWidth, com.facebook.R.attr.actionTextColorAlpha, com.facebook.R.attr.animationMode, com.facebook.R.attr.backgroundOverlayColorAlpha, com.facebook.R.attr.backgroundTint, com.facebook.R.attr.backgroundTintMode, com.facebook.R.attr.elevation, com.facebook.R.attr.maxActionInlineWidth};
    public static final int[] A0Z = {R.attr.icon, R.attr.layout, R.attr.text};
    public static final int[] A0a = {com.facebook.R.attr.tabBackground, com.facebook.R.attr.tabContentStart, com.facebook.R.attr.tabGravity, com.facebook.R.attr.tabIconTint, com.facebook.R.attr.tabIconTintMode, com.facebook.R.attr.tabIndicator, com.facebook.R.attr.tabIndicatorAnimationDuration, com.facebook.R.attr.tabIndicatorAnimationMode, com.facebook.R.attr.tabIndicatorColor, com.facebook.R.attr.tabIndicatorFullWidth, com.facebook.R.attr.tabIndicatorGravity, com.facebook.R.attr.tabIndicatorHeight, com.facebook.R.attr.tabInlineLabel, com.facebook.R.attr.tabMaxWidth, com.facebook.R.attr.tabMinWidth, com.facebook.R.attr.tabMode, com.facebook.R.attr.tabPadding, com.facebook.R.attr.tabPaddingBottom, com.facebook.R.attr.tabPaddingEnd, com.facebook.R.attr.tabPaddingStart, com.facebook.R.attr.tabPaddingTop, com.facebook.R.attr.tabRippleColor, com.facebook.R.attr.tabSelectedTextColor, com.facebook.R.attr.tabTextAppearance, com.facebook.R.attr.tabTextColor, com.facebook.R.attr.tabUnboundedRipple};
    public static final int[] A0b = {R.attr.textSize, R.attr.typeface, R.attr.textStyle, R.attr.textColor, R.attr.textColorHint, R.attr.textColorLink, R.attr.shadowColor, R.attr.shadowDx, R.attr.shadowDy, R.attr.shadowRadius, R.attr.fontFamily, R.attr.textFontWeight, com.facebook.R.attr.fontFamily, com.facebook.R.attr.fontVariationSettings, com.facebook.R.attr.textAllCaps, com.facebook.R.attr.textLocale};
    public static final int[] A0c = {com.facebook.R.attr.textInputLayoutFocusedRectEnabled};
    public static final int[] A0d = {R.attr.enabled, R.attr.textColorHint, R.attr.maxWidth, R.attr.minWidth, R.attr.hint, com.facebook.R.attr.boxBackgroundColor, com.facebook.R.attr.boxBackgroundMode, com.facebook.R.attr.boxCollapsedPaddingTop, com.facebook.R.attr.boxCornerRadiusBottomEnd, com.facebook.R.attr.boxCornerRadiusBottomStart, com.facebook.R.attr.boxCornerRadiusTopEnd, com.facebook.R.attr.boxCornerRadiusTopStart, com.facebook.R.attr.boxStrokeColor, com.facebook.R.attr.boxStrokeErrorColor, com.facebook.R.attr.boxStrokeWidth, com.facebook.R.attr.boxStrokeWidthFocused, com.facebook.R.attr.counterEnabled, com.facebook.R.attr.counterMaxLength, com.facebook.R.attr.counterOverflowTextAppearance, com.facebook.R.attr.counterOverflowTextColor, com.facebook.R.attr.counterTextAppearance, com.facebook.R.attr.counterTextColor, com.facebook.R.attr.endIconCheckable, com.facebook.R.attr.endIconContentDescription, com.facebook.R.attr.endIconDrawable, com.facebook.R.attr.endIconMode, com.facebook.R.attr.endIconTint, com.facebook.R.attr.endIconTintMode, com.facebook.R.attr.errorContentDescription, com.facebook.R.attr.errorEnabled, com.facebook.R.attr.errorIconDrawable, com.facebook.R.attr.errorIconTint, com.facebook.R.attr.errorIconTintMode, com.facebook.R.attr.errorTextAppearance, com.facebook.R.attr.errorTextColor, com.facebook.R.attr.expandedHintEnabled, com.facebook.R.attr.helperText, com.facebook.R.attr.helperTextEnabled, com.facebook.R.attr.helperTextTextAppearance, com.facebook.R.attr.helperTextTextColor, com.facebook.R.attr.hintAnimationEnabled, com.facebook.R.attr.hintEnabled, com.facebook.R.attr.hintTextAppearance, com.facebook.R.attr.hintTextColor, com.facebook.R.attr.passwordToggleContentDescription, com.facebook.R.attr.passwordToggleDrawable, com.facebook.R.attr.passwordToggleEnabled, com.facebook.R.attr.passwordToggleTint, com.facebook.R.attr.passwordToggleTintMode, com.facebook.R.attr.placeholderText, com.facebook.R.attr.placeholderTextAppearance, com.facebook.R.attr.placeholderTextColor, com.facebook.R.attr.prefixText, com.facebook.R.attr.prefixTextAppearance, com.facebook.R.attr.prefixTextColor, com.facebook.R.attr.shapeAppearance, com.facebook.R.attr.shapeAppearanceOverlay, com.facebook.R.attr.startIconCheckable, com.facebook.R.attr.startIconContentDescription, com.facebook.R.attr.startIconDrawable, com.facebook.R.attr.startIconTint, com.facebook.R.attr.startIconTintMode, com.facebook.R.attr.suffixText, com.facebook.R.attr.suffixTextAppearance, com.facebook.R.attr.suffixTextColor};
    public static final int[] A0e = {R.attr.textAppearance, com.facebook.R.attr.enforceMaterialTheme, com.facebook.R.attr.enforceTextAppearance};
}
