package X;

import com.facebook.catalyst.modules.netinfo.NetInfoModule;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/* renamed from: X.4Sc, reason: invalid class name and case insensitive filesystem */
/* loaded from: classes2.dex */
public final class C95684Sc {
    public C4SX A00;
    public C0x9 A01;
    public C0x9 A02;
    public C0x9 A03;
    public Boolean A04;
    public Boolean A05;
    public Boolean A06;
    public Boolean A07;
    public Boolean A08;
    public Boolean A09;
    public Boolean A0A;
    public Double A0B;
    public Double A0C;
    public Double A0D;
    public Float A0E;
    public Float A0F;
    public Float A0G;
    public Float A0H;
    public Float A0I;
    public Float A0J;
    public Float A0K;
    public Float A0L;
    public Float A0M;
    public Float A0N;
    public Float A0O;
    public Float A0P;
    public Float A0Q;
    public Integer A0R;
    public Integer A0S;
    public Integer A0T;
    public Integer A0U;
    public Integer A0V;
    public Integer A0W;
    public Integer A0X;
    public Integer A0Y;
    public Integer A0Z;
    public Integer A0a;
    public Integer A0b;
    public Integer A0c;
    public Integer A0d;
    public Long A0e;
    public Long A0f;
    public String A0g;
    public String A0h;
    public String A0i;
    public String A0j;
    public String A0k;
    public String A0l;
    public String A0m;
    public String A0n;
    public String A0o;
    public String A0p;
    public String A0q;
    public String A0r;
    public String A0s;
    public String A0t;
    public String A0u;
    public String A0v;
    public String A0w;
    public String A0x;
    public String A0y;
    public String A0z;
    public String A10;
    public String A11;
    public String A12;
    public String A13;
    public String A14;
    public String A15;
    public String A16;
    public String A17;
    public String A18;
    public String A19;
    public String A1A;
    public String A1B;
    public String A1C;
    public String A1D;
    public String A1E;
    public String A1F;
    public String A1G;
    public String A1H;
    public String A1I = NetInfoModule.CONNECTION_TYPE_NONE;
    public String A1J;
    public String A1K;
    public String A1L;
    public String A1M;
    public ArrayList A1N;
    public ArrayList A1O;
    public ArrayList A1P;
    public HashMap A1Q;
    public List A1R;
}
