package X;

/* renamed from: X.Erc, reason: case insensitive filesystem */
/* loaded from: classes6.dex */
public enum EnumC33503Erc implements InterfaceC02530Ab {
    ACR_BROWSER_ENTRY_POINT_GALLERY("ACR_BROWSER_ENTRY_POINT_GALLERY"),
    ACR_BROWSER_ENTRY_POINT_DESTINATION_PICKER("ACR_BROWSER_ENTRY_POINT_DESTINATION_PICKER"),
    ACR_BROWSER_ENTRY_POINT_MIDCARD("ACR_BROWSER_ENTRY_POINT_MIDCARD"),
    ACR_BROWSER_ENTRY_POINT_NOTIFICATION("ACR_BROWSER_ENTRY_POINT_NOTIFICATION"),
    ACR_BROWSER_ENTRY_POINT_REELS_VIEWER("ACR_BROWSER_ENTRY_POINT_REELS_VIEWER"),
    ACR_BROWSER_ENTRY_POINT_PROFILE_CREATION_MENU("ACR_BROWSER_ENTRY_POINT_PROFILE_CREATION_MENU"),
    ACR_BROWSER_ENTRY_POINT_AUDIO_PAGE("ACR_BROWSER_ENTRY_POINT_AUDIO_PAGE"),
    ACR_BROWSER_ENTRY_POINT_CAMERA_ROLL_MIDCARD("ACR_BROWSER_ENTRY_POINT_CAMERA_ROLL_MIDCARD"),
    ACR_BROWSER_ENTRY_UNTRACKED("ACR_BROWSER_ENTRY_UNTRACKED");

    public final String A00;

    EnumC33503Erc(String str) {
        this.A00 = str;
    }

    @Override // X.InterfaceC02530Ab
    public final /* bridge */ /* synthetic */ Object getValue() {
        return this.A00;
    }
}
