package X;

import com.instagram.api.schemas.MediaCroppingCoordinates;
import com.instagram.clips.model.metadata.ClipsFanClubMetadata;
import com.instagram.music.common.model.MusicOverlayStickerModel;
import com.instagram.pendingmedia.model.ClipInfo;
import com.instagram.share.facebook.model.FBReelsAudienceType;
import java.util.List;

/* loaded from: classes9.dex */
public final class OZs {
    public float A00;
    public int A01;
    public C51756Mtf A02;
    public C38686GzR A03;
    public C38709H2v A04;
    public MediaCroppingCoordinates A05;
    public ClipsFanClubMetadata A06;
    public C185368Kc A07;
    public EnumC76383bi A08;
    public MusicOverlayStickerModel A09;
    public ClipInfo A0A;
    public C47v A0B;
    public FBReelsAudienceType A0C;
    public Boolean A0D;
    public Boolean A0E;
    public Boolean A0F;
    public Boolean A0G;
    public Integer A0H;
    public Integer A0I;
    public Integer A0J;
    public String A0K;
    public String A0L;
    public String A0M;
    public String A0N;
    public String A0O;
    public String A0P;
    public String A0Q;
    public String A0R;
    public String A0S;
    public String A0T;
    public String A0U;
    public String A0V;
    public String A0W;
    public String A0X;
    public String A0Y;
    public List A0Z;
    public List A0a;
    public List A0b;
    public List A0c;
    public List A0d;
    public List A0e;
    public List A0f;
    public List A0g;
    public List A0h;
    public List A0i;
    public List A0j;
    public List A0k;
    public List A0l;
    public List A0m;
    public List A0n;
    public java.util.Set A0o;
    public boolean A0p;
    public boolean A0q;
    public boolean A0r;
    public boolean A0s;
    public boolean A0t;
    public boolean A0u;
    public boolean A0v;
    public boolean A0w;
    public boolean A0x;
    public boolean A0y;
    public boolean A0z;
    public boolean A10;
    public boolean A11;
    public boolean A12;
    public boolean A13;

    public static void A00(OZs oZs, List list) {
        oZs.A0a = list;
        oZs.A0Z = list;
        oZs.A0o = C16910sj.A00;
        oZs.A0b = list;
        oZs.A0l = list;
        oZs.A0m = list;
        oZs.A0c = list;
        oZs.A0f = list;
        oZs.A0i = list;
        oZs.A0k = list;
        oZs.A0G = false;
        oZs.A0D = false;
        oZs.A0E = false;
        oZs.A0F = false;
        oZs.A0J = 0;
    }

    public OZs(C51756Mtf c51756Mtf, C38686GzR c38686GzR, C38709H2v c38709H2v, MediaCroppingCoordinates mediaCroppingCoordinates, ClipsFanClubMetadata clipsFanClubMetadata, C185368Kc c185368Kc, EnumC76383bi enumC76383bi, MusicOverlayStickerModel musicOverlayStickerModel, ClipInfo clipInfo, C47v c47v, FBReelsAudienceType fBReelsAudienceType, Integer num, Integer num2, String str, String str2, String str3, String str4, String str5, String str6, String str7, String str8, String str9, String str10, String str11, String str12, String str13, String str14, String str15, List list, List list2, List list3, List list4, List list5, List list6, List list7, List list8, List list9, List list10, List list11, List list12, List list13, List list14, List list15, java.util.Set set, float f, int i, int i2, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12, boolean z13, boolean z14, boolean z15, boolean z16, boolean z17, boolean z18, boolean z19) {
        List list16 = list12;
        C14360o3.A0B(enumC76383bi, 1);
        C14360o3.A0B(list2, 19);
        C14360o3.A0B(list7, 25);
        C14360o3.A0B(list8, 26);
        C14360o3.A0B(list10, 39);
        C14360o3.A0B(list11, 42);
        C16930sl c16930sl = C16930sl.A00;
        A00(this, c16930sl);
        this.A0v = true;
        this.A08 = enumC76383bi;
        this.A0L = str;
        this.A0M = str2;
        this.A0K = str3;
        this.A10 = z;
        this.A05 = mediaCroppingCoordinates;
        this.A11 = z2;
        this.A12 = z3;
        this.A0z = z4;
        this.A0T = str4;
        this.A0U = str5;
        this.A0I = num;
        this.A0e = list;
        this.A0C = fBReelsAudienceType;
        this.A0P = str6;
        this.A0A = clipInfo;
        this.A0o = set;
        this.A0l = list2;
        this.A0m = list3;
        this.A0c = list4;
        this.A09 = musicOverlayStickerModel;
        this.A0h = list5;
        this.A0b = list6;
        this.A0a = list7;
        this.A0Z = list8;
        this.A0n = list9;
        this.A03 = c38686GzR;
        this.A06 = clipsFanClubMetadata;
        this.A0B = c47v;
        this.A07 = c185368Kc;
        this.A0u = z5;
        this.A0q = z6;
        this.A0R = str9;
        this.A0t = z7;
        this.A0H = num2;
        this.A0V = str7;
        this.A0r = z8;
        this.A0Y = str8;
        this.A0f = list10;
        this.A0N = str10;
        this.A0i = list11;
        this.A0k = list12 == null ? c16930sl : list16;
        this.A0g = list13;
        this.A0s = z9;
        this.A0p = z10;
        this.A0X = str11;
        this.A0S = str12;
        this.A0O = str13;
        this.A0W = str14;
        this.A0w = z11;
        this.A0y = z12;
        this.A0v = z13;
        this.A0x = z14;
        this.A04 = c38709H2v;
        this.A0Q = str15;
        this.A0E = Boolean.valueOf(z15);
        this.A0J = Integer.valueOf(i);
        this.A0G = Boolean.valueOf(z16);
        this.A00 = f;
        this.A0j = list14;
        this.A0D = Boolean.valueOf(z17);
        this.A0F = Boolean.valueOf(z18);
        this.A0d = list15;
        this.A13 = z19;
        this.A02 = c51756Mtf;
        this.A01 = i2;
    }

    public OZs() {
        A00(this, C16930sl.A00);
        this.A0v = true;
    }
}
