package X;

/* loaded from: classes10.dex */
public abstract class Ry1 {
    public static String A00(int i) {
        return i != 1429 ? i != 1912 ? i != 2164 ? i != 3586 ? i != 5676 ? i != 7463 ? i != 9027 ? i != 15537 ? "UNDEFINED_QPL_EVENT" : "OCULUS_FEDERATED_COMPUTING_BUILD_PAPAYA_RECORD" : "OCULUS_FEDERATED_COMPUTING_RECORD_COMMIT" : "OCULUS_FEDERATED_COMPUTING_WRITE_EVENT_V1" : "OCULUS_FEDERATED_COMPUTING_GPRIPS_RECORD_QUEUE" : "OCULUS_FEDERATED_COMPUTING_GPRIPS_CLEANUP" : "OCULUS_FEDERATED_COMPUTING_PAPAYA_EXECUTOR_NON_SENSITIVE_SYSTEM" : "OCULUS_FEDERATED_COMPUTING_PAPAYA_EXECUTOR_SUBMISSION" : "OCULUS_FEDERATED_COMPUTING_PROCESS_RECORD";
    }
}
