package X;

/* loaded from: classes10.dex */
public abstract class RyF {
    public static String A00(int i) {
        return i != 5639 ? i != 6056 ? i != 10357 ? i != 11101 ? i != 11378 ? i != 13093 ? i != 13323 ? "UNDEFINED_QPL_EVENT" : "PASSIVE_INSTANCES_PI_SET_CAMERA_CONTROLLER" : "PASSIVE_INSTANCES_PI_HEARTBEAT" : "PASSIVE_INSTANCES_PI_CREATE_CAMERA" : "PASSIVE_INSTANCES_PI_FREE_CAMERA" : "PASSIVE_INSTANCES_PI_UPLOAD_VIDEO" : "PASSIVE_INSTANCES_PI_STOP_CAMERA" : "PASSIVE_INSTANCES_PI_START_CAMERA";
    }
}
