package X;

/* loaded from: classes10.dex */
public abstract class S05 {
    public static String A00(int i) {
        return i != 1236 ? i != 2135 ? i != 2715 ? i != 3281 ? i != 4505 ? i != 6188 ? i != 6607 ? i != 11173 ? i != 12187 ? "UNDEFINED_QPL_EVENT" : "WHATSAPP_STATUS_STATUS_NAVIGATION" : "WHATSAPP_STATUS_PROFILE_RINGS" : "WHATSAPP_STATUS_STATUS_CREATION_FLOW" : "WHATSAPP_STATUS_ADD_STATUS" : "WHATSAPP_STATUS_STATUS_AUDIENCE_SELECTOR_DEFAULT_HALF_SHEET" : "WHATSAPP_STATUS_VIEW_STATUS" : "WHATSAPP_STATUS_STATUS_CREATION" : "WHATSAPP_STATUS_FULL_SCREEN_AUDIENCE_SELECTOR" : "WHATSAPP_STATUS_STATUS_AUDIENCE_SELECTOR_SHARE_SHEET";
    }
}
