package X;

/* loaded from: classes10.dex */
public abstract class S07 {
    public static String A00(int i) {
        return i != 5029 ? i != 5984 ? i != 8149 ? i != 10634 ? i != 10851 ? i != 13429 ? "UNDEFINED_QPL_EVENT" : "WHATSAPP_ZONE_MOBILE_ZONE_EVALUATOR_ERROR" : "WHATSAPP_ZONE_MOBILE_ZONE_TEMPORARY_DECLASSIFICATION" : "WHATSAPP_ZONE_MOBILE_ZONE_RECLASSIFICATION" : "WHATSAPP_ZONE_MOBILE_ZONE_PRIVACY_UNWRAP" : "WHATSAPP_ZONE_MOBILE_ZONE_PRIVACY_VIOLATION_EVENT" : "WHATSAPP_ZONE_MOBILE_ZONE_RUN_EVENT";
    }
}
