package X;

/* loaded from: classes10.dex */
public abstract class S0C {
    public static String A00(int i) {
        return i != 1 ? i != 2 ? i != 3 ? i != 4 ? i != 5 ? i != 5694 ? i != 7265 ? "UNDEFINED_QPL_EVENT" : "WORKPLACE_DRAFT_FOR_CREATION_HUB_CANCEL_APPROVAL_REQUEST" : "WORKPLACE_DRAFT_FOR_WORK_DRAFT_FOR_ERROR" : "WORKPLACE_DRAFT_FOR_WORK_DRAFT_FOR_POST" : "WORKPLACE_DRAFT_FOR_WORK_DRAFT_FOR_EDIT" : "WORKPLACE_DRAFT_FOR_WORK_DRAFT_FOR_DELETE" : "WORKPLACE_DRAFT_FOR_WORK_DRAFT_FOR_SESSION" : "WORKPLACE_DRAFT_FOR_WORK_DRAFT_FOR_REMOVE_DRAFT_AUTHOR";
    }
}
