package X;

/* loaded from: classes10.dex */
public abstract class S0F {
    public static String A00(int i) {
        return i != 1478 ? i != 4647 ? i != 5957 ? i != 6481 ? i != 6571 ? i != 8414 ? i != 8493 ? i != 11891 ? i != 11999 ? i != 15251 ? "UNDEFINED_QPL_EVENT" : "WORKPLACE_WEB_MESSAGING_FOLDERS_LOADING_TIME" : "WORKPLACE_WEB_MESSAGING_CHAT_MORE_THREADS_LOAD_TIME" : "WORKPLACE_WEB_MESSAGING_CREATE_CHAT_THREAD" : "WORKPLACE_WEB_MESSAGING_THREAD_SEARCH_USER_FLOW" : "WORKPLACE_WEB_MESSAGING_CHAT_MESSAGE_LIST_LOAD_TIME" : "WORKPLACE_WEB_MESSAGING_THREAD_SEARCH_CAPPED_RESULTS" : "WORKPLACE_WEB_MESSAGING_ATTACHMENT_UPLOAD" : "WORKPLACE_WEB_MESSAGING_FOLDER_THREADS_LOADING_TIME" : "WORKPLACE_WEB_MESSAGING_MESSAGE_SEND" : "WORKPLACE_WEB_MESSAGING_THREAD_SEARCH";
    }
}
