package X;

/* loaded from: classes10.dex */
public abstract class S0L {
    public static String A00(int i) {
        return i != 1009 ? i != 1227 ? i != 3195 ? i != 4178 ? i != 10971 ? i != 11874 ? i != 12231 ? i != 12322 ? i != 15985 ? "UNDEFINED_QPL_EVENT" : "WP_ANDROID_MEETINGS_CREATE_GARDEN" : "WP_ANDROID_MEETINGS_MEETING_RSVP" : "WP_ANDROID_MEETINGS_CREATE_MEETING" : "WP_ANDROID_MEETINGS_LOAD_MEETING_DETAILS" : "WP_ANDROID_MEETINGS_LOAD_MEETINGS_TAB" : "WP_ANDROID_MEETINGS_JOIN_MEETING" : "WP_ANDROID_MEETINGS_LOAD_GARDENS_TAB" : "WP_ANDROID_MEETINGS_LOAD_GARDEN_DETAILS" : "WP_ANDROID_MEETINGS_CREATE_MEET_NOW_ROOM";
    }
}
