package X;

/* loaded from: classes10.dex */
public abstract class S0S {
    public static String A00(int i) {
        return i != 1 ? i != 1962 ? i != 2023 ? i != 3120 ? i != 11490 ? i != 12767 ? i != 14067 ? i != 14553 ? i != 16274 ? "UNDEFINED_QPL_EVENT" : "XAPP_MSYS_LITE_MSYS_USER_ACTION" : "XAPP_MSYS_LITE_MSYS_MESSAGE_SEND" : "XAPP_MSYS_LITE_MSYS_ARMADILLO_MESSAGE_SEND" : "XAPP_MSYS_REAL_TIME_MESSAGES_RECEIVED" : "XAPP_MSYS_LITE_MSYS_LOCAL_SEND_SPEED" : "XAPP_MSYS_MESSAGE_RECEIVE" : "XAPP_MSYS_TTB" : "XAPP_MSYS_COPY_MEDIA_ERROR" : "XAPP_MSYS_QUERY_PERFORMANCE";
    }
}
