package X;

/* loaded from: classes10.dex */
public abstract class S0U {
    public static String A00(int i) {
        return i != 1587 ? i != 3703 ? i != 7276 ? i != 7654 ? i != 8735 ? i != 8921 ? i != 13612 ? i != 13959 ? "UNDEFINED_QPL_EVENT" : "XROS_RUNTIME_BENCHMARKS_MICRO_FUTURE_CHAIN_LATENCY" : "XROS_RUNTIME_BENCHMARKS_MICRO_EXECUTOR_SUBMIT_LATENCY" : "XROS_RUNTIME_BENCHMARKS_MICRO_EVENT_DISPATCH_LATENCY" : "XROS_RUNTIME_BENCHMARKS_MICRO_IPC_SEND_LATENCY" : "XROS_RUNTIME_BENCHMARKS_MICRO_BOOT_LATENCY" : "XROS_RUNTIME_BENCHMARKS_MICRO_ALLOCATION_LATENCY" : "XROS_RUNTIME_BENCHMARKS_TEST1" : "XROS_RUNTIME_BENCHMARKS_MICRO_STREAM_LATENCY";
    }
}
