package X;

/* loaded from: classes10.dex */
public abstract class S0Y {
    public static String A00(int i) {
        return i != 6384 ? i != 11098 ? i != 11526 ? i != 11682 ? i != 12893 ? i != 13278 ? i != 14736 ? i != 15834 ? "UNDEFINED_QPL_EVENT" : "ZERO_REWRITE_RULES_REWRITE_RULES_RUN" : "ZERO_REWRITE_RULES_REWRITE_RULES_REGEX_COMPILE" : "ZERO_REWRITE_RULES_BACKUP_RULES_LOAD" : "ZERO_REWRITE_RULES_REWRITE_RULES_LOAD" : "ZERO_REWRITE_RULES_ZERO_TOKEN_RESPONSE_SERIALIZATION" : "ZERO_REWRITE_RULES_NATIVE_INTERCEPTOR_ON_NATIVE_REQUESTS" : "ZERO_REWRITE_RULES_NATIVE_INTERCEPTOR_ON_ALL_REQUESTS" : "ZERO_REWRITE_RULES_RUN_REWRITE_FROM_HTTP_FILTER";
    }
}
