package X;

import com.facebook.catalyst.modules.netinfo.NetInfoModule;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: classes11.dex */
public final class VDK {
    public static final /* synthetic */ VDK[] A00;
    public static final VDK A01;
    public static final VDK A02;
    public static final VDK A03;
    public static final VDK A04;
    public static final VDK A05;
    public static final VDK A06;
    public static final VDK A07;
    public static final VDK A08;
    public static final VDK A09;
    public static final VDK A0A;
    public static final VDK A0B;
    public static final VDK A0C;
    public static final VDK A0D;
    public static final VDK A0E;
    public static final VDK A0F;
    public static final VDK A0G;
    public static final VDK A0H;
    public static final VDK A0I;
    public static final VDK A0J;
    public static final VDK A0K;
    public static final VDK A0L;
    public static final VDK A0M;
    public static final VDK A0N;
    public static final VDK A0O;
    public static final VDK A0P;
    public static final VDK A0Q;
    public static final VDK A0R;
    public static final VDK A0S;
    public static final VDK A0T;
    public static final VDK A0U;
    public static final VDK A0V;
    public static final VDK A0W;
    public static final VDK A0X;
    public static final VDK A0Y;
    public static final VDK A0Z;
    public static final VDK A0a;
    public static final VDK A0b;
    public static final VDK A0c;
    public static final VDK A0d;
    public static final VDK A0e;
    public static final VDK A0f;
    public static final VDK A0g;
    public static final VDK A0h;
    public static final VDK A0i;
    public static final VDK A0j;
    public static final VDK A0k;
    public static final VDK A0l;
    public static final VDK A0m;
    public static final VDK A0n;
    public static final VDK A0o;
    public static final VDK A0p;
    public static final VDK A0q;
    public static final VDK A0r;
    public static final VDK A0s;
    public static final VDK A0t;
    public static final VDK A0u;
    public static final VDK A0v;
    public static final VDK A0w;
    public static final VDK A0x;
    public static final VDK A0y;
    public static final VDK A0z;
    public static final VDK A10;
    public static final VDK A11;
    public static final VDK A12;

    static {
        VDK vdk = new VDK("ALERT", 0);
        A01 = vdk;
        VDK vdk2 = new VDK("ALERTDIALOG", 1);
        A02 = vdk2;
        VDK vdk3 = new VDK("APPLICATION", 2);
        A03 = vdk3;
        VDK vdk4 = new VDK("ARTICLE", 3);
        A04 = vdk4;
        VDK vdk5 = new VDK("BANNER", 4);
        A05 = vdk5;
        VDK vdk6 = new VDK("BUTTON", 5);
        A06 = vdk6;
        VDK vdk7 = new VDK("CELL", 6);
        A07 = vdk7;
        VDK vdk8 = new VDK("CHECKBOX", 7);
        A08 = vdk8;
        VDK vdk9 = new VDK("COLUMNHEADER", 8);
        A09 = vdk9;
        VDK vdk10 = new VDK("COMBOBOX", 9);
        A0A = vdk10;
        VDK vdk11 = new VDK("COMPLEMENTARY", 10);
        A0B = vdk11;
        VDK vdk12 = new VDK("CONTENTINFO", 11);
        A0C = vdk12;
        VDK vdk13 = new VDK("DEFINITION", 12);
        A0D = vdk13;
        VDK vdk14 = new VDK("DIALOG", 13);
        A0E = vdk14;
        VDK vdk15 = new VDK("DIRECTORY", 14);
        A0F = vdk15;
        VDK vdk16 = new VDK("DOCUMENT", 15);
        A0G = vdk16;
        VDK vdk17 = new VDK("FEED", 16);
        A0H = vdk17;
        VDK vdk18 = new VDK("FIGURE", 17);
        A0I = vdk18;
        VDK vdk19 = new VDK("FORM", 18);
        A0J = vdk19;
        VDK vdk20 = new VDK("GRID", 19);
        A0K = vdk20;
        VDK vdk21 = new VDK("GROUP", 20);
        A0L = vdk21;
        VDK vdk22 = new VDK("HEADING", 21);
        A0M = vdk22;
        VDK vdk23 = new VDK("IMG", 22);
        A0N = vdk23;
        VDK vdk24 = new VDK("LINK", 23);
        A0O = vdk24;
        VDK vdk25 = new VDK("LIST", 24);
        A0P = vdk25;
        VDK vdk26 = new VDK("LISTITEM", 25);
        A0Q = vdk26;
        VDK vdk27 = new VDK("LOG", 26);
        A0R = vdk27;
        VDK vdk28 = new VDK("MAIN", 27);
        A0S = vdk28;
        VDK vdk29 = new VDK("MARQUEE", 28);
        A0T = vdk29;
        VDK vdk30 = new VDK("MATH", 29);
        A0U = vdk30;
        VDK vdk31 = new VDK("MENU", 30);
        A0V = vdk31;
        VDK vdk32 = new VDK("MENUBAR", 31);
        A0W = vdk32;
        VDK vdk33 = new VDK("MENUITEM", 32);
        A0X = vdk33;
        VDK vdk34 = new VDK("METER", 33);
        A0Y = vdk34;
        VDK vdk35 = new VDK("NAVIGATION", 34);
        A0Z = vdk35;
        VDK vdk36 = new VDK(NetInfoModule.CONNECTION_TYPE_NONE_DEPRECATED, 35);
        A0a = vdk36;
        VDK vdk37 = new VDK("NOTE", 36);
        A0b = vdk37;
        VDK vdk38 = new VDK("OPTION", 37);
        A0c = vdk38;
        VDK vdk39 = new VDK("PRESENTATION", 38);
        A0d = vdk39;
        VDK vdk40 = new VDK("PROGRESSBAR", 39);
        A0e = vdk40;
        VDK vdk41 = new VDK("RADIO", 40);
        A0f = vdk41;
        VDK vdk42 = new VDK("RADIOGROUP", 41);
        A0g = vdk42;
        VDK vdk43 = new VDK("REGION", 42);
        A0h = vdk43;
        VDK vdk44 = new VDK("ROW", 43);
        A0i = vdk44;
        VDK vdk45 = new VDK("ROWGROUP", 44);
        A0j = vdk45;
        VDK vdk46 = new VDK("ROWHEADER", 45);
        A0k = vdk46;
        VDK vdk47 = new VDK("SCROLLBAR", 46);
        A0l = vdk47;
        VDK vdk48 = new VDK("SEARCHBOX", 47);
        A0m = vdk48;
        VDK vdk49 = new VDK("SEPARATOR", 48);
        A0n = vdk49;
        VDK vdk50 = new VDK("SLIDER", 49);
        A0o = vdk50;
        VDK vdk51 = new VDK("SPINBUTTON", 50);
        A0p = vdk51;
        VDK vdk52 = new VDK("STATUS", 51);
        A0q = vdk52;
        VDK vdk53 = new VDK("SUMMARY", 52);
        A0r = vdk53;
        VDK vdk54 = new VDK("SWITCH", 53);
        A0s = vdk54;
        VDK vdk55 = new VDK("TAB", 54);
        A0t = vdk55;
        VDK vdk56 = new VDK("TABLE", 55);
        A0u = vdk56;
        VDK vdk57 = new VDK("TABLIST", 56);
        A0v = vdk57;
        VDK vdk58 = new VDK("TABPANEL", 57);
        A0w = vdk58;
        VDK vdk59 = new VDK("TERM", 58);
        A0x = vdk59;
        VDK vdk60 = new VDK("TIMER", 59);
        A0y = vdk60;
        VDK vdk61 = new VDK("TOOLBAR", 60);
        A0z = vdk61;
        VDK vdk62 = new VDK("TOOLTIP", 61);
        A10 = vdk62;
        VDK vdk63 = new VDK("TREE", 62);
        A11 = vdk63;
        VDK vdk64 = new VDK("TREEGRID", 63);
        A12 = vdk64;
        VDK vdk65 = new VDK("TREEITEM", 64);
        VDK[] vdkArr = new VDK[65];
        System.arraycopy(new VDK[]{vdk, vdk2, vdk3, vdk4, vdk5, vdk6, vdk7, vdk8, vdk9, vdk10, vdk11, vdk12, vdk13, vdk14, vdk15, vdk16, vdk17, vdk18, vdk19, vdk20, vdk21, vdk22, vdk23, vdk24, vdk25, vdk26, vdk27}, 0, vdkArr, 0, 27);
        System.arraycopy(new VDK[]{vdk28, vdk29, vdk30, vdk31, vdk32, vdk33, vdk34, vdk35, vdk36, vdk37, vdk38, vdk39, vdk40, vdk41, vdk42, vdk43, vdk44, vdk45, vdk46, vdk47, vdk48, vdk49, vdk50, vdk51, vdk52, vdk53, vdk54}, 0, vdkArr, 27, 27);
        System.arraycopy(new VDK[]{vdk55, vdk56, vdk57, vdk58, vdk59, vdk60, vdk61, vdk62, vdk63, vdk64, vdk65}, 0, vdkArr, 54, 11);
        A00 = vdkArr;
    }

    public static VDK valueOf(String str) {
        return (VDK) Enum.valueOf(VDK.class, str);
    }

    public static VDK[] values() {
        return (VDK[]) A00.clone();
    }

    public VDK(String str, int i) {
    }
}
