package X;

import java.util.LinkedHashMap;
import java.util.Map;
import kotlin.enums.EnumEntries;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: classes11.dex */
public final class VEH {
    public static final Map A01;
    public static final /* synthetic */ EnumEntries A02;
    public static final /* synthetic */ VEH[] A03;
    public static final VEH A04;
    public static final VEH A05;
    public static final VEH A06;
    public static final VEH A07;
    public static final VEH A08;
    public static final VEH A09;
    public static final VEH A0A;
    public static final VEH A0B;
    public static final VEH A0C;
    public static final VEH A0D;
    public static final VEH A0E;
    public static final VEH A0F;
    public static final VEH A0G;
    public static final VEH A0H;
    public static final VEH A0I;
    public static final VEH A0J;
    public static final VEH A0K;
    public static final VEH A0L;
    public static final VEH A0M;
    public static final VEH A0N;
    public static final VEH A0O;
    public static final VEH A0P;
    public static final VEH A0Q;
    public static final VEH A0R;
    public static final VEH A0S;
    public static final VEH A0T;
    public static final VEH A0U;
    public static final VEH A0V;
    public static final VEH A0W;
    public static final VEH A0X;
    public static final VEH A0Y;
    public static final VEH A0Z;
    public static final VEH A0a;
    public static final VEH A0b;
    public static final VEH A0c;
    public static final VEH A0d;
    public static final VEH A0e;
    public static final VEH A0f;
    public static final VEH A0g;
    public static final VEH A0h;
    public static final VEH A0i;
    public static final VEH A0j;
    public static final VEH A0k;
    public static final VEH A0l;
    public static final VEH A0m;
    public static final VEH A0n;
    public static final VEH A0o;
    public static final VEH A0p;
    public static final VEH A0q;
    public static final VEH A0r;
    public static final VEH A0s;
    public static final VEH A0t;
    public static final VEH A0u;
    public static final VEH A0v;
    public static final VEH A0w;
    public static final VEH A0x;
    public static final VEH A0y;
    public static final VEH A0z;
    public static final VEH A10;
    public static final VEH A11;
    public static final VEH A12;
    public static final VEH A13;
    public static final VEH A14;
    public static final VEH A15;
    public static final VEH A16;
    public static final VEH A17;
    public static final VEH A18;
    public static final VEH A19;
    public static final VEH A1A;
    public static final VEH A1B;
    public static final VEH A1C;
    public static final VEH A1D;
    public static final VEH A1E;
    public static final VEH A1F;
    public static final VEH A1G;
    public static final VEH A1H;
    public static final VEH A1I;
    public static final VEH A1J;
    public static final VEH A1K;
    public static final VEH A1L;
    public static final VEH A1M;
    public static final VEH A1N;
    public static final VEH A1O;
    public static final VEH A1P;
    public static final VEH A1Q;
    public static final VEH A1R;
    public static final VEH A1S;
    public static final VEH A1T;
    public static final VEH A1U;
    public static final VEH A1V;
    public static final VEH A1W;
    public static final VEH A1X;
    public static final VEH A1Y;
    public static final VEH A1Z;
    public static final VEH A1a;
    public static final VEH A1b;
    public static final VEH A1c;
    public static final VEH A1d;
    public static final VEH A1e;
    public static final VEH A1f;
    public static final VEH A1g;
    public static final VEH A1h;
    public final String A00;

    public static VEH valueOf(String str) {
        return (VEH) Enum.valueOf(VEH.class, str);
    }

    public static VEH[] values() {
        return (VEH[]) A03.clone();
    }

    static {
        VEH veh = new VEH("BITMAP", 0, "bitmap");
        A0G = veh;
        VEH veh2 = new VEH("TIME", 1, "time");
        A1b = veh2;
        VEH veh3 = new VEH("UNIVERSAL_LOCATION", 2, "universal_location");
        A1c = veh3;
        VEH veh4 = new VEH("GEO_STICKER", 3, "geo_sticker");
        A0b = veh4;
        VEH veh5 = new VEH("HASHTAG_STICKER", 4, "hashtag_sticker");
        A0h = veh5;
        VEH veh6 = new VEH("MENTION", 5, "mention");
        A0x = veh6;
        VEH veh7 = new VEH("SHOPPING_STICKER", 6, "shopping_sticker");
        A1N = veh7;
        VEH veh8 = new VEH("PRODUCT_ITEM_STICKER", 7, "product_item_sticker");
        A19 = veh8;
        VEH veh9 = new VEH("PRODUCT_SHARE_STICKER", 8, "product_share_sticker");
        A1A = veh9;
        VEH veh10 = new VEH("SHOPPING_COLLECTION_SHARE_STICKER", 9, "shopping_collection_share_sticker");
        A1M = veh10;
        VEH veh11 = new VEH("SHOP_SHARE_STICKER", 10, "shop_share_sticker");
        A1O = veh11;
        VEH veh12 = new VEH("MUSIC_OVERLAY_STICKER", 11, "music_overlay_sticker");
        A0z = veh12;
        VEH veh13 = new VEH("MUSIC_TRACK_PREVIEW_STICKER", 12, "music_track_preview_sticker");
        A11 = veh13;
        VEH veh14 = new VEH("LYRICS", 13, "lyrics");
        A0q = veh14;
        VEH veh15 = new VEH("KARAOKE_CAPTION_STICKER", 14, "karaoke_caption_sticker");
        A0n = veh15;
        VEH veh16 = new VEH("COUNTDOWN_STICKER", 15, "countdown_sticker");
        A0L = veh16;
        VEH veh17 = new VEH("REELS_VISUAL_REPLIES_STICKER", 16, "reels_visual_replies_sticker");
        A1I = veh17;
        VEH veh18 = new VEH("FUNDRAISER_STICKER", 17, "fundraiser_sticker");
        A0X = veh18;
        VEH veh19 = new VEH("FUNDRAISER_STICKER_THANKS", 18, "fundraiser_sticker_thanks");
        A0Y = veh19;
        VEH veh20 = new VEH("POLLING_STICKER", 19, "polling_sticker");
        A17 = veh20;
        VEH veh21 = new VEH("POLL_STICKER_V2", 20, "poll_sticker_v2");
        A18 = veh21;
        VEH veh22 = new VEH("QUESTION_STICKER", 21, "question_sticker");
        A1F = veh22;
        VEH veh23 = new VEH("QUESTION_RESPONSE_RESHARE", 22, "question_response_reshare");
        A1E = veh23;
        VEH veh24 = new VEH("ANONYMOUS_QUESTION_STICKER", 23, "anonymous_question_sticker");
        A07 = veh24;
        VEH veh25 = new VEH("CLIPS_QUESTION_STICKER", 24, "clips_question_sticker");
        A0K = veh25;
        VEH veh26 = new VEH("QUIZ_STICKER", 25, "quiz_sticker");
        A1G = veh26;
        VEH veh27 = new VEH("SLIDER_STICKER", 26, "slider_sticker");
        A1P = veh27;
        VEH veh28 = new VEH("MEDIA", 27, "media");
        A0u = veh28;
        VEH veh29 = new VEH("GIF_SEARCH", 28, "gif_search");
        A0d = veh29;
        VEH veh30 = new VEH("GIF", 29, "gif");
        A0c = veh30;
        VEH veh31 = new VEH("GALLERY_BROWSE", 30, "gallery_browse");
        A0a = veh31;
        VEH veh32 = new VEH("GALLERY", 31, "gallery");
        A0Z = veh32;
        VEH veh33 = new VEH("GUIDE", 32, "guide");
        A0g = veh33;
        VEH veh34 = new VEH("INTERNAL_STICKER", 33, "internal_sticker");
        A0k = veh34;
        VEH veh35 = new VEH("ELECTION_STICKER", 34, "election_sticker");
        A0Q = veh35;
        VEH veh36 = new VEH("MEMORIES_STICKER", 35, "memories_sticker");
        A0w = veh36;
        VEH veh37 = new VEH("ANTI_BULLY_ENG_ONLY", 36, "anti_bully_eng_only");
        A08 = veh37;
        VEH veh38 = new VEH("ANTI_BULLY_STICKER", 37, "anti_bully_sticker");
        A0A = veh38;
        VEH veh39 = new VEH("ANTI_BULLY_GLOBAL_STICKER", 38, "anti_bully_global_sticker");
        A09 = veh39;
        VEH veh40 = new VEH("VOTER_REGISTRATION_STICKER", 39, "voter_registration_sticker");
        A1g = veh40;
        VEH veh41 = new VEH("SMB_GIFT_CARD_STICKER", 40, "smb_gift_card_sticker");
        A1S = veh41;
        VEH veh42 = new VEH("SMB_SUPPORT_STICKER", 41, "smb_support_sticker");
        A1T = veh42;
        VEH veh43 = new VEH("SMB_DELIVERY_STICKER", 42, "smb_delivery_sticker");
        A1Q = veh43;
        VEH veh44 = new VEH("SMB_GET_QUOTE_STICKER", 43, "smb_get_quote_sticker");
        A1R = veh44;
        VEH veh45 = new VEH("SHARE_PROFESSIONAL_PROFILE_STICKER", 44, "share_professional_profile_sticker");
        A1L = veh45;
        VEH veh46 = new VEH("PROFILE_STICKER", 45, "profile_sticker");
        A1B = veh46;
        VEH veh47 = new VEH("AMPLIFY_DIVERSITY_BUSINESS_PROFILE_STICKER", 46, "amplify_diversity_business_profile_sticker");
        A06 = veh47;
        VEH veh48 = new VEH("GROUP_POLL_STICKER", 47, "group_poll_sticker");
        A0f = veh48;
        VEH veh49 = new VEH("BLOKS_STICKER", 48, "bloks_sticker");
        A0I = veh49;
        VEH veh50 = new VEH("BLOKS_ANIMATED", 49, "bloks_animated");
        A0H = veh50;
        VEH veh51 = new VEH("NORMAL", 50, "normal");
        A12 = veh51;
        VEH veh52 = new VEH("VOTING_INFO_CENTER", 51, "voting_info_center");
        A1h = veh52;
        VEH veh53 = new VEH("UPCOMING_EVENT_STICKER", 52, "upcoming_event_sticker");
        A1e = veh53;
        VEH veh54 = new VEH("SHARE_PLATFORM", 53, "share_platform");
        A1K = veh54;
        VEH veh55 = new VEH("FB_COMMUNITY", 54, "fb_community");
        A0T = veh55;
        VEH veh56 = new VEH("FB_TAG", 55, "fb_tag");
        A0U = veh56;
        VEH veh57 = new VEH("RESHARE_STICKER", 56, "reshare_sticker");
        A1J = veh57;
        VEH veh58 = new VEH("SUPPORT_PERSONALIZED_ADS_STICKER", 57, "support_personalized_ads_sticker");
        A1Z = veh58;
        VEH veh59 = new VEH("LINK_STICKER", 58, "link_sticker");
        A0p = veh59;
        VEH veh60 = new VEH("USER_PAY_BADGES_THANKS_STICKER", 59, "user_pay_badges_thanks_sticker");
        A1f = veh60;
        VEH veh61 = new VEH("I_TAKE_CARE_STICKER", 60, "i_take_care_sticker");
        A0l = veh61;
        VEH veh62 = new VEH("KEYBOARD_CONTENT_STICKER", 61, "keyboard_content_sticker");
        A0o = veh62;
        VEH veh63 = new VEH("PROMPT_STICKER", 62, "prompt_sticker");
        A1C = veh63;
        VEH veh64 = new VEH("AVATAR_SEARCH", 63, "avatar_search");
        A0D = veh64;
        VEH veh65 = new VEH("AVATAR", 64, "avatar");
        A0B = veh65;
        VEH veh66 = new VEH("SUBSCRIPTIONS_STICKER", 65, "subscriptions_sticker");
        A1X = veh66;
        VEH veh67 = new VEH("REACTION_STICKER", 66, "reaction_sticker");
        A1H = veh67;
        VEH veh68 = new VEH("CLIPS_PROMPT_STICKER", 67, "clips_prompt_sticker");
        A0J = veh68;
        VEH veh69 = new VEH("JOIN_CHAT_STICKER", 68, "join_chat_sticker");
        A0m = veh69;
        VEH veh70 = new VEH("SUBSCRIBER_CHAT_STICKER", 69, "subscriber_chat_sticker");
        A1W = veh70;
        VEH veh71 = new VEH("AVATAR_STATIC", 70, "avatar_static");
        A0E = veh71;
        VEH veh72 = new VEH("AVATAR_ANIMATED", 71, "avatar_animated");
        A0C = veh72;
        VEH veh73 = new VEH("PLACEHOLDER_STICKER", 72, "placeholder_sticker");
        A15 = veh73;
        VEH veh74 = new VEH("IG_FEATURE_LINKING_STICKER", 73, "ig_feature_linking_sticker");
        A0j = veh74;
        VEH veh75 = new VEH("MESSAGE_SHARE", 74, "message_share");
        A0y = veh75;
        VEH veh76 = new VEH("MEMORIES", 75, "memories");
        A0v = veh76;
        VEH veh77 = new VEH("BEFORE_AND_AFTER_STICKER", 76, "before_and_after_sticker");
        A0F = veh77;
        VEH veh78 = new VEH("GROUP_MENTION_STICKER", 77, "group_mention_sticker");
        A0e = veh78;
        VEH veh79 = new VEH("SUPERLATIVE_STORY", 78, "superlative_story");
        A1Y = veh79;
        VEH veh80 = new VEH("EVENT_STICKER", 79, "event_sticker");
        A0R = veh80;
        VEH veh81 = new VEH("AI_STICKER_SEARCH", 80, "ai_sticker_search");
        A05 = veh81;
        VEH veh82 = new VEH("AI_STICKER", 81, "ai_sticker");
        A04 = veh82;
        VEH veh83 = new VEH("FOLLOWER_MILESTONE_STICKER", 82, "follower_milestone_sticker");
        A0W = veh83;
        VEH veh84 = new VEH("STORIES_TEMPLATE", 83, "stories_template");
        A1U = veh84;
        VEH veh85 = new VEH("CUT_OUT_STICKER", 84, "cut_out_sticker");
        A0O = veh85;
        VEH veh86 = new VEH("CUTOUT_STICKER_CONTENT", 85, "cutout_sticker_content");
        A0M = veh86;
        VEH veh87 = new VEH("POLAROID_STICKER", 86, "polaroid_sticker");
        A16 = veh87;
        VEH veh88 = new VEH("MAGIC_MOD_ADD_YOURS_BACKDROP", 87, "magic_mod_add_yours_backdrop");
        A0r = veh88;
        VEH veh89 = new VEH("MAGIC_MOD_BACKDROP", 88, "magic_mod_backdrop");
        A0s = veh89;
        VEH veh90 = new VEH("MAGIC_MOD_RESTYLE", 89, "magic_mod_restyle");
        A0t = veh90;
        VEH veh91 = new VEH("CUTOUT_VIDEO_STICKER_CONTENT", 90, "cutout_video_sticker_content");
        A0N = veh91;
        VEH veh92 = new VEH("STORIES_TEMPLATE_GALLERY_OVERLAY", 91, "stories_template_gallery_overlay");
        A1V = veh92;
        VEH veh93 = new VEH("EXPLORE_SHAREABLE_GRID", 92, "explore_shareable_grid");
        A0S = veh93;
        VEH veh94 = new VEH("PHOTO_CRED", 93, "photo_cred");
        A14 = veh94;
        VEH veh95 = new VEH("TEXT", 94, "text");
        A1a = veh95;
        VEH veh96 = new VEH("ELECTION_ADD_YOURS", 95, "election_add_yours");
        A0P = veh96;
        VEH veh97 = new VEH("NOTIFY_ME", 96, "notify_me");
        A13 = veh97;
        VEH veh98 = new VEH("IGBIO_PRODUCT", 97, "igbio_product");
        A0i = veh98;
        VEH veh99 = new VEH("MUSIC_PICK_STICKER", 98, "music_pick_sticker");
        A10 = veh99;
        VEH veh100 = new VEH("PUBLIC_COLLECTION_STICKER", 99, "public_collection_sticker");
        A1D = veh100;
        VEH veh101 = new VEH("FITNESS_STICKER", 100, "fitness_sticker");
        A0V = veh101;
        VEH veh102 = new VEH("UNKNOWN", 101, "");
        A1d = veh102;
        VEH[] vehArr = new VEH[102];
        System.arraycopy(new VEH[]{veh, veh2, veh3, veh4, veh5, veh6, veh7, veh8, veh9, veh10, veh11, veh12, veh13, veh14, veh15, veh16, veh17, veh18, veh19, veh20, veh21, veh22, veh23, veh24, veh25, veh26, veh27}, 0, vehArr, 0, 27);
        System.arraycopy(new VEH[]{veh28, veh29, veh30, veh31, veh32, veh33, veh34, veh35, veh36, veh37, veh38, veh39, veh40, veh41, veh42, veh43, veh44, veh45, veh46, veh47, veh48, veh49, veh50, veh51, veh52, veh53, veh54}, 0, vehArr, 27, 27);
        System.arraycopy(new VEH[]{veh55, veh56, veh57, veh58, veh59, veh60, veh61, veh62, veh63, veh64, veh65, veh66, veh67, veh68, veh69, veh70, veh71, veh72, veh73, veh74, veh75, veh76, veh77, veh78, veh79, veh80, veh81}, 0, vehArr, 54, 27);
        System.arraycopy(new VEH[]{veh82, veh83, veh84, veh85, veh86, veh87, veh88, veh89, veh90, veh91, veh92, veh93, veh94, veh95, veh96, veh97, veh98, veh99, veh100, veh101, veh102}, 0, vehArr, 81, 21);
        A03 = vehArr;
        A02 = AbstractC12190kN.A00(vehArr);
        VEH[] values = values();
        LinkedHashMap linkedHashMap = new LinkedHashMap(AbstractC37302Gc3.A01(values.length));
        for (VEH veh103 : values) {
            linkedHashMap.put(veh103.A00, veh103);
        }
        A01 = linkedHashMap;
    }

    public VEH(String str, int i, String str2) {
        this.A00 = str2;
    }
}
