package X;

import kotlin.enums.EnumEntries;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: classes11.dex */
public final class VEP {
    public static final /* synthetic */ EnumEntries A02;
    public static final /* synthetic */ VEP[] A03;
    public static final VEP A04;
    public static final VEP A05;
    public static final VEP A06;
    public static final VEP A07;
    public static final VEP A08;
    public static final VEP A09;
    public static final VEP A0A;
    public static final VEP A0B;
    public static final VEP A0C;
    public static final VEP A0D;
    public static final VEP A0E;
    public static final VEP A0F;
    public static final VEP A0G;
    public static final VEP A0H;
    public static final VEP A0I;
    public static final VEP A0J;
    public static final VEP A0K;
    public static final VEP A0L;
    public static final VEP A0M;
    public static final VEP A0N;
    public static final VEP A0O;
    public static final VEP A0P;
    public static final VEP A0Q;
    public static final VEP A0R;
    public static final VEP A0S;
    public static final VEP A0T;
    public static final VEP A0U;
    public static final VEP A0V;
    public static final VEP A0W;
    public static final VEP A0X;
    public static final VEP A0Y;
    public static final VEP A0Z;
    public static final VEP A0a;
    public static final VEP A0b;
    public static final VEP A0c;
    public static final VEP A0d;
    public static final VEP A0e;
    public static final VEP A0f;
    public static final VEP A0g;
    public static final VEP A0h;
    public static final VEP A0i;
    public static final VEP A0j;
    public static final VEP A0k;
    public static final VEP A0l;
    public static final VEP A0m;
    public static final VEP A0n;
    public static final VEP A0o;
    public static final VEP A0p;
    public static final VEP A0q;
    public static final VEP A0r;
    public static final VEP A0s;
    public static final VEP A0t;
    public static final VEP A0u;
    public static final VEP A0v;
    public static final VEP A0w;
    public static final VEP A0x;
    public static final VEP A0y;
    public static final VEP A0z;
    public static final VEP A10;
    public static final VEP A11;
    public static final VEP A12;
    public static final VEP A13;
    public static final VEP A14;
    public static final VEP A15;
    public static final VEP A16;
    public static final VEP A17;
    public static final VEP A18;
    public static final VEP A19;
    public static final VEP A1A;
    public static final VEP A1B;
    public static final VEP A1C;
    public static final VEP A1D;
    public static final VEP A1E;
    public static final VEP A1F;
    public static final VEP A1G;
    public static final VEP A1H;
    public final int A00;
    public final int A01;

    static {
        VEP vep = new VEP("PRIMARY_TEXT_LINK", 0, 0, 5);
        A0r = vep;
        VEP vep2 = new VEP("PRIMARY_TEXT_NEGATIVE", 1, 0, 6);
        A0u = vep2;
        VEP vep3 = new VEP("PRIMARY_TEXT_DEEMPHASIZED", 2, 2, 0);
        A0p = vep3;
        VEP vep4 = new VEP("PRIMARY_TEXT", 3, 0, 0);
        A0o = vep4;
        VEP vep5 = new VEP("PRIMARY_TEXT_MEDIUM", 4, 1, 0);
        A0s = vep5;
        VEP vep6 = new VEP("PRIMARY_TEXT_MEDIUM_LINK_BUTTON", 5, 1, 29);
        A0t = vep6;
        VEP vep7 = new VEP("SELECTION_TEXT_LINK_BUTTON", 6, 23, 29);
        A1G = vep7;
        VEP vep8 = new VEP("SELECTION_TEXT_LINK_BUTTON_NEGATIVE", 7, 24, 6);
        A1H = vep8;
        VEP vep9 = new VEP("ADD_SELECTION_LINK_BUTTON", 8, 41, 29);
        A04 = vep9;
        VEP vep10 = new VEP("SECONDARY_TEXT", 9, 3, 1);
        A14 = vep10;
        VEP vep11 = new VEP("SECONDARY_TEXT_LINK", 10, 3, 5);
        A1A = vep11;
        VEP vep12 = new VEP("SECONDARY_TEXT_NEGATIVE", 11, 3, 6);
        A1C = vep12;
        VEP vep13 = new VEP("SECONDARY_TEXT_POSITIVE", 12, 3, 21);
        A1D = vep13;
        VEP vep14 = new VEP("SECONDARY_TEXT_LABEL", 13, 3, 27);
        A19 = vep14;
        VEP vep15 = new VEP("SECONDARY_TEXT_DISABLED", 14, 3, 17);
        A15 = vep15;
        VEP vep16 = new VEP("DISABLED_TEXT", 15, 0, 17);
        A0J = vep16;
        VEP vep17 = new VEP("DISABLED_TEXT_DEEMPHASIZED", 16, 2, 17);
        A0K = vep17;
        VEP vep18 = new VEP("BUTTON_TEXT_LABEL", 17, 4, 7);
        A0B = vep18;
        VEP vep19 = new VEP("BUTTON_TEXT_LABEL_EMPHASIZED", 18, 32, 7);
        A0C = vep19;
        VEP vep20 = new VEP("SECONDARY_BUTTON_TEXT_LABEL", 19, 4, 0);
        A12 = vep20;
        VEP vep21 = new VEP("SECONDARY_BUTTON_TEXT_LABEL_EMPHASIZED", 20, 32, 0);
        A13 = vep21;
        VEP vep22 = new VEP("NEGATIVE_TEXT_LABEL", 21, 14, 6);
        A0Y = vep22;
        VEP vep23 = new VEP("PLACEHOLDER_TEXT_LABEL", 22, 4, 8);
        A0i = vep23;
        VEP vep24 = new VEP("PRIMARY_TITLE", 23, 5, 0);
        A0v = vep24;
        VEP vep25 = new VEP("PRIMARY_TITLE_DEEMPHASIZED", 24, 6, 0);
        A0w = vep25;
        VEP vep26 = new VEP("PRIMARY_TITLE_LINK", 25, 6, 5);
        A10 = vep26;
        VEP vep27 = new VEP("PRIMARY_TITLE_LINK_EMPHASIZED", 26, 5, 5);
        A11 = vep27;
        VEP vep28 = new VEP("PRIMARY_TITLE_ENLARGED", 27, 7, 0);
        A0x = vep28;
        VEP vep29 = new VEP("PRIMARY_TITLE_ENLARGED_ELEVATED", 28, 38, 0);
        A0z = vep29;
        VEP vep30 = new VEP("PLACEHOLDER_TEXT", 29, 2, 1);
        A0h = vep30;
        VEP vep31 = new VEP("AUTO_COMPLETE_PRIMARY_TEXT", 30, 2, 0);
        A05 = vep31;
        VEP vep32 = new VEP("AUTO_COMPLETE_SECONDARY_TEXT", 31, 3, 24);
        A06 = vep32;
        VEP vep33 = new VEP("INLINE_LIST_CELL_DEEMPHASIZED", 32, 9, 0);
        A0Q = vep33;
        VEP vep34 = new VEP("INLINE_LIST_CELL", 33, 10, 0);
        A0P = vep34;
        VEP vep35 = new VEP("ITEM_CELL", 34, 11, 0);
        A0R = vep35;
        VEP vep36 = new VEP("PRICE_TABLE_ROW", 35, 12, 0);
        A0k = vep36;
        VEP vep37 = new VEP("PRICE_TABLE_ROW_ENLARGED", 36, 37, 0);
        A0m = vep37;
        VEP vep38 = new VEP("PRICE_TABLE_ROW_DEEMPHASIZED", 37, 13, 0);
        A0l = vep38;
        VEP vep39 = new VEP("PRICE_TABLE_ROW_SAVINGS", 38, 13, 63);
        A0n = vep39;
        VEP vep40 = new VEP("ORDER_SUMMARY_HEADER", 39, 36, 0);
        A0e = vep40;
        VEP vep41 = new VEP("ORDER_SUMMARY_SAVINGS", 40, 3, 63);
        A0g = vep41;
        VEP vep42 = new VEP("ORDER_SUMMARY_ORIGINAL_PRICE", 41, 42, 1);
        A0f = vep42;
        VEP vep43 = new VEP("BANNER_PRIMARY_TEXT", 42, 15, 0);
        A08 = vep43;
        VEP vep44 = new VEP("BANNER_SECONDARY_TEXT", 43, 16, 1);
        A09 = vep44;
        VEP vep45 = new VEP("NUX_LEARN_MORE_LIST_CELL_TEXT", 44, 17, 34);
        A0c = vep45;
        VEP vep46 = new VEP("NUX_LEARN_MORE_FOOTER_TEXT", 45, 35, 34);
        A0a = vep46;
        VEP vep47 = new VEP("NUX_LEARN_MORE_HEADER_TEXT", 46, 18, 0);
        A0b = vep47;
        VEP vep48 = new VEP("NUX_PRICE_TABLE_ROW", 47, 19, 0);
        A0d = vep48;
        VEP vep49 = new VEP("CHECKED_BOX_TEXT", 48, 20, 0);
        A0D = vep49;
        VEP vep50 = new VEP("SECTION_HEADER_TEXT", 49, 21, 0);
        A1E = vep50;
        VEP vep51 = new VEP("SECTION_PLACEHOLDER_TEXT", 50, 3, 24);
        A1F = vep51;
        VEP vep52 = new VEP("DESCRIPTION_TITLE", 51, 2, 1);
        A0F = vep52;
        VEP vep53 = new VEP("META_EMPHASIZED", 52, 22, 0);
        A0T = vep53;
        VEP vep54 = new VEP("META_EMPHASIZED_POSITIVE", 53, 22, 53);
        A0W = vep54;
        VEP vep55 = new VEP("META_EMPHASIZED_NEGATIVE", 54, 22, 54);
        A0V = vep55;
        VEP vep56 = new VEP("META_EMPHASIZED_WARNING", 55, 22, 49);
        A0X = vep56;
        VEP vep57 = new VEP("META_EMPHASIZED_INFO", 56, 22, 52);
        A0U = vep57;
        VEP vep58 = new VEP("POST_PURCHASE_ACTION_TEXT", 57, 1, 1);
        A0j = vep58;
        VEP vep59 = new VEP("EARNINGS_DETAIL_AMOUNT", 58, 25, 0);
        A0L = vep59;
        VEP vep60 = new VEP("SECONDARY_TEXT_EMPHASIZED", 59, 26, 1);
        A16 = vep60;
        VEP vep61 = new VEP("SECONDARY_TEXT_ENLARGED", 60, 43, 1);
        A18 = vep61;
        VEP vep62 = new VEP("LIST_SELECTION_TEXT", 61, 27, 0);
        A0S = vep62;
        VEP vep63 = new VEP("DETAILS_TITLE", 62, 28, 0);
        A0I = vep63;
        VEP vep64 = new VEP("DETAILS_LABEL_EMPHASIZED", 63, 29, 0);
        A0H = vep64;
        VEP vep65 = new VEP("DETAILS_DESCRIPTION", 64, 30, 1);
        A0G = vep65;
        VEP vep66 = new VEP("PRIMARY_TEXT_LABEL", 65, 31, 0);
        A0q = vep66;
        VEP vep67 = new VEP("NOTIFICATION_CONTENT", 66, 33, 58);
        A0Z = vep67;
        VEP vep68 = new VEP("SECONDARY_TEXT_EMPHASIZED_LINK_BUTTON", 67, 26, 29);
        A17 = vep68;
        VEP vep69 = new VEP("SECONDARY_TEXT_LINK_BUTTON", 68, 3, 29);
        A1B = vep69;
        VEP vep70 = new VEP("PRIMARY_TITLE_ENLARGED_DEEMPHASIZED", 69, 34, 0);
        A0y = vep70;
        VEP vep71 = new VEP("BADGE_ICON_TEXT", 70, 39, 0);
        A07 = vep71;
        VEP vep72 = new VEP("BLUE_LINK_HINT_TEXT", 71, 40, 29);
        A0A = vep72;
        VEP vep73 = new VEP("INLINE_BACK_BUTTON", 72, 3, 0);
        A0N = vep73;
        VEP vep74 = new VEP("INLINE_CELL_TERTIARY_LINK", 73, 44, 29);
        A0O = vep74;
        VEP vep75 = new VEP("INCENTIVE_PRIMARY", 74, 3, 0);
        A0M = vep75;
        VEP vep76 = new VEP("CHECKOUT_OPTIONALITY_LINK", 75, 45, 5);
        A0E = vep76;
        VEP[] vepArr = new VEP[76];
        System.arraycopy(new VEP[]{vep, vep2, vep3, vep4, vep5, vep6, vep7, vep8, vep9, vep10, vep11, vep12, vep13, vep14, vep15, vep16, vep17, vep18, vep19, vep20, vep21, vep22, vep23, vep24, vep25, vep26, vep27}, 0, vepArr, 0, 27);
        System.arraycopy(new VEP[]{vep28, vep29, vep30, vep31, vep32, vep33, vep34, vep35, vep36, vep37, vep38, vep39, vep40, vep41, vep42, vep43, vep44, vep45, vep46, vep47, vep48, vep49, vep50, vep51, vep52, vep53, vep54}, 0, vepArr, 27, 27);
        System.arraycopy(new VEP[]{vep55, vep56, vep57, vep58, vep59, vep60, vep61, vep62, vep63, vep64, vep65, vep66, vep67, vep68, vep69, vep70, vep71, vep72, vep73, vep74, vep75, vep76}, 0, vepArr, 54, 22);
        A03 = vepArr;
        A02 = AbstractC12190kN.A00(vepArr);
    }

    public static VEP valueOf(String str) {
        return (VEP) Enum.valueOf(VEP.class, str);
    }

    public static VEP[] values() {
        return (VEP[]) A03.clone();
    }

    public VEP(String str, int i, int i2, int i3) {
        this.A01 = i2;
        this.A00 = i3;
    }
}
